sprite $osa_iPhone [128x128/16z] {
xTDNTWGX30NH-GKLhVslre5spYQCxFDK6xW4wV9PMPPbsJ7S6hvP6ShQiSItKd-P0LYrDNwfGpvMWdpZJDGt17pUz8RVxXklikluNsSzWdopGD-U8i0ts-bN
Vb5xKLtbsu_ZHG4-sZxQFf5--cZxQFje-sZxQFje-sZxQFje-sZxQFlizstKj_q-sZxQFje-sZuoFl09B-6tZtokx4Eattl3H_g4-13fznxvG9z8_qp2Jp_z
zDDdr2VzsT9FF_snblcF1VjDss_QVlkBFi1s_siUmdomMWss-vyGKA7kzpyJe429z6ifTR_VUZ7pv_xeZ-oV-wpU_R6wxpx7p_l-Rtq__JRSwVkKtm_0G9rV
uVincC_wYxgC5il7-vTGlXUgztRfMPRT0W
}

sprite $osa_disposal [128x128/16z] {
xDU7Sjj6483XxUt4yVk_RVP0Y10O30KuFUPlIwTX-vOD1VxTlNltxjsxT--o-qTv-oVz38ayU4d-9Zs3FN_lUsJ-BRoJxQKVFxmgWpLdDKRL_FNSW9-gzZKl
MKSbeqRxh_hZl2567PUCoEhvQePndGyLNfDGH0ccmpXmHdE6KAObV4Go1x_i1y9d58BJHpXEVBCid70VW5qT8Ai4w2FhdkFCiceSbXj9P3bsXGDUzQiAeMxZ
NXakUNvUa5axNrTyllZovBi9s6NV0MwtYiZvy8ptB1SjtSpN2MekvV0v09FNi-z0LNM9BmPfNycoAbOUK7DKcagtpXAUxSUdJn8vjggcRmH-qK-0d3uYYTA2
mpGqO-gp2QUhpKKV_kxfvwnz0wwgAxu1VDnkmt0DEYH2D9KrpUPxyJPmvMUMjVCpp06owW9V17nhFpTzyGd97XD4ypCrXuVVgMTj_im5fAeklVpH_aV9nhVV
eJm6YCTRGHlViLXawvMF732l-0hmCVtXhMzHnpO706oMLvvnxxEeP-NN2BHgNFZoqstnS_9RUFTb_Wc0A4jFV2TYiVFjmZQeAW1y-YCLdYDHNeVfDdxlU-Gk
1_2gatm9m9X-2hngcaTyPxahJ80gy_JBZvCV1j_vo2lUvkPtqQfhNyOQcMuEd96djxqs_QJl_Hc9Byd6ixeIhccucJPVTNBR2xLy-ARnUW0Y93Qt9UVDtnq2
S9Y7d_RRR3mpMdZjKoVMgQgPySO__6LCoUPDg_BSoo-t31D4-ePdqQyzV9gj_0pDF12hwjp6n-Ukl-nRNExnWptc0SdI0ABgtDjFDJT_8-CmxwBBFCvDddsq
O03xtXzL17yuSNxoENhHKw-_u1zFxSd7x0lib6_qnxDdNxmlFUSd__62wSi0lOREIq_vvRmbFvNxjlrPU8c-LEla1iXK3jEp1I_-LjYyjFap_XylQRRncdKF
_fu1adS3o1M-6oFTysjNVQ5xwsbfDqODEEs7MUJhNlfA75zkcT7-WFD-JlziHpvxrbPuRlnb__eSQVnRU_M174480r7KaPPePdJ_sxhaR5TQ3QhL1lu57Xdj
QNvy78gNER-xFv7yzO5-PlzLlSC-9trjlm-5jdPk7_zyXdrC-LBiwryVKH-PldpwouzyG9c-bFgezvsF-9hhwxNv_W7TZDzQh_JrWC_Rydd0nwtuqX3tSRU-
b-nBt9ToloNvyU_FVStqbLn-pGSK_VxoVJtaCz57hG_m2dtSYYz7VMJvuduiKYfz8mMP_XxZStqbpIp0kw_PlWNuVDyxdRUHvmFTVI_YTq0oV7L_dExRfyyy
dt5_I_C5GcxsqSc-aPeo004wkOVzGGe0o5o0A3aixEza5yma44yPclxt03QIVVxsaUImkEy3I6gtRpyq01jZa6EopKAyPvb5UQ-KzsfvhrRtIlNlqkNLQhLQ
hLPl
}

sprite $osa_wireless_network [128x128/16z] {
xDW9akme38HXALC2r_qlF6E3ATpYLRiniyyVQwzVXjU8ahzP__T___T_QN4J-EeczCNTvzq8NHVCxmuuTCZoS2ounPlA7n73W35FETALoHw-7t3okhmuOCnR
u1SkuFU-1dwXhtuT47cxpmCqhxVgv068ljxZcVAslLhRbfrt1kWtlel8FNox-jkT2IBYJtrwpdahDRwKSvWGVFlispS-KzxRQeql_bx2ZGjWqeVdqZOgrnmV
1c3UXwMKgl71JodP7-5Rsikr0qpkPfvIBdprzxZQXwTILPpuScnElcHhVNZlEpK6UkUxOw5Fhtuyjl4SLT-npAVlnGCRWrL-3ujyy-ORD1Ol52znYMzUImwz
4JrvZGjycdd9z6PUCyDZ7tRwrDjPvStmq8VjLVv-F7rxviDARj0VXSeR7_cqsaq-BZS-yCbFF6Z7KIPq44yVqpv8_egdftmsVYwmyEIqJvO173veSzVmiSp2
4vC-YXzv-flVsW37O03t9dsM0cydlvMgdzp2W1AcVB24-2g--d50-1TF_C3xXQy3nY_Tgoy_yG4CU7hd9pFIFEr-BhvXS000JFa8Hn_M_4ILcZ8rt-81mBGF
KY_PwITAdp9LFmm09ltIw5qy-eX4_VIfVPZonppgkp1HOcgdZu6F5JvPVCWmLf_QD-bhy0NLfunJgpwYh_Ty5hzquKNqV1kf_7B07WS7G6TyRVuXWYHxFeR2
KyD_cVArvxNwa0-n-0Z_vf4lnIy3LFe0wTF2eonUuulqFdejlNxFfOkTBqjyUViWgTB2zZhA_VSEllgom9VU1odlygkMfAKathuyzgMb-iMtLmkTV_0gjMa_
yeezQQMtRzB2rPT7lbnylVhvxVlLlmwVzqNY06dvs-V53yidVP4meFVvzYzNQLo-pbUChd-NbWP-sfUlXKioXzjFXdyvvV_MhdqeIQi20HJkHca4XFF-RtjB
nithmgrVdGhpJOx7I2NatV6VnnHZojBhoqbz-Vv-OLt0VS-VqPVVVVbaWh3T3Zx-vBI-VFuaW9ELykbJEV1_-pAYfGDCd_Bdz6M4WqL48KhV1Nq3ajTCVKu_
qnJmqZVS7yqhv5JPv6Vq3MQHAG7egNqPajf-3snC-ixkGnAt0ajblR_lmHjG9bd0dTSVtlna83u6WY1zv_OhG9tV1yAR-pD0KcaCfflxaKqEhQiGR-vNTZMP
ax4nUAG_Q09J7mjDoU1lxI-mJob9bIRTsY-VXfoviD7x-f_F-2dnO3VsmpxYgHM04hImtjXVAH-hdkR70U5kwpjODEohxdGpmN9NNmqoc-prpKfHrSlxkiaq
UTOF0Hulh-nhutXNrvoMuET97KHzkAol3mQryas5ghkB-hfBu9oRl2qnhQNopdHtRH-I-sps5c9Q8VzhVnxfUp1rFxJDqkjF_Rxs5i1AwtohgthMgPFlpV_o
qg7DfB-QzC-yTlgOcKgFTdGdc7AKPnaU00-C3By13lAmxu1XxrcLCTvi1GxoX6q3N6TV_UC-PkRaCkhD2fk3FCdCgrp5cotysITUjmMqvNT7VPQh9g2tAHjq
-wHzdfcSoMrrYmpqMOCr_ZJMXCnG7tAmquN4KRxXgnoNS9eb9g3JlvFyujbzUMQ-UMQ-UMgzUMw-UMPyTqFyvUNbvJy
}

sprite $osa_drive_optical [128x128/16z] {
xPg7bkig34MHw3Zb___sZL9kV8nj9LuQNik-lOpt0IIKAMx6bozVldpvygNPCLZVSr2VmYV4TSf605NldGt-ym3Y3ywAqFjrVPLVwI3yWfnpSWH7bgzxT2H0
EE0dqLlucHnrVbMVdQ7VfIw0vcVHs_ZPEVxOxmpzvAX205qVJVr4GVoMrOT-FG3wzUQtzcS8eFczwEtyJEG_yZjplrJWWUQtyqTPbc7peryFmE0VklrOWRe-
6YuVAz2a-L5lUmM8lZZdsDYF5QWtFxEf7YjGhpx-mLOlZojg0D4dMRvWg1TW22dDppTqlNa5taSFFp3GGu0a0VJNdREdc-Zn2j2Rd-SOs648DNNq42EAtQu2
iVeGHMrm1K3p_mumX3P73vk35QXLdprOWVkZX_WNWI6qENhimGfKgszq1UBeqJ6z0h3v6HXNWJXwxC4XDBxviGA7DZy2BuEKvXzGWTZyB0m_06p-CHKullbn
20rjVcJjPT2WwiCXrB_k70DKeDByOuOGRl_u2eIxTqG0yO-yV10Iez9zWzTF0_taU6t_7Gt2kT3xoOt3h_d9Cmt1Xx3g3vyG3v0UZFEZtj0V_tt-PEYFe_pn
66aBtL_gBrAI4FVyzR_ihxg_r1l1BmallC-jpcajpF-3xoYV-lsEttEijG2rUjuBa3_q5-vuFPevboKry2m0Budl-szaxl1FnDyJuNyi2QMyMN_vxYSY_F3d
xEb4gIC7eaq_YLzun_-3-3ly_5tO51SaXeHBujl-T0z0pX42dq-FIm9-qSUIL4eMLltNQUuNScRqE-SO0WJ4qxu_2nl-A_Y5cBC7Fsw0n24_XnKzFTKFV_pn
Nv_stXzo3fj-4kHVUMudPaY3iEYN_kj3t_kb24ZyNO2jln4vw968_dZtNti_Ri0-_0hXvr07vtN_zU4_TNxPW0Lk4GYa-l9xl_377yIF5KWRAFebh-M3Vvhv
pwr58iO3o1lU1-_h-zEFIVmpMgkCFUPpZhi1zkoezpdd8C3N19vcUYd0j0WW9KYErj3qYEWZ-fCS_vnBQwt60BCUBq7zz7a3ENmWbxPOlbJWagcLdG3CwDuc
vLod6_3qwuBpj1N0hVe1NO_-wS_gtUmCpgS54i1BWEDwcQMdy-B95z61VuDJkHMXE-gNqgjx0WV-ddF9ESdDTqWlbqYxxk6q09UIvIOyulSfvp8fUZN0jKh_
yEVwU3jwrQudc6GB8d_c3sAl5qN_PeA62TvSUpahTc2_2geaIE6j7P2BKpjvjyP-9vOi4NnVY139nvkyDDMzpUOUb2oawCM9Y3g8M-nrEYBMivngoGzIZ8zt
1M_3AiQKXOsbk-Cicw6MKl86fTHsCLYuTXoj5c4c5kfPEM-R03WoQstJIMjpWmH7SKQCjlSCj_UCjlUCb_UexX4exd7OMSVpvSjV
}

sprite $osa_drive_harddisk [128x128/16z] {
xTYBRgCm48NXEMC3mUcMzt_R3UH8Jckp6MU7i1V_adflFzFQ3AhyWVLwlLulENIcpSxZsOly65ugFZPm0Ut-92vXfD_8p-8KPYwWpGyY0ckw6qJ2Ixw5LqCG
q6_YHpzVrZtOwgk1Xrg2QBi_YwCl5ox0pAT8ti5NGMpsuUW3eDzqxu6nZNZYynxaklkoZrnftryq-bBuzWfU0N076ld1m9lMm3V07UYm-wpPTs39N-It_PTt
84UFbyw0qE2BY1zF7pDzq-Znqnd08MGy_Eggssy173sgwiRJnyG5M4QFhyyTQFH1tvNd3hGSVl_Bj-z07dxophwQVEu-LzqwX7ZuwVlnvH3ottqjZq7-XryD
SGXP3hyxRtaCugzVcttBfJ_VWNpkn8FFjnrymmxawD47qwH3xRuMVhdxjlXZlNWOTY2VEx_uNXiVXY74tSS0EFCSGhiBuEXXWC2DDmoXF7eOH1pqZOTX2ENH
Oro0NOVc-1YqFteO5o06tS0RXb0-_8O5gAtQ5syxSE_mGyi5I64twJ0z1kNHysm5TbnkmVeOnCDV1jbgrOLwMNq8SVHmXRKLY947SIb-pluGuk7VtpDYM0Dj
Xjsz2AtvCmIrJSCWEMoLFrmOzRfV7qBVdpjthgse_h7zqr3VWVpr5sVMi8R2nlFxC42_VlE1uLnBKSlfa4lfWtvBCA1Mdtlc7GdcwlKB3YsVf53rtvR6cWye
tf76MFSrDZIqDxAXwklH_cZt_VdkZux-FXyZNwmlDuelnXW7ip-jvVKs5C9D2I7Ul136SGXymGys-kpj_kZkJt-Ht_tXF_ENx_x8tkClopNxMvjvhBzall33
m8xqbymN_iET_ZX_8L_wzxV2lHZT_U7kB-HBFp2ckYuZUld3vg_j-8_orhe25jTQ_CdiEpntn3XimEEBaI-6qb-o7u0ZdtiO_PIkN_oFb2AWuNl7F92L_cTA
irh_nHD-aMsHbvG-iiy_mAJ7yTJPbFZdp_vdkdNXp67JIrsUDQUKBryMzkEQtXTv-kpwhXLShvyaUVyzBLaxazywKMSdykn4dPsgirFiieFW_xvUhzVhzNgz
Nkyd
}

sprite $osa_media_tape [128x128/16z] {
xDAr0SDG54FHj0-r_xGXDsPcwonmzU5rD28Y8Y8Y8YAiwO1yrOnyncnP0s1wNZj9bGuA09lbHLSVKEIjZRQpNbC70AfgArBDYNtHJbRb5Uq_CHo7z7D1tnRn
2flUjtNbzBwE8cFCwyjSn_S_r9Y7jk8w34M9BPqZEN3v_xzzbXpk2rD3pBJDBDEqjAqoxTBShHznqkot-w4mgff35N_4hw2gcixwxJlyrA_fZsF6RwVzIBNR
d_97wSoNS_C_etVGd3Ht0dZPVrs3vcyY_Fq6n_rhuk_pjvxkzehV1ssEtGHF-UVjWmc_luK_wJSxuxU_nq_Glu1qcEyWGEAR-ba_r6X4_39WtCO4Qg3JZ1PU
28qaGCSM111gRkI4lnzATmgXyQ0BpCDdupqKGdTKoPSG2gi9n2eeIB_PZ3_gfpeGByG8zRYGXnzGpVTnn7tiuOTLCofisky4BKf4v7FaDXZSa0CXutqSx1WC
Y4l2O14Hnsc_jzUNtLHfEtwNttRC--tXd-39tyxvv__zVzR_MC2p4tYgdpphVyoXBCkbqyyu5bl_PnFLvmZOE_nESfUykWv7sOt64XaHnN4P8RI4itu0r4Y-
r4jjUYabiij-ma7gwwKqN9QCg1Wy_DVN_47u4MJvqc3DDGjSYdr2xMJvjO6jgNE92-ZWuL_F-Sc7lvedajd9JxzqIfPFJpGZ99drcw_NMoqvVGiqnrpMwzhy
oTyf5c0iG9Laoj_kYMxb1Rga_thRVhAokjHQXtz4O1d-MgDydV6lms-HlcAWuQ_vivwymrKxUO62ZUX_qGJwXlhNNFhISzP-PlBnCvvRfqaG4PUwBB696Lmb
qNVuFxR-Bh5xsNxlydNSmMfGUaGWPOkeWzdvxngGKnt94J-TleuxIDbOzX4Fwhm_u4YVXbBaunwxbtTObq78_eyeoqOvv-VmUtj0wKG_ExhxbxbHTjH0zkYS
tn9-3OwJ_jRE-mF-a5_dduNWl-Q_V_hTpJI9zwWyuUVcNm_hTtupVlefbGG86A1KlkY_7zL_-kt9BwYcLVh3H6eLUSr_lT-d_528QJzOhL9K3_k3zDyFwSDF
MhBpQwqLWkq6yUAG-Mr-KZGBVtG01yJd_AsHpzdoBMWWs05Xu35p0BHsE-4_37yCuEc_7_Q_bV2_rdyxwVaEB_P_RSs-WYVP_qlYuE__Mti_Q-eFDk1ZVGTx
-y7j2-w_YijH_gm--BFs_zg3Om400020GVxMazXPZG0002
}

sprite $osa_media_optical [128x128/16z] {
xTO9SYif3CPnjC3dTfQ-_ss7Kb6c4vdXnMBMn_y2FxKWnEbFs-rskzrkjzljThiTBls3TkzljajM5MOHrLm0w-_Iip1zZRNy3HCqtC17PAL4OYFynNh3fSQF
sWI9Ccf_8QziTklg-mdMwvcvwSxl4t01y5VmfUD3dr9DrW_GFbvKftwDKLlCg-arxpFraaK5m5A-MjgQ-LO6i91durkT7_j90QpcvtxgPM0LByHwRRf-gm1h
U2MM8J_s2S0AFnDNpVipdXX0d2z4narynzS4G9G74uirvUcgMnbOilsvxtaBmABFxmDSURhcUTAehyJckxhjU6PQim00L7qM5uzvujgQ1G3otE_4fSxNbYm0
C9vvn7kVhJKB0BBvxbVFq2TsZo83mVLVCttAM_4308ntpNahUW10JZIXMTZElVfkrkW109A8UCndM8Lj0dO53m2WwjUUyu97sIw-B_PF04Y9h6T-_u676XCD
1v2mRttb1O1x9tq17oZDxxbdpRyKtkTN_UpyqQjc9z18uMiHNyT-mV2f4hU1LtqP-y3mgHOtmAi-9pV0s2_Tbsz-2VXF9qZ-I86BByjyo_kJx_yoGEJy7ttp
a_TrlQ_fMztFWBl_tFth096_VnSrtxq_XRflXVs4admLjnIuyk2-_XQt8k__E4AjyrhvaQ_hVQfSGS_pVO30_ryUyVQi2bg5ZRV43u2NVKrFCurghBbaON9y
Yot71m-0caUFkFD-00tub7nNye9Rgkhy4l3r2SyFtwNDxqNMdm1uddWqWAWbrzpwWmVGPAfvllNLBo6_EBvVFi-t5ds-VmAenHPvlNNn4VIBu_tgfJRmrV6H
1Op-u4S3i23i8qq7yBusFqTu2z3005ZWWryUmFZu03JqhU4LA77-FCyRG2_SGP6Cs-TvdZ7T1YW_Fm7ZtqyhfDi0-QS3Y2ZmThOYlDy0JGUmhyVzx8NuyxFV
WVaTDBxWrlXMnAyT0F_g2OXeQMVV2_3M7P3f02s5tVnbts-ztr3ebmR8m77sudw_19ccTp33ZZxAsm1-1L0QBS3IgX_dW8zFy7O3b9Fb1v0CuFYCyhtJTxy1
o48sGQ_XxjfxFRw3umQWg0XperKpgdqxFfRguujW8_GClqyMltQ6Z_jnt5h7SNzRRO-7c9V-wbvYTxlTRhVRxNQxtUuF
}

sprite $osa_camera_web [128x128/16z] {
xTW9ekic38LXPf04Pl-xBI94CTU-at7d_9tRDDynSTo-ftxPktVlthrxzmuG4RQ_XKuuzHVhUEmlvrC8tZldVOZ8fR-KZusMV82_yWGQ5dmly1dq4kBsb-0f
Ha1ez9IFY2ccz6VZhHWJ8gHUR2KE4E7nftysdwBJ4K-oriV4_QcwrwfbVEmMjFgcO1LdPC6Vfd-JbGNtyu7rRxE9kr-FHlqmbrftyrxzF9DQz_9E_IRDTm7S
nFCjRjGlyys7ctY8Mlqw1-AlyebvlJ1WdTUz7s_eQ_qD0w1b1c-i_V62_iB00vPz--2DRmMdV-hpeKKUiCWxuLtB_sv0MlQZLffpZJVM-M1-wlC0ktO0km_V
zoitpjiV-po0Fu4LFZnlVU_u2SZ7e9wP404nHNVkSyei-aRfuNjdsddwv_NRLAf4uJDV1nvmcVVwwTjn_ut__y0XRyy_XZEVM_BrAnSyPrGhTV8LhoZstFUN
1_3bxx9DTuQ_LSHwsTSNXADl5Wu04OpMnkXzVFP5z9pRRwN70zAf7m6l-dhdoniBByc2EF7ZttQ8UCttMfk3Jvtlbut1MUjZVWrm9xwvvYEYFV6JN3t93HTA
Zmz6JxvfQPqGhnw_uVQ-4Hwrajmua5hXm-LV_m0GW_Yl0LXhoKpDNpVW0JbljTgZRoxw_kZRMhVciARsXV8OK2jDFAVrHT_9EyY0L2lpdD6xql1BhVhe0-Bb
ss_sSzsUVdAxSf43y1ClD-0btvXvW95FlmMX5MDevVBqjuhCptwyvXjjxEHh_ph-RTio0eTKjjVpi9OFlDKwNFCr-zE0M2kH-Dlplt_bMQPIjmzyy_rrVnwG
whRpQs_sSwtcuBj5NmR0tYylF-zzE_4Brs_Obm4VVNxUZtBE7tspzyFb-z_E0-Baom4G3n1_vjbFLvy_niu3Wjn_ZEN1PwBXK_EtcMSVhlbU_95spKSIdmhp
X3GE81EMchKHVlZN__jZUqRQQa7CuYCI020-VSHQqmVUQ7FHZ-pF0x1kimyjkNv2gjLDFFlsaa_Z2pWD2FsuyuFFHDWZ7j0llzGoyUFhHtJ19xBYou8i1q3C
4dA0x6Vaom_2Ym_CNnaWDu0CwFy5u07ifnP0YZ7r8o74hUQNBXy_NVNb0v01McEjD0Qa6BnpFaGW_Z3uzAlJmilnN_R9yW5C2xGjTKDuda3mFW9cvW5ohKdh
IRTjSM9--GEGjxCR3m0-SMRp8-oy7DZQyOkFvcI0htKZu0NF2A7pTFRoiE1JEBaW_WXg1Ww9nZE0jbf1Cp-bvV8l3c3kCC1GRGiGfFuW3lhijN7DJqqxlgds
36wPhvvogIqmmZllvFAjy9U_0Z90qaffJ_NL1gQzUhmk888i1UPN1e0-6T0qdf0mRuKWMjLwNdp2LdzHunsj-XHumCc2ETaOcO-3Dy8l3F1zW2oGz8IFFFFG
TEOr3hyk3N0yG1RC6JkNs7VcmSFW0N759zC7d2yu-iaEFWqUMqi7W3BW-md1cS47uTbV7A3wW6ysc6VwDfwZbbDZWNGc2w_uyDclmYyE29hlyn_4kZ9u5oy3
4W_GFzALeztXLxKUjT0fNl2zhkEJPp-fEwgPYC2gFa5_OZ_qGCBBvTynO5fmbffr3hbx_5eABqZZkNl0EUE9AETS9_-M1Otd0LnqMXtJDY1nkQNKlGiUFyd0
RquzyCRe5wsDYoGrlzHwsnampdncUmfJ3241aYG3QczQS1tdEe_qRN80nmKBUYsT7nr0t4KjyLkl0PTryGz12-Va7ZnikypByOif9TZrz15pFXcxm6_Cqyod
NV18VChvJhuMyISxzdOJXW-KosjxALLnz_a3bmu-vbodblZF_H22dC3B1w2R_Uten-7B0F4XfPpBWYy3vliV3tuuyJ75YBVx_FWT-AS-bs8Bpldr0I8Bxdtu
MEIdptR2hm_81AyBzot7-MUC0-l2J_xwFTWZGaYF3U8sE04opPLpVNr1oTzNRjDbmRoXTGwtjgtUfalrj6sgdgRkglu-TNSBzesjoFVtQ_BTktVlthrxz-uF
}

sprite $osa_ics_drive [128x128/16z] {
xPc7rhEu3aN_MCM5bFT_suivIubrWnUWwJFVdaxAFh9amvhykiuFFooUlz0F_W9_UmF_dwpF-gRz5NxzKFy2VrCjGBMW0N-slmBL_1VuwzkV_tp_wYk3N_y2
VzPSGL5jVxvVHtyzyCSrSx-MMW4smFIOZEixy_4_zYyWh0VpyJ_OW8iHrJTf-FXq_ESR0FOY9HPWMQb4LBuBM3fvz8lilwkfYEH8W2qxTV3LNluUVr14wWBS
swfiQ5_4m0Od8kv_RT_jxQsOltH4jBG534lKYozg0I9wPbh9IyViTPNBIW7mon01xwjTN5RonG3G5-WHGDgxyCm4Mou3MN4HRK3nq4S2zFJGlnCKs9Ke9I_t
4TJUkAqzG81hVZ6_1T2j9IabOYqJtWbwGzJtfrxpjz7FtSkwsQNCGANTRCKRYaqO6J-3KeSEz729qsFvbyi3o9J81-Y1u3zAe1_tYeWqw2zrmFkPy5y7SZW_
RkWhz1TtO480nt7zpWrzYHt0iXSWdrO3TSs_se74tsW-vuRUDJ_Q0Ky-fGR2a-R7Em3_iHjwHlDZ_cMt0oVTq4-Q7-t0IJLGPcj-D03x0EBSKNzy2-I9Ez3-
q03wweZITYgBvWdX1O2-9b--ZF8qG3nTWEpyyVAf8sRlKXIkmgd3XmiGBvyCrCbu45YCjbr9iZ-22dzq-CcZEVULryLJ-Mi9T4EOOmSWogS1vbw_qYeQ7hOj
GUdNrRdXnm84obUlvzvhpMJ5-pTZhvAvpTvJSz1Fte_QAAKys5q2xYlWzIlk38WlFwQB4wgVtYv4Hx1mClMVNtxCbgJ4q4-FI-TdB42p8Jajdom_9S9sdj-l
-FyRa8ZzRZaoWvQydr6-7MVpBUlhnm98BirbcAiXBxtJv92j_BdUZYpkNXdqn40qrpRplyqrYvtj7xDi3L1V_dm1Y4Ym-0RpUocqj7t_n-pqt3klhDlmjwFs
vPJWTQUshFG88E_wcpSRmvb6wU0emRUOn-Yz480GElVJ5m9t1tl_yDGYTVb5FDpzo-vvGtkeWVOVtxHex3oStY-x_kBznABg_99IEVPBIk_1JonHFyE9zW71
-1q4q9HmxAomxFfvxeVeunVOh_cbow4_xKV_6PC6Ft3-UchzdVwqlwLaQyqJ_xdvIu2-pTYPCt-tOhs5HJtdzr-wtPpUcS7CRo35df-F_JVuH_tWnarWrzzl
EYf3Y2y_fNJepz2xvfkvT3FOyuDQL7m0Tm0StdzsovUwW0ltN-Ph3S0Qtk1dxsypzpn3tl6pBS1yzxdo0H5FnVCKrJS0jx2K25yqVVpOBLyZ__zjQ80OZ2qu
ZKrMllUNqFCliS0zaD21oVpmL_UnyLle-P_8kor0dUqVXTxy3EoykTu0ucy_frlADatEtiZq2MfWxOyqW6G_WBgTPC_hltv1dyZh2NUjI0DuFy2jJvH7DprW
xvSbvb-4I2O1RfJRHrvrlGGz_BxycDyjW8TwWaIQIwr5XMuhYMZFxuxCm0Imp18uq7F-ybEY4lSt8f89JCd9dVzi-V45O41Gp_mqFo_Z2y2E0t-yVji2VCuz
wt_AmG0uqU5txlD-NAc_VGFmAOY-_EX0A83z27sMzCP5iX4CJXy7_0Gr0Uj0hFanFutOGrEW-I7_BP4d9O4_qFppG6Mt0kTtZwt1vXETqCEFPq3VWOO0qURR
JorpzU1FODA1IFCf0QAv6w3sdCa7m35ufVd9wqap8yBK3O_zE24k02vU-kd35K-rXs9RLwVsyYHjsSX33t08ti_xAwKqw6K1XU6OsxakAuzxd-3-vc7-xg_N
EV_BVdcruaiF_q02fWHsvAJTtaMl9nvALpPznTLp-bSFa76GsO8-rgj8KBD5y7gIii0ExXYZP0MyEYVzJmlGPtcn3rk2fHKbx-yAs9ylu_7kGSKtdFE_Frks
VZQKP3pl2n3lBvlyyN9W34r_Ci0dV2Li9Il9sAQhmc_Btz0Y1tfGCNhN_6X1gwvu_yLeW2t_v7qFDnBd6s2hvwhotqkZdzqRNT9hUlW1ai_yFFeL7JxWz0Oy
1WCuZbzC7_VdqT-mKc6_vvI_ZdvqAg2F1hWl3NuR_qT07qtWDo2UBfu1UpI0tm0O_v0-dk293U36Fs2F9y3T5M3y8_Pu0joV04xV0tkKgR-foegg5en_G1xF
i7Y2xdY6fzFV0-uGFiF3dZZ2vZWJwp-37txuuOSV_WS
}

sprite $osa_device_scanner [128x128/16z] {
xTg7bkCg383XEG5984Jy_czxPOM4yPOCmjoppV_MgH_7igP_M5TNLrTNLrTNLrTNlBHVobjU_fSUW9WpnDF1g-ppcPdMuURx3u13qRlIC-DzVYPVwKrJDs1Q
WsVDmViFaDxYdNVxl0Gtlaoz0SndSSinVCy41cm7xpj06iNRyESgpEp67RpZ5l3Xxwy-Hjy4_FZxuGC4rm4SzWYlFhfkWUJ0HuOF0BvRO0vllCFt7Y1_4I_m
USzjTtw9pyrqnOly13nPNk8J8E-LuHgVwBpFp0YODIwiVmeFbdC6O4RuJYEd3q0s_6BbT_Ldq__HxXDeHmy0q3L-IDO-0CvVbUmYvQG19CxGEZF-ldDVB45_
jZsq6qV1FJmn_j7DJuV81i2DXCwxnq-K4ikh-kFaSqmQnCpSqSdj1zehrLLv-DJyVW1m-jXygVTjk7iLqZ3Q0FRGN3_F4B7vMwqoLjsaFdmRW0KjhnyZsW5g
tMIlV9LewYT2LDy6OFbv6x_w6gNTBwEfdr63DW3BhTlu8-1UhlLUXhjBvOSVJtxu6xjVIukrmbtZJnMhIYqx3p6aStu80Fi9kDwhKGCzxW7LTnzF-QI-LUfT
1cGHdPCkQfNQ_3C3O8QdBpf-_bG-fF3Ezkwb9jLZ324pdxdy8SQeVgttxzrcrvVSVQuvxeKRdV3pBKGBpV-UbjhDZcjSkVdp0s2cfq-rriFxERlY1_COYpJ_
TiA7fv-wpqQ_ptneVcAU7l_JpqfAqUJBYYPL_-3Egm_Cq-E_XM0-YsHNYOMKt_t0pBFZLzyEK9Gd62-bB5bvEq2UzS7yeBwKd3uSnKJ2eVd8F3b-zIqGoJdS
nYFrfVcsWTFZjr24ioyg4fy7cFJfvPD8TPsWr5G4dtwQy-7b9_MTPPRqz87vrFX3dl2pvERR1fuPVoXkldAI4aBVm3FZ3pBXa_GRa9ZFZ3-Awm2onrG43Xiu
FtwGdzK__kkV05ABXS9X0wV73zzX8ubWE6pWzFYZp0Kl7_n-x7wW8luAXZ2xWMtygx8Dz8z_eKzUdzRwqUl7XNxRGE-7VWkp3VnLu_Tle8tVFdeEyNJzqn3t
H_wtswe3k6w0hVcX-U5iFd_RsYU-Enm1mlbY2Efl7Z-2zlXBs_y6nFqmdnw8ezE1Xx-DyUgZ-Jt4696q41uF06dgmr3cbo5_U_fuhFjeVdzWeAU_ZVhqdG_c
uuC4yz7XHwSVcz-3lHZ2uG70iQBVfqD6HXLZVo3Q0oETzwcH4GyF_5z-Ya0BmmY_rASntp8_0wI54JpyuRT_341BVNJw28ZhnWz0pCQFj1Nc16lBwdyutW5p
feLvVm2D5sUygr_AMzl2FgRwfRhrQtNhL-AjNugtVYdUcgBNTmw-khgwkhhw3m
}

sprite $osa_padlock [128x128/16z] {
xDCtOkKm38HX2Ma6ll-15rImN-wWJVmgLlmPbp_QD4tJD4tJD4tJvB41G3AJloCUA2nPc5VLezpcyy3yMleXRhXx0CnlbstUP5sMzI3goDqbD-zIRP7rbWQp
i7_tlZxN1qKEtNtxgOkggHxZuZbSa1yzHvxWilCixCnxvOi4cRUWCaHtVztwnYF_WoP5EOPzVTlolkUPXNboKLNlw_kvVHrvyciv8GUQ5hQzm2WZBs15Hlr7
ZYor84jNtqVVoESZ1YjhhHSG0HlzU5d84jMtlZwWe__cXiyBQEi3aEg_2vmNmBu-r-hxctuMx_m0uCYkyMP-7drqzRdrvLC_gi_VrC_sVkPltN_-0VtPrx-W
pwO-JIr04Zzu1q1N7y2lTkm3gM4O2A1eYcsr9Bh_RT7C3wCXYi1Q5fQYVu7dgiQUYrgV0cdhVgCzFEdwBKyDNrFdLxOQT7hRkRQi6nUWp9yEzuvDZrUoU6qV
dheyllO5u2zFwUvBMF5rRxyZrXQwBqEZvfd7SRVF1JX5VvFvuQ_vbUjdwzCN-CxMTp_1FrfzVyxzPp_dLt_m_uivA-1vnAVgbpwbavVw9DTL_99SnvTzV_Wa
r2d8_Pg0r_99obU_vzPwFebqVFdtHoJquxVwMTsl2VZg7nw-lh7tJo8_5VyqkFuBGZy_g_ZBeRHd-qTByLD-aiZtF80FDa24xuj_KVEZAvq6VCVZL_9v06uv
OVPv_6KDfNXLz6_U-QRmRYdh-7GTr2EyoWz0QIUFVXFmbBlTKWmXFfJQBjTCepvbXOGy6V9aw9CXJuOwMV9agPEbJfOwcUfaYfCTNZEqQqPqcyoTpMQpsMms
cxq
}

sprite $osa_server_application [128x128/16z] {
xTXNOgCm483X6KrHm-7-jrraLeaDDaOWq1R-1pfyanuR_jQkhiBwclAffdpg2DuRN9Dn1moGU8HreQy-G1WYW1O3P5vWVIOFK8zNW1O3PDu2j1WWymwXCAer
GCZV-eq6IBm1Q3D0_idR5AS1pll9cyTXQBUli3cfuSFsJ6CVA_cugNg-sTA_vNDPLDkNmX2R-bpVPrfTJV_oB__oBx-aVz2dmchxvZ___uSAg-oJ5DROPyJQ
FjFgBl_oJKN_yY-_f7_FDqnbrVOD5jR-_O_BD_-gpnyxrfUFDVOPiRhFeiBPvu-__olxfFU46ldwEsdZYweDCLXLRk8Fl7En2whImYTLvttiEgkwt-zM5sDa
77qR1pxgQj-yyxlIFDs__KBQL9NTlaV0CO2yNWY36iEgwhnLLHhzfHRzhYDW6IEGUmnBSKYaZl6Att-B_gtZRzz0dcCfYSdapE_slL194gAvHqncZAQPQOj-
x4eAoNyVlcp9TpwMv7qqvItvpfTa3_73YqxqGumJF1qvpuyAipIUuzlaCuL9oAVw72UPStrZ9-6vFimwrPUvBwjzeiaoRvxWZnnzotbPuDljFb4DtxbFllj9
p_D_2eVxE4i2v4pqxtrCIyJ48KuExF9Z9WN2Mpz1pECo-SCo7o2YVNxE5VfOoVU_qsKVd_s70xM-_bjzEi9tQtm-r-ViymU_x-lwTquaSIB95ya7aeyuy_jN
Vd0qoxbZ_7xYw-3xE2_GGNu_yTLQwxxx_lR6XuAtkPaFYGD8Fa3oyu6tVZ_p7_8XetjzaPaV-x5QFZF3oRvyzk5aNpLngibN7NpL9JzLwCSb7vxz-m7PxiUs
ldlfksLViYyLV9hnzEpZT_Vd0j6mH28S3AB70m-zzFl-Q-hR4ES5--Z3bcP-qcT-oispH_ZZLgTb3RviorRokx2nDxwSvtUPt-NVjfQy2dw_DtZqBKj97Ehw
jsYBVDVTgl1vWAzRLrGLVZ91GLzzHJxLdnlihAMUgs2tx-eN
}

sprite $osa_server_media [128x128/16z] {
xDS7WWCX28LX430ZU__pffDUn6LYYly5lcVA5FZKHYEjhnjlTUEjEVYIiAOqpJ1WmoFKXILyWAuZW1u3Z1UeBzc0E3u3z1XW_0AWnm3Z9mHd53L0xQVVQS26
Jm1z1jW_hodU38Zxv_bZNVTlFqDp4k53UwcpZq4-DXNdfvQ-osTV5EsBCyIkFiVxJDLziZ_yuG__Jm_HAtqzgKoBB5muulhdT-sui_idyDgLlSii8ZcB-UIi
sb-pkmFJ4SxMqK_eo-6pkGQRBSnilhzgdzZS8xpVHDJw-RlyItcpQ34LLJQVn9dBtyCc5xKsFhNuZEZmJPuECcmwz-ElF-OJNShmOlz2xk23zIr--Wf_-DhR
J_xht_VvYSbNj9_GLxJlR_YGljNdfythozFYV6pn6R7PL-l2Pyd2vlFJwx_3PzKBl9HouPEz4CtbcpxbuwiO7VsyJu9yFKIhTkj5krKUXm8m86blsP3o_cyx
o5fuaJIqoP2P_xhFZRYNJv9zd6x-l4PgBOZ-DjaiZTqtW7Mk1FIwt_7kBy7FrMN3KqUBQ4qVeFkyLC0k-pdb_1Pg5lvjNOjN3ptzVRTPX_05y5BcPI5mqG_S
iiyMQVqNTw-QIxrz4wrE7PlFUUDdlEnFp_rQYmNUa4meJaCHYtHTnQgBWf09G5sMfG1soQ-LCecsvliceq9LKJSGUq9WvJIDanXD4Jj009B-JpdtQ_MWZvji
8eLjvgNaUcwACYOL6KS1WOo-TF-T-ogcBPtNKYp2KYijQuiN1I9JPfoKdR_cYy8oo25RAMWfTLrgJ_6snLEl053TNyfZfiUS-X0D6L6aX5uzUPRRkgxB77R4
xUuRHm4FJ6PydlFp5sp6M2ltu-wbs-dZw4S1HfbUpec_1k44lSHJ7hnz-rFt29dzgu5jdw9HuB8_n2sVcMUdTDwmsyapzbyH3oH8asq2jCl-iFOuymwq3FsW
CyRVTASNDoEt0eHosUy5n0dNOzZrv8s0WKv41OW235VzoDv-VmymqmXstsaYIbY43eCN4h43SjtF2Wert-t0PA4Y1f28fsaoclK2ZANj0Eowdo77y8rRicdY
xZh1xfl74voQ9-13lhNtLHAWCmEPCdT-3i0G_lGvNpVVsXv7-uZmUBoKTZy0nXr0RVVlTFTtVtpT9sMSXCZ98XCjzWXf4LKD7uojpmCW7UsFyhRVRbHxy6tg
oUeqGXfoDeFXWpuUVN0wHCciW6Jmd_G7ol2a_rH4pLGaAhW_cUD0am_vEanvnN3tSuy57TKeHREKzCVcgyWu1ZUE8STZBBpdsp1EZ09OlEbcf8YrDLCpGrIG
UV0rEDNmu-zSY2fUzvtn5O6XUYFRyKVg6OkLOmOXHBxvut_X5-gGmqRD0R3ngU-vBs0SwD_ziVcvyB9V2ZcCSSZ1J4ZAq8y1ZzzoedFpxSoNjto90lA8MNwf
qVG-HZcq3tYyDjD7Nz_qrq9m7ARx48-yqpe_A54UVFt5NzSptuqOXXzzewU_JnyewBvP-6QRdmkv2u_-Ukg3-b20yN3suUwbKFRkHyBUzxSyzmk-5w3SVmAA
b5Ahi_EWcRkzwKUU-NDnCz26E8GzO2cbqQL6dBhpREtJfl2ZRhFD27yOS-7KNv_uRG06OXo6-m9gJs7oyIbvLHU4Z-U-sJT_NayBg3400od74GZ8xBqucVom
0Or7uSVy601j2uXfE9GWnZsQlG_2vDs1s7JWtX_UzliEv0WiAkXVAw9cgfBuc3h8KkDiRElf0-4ZDX0uzyy7i1I7HH2zXhLfMwBhBKDaCf9UvcLPvdckM-Rj
gU3W3-7RktuKK6CBMbX8cgIvfnq6h_CSVPF45cjNGvbdnrK_9j0ByALw60n1r02snkCWHjDxeXYQJCAb-NR9Nx_AlWTbQMrkQN1UFwNKp7n8RMDZbHZN9187
L3Pkt1OE-TsF0jQoL-3pKajBipFrn7UlFloIN_siuBOnZ0fGusJrdFl1SyO5VxtB4Zr72OmAvlgpNzDVQB-5p_prMRx2T2VWDV-hdITzN-ehUVJNqzooRTzI
ik7bMmv-USrVNkGpN_5D--3dMopjkTsMbkxVNiZwsFx5VDrQ1SKPdRsUuKD-f9LGvZ_CZstQSdkB_sm1COIlj_ZFL_0c_uVLC5pC7wjdFc3_yVat_m4
}

sprite $osa_device_wireless_router [128x128/16z] {
xTRPkjig38RXVHPh0Dt_tMuJLfy6_pOHmQjqq7SUlq9a-k-aA8gYABAzgHVFygKLBwvPpZE-Jllfd_333p_yyCCFF_pmmmy__F3j1j_cVLldw-U-cScqBpD-
5YjDy4OpljxbsuVBc_OJ-4F3p_bc9bF-LdrRvEU_qjVhljNNaMxsiuwNR_4vfQHD8iB7v9bYCpyVcl8hNLY26899dWSOjLz366aCz_61Bdo6IfkMv5bdYb6_
s5lffopdwI4OHBGsm1UxLkIQzFt-609-ZwV61X_JgqG61oW-rxK3EzJn8wjxFbvs7euzEG8ieBzz0fv_rFiWNWy02-XkdruVoO_7Osi2_xJZ0jZXwzvn-vlF
nuPk0BSlDNwC-dWTtXluMfIyjatvRMzybKFCN7Y7xn_1uJCJRGKkpVauI9zlsNaVfz0kZpJwX8qC8DS-NTFqIOnr_LQbM_Fu7lHm6CQeLzVthr8SyRC1dsbl
QvhmSHRQuxw_FVRkyh4tVlYYdWHJJ-zz_STzQHxly_sD-XB-LqIYGgJAHClyRQTf-tvVWLUcCWIh2l7t-FRYzvlrRRsFMVLPVe5lrtwj_b6Tzl7Nl-yBGGoZ
EFsh_sBIyuL7_j2s5c9OFSoPRtlwEZxTr-7_Gjufz4j9BnRv4LbGJ9DT-INFtJ8chhJYRtnuw7HS4rLp-MsgAQUaDSyXIqbLkSdhwzdMi9np-YhlsR6a-22V
Zw6FeGzv_7J6PnilTm-2_lrbp2RyErllGmluTNxus09-fOyjvKjh-T9IlRO0XnROs1eQM-DYjxfH54N_0m
}



sprite $osa_device_music [128x128/16z] {
xTk7ijis44RXFVy2bDBV_sbJM7Q4aH0HR4Wi7NUQuszP3Duc-y_spNVNJOzw-xjuR5Vi6M3FxD7_sjVNNq8DSRYVSbFfODzpOphMJpcfePpJuRurbBhxkQy_
tBhwmxslV-lgGrUVlZvzVVhwzFNfwzFNfw_FP_lqzUdhqzUdhqzVdy_swUlJr-UpVVhwVBPFNv_Fzlbidmlzx4-beTRzFXphAxzekDVpOtrJUlPlLVsMlX__
FTF_-b__wpFNmmSz19Vww4LSumSFO20G6kCI7qs1JTzCiUa2NqiG4w2bittq9axrqTiuqKShuZnVgphDryfEyj7AECL7g-CCNmtzU9__DpNLs-Tedyv-1QcE
Te5lqVa-5Q4w02Vw0KGSxoVtV_NhJoR4Rj_72XypZ40gFeRP3Z_qqfS4TVznkmmaRVUroAKVrVreZx_eg8SVN_IOXjnw_-s__sD_3Jat-BJxTPwHJobrM7zy
CeUKtlfK-Bs-cULS-1L2A_wktSVCXn7tzyzVW2EVlsdSEUKqLlejkO0DVbpzyAFrTYJQVMe-3NhyJbjy3Ncgy6sj7gSUkJkDlfdnscST3nIFadRVIZzQmmjc
MEDly0tNFmzJZU__FHmy0iNzdnjzB_s8TxvctWJo3Gl0BCv-cls8juTlnZyQqu-fzIz5M7RXDXP-z9wVGppUX98NrVc9J1NVtfrzKkMgZe5K7s74vtrJuTSk
0V6J58V_7F7l55EylFYQjpE4Nn_0363cwxxvmweu9Pu7AD_eD4_nsp9glfbJyIC9G2wJvwUzOeonYczKBdzbtmLsTo87JrQaoHltg_fJiC8dJZPn7n2-t5-T
fcNQy6i1cWFc1JVR525J7c7u_pYrwvJ6do7y5ScTud-IiASe_CgxFef1jlhnsxfFy9LQVToNvGUNrVqu-mT__YjkCvFNzo6MG3lOdnT0gZvoZqxur5siG7Ai
Y8BE5Xtg4rV0lLn-fb9iRl3Lk3lp99G7dRQ__56iJOy3J8cTBq1iJylgQF-a3Yy0nPRmuFUCa78UXjljTl-xdwP-VchSV4_nb8qRpmxeZzNTaqUXNph2hwbo
sryrWvrQHxliCFOl
}

sprite $osa_cloud [128x128/16z] {
OXYQO1ICWb4m2aR1A1W5em10ZBaeEiw2GBWgYFh-3xm79-7GfJGzz_blvkzqFaIJk5sd_fGE_I4T-Wlw7DAxZ5-l071kjK4yb-fNyRs-gPsIfVez_6Z0a-gz
1R-5bqsdBMOcQaH3F_WT_a3hZS-iWn_hm3frNCo0vyv70Jy6XpQ-HNpN0bWTtusFOkpxEpmAwE1_Etr8vouJ5zFmdey2q2Be-vupvMrOtjJaVVeHBvr83KxV
WUSzB13DDJEy21D_vri1pTvqHTPQIgdISxxW8J37c-Q2liQVslfwu9YQLf3ZXQbFOUZSBr_55u-ZglmCBvtOrFjHmHUwN-_ngchyamCyvFcgBpoJiVKQqnsk
SwlPz8S87iHVBm3TnxVdw0X59jS7-36dMQqnNofWUStkSC27TJQhVG3Dh_2d7Dd3HHvyEjNX7MRr-2wVQi264muPkAajKa1k9rw2rUEn0f_1zmgrrZgcTMur
fJS_UubMaoGDkC8J4Y6QQqa_-UpmZ3V2lNKON3LoVexdSYRgP9jYv4Zir8olnxw-hNHl1Hxw17zKmwkQhlAC-Fs_4-k9nnP-TTx7VrhncSVXIdptcLGpjGB_
-W8ihuvCVyBjkCEsx6dJrv9ePRrnrRDDOG5okgc5CmxHUYmgqJgzOOvhlZa71YwJ8IAngQjEwug7mNVhsGFmB_0THmtzSeylMQQkNMNPrgRMIYEnuXRGSJyF
8bTuANREej7kCt6uv2cyyQE-M_KidbZj3NJ5TwUyMbJLCkaz1aET_6jMkvHnnGU-744xbOZENSqutB9gADwihPO2_frL6DerwRKLaE6dhgPDOi-f-Pkgon4A
Q_7McbYj9I9s3iluxNRpExYTiixAdZ-DRQrFhU2R1GKiLOeNFoNkR3Fo2ylx3XZtraw6zrR3mtKU8Z9-mVGpF8JfrnUiuBFXdpPWxJbL1qhnfAllhJstUdn_
rW3SKEqgSzzLQmciT6KbJySjiFMGJxURQscMsLbUjpey-FA4Ns_bAXCfU_UxlPTRtSKrlzogPOBl8btCIAqU3_bn5-ElHtpTKxPoERvFyACrukKU3_v8-FLM
po_p4xmCjHRUkh1AT-EJBmcVRiNcb6Io2llloce3ZzVQPyRl25NtuynpkAsa8_1pgyD3K_bs3WdF7pg-_JnphMdM_WfUJFCyCGKyRe2ZTqypvxQMQoi7l2Xc
HFvQMFz2sBKk4tAPyx0sy1zPASEF3Nh8drMFKjNpVIgVLxg3cbhBfPLFl9l-UGvCVcF1qO4W7tjUzF-id5jZ0MED-0e2ljdlMyoT89ThmxaM0GyhUwVnOm70
JpGXyhlX7StbkZzboyQtIokvFM2pjqtmuEYHy25yYAF7IzRuozJmDq6OlcPQQ8kP-5YdRvrAhVSLn8T0u3Vb4xH38H-g8jRLD-iJlhF42aRWrrjnUF2TBBJ3
6Wx9tckZ-49q2n1U_JOF5nhKlHNP54pr7CHjaF5nd3D_33r-s97DTxc9jMO5n0s8-HTu8IQAaIhbrvBplJTi0rT0t7yQwkN2lDXRWJT-CAS5H3wL4larYjPY
M0qFhpUNSb702Fp-WEy28Os5rUF13rvNGSwt0aOfDPb-SQfrhWahyBatBq1a1lvgrbNVKIHw3QmLGnaU2WMS3LY1ZmOWClBXAggsreJrsbiI_dnm_9Y4L6J6
I0kLjM0D_EYjgh00OVfeGDKlj7HAlW5L_qkKrvhpRVf90M4b4Uaokvw_IlKAtemF_6F-cXGYeVyY1tvfzmhcVFy17xHKWrjBOY5x2AzfrkZEuFpqDy3rMm8-
wXVnVrZ1l_RWG000081XqFsf3x9g9G000007
}



sprite $osa_device_usb [128x128/16z] {
xTg5ikCm38NXdGOjwLJl_xQR77innPdOkk3_Oc3wsId3ZxVg-TtQs78ttwghYwa1i6DShIRkzNGb_J10tIln1WeFCmCMhy8Zu_OmZg364IYyFOq3E9yl9sqg
QRrRahANdyrBcRsiZqjv0E8d-mOpyaypWy5EzydR-ZpXddukhzbFwmjnJ_KQbxxrbVJygu23lhxaYndEzkqDFvr-0N39lhpXYv_furqVNyllVlUj-ztl_ZUy
_dU_-ztllWRxbgBzb69z5kkpK9_5-YpOPpTuRUcpl_NKqZ_Mnkz-zxlVVL4pYVC5UnBisxVr4tsDyvNJZ_EJae_p1VgTVK6eBmZqoKkSJpxE9vy2VJD9WRv0
oa68yJNxOVU_XaJV08dqLO00Nm48_IImvhvWB_iSG6DVwSlkSobc_lIvf8tzP03qjmnhxITHISKN1KpZ7dy8jkpR-jtNBMdW8-3nBtExxTkjvx_6bXgVFpjE
7pYiH8NFdo7x1ykEqnUhyFapBMV02-S_hCo_mW4u3k30QuNfqoy3aFGmipg-yW20FtelqkIL_eavoX5u5c00lCA7lyl9ux7ExKx_r5moOBBSRnIzbWj_XG6e
6Qucqt0_-aA-mW20vxvVbNo5tENgJtqdNsi4SJxx2Fuu3EEKs_xzQw6bFsvjPlPBpVpBE0zxytYvN8Pn7lVcblx22I_Jvl-rqCoVrdblpVwwS65kwATrBytP
_xtGpcVqVoyixVmvrD-SCJTiF1TOC_zEiJxxwdxtzT7zxoXAlkhy7rNVTtsGw9L-lVnnx-czNkyd
}


sprite $osa_home [128x128/16z] {
xTU9akCe381Xm3Q8euVtVzk5LYSYmQ9nJCZkZlywzkZZKmMDgaRyPxkwkheAuRDyxeCyza4T-nnlhQS1flFUMXfWFky0Q839ElBp1o3U0lef5rApdnxGdpu0
yl0JycxY0FZqjv2d0QOzFVaE2xafF1GXJmFCUtgCU1fWojEJJxtv4D3Jb_wi0N3pZAdyAGCW3oRrmDj90-3ccUzAlXg03i5etfbRn4yQ09_-7l4J1g2dfuYV
C00zFKKwEq0O__GKt5nF4umUW7ZByY6yTG3aWUDzo5di7OSW_COxoAypVW3YlM7u_15R9Ste0VZDmopnHaafzVW1YBSjNakbqWGR3Z3u4E3JQwtPpLipdmTO
1mz0Jwzp-xnVf4HUoiKt_no--lJw9sRp90sWXXu2vAs-Lpyz5Fpu0V3fY-hDGrNc0J2RHnuoGCWP_H3oj7aOyjYWGu2yrqyzRLxTYKF0Rnvru_CNrIChXFnf
Epy0FNrPkVZmh0iQO3qz03rzKRrv9KyJC8UWTm3KFSFJvjKw3Q1E3C0ylM4tJvJ9haFGSNIwDqyyrNK8-ZSFOpTFr4aCygZ71w3DAs8tJ-o6NzBy06s_jVYh
489qBlmYUmZyx_wMsjiyaIAUx_kBrI4WFxJzBOS30F5EbPzlHzmXQFe-yzZZvjcRYNnFp27ezotnflnqUvExXy2tV4T-oM_YfUf3W7xeyAlDUwczGz3ohTOL
xwHuFLCCqEVd0HusJvofFWIyJyU_uCqfdGu1rbo0-_K_ltbbIpb0XryyVLXEkEmbQlZcWVVgXCfTehPVtRmJSPV8D_o21p4mLrwY40BZ5z-XnT0iRM733_VD
is9mxZv0Q2n0GDvREBRY1dOpjC600n3F3E32Dt_C1ovJV0iEu97d1i0Hu9WlirG7gNB4aFAXwMFY1Ly_X0Cy-I9WWW-__Eoh_GxxWdX-057v2lPR3lk2UBPE
tnXpn9VqxwTyGqtqoUtpJUMh4xuaalTDnK_sZI6-zfS9FbRezht-Mlj4kzHdVBIV_7ME3nRnkRu2i0HFyxV2Hvttj-7-vUl_bYy-wUiJlZ1C_oP_hrc-0APP
_iRnwsbVfZW_ObesKZ56BuGvwgEiKil2y11_0iMs_abV3r8cFtRYCKQRV9dbPLstJRTypCDk3h_wfLJsO-pYqPToINIsmJA-ZPrzBKlsSnqy-agjsGRhV3Zj
hojaFzV1ex_eRFlm5UDfVqk-ZLW7d_rb1Hyo7bdVzViR-R79OmvWNTrNtjqXlYxzsELlMuXncAyF-rfRVulnhU_C7lLzybDcK3hxxe3_XN-XCwCcW9Jlyp4B
07PSW1y_-Hq3ZCt-8Rx7ZzxPWVb8VBFuziGlVL37FibZ7zMngJRV77b-LrTNL_y
}

sprite $osa_lightning [128x128/16z] {
xTT9SYqm349H9DZ_bd_Zqi0LPGnfV3TmZD8-_EXUhzVhzL9MbnJcbTEdCA-SFWNv1YMbT1O0Ih7n_oj9iV7pWD3ugQNG-8bAZP-eqFYfvDFLXLNBDtxpe6GR
l_tM_opZDu-YJfxnoszfCenVV7dq6RzyMiUVxASVVdpdwN7fQpwDupVVrl4V_Q99_vodSJpxydsdt_punHplq4ytV_jjqO7XFyntZ9y-E_yQx_e2UFLzW7Lw
xmFEUdBf9hzEZ3sWwXG-03fw000ndySFFg0FZyfz0N1gymFMvxtnpVp-fo_4Kpv_VzgjfNluyJlA5rDysSTZVTfcbA-b-_X29SPhyqZmrKhoQxo7N_zoMtaE
lyPx-LQAFpwZV3EX3z-Znta4-D7pFCmyUUbf7dwUtSpTdipTdbFezfUUv_6RURXvVY4UkTldUVmg_jRpF5Ayidn4p_99FSz3Duz02esVikCn-c_d4UE1C0yX
oYVrtypZD_E8PkDVhzVhzNhz1G
}

sprite $osa_media_flash [128x128/16z] {
xTY9RkGW3CRnnZPC0jFo_c-xV0XHB6ME16Xsj_obe4GzVYOzvlYecircizczNvVow58UdV3zsgaD0npVlbkl6m3-jcwkIsM0Q_moG8FlJwS6EEVxUrF-n035
XzwSBmCSzy6xzNQwrPK1Jldnv6QRMh433E2E-zZ-QgqX8iQH5dfonJWudo230N03DlZtetuStLfUFZwMUEHbvmeBZX9HNaYiZPk0lvtoLskqiNzLs8gcj5Yx
dVOzVlgYDhHydsY8ur7klqWymK9axDhcyrj-LBCljSyiF-8dMljiX7YeNsuzgLlFn5Z425V-DiRNjxxuHlj-bC_9BxTUiczCXB4Czpdx8kFyGtznOcIGJtNw
nwvztl5Tgw_Z66ZjcxWOxLCtVwd213dGUH7GbIzCNVpzC8AWwY_EQ9_6-OIg4I0-yNrVdweWvMgVaayzVLBjZu14qj7eRze7ewjy156dVTVYQrrop4LN7p7f
Oqnjlgjz_Hml-zWZwqZLpzzxZ8EFHEb3_6hhh1vZSYA57-ZlFSQ9gMRew_livrjVFyRKZx6Gomo8OnBZNlxEOomhdpdHHaeTVO8lJtt25Jx633UTy00_6Wbx
w1D9cRIdd-YznrY8cHxk6_KO-zBdFhxKFYkVViutyjWNrZxi_Zu_ylLFd4Vwht_ZGVVtsIXVtlMNPd-r9ZtqxHhbzKywYHYLfPmOkxNupbh1ztbgB6LHLpZ4
MjVYu-qlm-fTfR94NPqGaswXzFxJQHy3-9jjwWR-XE-Ixp79hK7Vm3VuFTv_RV9zCz_WDrNi2tpTzVxqtR_XJt_wqv_-zDtqfz-lN-vFt_-3_hrJ_ww_TkYa
xvFlcclsjtM_JNridB_AVlfZst_eJr_QCzz-U8yFtpulpN7nFqFijHw6-k4r7pxXW-_atukFNl33_V22x-nByRz2xce_FEV3LsSV0npq_L0__9r-6Ek7T_q0
toMVcZlZumyWvdsF_Nk4F_z3_ZtvHfgp1_qo0FAkkIWZyCf_DK3Nm1_omzTdh1CT-me7_B5fNdUrVocFBkNHfJowbaVNwQKVmcUpFm
}

sprite $osa_server_proxy [128x128/16z] {
xDQ70OCm44DHNQ7klsyIDh0SqUyly4G7TwsgrlPEvRTEvRVsu1UtbdpUOS366zgoHJvW_HK0DK3C3sZF6mQG_0ZG0uJy1EW6yFni80lLW9MuzVSOiF4EY0Vm
JnvVRWDqJnvVhh_-zaTqDoXyzESd-oRohIkTxpqzoq-kKFi3cTcfVkhzZEQKVldbbry-qmFz85Fx_lB_do0J-p6GdUodcThFQAxyyjrGVldBD7tRhGyT1tKb
0CDu-WpPvVtVzjeUmeKqKiZfloH7QuW_8tbH_fptt-oRhZOGuwiTukkyLbljJHy8N-li2rNVSwLGLNijV_ltn-npGLt26lIMktQQ_JTQ_C8LxX3-EJwgSlf4
s8Dpk8fkzPaFYv-KlrmSu9EgUIzQxvt_RRJR_trGrHWZEyZdtHO___-I7bxkNPzAIT-qTiplVs9XElkq__vV_E487wN7-Ag_p_z6p-sHBtFycXzxU6JkCNVB
Hs2HTefLX8xqcwppOaGiwb6xz4b1HCRJwHGYV9mV4SQuZSIZjlR13KNir5AHm_ogtro6DI9yyOj7yxNneppjmvuV8NWlyOX8lxYfGNMZ-Yx21_aHZBUZDcX4
TD-CL854n5phYEa_QjTF7kxmBKIoQaU4K_E19IDe_axxleV0FJz35Ezy-a0pVumVZe1t_GpPmvca-IqaX0mlWyjs_0ZELKZCtCsKQSip2nDfvTE_MxdPZf-F
J-fnpYDCqf_v6X59-c-K_eF7rwhM6iqL5lTy7H7NfDS_yGi-0bhLpTpP1CWKeJeMBfJ-t7TyH_ImLh0I4W4B41E2k0lHjtq3Qxogcm12ZKe1wkU6tPY-wxjG
cBP2seq34PPQNWKB9U8l-Y7cJHSDR7pfjyy1aRWpyHTzYywBEVI7Be3jCol07l9LFxpop6BIVK0eK6Qz099hyj_pHOHOHQdHM8Toze4i-Vi-ucRSJZpXUvY8
00MhCAqFN_raTIEIUtvokCZB-88VtI_YOYhCa7pf0IT_sqSynbTc7bZDsmOwNp80SqBYSqJq1T-75egxcqBogOE6C6spe_tiHEH2oEtUr6iIDzhwfOrbFhMh
YLUUlnO-buRd4URLb4LDVBrkGaGvDh-DET4kFkaRhe8Q1-Vokl8zOXpDG6Z7Bw_wEfHr0xZaukd7dCSOvXIozSlMNq-yvnTNpCZMZ-zryE3GPtryppURTI9P
-33lO_LjtwVt_K5S22dZLDFt2DUHmwzyElkquq_JdZ-mCukaNZCLzUwRkQkDilOxnzmuvkOpvyHoB2_zwR4_O11MKJYJcfhNLCr4FTm-ywV7FfZdiPVaMser
gR5MdJxqfxj-nc6W4Q5fTxR6JAJgZXV-qBXXg7urcZzFtFUdn_u0vioUljQHMLYK45d4fR0-vpDV-UEKFVJR0k5ChBtA4v4gLetTe9Z0EI8Q3lTp1-vAecRf
gnCWIkDBy8u_VEZd3iZ3j2R2ObPvSPUwE3fU-2AD4sc-j5j4TlnfwqlpwqARsf8UuJqrzz3-grWLjlwmzVi4l-u3NUzWACZcFS4sqLQXO_rfIjz3ozKvoDP_
c29U-Nps-ML_cdsBKpXU-8ccdB43bAM-xe1Onu9Oge6udbXrnv_I7oH-fcaCkVAtON3ElT4jVvfzZjDKEuLJ6Hxnqfx-C7-QVLokZE5OXfjy6VZyKkPtqhk-
zmlPxnZEqBYLdtzQn1WVTDUFcDQT8enA9nTy08auVSZ7QU6t_dJHRzi24qB9KBn_-VVdewQRnt-At-cwd_bPtJnguyzqLDktp-D-VaxZwPJsL_nX-kCRDlsP
VFPdyjcVeB-tXU5B-jnpNpxMtj_6y8t-wty
}

sprite $osa_device_usb_wifi [128x128/16z] {
xTe5Zkmu481XK-50xd_RjTCfnQrMmuBB--Jyee2appGyuUztTNLrTIL7y-I-2JZl-GxXa8cmYsmKBZhJ2NUNBAtXF1jCVUS81lDqy8-rnr8RoVCpt4OWjN6y
6Eyy0FDDVpE0KJmP_xpR6PWmVSiMm7twbYt0wEbZoId645FA1SSlW0XtFEGO-bB1q-VHFjpmb4k1adCAhMnlH_bq-D2yk7CMv53BBdvfEj1TzXY9X946-fWw
_N44m3hMZssPBOHI0CwJ5qF0iJw6K0wif70Kior82cMiRsSGyq77KBCjOM4PwTzjTSZGhqJ4oclDmMzUeIviJq3Kn-_FuDtPS_9307eiX-Basnc4d6A8nrSV
KHONtyhX38ZLyl4Xr68kK5AiLqbyVVi8EE_GqySGabrp3MD8dZuLC7nF1TdHDzjIoy_dBl7s-JvrzTcorD7dnyJHv_d-8x-shtDzMTpNkRuixkjSNnRtTQul
SttHfNrHRx_7QzDysLDtt-nfldJfasGDNv_xwE3hshwkxUixNuRwkhQlStrTszUvlgxjwrnVv_hw1_YCDCedblVHA9_neuRz_L-Oy8E8H_q3oEU54SajVf7n
mrAL6FEJOYJLO2tWB-gdL6hGohd0aPFFkm-b1P3I93-d6e1TvdRfvmEM5k9vwUiJj0YxIrUV2MjCAI5ZYrrzPAQQa5soa8E_RMg-xD5vQVwsRQFqsfVj_r7r
Zoky-LzRQnI_VU_-anRndxQ4h_WY6Url-gPVymSDuFVhPSQFQVkeyB_kwkhgwkhgwYy
}

sprite $osa_server_directory [128x128/16z] {
xTZdOgiW5C1npeG3jhx_sru87PhM28PUx_3_8Jl-tClzhLrTnVPEvKkdygMVu0sX9GmnDzutS6s1nTneFf9pvun0vSMrXnPpGtbrxfmHgBntxfmHg7m0rnbP
p0tYhV0dZK3XqRcpHY3co1sAhVZ3jxpsEEQUzjKTJaRuxdXuiW-3V3ZKE1-Fz6_vt1UDzgKpW5Dz7kypDNVvbt_vbt_M_kyVzAcpqJx-v-S_rDbWdwIpatq6
6EqpDNVvbu-NV_adxV_-FH-P-Xhj8_JLur_tN-OvnfZIbEvwqiSjFxKstg-y4YBbk4HVmrkwvVDkZ_oKfEX8_3YYP6RV-RBROn-ppvW9UHHZzAfmn6U01tw4
xDEkBsY2pEy-Ymg_-zom_z_qBVlSv7iagJxfBQ41VcZrGq3KwkjRyXjzKYDKABwe-fYYL-NdVT_iHuBgPpw4D4LL-Os-P5ym-wGQpD8qUTNdVMtrEH4mLT-d
p2Tjzd7RbqQVAJ4or_clSPecKvL1FZRvNjHZZbKrcC-FLFr7jVcqxsCAtdkJGcgD6_T_stvCtEn79I89nUGt_ca_DVk25ZB9HbWY9gpHVNZVGv-QVM-gGiQu
7NpR85zlVc3ixf6FhJv9L5NoyWC-jFkgP_cSRhuVwqEhprHybZ3KZps-ppxRMJwc6etqhSEFvdFHHllKv0k6eAgY4mtqGuVlevbvcHYN4QqUrn_i-hx3r-87
IOhlLOu-vSLZguz8rEPBghv_r-bvNsy-jlZ4nJU9uLpVRA0l7JvLFyI53-KHoYC2h3uOxZEcc7tr2MiLOgwFnI-Fo5nzQl7vW3_H8nz-pe_5zphnmeUrl_nW
tv_x_73pPP8cd_RzAL6xNyy0LVPzxlEvrTVeSpRHskTtdtVyULxpyvImnvSqvJxtVpTEf70YnHUf7rGVu8i_V-SJ8X7nVNGVSiGwNSVzUSbd7su_ujNayrQI
0Af-t9-_-EGj-8Q2MS9xtnNEkU8xL_ot3xRzUUb70B6Wj9yKFb6pB_B5JtDjvPCPDSHc5fFYqcTczwHleAROaB_vrE2xFZyOjrnCXarVjN2gnLVDlkgEFt_u
AK8mWORybk_M_kq3QVMdXC42kFt8SZ_WYvfvTFlnjY_lllJwSpAod9VlubNYBJ4iGomZJfGVWGYoGRJyOD6M_vA2MdD9m1tigp_VcfA53XzXb3-_zPew2bvL
ZkKt_DpBVg-vAUNYuJRyzbwU7O5flVZxUosz76sUL_vfkV_RTs-TovTEvakdwlsTgzS6sETtzGi
}

sprite $osa_desktop [128x128/16z] {
xDXNbkKW34LHeuJaclzysxulPmHKvxFqlvq3ost_-z__QdV-q4mypwDVgQESRoeJCzzAyLIMJEL3dFHbcLkfxfxm6ViqhQLepgUDfscLPP4UN-gJh3svzYFI
VensvKVABqVV3bNhUGIimHlElFkSyktekoBR9b_TVJOLfcx_8dVvSlQfm-VDHmC-Zd-NJqD-tLf32QLz7V5XF_YUzoLg5ttnZKXKUCpFozU-MRUlRNu5_ifd
WLzgnfUo5FXTyiMlX3fzYvgIN_i5VkRr_y9FFOqZd8XLUFSjupFyUkzNo6svnxhxQYhSx-Tbu17hNXokFovbzwF7XznZ7ttKvtlKR0xxcQyPdov-jmwVYLM4
-_o8CHs-u0KyuEVF-gKG8X7ual5BqdVWJtqqxkTv-7hjhzdFZnZGmOUUZp_7EjrttmRyw_rdqqvVtlk--vl-DiF-p_GlCefFFahw2byZNiXDEggzVjbzl-Vl
Yepl8pwuF1y-u1jyI6dzqQU4BoSVzV8exzUJNsEOl_Phmby--T7bPpy_ndJ4t-17scU2lqxn8vFiEk--DVj-y2E6TVWClpJxxlJQZsHAdFGTFi4Vq-5ptg_m
-T6F4Lz7_UZ9Hlo4Fj-NY34TrRClpRvT_0G-rIz42Zy6ysl_gz4lHnzDyNdpuolbsn_lemvVIvdkK-6aNt-Dxz_cUyxtERxaVVaj_9Ziq-P_jVeqpTVVng-j
FiCNcn8VVShvsVXLt-VNmr8uW_y5lidcYu5lyItZyyHaYvlzs7sMsRNw4I6RhvDZ8c_rZKefDDZ3wPUrrVSVxPg9jgiW34K5aZ14w___xUjHMCKgnLxh6j--
yxWFIRFIYQsvWZs2WiBV9puHsi4VaJP-9MPzdmY21-4pyHDfWvxKWtXCwg4TXjCKdpuP5nHVbH3DVAff_PLnoemWsxzZhfdIan0puPYKu8uUlpVEMuPB-dbC
nGg_F-GLRxdWl4Muf7-CgRupjEKF1Iyiowz7VVp9Fs-P57ufCo67-1nDbezCLCOIqQRvYl-X2Z_dQHRVPF75c8BtGivPvn2Zy2S_K4qu4nFBaxQScL47rN5E
InP62AIWaeA_rODn2H240BCSm4n0C0Ygqper8OTOKhn2VES7kWP0KS4Q0q4OOC43XXtwSIwK42M5ond-441Zo17i0P23gD2_4tsfadCvmdT-j01JKEOhrpJt
5bqlzhs-J639G0vfHSxxmQGW8SCnCIaO7mtzYW16WdO07xSRPSpeIhK3zjjdd1R65xljioPmr0fmPTUryRK22Le1Ohgkx-zV4N9yw4_eiVyjKLNd-Is0ezRv
nVmO5tLTHNK0ElJdvsrSmUxnhx5idx_uWt5o0OQG6CWA6qwgzInog__mi-5Be02ymRe8Vq5arKkh_7m9slcTUJKW1G-x4saStnl7rtZwdN2DeQK1kamMx0pz
BUNF3P2tH44rhhk3Y9exK5EAADxl6o2gGH1An3_9St17-NC3U8DnILDvqehESzjFXhX6ph3p7pO0ItAQCmrzi9Pgl9S-WMaB6a0rpd2UW8vVZACQTjJ7ojvF
J3LeW7Rqy3lplPuix_rlcOm9UGTyLNwnT89TIBTlm806T8_Fnl46UsxWP3-193LaRDM0eUMtXa8DkN02iVxz6q-aVkwG6EDLfsnl3__khYDt1kieqzx10wbg
jhVBRs_3cAIQxStot-aVglk0M-M_rKyzFvlXJapFdx0UVe_FnAuVw8tq_NepmqVqLjBEzv___0C
}

sprite $osa_id_card [128x128/16z] {
xC610000082W_QaNgG80003WTkr3kN5T1y2m090e16s-_zjUa96lutPMObnEoR-xCbHclb7Rblo7uZVqKNtqbtn-QJnwoEFoyX973_Zb7U537vQtb8Awwozl
we6VFkpZEso8N_bZFa3tqouVdgZlzREOUr66f_1xVIf-AZz1t-jBkCLKhSHWy0Hzbw-X2qSYMjpjxaD1ShaP4Uxg-_qK97FcI4JCdPTpr6WPSRkyPAsrOxxX
9tmeNeBllaHgxdZb8tGVQ03qvHyX-TWt3aQurc7h-y_k4dp4t7qjhXS--B6Ly0-jZkNXom-qIT_d07uuCi2ShsxSpp_bp9rNytBXym4mbWrJGswK6gt-SjHy
16Wv7qaFitwvzlNx3KWDYYtBWRajsDBNSlMfiVcoLBMZkq_wuAx33_x_VWWZe58NFb9kSEEJ70wGnlN8BI5D-ZZyqU27dqyxMqqBsF702nyNQ1JBrM_jOB20
7Wy2SSJy_GzVH0OVlWsVbit1uxRvvYQdjFlc3XFwh2zUDEIk3rwBsmG_xPExgMZFEc_kUKAVzfS0THJwZjC7U8wlrTrDH-iVWMb2d_J1QlMed4u-gZLFy5C-
b5fDRR1bBDtKQ-Nl5cvgofVWnv_wfqhHMAtrV0XjRSB7MalmPiMqT5tx9EhLbZNOxED-twfhy57uFHsZMgtf3NuQLz-kAgPQgiFgu-kklupJl_6BgjQQxZxh
Jtt-h1OLAnSwOogcwbLsld8JleVVx_ltSoV4D6w0RPJdVQYrIoEBpaFtVVaAjpvsy-T_dGz_w_C_xriDoSfj5dxPTFeHJljSgzwx05hCgxx-_B5M7t_iNvox
gHPVtx-BL-x1sS_xYzHQz4wbLXlyfkPz2CZjMZUFhJJq5_iBM8tSlPnohr71q5_lHzdgJOKXUeiV0QNyFOhTx_IlUvAE4_uJTPpmdwZF-i_HPtru2Z_XFrFV
xWESr5aSSINFzdOVLN41ZNB_I80QCO1eXh4XOkM-Y12IwdeO0QqR4FBNraWqGemDUtruXeyVzH5VvykVVVnd-l1dN_xTFlO0Y20MKT_K5sDQPwHe_K30YmL-
RUrHRwiFCFoVXRTjzE7a8rFEa94JG1-9CGk0KCh0AN6C2IJ6s356p3d7c8MOnXWWSieQwvnt-y0P18KaGn3C90JIqQ7hy9DIPkr-JeesV116CUu-IjQ4mbdK
Tlj8t8540i6Zn3eb01BKM0yancmamanZJ28KOqevSumv8t7AaX9oJhhHF__f0Gc8-WS2182O0CVM60Y0nXu4mlCu7hlr9wLrZ4MA7r4V7_ljx4-76rhzTis7
J_7vQdxupDBQXHu9vn_vk9aFNrjqmJUz__q7yDmwGSm-o0k_lkiR461S_j6PZ-mztu51mTHxVXEE4Zqk_RpCaRMxVZD-H-Bjqb_QgOFAgrDhLtpKFj9oxiDy
z55zz55zxOFsPIzcV_ljjzz--ny
}

sprite $osa_awareness [128x128/16z] {
xDU7SkGW40JGwGcI_FyVV66fAMYyr5eUBbzNkkZN32Z97vp_UVjLxfnVQMT-FdvTLw52GJyZtCrKrSpSu_mP1JfkBTfZdXL-C7-wMOkxHuxXaQpmutMFW-Ej
Wr63xVmLX7F2LA5-_P02NMUSumgexo-Geqzz7GEWZn7ivWyty-DbmW0zvX7K-N1U_3eE87RxuUup59JXpm4O5zZFCyuLGW6d0dK-dkZUCpLGse8gVqohPvih
z0975gZwvyIpRcRKe9-1C_qQVp4VdRSXtA0LkB90TVEP9tok45d00TlXd-v1FEaSAc2v0xNbkplphAyB14IBHx2T_NZ1KuO29dAGNru-yQyBG903A2p_3iy5
N2IA_ZHzub-VWNO2QjT-tEJD-dt0HAxqo-DF_aQ1e0seZJ_k-q4RK1p_ajUMfmCm4VAtZrypN247KBa2wDPFFE6SUGSWNl9ZxUlppBuLV2T_pQyBgEWMFsPV
F-hZy_wrtducEUDDq4Hs-wol2zJzattxd7zjM7-Ghn_p_GVv-ZBaryy_-_fXtoDqkwytVMpmuwwV1Of-lFVrde_I_Uzmh_bUk_-VvFjzFv-_jGCGeuyxljBb
VzyFS_PL1Ei6c7q8tYh-QHQplsm0aTaNyTeBk9jttnz-Qu1t2nV1_0XMaRFu_MCMCVW60V2-0l2T1zZFyPS6OEIh00eWnm3aRrGn-RhX0_Gqyz5FfAaPG0TU
hKL4awzS0gs0vmPq1YtPP_OXSjRzt87qbVoK7n7oaOU_ME0ojS6tmUVm-LUQVkq8gBcFFfxvmtsXyRZIhnVGxclw4qy-yNiAf6zhl-zCdUVRaAgEFhfFFFRo
N21zNVfPO2kV1M2pp-c-YCnylO03z0h8_7WlmkAbeteRW95Fe--_LwMdpiu1gBNeemCzUyowB-B9xomGe-z6lZlvyIFyGxllxZhmYA_jceMwhY0GHLMc07zv
_xUznDPFJuTpUvtE1JDik-_hEwtzukEVT_z2p6S_CTDqygk7NyCCVVCBdVmY4iv-YnxtdyEyxFvGZGkOvs2gyya_-zm0vshQ4LKAWDHCZq1W-JluTMa5e8vK
9LMu4MCK9cJ0PVaTcq3ecSsCWKGpuGw5USBMns40LWl0m2p2oHgZIOChIB-BF_Ao14nKpGGxH3KxBfIIr_JHWJu0ghIc3pz5ixvDv4eBlwC_zl1t3Z_7A66f
1AAg5-Yz1o3HY915x1AhVQ88lmUfjs2UJyV3O3y555TzJkD8g8qWNFNZC42Xzo7dRFsk3BPqbJ5pd15JXDxDdqJ629uVV0vxojdJ7uL9OqClGpWU_Sh-_X0a
3an5MDJi-5gTvv-wVrdOuWKCHjMr0BaLW6ZiQeEemLpLJCoEVf0hrlnNMXY7tzelkFeZXxQTmvflm4zSzSbx-f7hzAUTYnzwNxzK__IIl-aZzCxvW_lYPrKH
KU_wM_FFp_pZ6gd8pyd_CjI7Vpm5U-Hl_IdvXt_1Rf1-LlxJoF_yUludN__h-MSr_-bBNt_WwbVJvEtNj_AF0FwI_8lAlW1AyP2NKbxDVzKB0j3yu5Pteyt_
UVwRdUaKW7BYBZVysQh_bFzgfzC6eElNyeHxx1X0L1f-DFwq0T2OSgKyvmvxuv4R9XZ2Q41llsBd2_rpRh1NjdoG38nPWxMynWrsZE1r7kKjxj0t7kkQdxD2
_WOtw45AATUt_U2NKyhb0zpcpzrVxQfIzPBIUgk_lCEQ6eS_flGe7-4k_tRn6yh_imi0VzMdxIVxIyO0BAPqxRv_0501uA3_q02s37ik3deCu6ssDQzRST4t
oWTmieDVQGU_KWv-gHmuk3r7CVboc_O_Fm
}

sprite $osa_ics_plc [128x128/16z] {
xTRHRkiW3CPn33QXD1ll_xOdb9vForGl8b1GrVulejpzufXiDMgVujzDrD4y7ZsF3y8EsLr4v2J4qfDy8JLJ8hd4qXFuG3bhTJzdFVRGVtp7ZoD3TejCZXps
qDLd8bOo1iUW-nxWEx8Ax-3Z9HYxn7k3VRm4OknXZ4z4lru2IRpNmxV7FlNV0tm-y2dtS0yuZ0Fz_Hvyl3VOnqimBiHxRRxROfOjloL7VevC-nxWMyUPNafU
EV_AIx3OGulFYlzdP9Gz3F8j4VOGI-TzsViCNuzA-psSdd-fz8cGAN6J_p-fzl48bB-6GVx3tolsfE_OL_dgBwPHFYd-SjAN7ZwTztsTJvrzVXbVF_ijlZJw
rEh_gCdt8tnIUZrVYizJ_Oylx-sxT_PbjY_orZvlOALl-_dEodlxhiP7FNqqsqVmzPxZ8_Xgp_8HVANPlktdEtOiBCpb3lv1lNps8JWEwtgxE_PHk--pxq88
tgth6czt3F-uBZul8J1VrjLNp8-QVUnV3lP_s3bVQQ3FpZ4kFDndoUUVyoNVZVHn_cyNZ_C_rETDPLxoGsoN2UVF2JCkSyz_rb_t-_luyaB-n__uFDjd4NRx
-CryuNqopb-ovd_rRZvlkHyDzjlF7whtkvu_Esd_y_tvxvy8VklvE-FJrcoVEkt_pNobLzi__9J6-WX-gl9zp_z_oyrFTVxYzvtpQUCfnclAZPiV-1Q56DTg
Nnht3vrZ7hyqqATRRedWw_ocxvzASecvDQ5Z_uhpzwEwyuVHSzUlb6hy5Vu-nLTmMqQ_hj-WAtrn-zZ3lnbrewCZFkc-zuglZ0wprW-IVTudFaVmwR7E0QEV
yx_kFaAwZz5znEXDlXpxwkWuSi_pBNpWJXkzlu-WMxvWzA6-zhNfV4TV-KFJvfllFtrhI1kzavzYl8YQCqOPlPs77tt1-47Mc8ApCdg3Zt-0ST4Vm94nP7qP
_OhHctcKOkuIr9Rbee_UxfjqZGTXzAuyIklr25yJwiUZz8nCHRDuD4r7qtGqWQv_2FEIVVhq3m
}

sprite $osa_printer [128x128/16z] {
xTVdagiW5C3nKsY75Dx_RIz6Duop4aj0xhZylpi_YWt8rElrR86QuQdMlZtAA_uwzOMFK29pr3TG97NOxtxtkzzzF519d_PtAH_Nw_VVl39-l_zmgAN_PPVm
QNz5VTuVNS2_mls7rU-_4tp-sFLz-bXTVxqh-_ZNVTfHEp_V9NpUNrbVROivLT9N-plgz_jFfahwyjCgdYgv_v9QuQlxii8RnMCc-Ro_kQ_6j9FO9zuX_AHh
t7yiiGy-GbqVT4Jol8OwFev1p4KcnpkevQS1eCGoFjNo0QVI3Ypm1kQ-XIBfvETtG6A_BcCe4DhafnrOy1NCeY7yEXg2-O5qqNTGBqob7SZSVDcmJ020IpwS
M6lVDFRreeynEXvlBUlJ5EwDDiHgQit7Ij4s7wl5MtmcVDq9n5JwNK1wtMV5Wmz8oY0K3Tdebu-OzvLM0ux4okd2lhBhlZOQWPXP6J65VRt5jmO1ZTPMxWgA
HiQPTTzP150Y_YvGDh8RVEDSz86TQ2WSEVdnJTRNuXZgf9peLL-9MAWIEX6rwfCLiKpbKv6twjMoZ_ZoMQhbrAeVOojricgAAEyFAMqEPlCPhTRzrNXtQbxt
kzzz-wTzvl_Jf_FyxWU0L6ZW1qXy4pyaVl0f-NL7mSmk-h697tsLyykFHydeXxVlHHpNnLFAYVYt7rv9p9fvjavEOi-HVViFERLxIFwKbzFop_3Rltllp9YU
KbFyJYscbyhz8Jllxs713zvxc-TNnh1v13OoOT6_UU-TVMNUwKyTE0guYDoM_U1FAcJyS3j3lytuM4WzxxVAtPyXupS8nbhxq9QFDU9JhVXK8ptLJ4-rqrCj
xTG9SljwlNy
}

sprite $osa_server_database [128x128/16z] {
xTVfOfim3C1n-P8FOBp_smuHfLu32rPGvhNb_o5tyfET6xvgLrUblQuyrPMdti5dQrgowGq346-WBPFL1oXB3g3B0Cm7QC_o08ey0dGPWFa8q6K0vfC1OKvh
WC8l_Lu346y1EWrGttdoF0sWzywJvylIQH_XvOA63wzdE_j6oJSlfUVRL_fUlfVbjFqWp9YkljVtlMjEqx_yox_yovVq3NqdJDktF_ptZnEcxBiWhBFlZT7s
lMlkyY_VAlgNV_cIlfzllPEbxLiZIzkNT_bWlwll3tkl7mxhx7jZr7qVCFYxxni-_rLzXsl1TVAH2ttyW1ZBK2AYx-8ZuZ2EOq4CFNo7c4Og8dRo8_43Dlls
1Jznk_jV5ZyZ1dK_fh_suNj4J3aYehlvpzhuShhc35WYyPPl-lohVfiTDwLQN3zrFFDA_fRUzpc2dNVsbdlCFdRWL_eOvsAmkvdTdlevKGARx-2jeEhlyiru
vkYqr_0zwIAyJk0L_5q-7U4yWDFmfGldIaufdFOB-rASIYcwitucNxBhP7Cv9N_M7yYNuXoz0CxwKqf9ikkV_NBUB-A5LpuDg-yU3kl91d_AKhpoPMBELPaF
s_qfItQT6_BAJrx1dueC7uP2El4AFZNo5XpRXD_qF4vAFaNxkVOSBvblLnQTVKESCSGPGp9V8F2fiUJ4xVf4StcOxdc2F1-IJuTyWNDEu5FZGCQpSXbevSzz
8_4tyIPlwSpqesy--tzU8FThzFzYRHohA_FT2N-JoFV_rlTttn_uywpi4nS2SI6G7m9Vm2_BZJ_tzcTDFqXzIjS7uW381o2VBzZtr_wD7yB67-Q70URJFfpn
vxVuqEhFf_r8oqKa3f5ynCL7FF1dva_xkFM1_D3Wpskd-67nJKS_8wv-kFj1xFywmG_XzgNZBC1oQ1R3EG3ukE2FTlop0mpUsOKtqDJMFpS0yGe-zH9VKbp2
fT1MtFglRy7znr4HjVNb8x0kvgcnyjMl8pJDyEjJawGF2Ue0xKCGFQi4tFpNU7LrlIph-Z1t2MfzUQelJ_NKkPuwrykMZm1lhHUzxTtgRm
}

sprite $osa_lifecycle [128x128/16z] {
xPTdpXix300DQ5rKoBd_QTzBb6RH43xJZ9Mc-Ut5i9dSFNt0PhFPR3QRpMQp0SjokQfAHrMXiqmkqYoYAq80LDe44O0tsvlbiGfhxPPtHM3jSnJUO4VQimYm
DdcBmeBa5mK0D3SAQsjl4LYkjm4irzi0rkejodlryfat-wTkVg0Y3dz0R-J3wy0R_7JqCsBjpnod_YkY_exEbxkDmFevnO4dzXhmwESd-SKcF_-PzHEKzogg
qKy3i7wv4Ho0xiSij6S2w0-s187XRxL0znlz1FjHG4cP5pjUSwVdWHZz3Ek_fGFyVZH_enS0VR6CrvJgA_wQlwE1_n7db2xu7oF_e3htoFqt8KTA2Tn-oNSu
duVhhJIbapxHUBdy7S7TzCxvSilf4rSYvUyDS45B0mVufp_KW3GY-DiVQi1bzBiBM2FvzwqtS7C_F-WBxkqr-YzUVnweRZ-76S38-FSB41i0YFZ5xx-DVWtv
yVlpw9VL_chzaVMZVdzRvlVdxv-_FyzVN7vBt7-B-Kjq_vpj_bcx_ndrn-hx9-R-QEp-Q_3-Pk_piGDepv__1PGIQG0jZQZRtm8N63lzTlpz6xX08FqBaU-V
ZX18ln7u_lDE0EGKU_st3UXKSFpt1medDs0Be7Z_UtRw_0NmTm2kLd_rwZjGihy2cCDdRb-i05d1DNkTCo_wATaYyC4ZHcx-VD42v0hCxLmUzLTUzjFo8mBC
VjudF_pVjnsmD82J0Jjvyozl_nQsL07WpWsb9s-vm2a0aYUKfW1qlLRJUCVXTMn1IwFhpRbpRbx_25XzDL9lzVq1nFNn00JCnd4illWCADXzwzVx0x3wsrH_
g4FlNOHuz750YqdVd7hNrlS3j8VNOP1ZeYy-lRy43UOx_n27tXD17JemkNb7TjWzC4H0bu0TWen3xmIWbRltSLk2I_7R_I58BT--YEvASBvM7FPO2AYqxovG
LHpoE73l2xZNiTbiDflDPhFPRFu7
}

sprite $osa_site_head_office [128x128/16z] {
x9RHTgiW44N30CoW_l_tNgfpOhfg6LAkQhiyJ_jjgnfs7jNTktVlthrxzsBJTlIJCqT_sU_9dD_Ltx2Tdxzd7Jt91T01xpznAcCMpo02CPtXvtFzk7y-olyn
oTcpaj1AVVwOwflzEUUXhFX11EhqnnZgc_t5f7uGyGBTVdBrXGlue-Xy0X63EltUMF4JUTqsxUqFndgVFx4kFCbxKDYpVpZUqyUOKr2I677GnEFzVBGVhXHa
oq_6klsYnsiAe1YVHCuRw_VhePf2LeeHzAd_JqekWERdtx2AlvZK3ueHrDJ_uAs53h_TV--i-OgVH1SzA8Gd6VVVwxUErx3sNxxlVx1MyVlAr9_BQlqFZh0j
mltlrb__45uc3iGhFVRtumXb1vALuD-Z__r-gkvJ_zqcBSz_qHShpx2IvU_l_-ndaPo7Olr2vlDddVzf_uiVduFR8FYD_XdztTcVJlOpyu_xxny9ELp9iIx2
N--__Bp_mPWt_4R_2RVqNVy3rLSStVtbP_-uZ43T_Jk__twZ__7I_HUXbLpdz-T3RRDVrluh4KkXw_IVBzJ_k__fj_UVw7Vr_-w_B4iF1ZdG6_q7nVYabkyl
-Fh8x7_M_Yd5E1FwdtJEVw7Oqd_gxI-Z_w0_sVyKGF78_hjp-n_UwRzizB_Z_-V4_xd__4t_Gvwsz9CSrFymJDE6VkIc_kTbuXE86DJebn4NW4r5dvlyhjf_
zzf_Nlkl17yUY_2pViYslxt_BABLPyclfFuy5ENhiy-vmT_VV_ZBy0wWFzIl5m1_FiEVfqdrmn8uCVtlzPyt-fzU_FFF44z_QFFtzvzcFzu0dhwMpjXB_-DA
R_P_zUVPFy8_ZkCmrfQq_wpzLo9GO_zM_pZXxUC2R7z__rV_C9M1xQNk_iEFpNwiqJzlk_zTVdkpNmJz1n5eVx_Tt_Vzmqb-V7zZkz_kVxiV1z0qlULt7dyZ
AIpxrvvz93SK0a4OTWxT0zp_j0vKByQ1OIXJLlnNsdtDKvRyhQGFkDSVGzfFlVxE_LS0_WqWxQV-_twQXezq_Evpf__CQVBPVGtOvZ-jyHgmqqUSvnS60CZv
6Lsy6s2Ou6cV51844-y6CEP9PlpxZ4_nFZCYvldwcEYLPEo3FtLT0eH-li273lyp6ovOzV5He8jVk0PORl7ighN1Wd_Gcp9Ds9bmQny5jYgQi1alhQa0LrKJ
zkCgqFq48_4NkjjMc_A93olM8x1CWsOw-2Zvawf6a0HIC2cwjadoCoEAAVRmBVPC5T7Jd9_TKMnGu0R-0RlwDpS7vcyEotzqI5qTKbU7idq7nTNXQDy1QTy1
t55hw0dr3W
}

sprite $osa_server_gateway [128x128/16z] {
xTZfqjig381XC49iwUJ-xxR8Z8WLsmqcsExs_lWMpcaV4QzJzQVsl__5zcxbgLjvwWm-JBgboPym0F5QjQN3y05YpYXrnm3CMzNUL0OOoQDITmp0l5FgZW6O
zreTp8mQ8FAfVzC0n4zAtJC0NtbT0GrmxPKdWvZxsaVLdHtXg_wcctqzoDTTZVEddluk7uvbHllsO5hVwiDu7qnpH_p_Vjhl2Z_zglDzOPNujojyCiASpxaS
OeRBqlb-oWKoQvMduWM-nrSqI22UEzcdtHFhSyHvHB_WlHzz_tkazsZ7DKH7vqFDXy7-YgST1wwSU_7Lw_Ct1zlnrNhxRhbzltVzJwFUVr8kUiuX1hbzsGdl
7-LJv-JsqTL2kJFqVlx2tnz07lr5XQ--iGUJ_dg0G8RCbKZtHHV-mFUF1mt0UvTvLpSl_A7td_q1dDZy4Bzr0BdvatsLDWRmYEZAvNcwhvu4yG1YyocCy3-_
__C0OlDN-Jo0G_HYy_FYwRuSe6m-agqKhRbhV1u0w-RLQ3yurp80RtxVFrRrlLiCGCX6tiVtXH2v0RvBSx6yKpT4hFGdCCTY7u6VfJddd5yNAF7xukVUzm_s
hJQkPdBJNFs_SiPQMkKC8W3O4liTiQzjXWkqxK-id-GRvspn0SpSore476A6iVITFrM_KA6fk7Z-ZF31yVqqKkbp8KHksuUFlVp9EHTJf8RvzcFLBzTV_Qjg
UpRT_z05hjC7hOllNOxDHZzi-s3H0llGSFzdN-tuAEF7mBPlSCwQmxxQy_MwsVTRFcB97lEZGALlz2JJnNVeLxwTFvpe466O3nh2CZ_xX8ILZuZfyNX4H3lC
nyb8VvfYFVpIDuZ-GJd48JuDa3tf6qE-t_OTyGcR_UcZ7uqf4WSGnE6Ndt_CVa2qm_m4WCAtuClXN_k0Y3uuH3J5_rMjlhDM-6WTV_pI9n9Bq73_Q_Bf05Yx
j6XxvFkLJm7pu_oKmQNl4MCARh5GVSg0uP_UczvhysDvDDVcHvL_yItl7tgp1fy6y780xtrAYt7OxwZDZraCedcjX8ZnD9y726_5nJzEkJ3ARn-Wt84eEXbE
zXyx0qJ-A4xsQG3YHAbsja-bLQFz_W6K6k7tzzlwneYlSk5alt2colpr6j-Ok_t_lgQlMXEdjLYumYS8e7mbFt_b1Phb5bzVwslfBnTkzk_RFrph0_lmmNy-
LN_FjJzprX9dBVdMbWK-BLV-ivyVupzx-I4-rSVl-OeufSXNYdnUsFQf7lwuR-tAJy_IA1y0r2N-yuYlBlOHYKCa7p7xYFj-QQIlf3yls7_Bj-pR2tpzQlvx
bJ7vgpP6PyEOvSAYKNvlVubl-tC3_A_gzdc0zAt_wEJ9ftuyVdpJarF7UmvC_O6-kfMdRkMfUtdgNfswK-S6sFVtlvy
}

sprite $osa_site_factory [128x128/16z] {
xPZfOhGg342j2261gU__jXSJcSyHCZgzHU_2-TFb64_KhZFyC-XqEXrY6XiTyfCn3aanLZ7Q39YwKNOT2CqqMMk9TcOcNpDXcSac56U3rS2PF08WJIODE0UR
smQ4BXbJ6b8DabUC1halOyQKdvO1vxr7GZ5sB0nLZFMGJ10pbORUvyTbLxvV3i3PzCRJh1h9Vsfqw4jsdMJ4ydtpz6gcPDYBmPh1REp6s6nK_9Z3orl90wI9
EPjfRmX6pfScW56C1e4ix0mFE1a030CvDc1t1XJ3crd5g22OpS9k0H98GpWqfZ3a32Svlp4ugE2uBEpCUYgG2KzFCvN6ZzQz67WrTcUGz3vD4q_8mf11OWDr
O-p7HeDmj3mX2p-XnKpWfhgndneLGcicjrjOBePKasVSUQD22R-FWASZ0-TDxkli5mPF3SpxFjJFvNO6WshoZ2lCF1om3Zp7i97H0O1Xy1ag30YdZIlDCVI7
7vYWczDzPBZIp1ptaKWp3Vgzt_kzt_kzt_kt_luBr8JJVRgzZqtuj_Hxl_TxdtwNVztrUmPNF2nupBp8V6mLBtpQzm9i-xbHI4QJCkW_x0FmomVFSxe4y4b_
AC_sOmpSzwzd0Vv8J-WIigHmflxiyocsznG99I7IFwLyj9MmaUoG-p4UrrES-qY9FsUXXFIF9TObKKmSra_sFvU4c3TGwqpbwn-ya3-ISwFWpqb2r3V8zTpF
SyetF2nivDQ28WanRr391x7IRmBXIl5r62MVQVNp7pSBHENUDx_-yXdmnL_RvrkWvA_fomBIhnxecVKj7k3T0lZye_T47sDSyrGzS6ISbRS7VHYPTMWwrQSO
rxklzBz-qlywtUSdm7V_Xkjdk1_kwuV8Jxz-eFcyRzQ-FTcdcC0tVME0-yQSw1iZVMFEzl5jFy5zVdlKDmmF_L9_MllcJD__U_jqNvzYhFxukQZFFu1YlAvF
nUsl_VWdEGxS0e1Zy02_HSadghy0YiCQihjyxeTQF_moPJzmNrtWahooG0EqVBa0qxJDUVqFuFPG2gh_0BGdIBxyj_yIA6Z_00QwfXxVlFJGlfxpbz-3VEqw
yymRt5AVLzey1ex7EQ6tCmzPuRVZZpcZnpFViaABkB2hQol44EZlfBaTl-SAUdxx99X0z76QECqNhi7zGxxp4Y4GdGg7dFwU3oZw-XAFk18OsX6OkFAGz35g
Nz_Z4LNqhjw_aTuVXflpmxtvnBrrvjuwSsSxSsSySsLQvzAqpkLTdQRHw-bqEftENm
}

sprite $osa_vpn [128x128/16z] {
xC410G00100W_rTx0LJH1m00002olRfRRnG4mZZ-19aFm6pk_svtV2jjw6Ce6Wmd_W_Ox_qvKqDZXmRYkP4y6icZOtpOaxue7FP3aHukMiV6dsxLN4DUDHpp
mR__09GNi9kNMm_V2HRGSVpzNu5exUOPme05hBxhvKzv0RjuklNm4Uzx0FZQRNmi8C0VCNxv6Um_VkzN47pmpZNn_HS0NftLmFTVG1uVjV5TBo7mud8zTCIY
yDjkNlTK1zoQH5eM09xTxofsrmNayRk71U0LR1o_VuG5j5mzM7XN-zQs08nF-SlTJrzQ5Y3H-llgkQrruv5p8k5ltv_d-xo0-lZdxF_lps1vyxhkLHS0NeEu
KsCymClfsw-U_fSGncTtSeG5l1fVCVx92r2ZAkEFMK2qCFxPJOmtO7FzqjlQoBF8jgzAVa-qDqRcXnV--xptnjZ1TlZreFKe_FYU3pw5hw80deXecaon9Q-7
_pecy-se-s6_Bn79ugkg_w1FLj8PZVSDLfKF-lJR9_DeeEz9gDNdjtr2YGHXVdiEVvfFcsbSOo8sdx9lXvWluh-FNJwr5TFQilyqHy-BBuB3um3TxbDJl9Rt
pyhC7hz_q7yyOZA_Wctr_VufxbSFdxFl2GU-g-0GQyC7_qWfgbQykY-2-qVOUrQ5kjBPvyL7Yv_Y_2ZurUUM9FVi4tnPVIvzoZvQ_7H_F7xux1TAjT8Fc5_e
sISSe5TVLN_yVsPcll2blKIAEAWAA24ILJj28E8G-FiGPbtwyItmXI_rj2ZbWkweucT5j4lXEGtvARDlRVW7cFP---0BlwBqI2tcc1BGma_wYN079VZb_h60
CZaUrz8DVqvM3Djr75vKeqbpwUS7c4_Fa88l7i0wNmTV-hdxFDzFRLwwPoxV_sC2ZuRoQ2YFXkfeh8x6uMNdk5TNLrTNLrTNLrV_0G
}

sprite $osa_database [128x128/16z] {
xTD9kkCW303Xx9gP-z-sCrS6U9WOMHlLFjyloUGqoB8iox8iox8izvKAsav1_awH9a7x7ydCq387hHjXIgP5LvYXQTLR-0LVzne5S1hpwt7ldQEbkXlZzxOD
CALliOa9XlnAd9XWB-ycSMA0lY-04_vF_8GzDG2-14uX-BzzWQjZN-lw2LzWyMVN0yI67_25SFpGy3t-qgiJ7y0FxY-m-F3-sUFBuBo_tFAZEoTmzMy_DFqC
8B4ul4jjtulYy2wt_IHmTO9F7JydKJp2T_oS1lOEF0OFt_Dpai7HBtpNlnIMNHqStQSyy7FoyFiNl-ITGn_ubwAZlNZmh1CXcZv5xsZU1dSKKXxwb89xRVgv
iJVuZCyHQ1EFpEyu_2QV4XSahW5v2TUH3-0pFl4LDuUTCatxb1XYajxlK-9TTRfyaeYyrgTqBbxYhvPIWjtXosU--UQJ-UQRN-kXVgqV_E5-VTCL_0glurTu
3VyIlBvVZ-OlQViLlnODl-BNO_bll-ZuL8xaYPHuKkAfAF4agfSwhYZfL0xKJ_8Je8zzAj8ulkm81Rt1upShHSA6nryw0_R0Pu1rKo2F-KjrgdAke-9Ey0nm
KEYan9CMJqewQUcafPEQJcewQU6aXvCUJdesQT3VgSX40gv2bcLPrdy
}

sprite $osa_server_file [128x128/16z] {
xTY9hkeW481XO1Pc1czy_xUzO8DfzLYd7awuI_yaxlgrW5l3tzhPcVcRohUcygsVu3L5JqciDjxN67n5jTfetY24MHjWDGh-abfjACyXpDe0g-KGPcs0rII6
Wy6e3R2-z2TjGEDJ2BCsm6eGFWgr-SFVUVxGQj_sENmSZV33vwN9VXpanuyQvwTF-hTyF1QCzkbWCKxrSRoFuExqJ__qJt_Mvzy_wCF1HllfF__z0mSRx0CT
RBAFCOxs4ToT_kcdqp_zIPz__vwV48ursa_nOFEFVvn--bTzVDlF-lIsoJx6EDn7OiBke-FpVwWFV8jWai-yH7DyOivMB3FZ5B_o8kLYp3J31sPHBPTBPXxb
Mx6dT9NSu-RdKld2RZ-zyuDHN9TUHPLaPhjSBifCutmChfgFp2oQcHaMVo-dNzZl9-8bT7p-xVYsJdm-SpEnyz_npN9DbhJvaVQ2cq_f5Y2a9NWiFVR2r-Rt
b4DRThk5MgQqK_oob-EV-PvYyryVmEar_t2lVUff8zBhAUm93lGbSw-4w1bJK1Zft_S_QsXBYNPhYrtIZ-o_uit7LV3LmcOUwUlTBp5L03SzyJN1eJxpVVWR
JtiXr3IDz2rdlcKOmHDB6EepKujB14IalQ0b57vY_qK2VkdZGnQVVO3DwVQ6NRzqto1rVNS3ieIjlt1mb_kfp-yVWBc4hkzlWkB61_YkBvbhcYDvoXP-n2y0
HFe-CrdACD8N2qXPsP_ItO_jDCR6nRYvmUDhpip64J4Bk4F3xbS8SJbjVZtjDm20nsVcaW1H6CWN0sdQyUC1toHdiOY8IkZa6N9U-N7hhszm-3cpSlCDqSaJ
ABjySFdP0AfjNfxRjhxnqUsBI6bFO0MFtaBMjFMn-_Z6lrx3DklJdmKTzEABTF_64JMEgFb4_ORcn_ZaNnzy4PK809BHORS8bJ_sQqy-f-ehunkwHsJuiTzw
y0sXPYwxXMomyaFZGcX-2DNlDxpmMsjVnHgFvg7lq-_nYPxySbrwzbdHORU8b5T7FiFtVQn-pXwxHMomxuSZlebHzPM9VL7MjFMP6yVSVERgC-_vhOtFrJTo
-vgtVjZwjnleYA-SHRq-iU50lrI_9GU67vvywZuTzOE9jZ9xanplBOSa0Eff18ZL05ZVi6hVDtQd43vfrpTbRw9Xf7-rgfi9B-MtQQOFor_ursknwcls9lPv
h_nYulRLljFbYRzUYXxQ_Sklpslqe_-hc8axAzS1XR0PW4CJEDYVKLWrbszDvNlEPuxMZpTJxmsmvtVs6m
}

sprite $osa_server_web [128x128/16z] {
xDQ7WOH034DH9sB__IvGmLbp6g9_0qzavAbLrPhlKlxeKlwe1x-OPhAvmu23Lycb2tt0kkSYq00oFqW-Imm0-L447a3a9n7U09oVLS2SDM05RlqU0mxUHCW3
y2SFBuu1l2SFBzQzV_kZD3SmV6dFBlQLv6jJFDzQUfSVMCxs1p3LI_tW--7fc7xvvPTVFj8BVGTZ-_Rn_ny78_i-W5tiXohR3qzNVlb6zCil7-bzleLZiNrJ
BBQFLxxOM_tuixv-ylzlAxvErnlLOG0CQvTjUPhxlzk3ua0TwAHC7dhw_UYYMLxXxB_d2-BblgYfhBwSUFw_r6Uxf_nBlZtIt_7Lp5iqDvDVyHU-bEZDJ7_4
xrd4-7RqsQpK6hsxsUL-MyZUenOphotobtxqFRSBE-tJIR_tQ2e4zt29jEGE-_EtrdklPdgflqYEy9c8C259wT5dNonl0JSp7lwhplgf1mCIqJenPb4L9gcz
zzLFqaPouldlhDzxA2my4ycOy3rHKoPjqJzzafM_pEzHaYGGHCm1gX5d8ao8P3rMFsDX6l4-sdV2xo40f48CaZwR4Zry0YHareZXlmY_x7k_Tm8mqIG92PYH
Y4HoWuKl22H04Uc_rMi_UJ8Y12PSOisbi-I1XNCA57Qzlnw-tFyMydHecR0nAmBaIBfSxYVlurmnl-7MUZTJ8nW-Mj0F-8yvZQ-ppmo4C48anD8kzoCGraXK
dds1jHmWXL_jz_99fF2q0C7MVO0QVAqV7M6BDDqNFc6KQ_tkaquuTzVLX6JoBVX2VxvyrIy-jfemiu4zVAR3FO1v_heRVElt2e-OzZmHytWDL5CQFgCtsXeS
R_BqzQmlC4B3NTidDn5HSny-IUTLv_Vz_V6JqO5FFICXLkNXCuLTv_SO06XgJmr-T_yNPghrGhy0i1jB-lIA1n4aAcvaCVcONn6JGvm6Ptq5T15cfcp_s9_Z
maHIYthdrKz8P7nDNuJM0JEVyGbOxpvJjhlhJI6w4R68UvTNFlwB7mIaJCBp1lHevrFX9IdsvEEpFm_E-0A08B8kC8TxtvrPwkBhAV_K-Gin0B48Rr76J3iU
IGfhQqN3ll7bj1zAQeei8iIxQEzJqLhRyVfbzUKR_tOx-4QwX288o2IhBTcEJr1Qcsx_EwUQd6hwgjjW7ClUto_GdJGJWamaxKSg1vwjDVVEx_ktdL_p_9SO
xh5ivH3LJF7JbxhufTExVlRiDqf2bM14cvwvBUd6iqPhLcFo8Jc0z07INmTV-zcJtrcI45XBUyqobusNXQ_MwXbVzU37xR10TED4U9h9h9kxhJoNbdU_C1g9
2BpfptU0L0ZcPDFDbvW-Bxzv2Nxfmx_vmUfv_NFaa-w57_pT7yS_-MR9cQLljlXch_nizhlnOXZCoQHxAVRWqoyUzkJ3ityVw7b_782xJ2CicvvyCHxyuzxF
b_en3i0PSHtfXdl9zC7h_VATzhwklhxXhmVWWciowSCVV8rcjU7MU8bc9W1aniLWdWTJh_pkR6MSm4YVz5fLxdn4Sm-1T_gxVxlrhfBOzXQm3dpbgoV_EFs6
r_hvQm-LuMTUaztqxCvR56_XPlfM_XS_wqqqx-R9SvtraINVgjSUqTxkw2UVVVIQ2t0cTS97hIoyj-INtlVxNou_5sYgpbcfAK-rrggPLwkzVsH_tYoXexyk
4COi8jxsUlerR_kU_yC5mS7FUXYnbAEU5VVe7xSVyxFUcxBlxQowrylvum8VlLTJywGdlAIUPtyzdzsc_lIedYiyxlsbkDc5UlAl_DoWHqjrv6N1BzPVBv0h
P14j5dh1FtvKpsxxriVunnSsN6gFtlX_BkvNzT7_ZFy7
}

sprite $osa_warning [128x128/16z] {
xPbPRkj030JbVPccS__JPbDSi1wYU2ZrODvM_qercxGj84EI__pdFm7GnoqbCjZaUgTCa4I4vl8o0n4QoWi87X99ZI8WnmpmK4CxktwaGGBio2iYn3jkky2J
m3yxy6bmwB4lIU3HQm5VIrYfLy9k3X3ebpBkmDnzFa3qqXF0j_hsHu0V_Ue44Htqm17sq1CWltovu0Jij-SFu6-V0Ftq1F3h_JTOTtlNoyZrav8em3F-RZkX
90fmZ5-sMRyemBBzxHJJ1J1-jd_9K03Zf_sxn6VGChxs4_zUwmjWVDLmIFefm3E-ZXF_GOa27EFhDF4VQ_rgupyfKO2ZVftR-4kj_pBndsLO0FNd_PVCpx2Z
Vbqd_giI2t3KhxBKhrXLFqpyHOO5K7_Uhsfi_brd_pxpymV10UJFR_u7QE_mStvv_o7v7kpm7plxJycVF_p5up_dVdwWYJz-OPbV-1C_G9lDC9mHGtF_TRGF
7rpYEzhwowTyv1epjFHl1YWHbGd2TN-XeSeVJVmHap-Y-0ctFqOs0yGJ157M-kFEbYStyPG7lnRvaSEE9xTHmVWy_kplBtROy-0kgf364HUzVo270m_kevAy
7pd0aGUFKKts_GixW0vtYia_jZCZjy3vpHzWHDZT8DO_lu18uwcV1JIaFFUNI61RFmj8-Q-d_V6Ihz-q08tV0BkIhT-p0Bw0DyhMR_a4d7bgdwlVLC1k0Asi
7wA-00q3NAh7nvyemEGNs_TSm3RNFzjt5N3YcPrjV0h87E2cv8xFTW7Z5y3scXdVMK1S3hl3MM4Sdm8KHXZV5y2l1-goaVm7E4zqqHD0OIAbzvz0OVa9loi0
JGwT0XJQxn50w1S6A5ghrmBzopi4MAz_UITZ7xdn5zPzxcyl8mcx8u3ANGyf_ReTYEuVoTYfe90WERo2uI6X9m09adRqZzJg8P89iDFzb6e_y4UBLBNtKh03
fFKaU1f1fSpR8Qld35I-qEpWDFyJIJy9HWi82YY2ipFvuNQZvUz0ZjtdXti4XgQAO79m-ua0WBordrL0HUc63u2HOPPEUkYbXsv-w6M7RdhePOT-UkWcXtvs
w2U7ZdBewGQ3se5Pt9yt
}

sprite $osa_arrow_yellow_right [128x128/16z] {
rDKBYjqm34PXwu_j_U-uBz_9mJ29g2KG8zubz3lN8oVjHy-irUSivcSnFulvMSpFOduMybtu1J_-ClmAlhNbr_1gow_XXpNy4Xw_OF7_yi8lu4stNx3upOHV
iFWc_18Uls3nJH_V0dw4h_2vTohm5z_W0txitbNu--BlVWsFNx3u0J_65_WiFlpchodWyVs8-BqpkJuD-Ol_uAz_lleOJa4cZy-OwReRKXV_aPVP5c1cwXGa
ydB7xlawXRJldSzVQxugH47AlNDrPYz8_Dxv-fvm4P3umV5r2Ze1URolKo2E86VnVPvX2mhu-mW8EBbtEk6Piu3rwzivpx25YRi7xuy-0UdB3-y7ZFzV0Tuz
vpm1Cn1mphC3EWpe19pm15o1IsZdF04Z4X3rnL_Ww2rePpp39JmBQCSy0R7lG8o_P7R50ipXmmVWlmhX6Rj7SWwWXmCWyFVHom48_p3WuTqYIKw2_mxmNmHc
-lvdhHdz4WbP6xW7s8k_8YuA_0sC1-2J8FksL6O3_-mUcjdBMkq5_Ws81-3psFsWNbBJ0lXFzm8H45i0vZxQ5v-2Yu0alzq_pF7RvC9cBS0Ue7UVWF0Rm3jP
_7tMWti0VaA0uxVFKIdNvuV9yTldkcJxV0pUV4ALx1DW-8_FcLcwJy2xtpY0N9zN8Rwx0VYP0VWFZsdpUv9FWETtV6Nvl0hndvuQB82at-tQXNBiC0o5uGjc
nz7xlsrpbXoOd2LPG_qB0uKlqZ9u9Nvz0DmF6p_e-N8xW8ilkzPdW9MlSFQJNktlVv6Jy0l_kk--yUNOvG2OdqDmAzz_w0kPBtZYozh_RFr22-WL7y7Nn544
7r_pFNnD74Nc5_ZhyQk8AE8e4Jyj_eDt_OHIqr4-z-FQtonAIqSbaREdsuxVqz8HyTVZ9zaqdCyX-FMPN_Pfwlpan_QB75Ba-SdlJoub8_c4zPFjNnh7Dupl
sFOlZU9nwdjtpUEyVzOWFc_uAEUD6f_plS7Rzpx4MLW3_1ZNV1DZFosyVon_4bk_ynWUon_gSpw9sFeJ-6i1lB5V8ixw2BilqhEu0BQKmfKF67v-YTVpIuhW
RpeVNlyAk6Rm27fkR_3eUpsjz4b8wZV0SysNuUC5JxdAkppwJh-LCfcTyKZUhqsrb9HYIX6JbzhaGnwzE_cYrvBHGfTQf_aR7RtdBxMbQS9ts5_oI2pwmxB0
UIOwpmJdcU0y6vndPVEiQ9ubp3DGBVhjjny
}

sprite $osa_laptop [128x128/16z] {
xTc9UgCw38PXBDcI36rp_tTx-0dfGp01ESSCPyat-_g2PPQPTl-KFdtwzEdJS51_N5xdjrlfPKv-zSTjBzrDVbDr7G5qKobA-qL7QJg2OpuHyIDgLWY1rUFB
oCVaAGfMtqIZ9mg1FNuaYlvm6AwOGw2SxT37yh_LyGJ8pEkBtfCsiTyN-9BRffFF7byf4AV6lbJuuGG_JNw4VtG01ZzUvsVutDYFav_07_fqXWy-YCVlp_2v
rhUsFfQ_2_elyFkUGs3MPhHPZT_FlZIH4Nox--RoOmlVbcMjz8bJAnpyv7ST-Vm4FxR29rzQ-tvyyjFaiyyN-Dn0BttLxlW0rEFxTVWHsw-Bwl9jz8cQwV2v
thTAtU4dyCT-3Y70RwJ3ftfVc-YA7hxu_9xWIvrUmZCEtnhuFXrgqUm7hV6JMmTfkjDy-tNx33_cVhTSdEzhNwhyVEpdREhEgdoyBCBd_5etw1L-cdogyYbl
smNky6ETd-v-TYoxsmzTnrvV9jzMVc7xVVRxE02TRu3BDNyB5r4HiVds5_r-D_c5x5R1pZtvdSktoPTS9qFTh7Zy-FoKwyztsxTAFxjygAwotdsfy-EsNwhj
VTmiYBCvN4UFs--xllpDShhxwlOPFcMJ1btffuJFy-sN_7wS_DqxZxZJpFN-_GROA9fyzlfcQV8flb4gYnK-CfFHRrAtAFfzez0rBWG1x_I5gNNEqqU6r9Me
-5Br-uv_L5LdkH_SV7_Sy4vElqflxmF8tlfbkT_vVV2zl8LtefWIlk6Kxl_Rd4qfp0aEmEbdUTEFSVBZv2Srary_MOKV0xMETVHlDvTlFFhIC2OYxKT_p35-
7VdOqez4GV8mVDsEZk26vK-Zdves-j7Wttkft-1RFC4d5co0kPSy_Fj789l6640F_z4B7hvCfzzy02aFm_Vjjsr-mDLtZiywRu2vWaVprSUjVQP0oms0Ilvt
_B6r7p607lwYaeTVN7tDhi0y33-tPGN_XV5lBRzKvTe0QCLZ-oblBB_QSVh8JBOtGC86sFNd3x_4LKcbd2W-RPP4Ona6qCD_wfc77mELFdEiYDAspuODiEDZ
_1oem8HYbR-rCXZ0QWEWOlmK2gpMPv9OHY74qbylVmeRVghpuxPFWR41zlsjcvymL_gf33wjDW1w7h_HwDiwYbQJRFx-qGzI3k1v_8BnwogXf3K9iPNnVGEK
0rXTVIVMqP5Ff_eXsDOZu7dyfxNQ08MFyGSwjOxN0tX-zlFPVbZvgtSVwiuEBu7R_XUs_t9O2D-qZFkd3R1y__Zk7mtdzltY1SYXD-ddnGlWy6VuhvSlm3_B
ttLMcsUFRd-uRjsbFBgMHvVgw5eUNQkZQtLqhOwkrT6L-Dor-jIb-Dm5Tj4LTjabSbaR-Fe-VVhq5m
}

sprite $osa_server_terminal [128x128/16z] {
xDQ56SCm44DX7GJttxSmGIrN_aBt5lWL3gvQLUtj7Sf_EvJ_DeBVt5hoTS20BszeopRvWFrJ0DG0CJ-XFMyOGF8pG0yGyWkW6y3pgu4iL0DsujOVCU3BEo0U
m3zvVFaTe7lo-7B_zBS_exj9uQC_FzWtaMzTwNplwLv-SeNQdyZC3lLJxsSqf_JBBx_yyfbkw0UPslU7__y4cTYFYUnWFytKVaPpvPVlGh_yyfdkvti6bzft
urBxVEN3x-hdpyRwqyyEzj_5sqdQgoeGW66Wg8O2m_vtUm5Z7Z5wr5zp_GRs-XBIpEAjlTttIEWdt-_-_j_i0xKG7lBf7JxZ8n5hL2RoZ_Y55ub9YV097uWa
X9WI4ptaSonyfCE-ktd-ILDAWGYl-xWUpUEMY82pHVH4986924R_NtN-gkxtcWzBs1UInlontxzjlvuq9xBMWg1pVkAl-OHWh8CpEUkakk31ZS4ojspJHwpw
oQmNjvLTRTjt5W0yyHHjXU_Q30YuawtxZBRu53GSJRXE0ECzFhNf3p4TJx3uTAVlms5y68Rm4pyW8kt7l_EdzdtlBT_kKzUExvZkzOU0-AYlH7mW-Ps_LSU7
rokGnuKFq2sxpHsVcZyCofj9AmIjLH_d_iZ1H-wMLtsH6JxtXTuw_CplyTw7s_rO84QMUQ6c6kVzobTcOUiyBuQWYwfFrFcsBgsjdBNTWNsVvwzVoW7hMSAK
ng-MVeEy7vVLBylf002Sy4CGQ-OZq9ME-VQupzMNuXTG4COH04aerah5LoBodMzxVtxWgFzA1TGGXBmp9GYTsllCHtquullHdn96P-rLtv_mKLwlf6D1o5jZ
hQQkYKyRlfzyl-FdlF0TVFpFx3iCiM_JRnnYvH2hZ_WvC4xBqi_hVenHhMawQKpBEbymNF3pmiVg3yLeFd2FzpLVBlfvvaldMoynffE-gPmnrJUc-jE1JJ_t
FhtzYA7Yj_c8NtxC_G3axUVcL_sSxxqtLtqYVkNNqDhZXvmF-EQCxoT_rbBzzFQfzuagHrHzek8JxVZvtxxoFDtnJU-t0tZApmi_sEx_2p_qG_5vnPzrnCV9
n_C-V_ifTgtuQ5ljkGQWB2s0BGR0_C2iLJy4UFi7opcElZdVke_LFv7-m4_7-HTnzHdFn-k-23DBY_SZakhhNrht3yfIgwihVkfvezNVZqaaXDc-nk4lvIap
fGYodmEInlFa3_bA7pwhEDhtqRzX6ddHV9EV587aKCn4F6vekedFEIe1-4_OHSku9XhluTi0agfGZLUIxuBUnLU_bkAfqd2JNil_R-Qh1-ph8p3tzm3zTFy1
}

sprite $osa_server_mail [128x128/16z] {
xTRNmggy4e3XwG5bR-x_Rdz3-KPwWd6n2k-1NP-99G9_QdTtZ_GkuhsBUEyRV4sO4bLV623o26bXNNo0noi6k6I0WLT8Zto0Khm1N3B0m0U0ImOO-0eXCour
mCE_-fSC47a2k6W0_-Nb9t600hp2oUJnwcFVu7HQmeVpqSK-5lBnLELyEjFVvKjUNDhNp10lzQMyBvpSxT_-xT_-LVlVN-XpPgLz-iUFVpYpmZvhPXVxWbZQ
5qxkzc-VRl_sBzh__ZwVXFCgxHFcLThFx_Q1_bPV3lkkhuTTx0jYSL_KL4PV3lV_B5_3Mwi-MvVo5_mGgzvQyMr8o_dEAuA7MbKBNyt2u_a8PbBATvvW6bLL
E_DVV5KzcuUP5lATHm1y3m2hAanyDglg-jaqmQoi7moSzmdY05C_F5_yqv9zIl53v74U3GDCtdzxD4rJcsb1NzTu8Xe7S5yiVWB1pBZtzvhvMQkdFko-0-wJ
Mfyax7-9lYrvyhe1t2TnlemVR8lt0Tn_nSBKn_DeNeBllElp0MhtjyBLZlqmusaPO5sxdvVxIJoj1bJNt_7D40vqPYRW6ilwpX_fCGIj2lhEqpxFOuWMYljc
3B2xU0ynM75V0GvqKLFMVe1Qolfc07jwn1a1GAJ_3bPSqZT3sDIZBGH3ogy8BHJr5TPrPb5b14za-0Hu_iZPgLzCy0KGrnVkzkGDW4hefvvZb_qqtL_YIh3I
i7xtcKluG1wpl-cBK9df2pxmpyA5O2U9_1Ty45_uHlWAK73XOpn5Z1pYx8Pa7uLfZnvYdFiH4kbFenzFXnkOETa7uatQOqhoyOGFJ1kq5x4L7wV--mqPFWXl
qSvd-fpZexBJAx5WkYyvlW-0k_osBwCl1txRRlj0nhWL2Qtv7QSQETNeguutH1znuRVRFhBo9izOo6_NVOo9CirofvJVBdqSK-KZVkv3v02Y3n3zuOPjlvtx
wAdoCX4wuQik_6VRj-rJ742dEJ_tHGG-z_4znpt6B1y-yR5_YR7-1jhrpI9d5dqp130xyDjjNvJdcp2hqeuFKx-xGS_weZZQ7edIB_5fwpzWCa2bSrz7Np_o
oHS_ZvNT5nmY8W1W9W1aHW1YVhy1lGIVnVMz7RXYoE_O5t9-Ou0l-iGmuxUFVqpF5DPzXOudrpSZfiv_d6pR9tJ-S83pVhFWsn1zSlqWefV__D-v1jtzjkry
mlIYtxIVDUgnIW6pAk-lz5KV9hx98jslRZxctMz22DMYUgN7J_ylmCVQNnzCkqptBh6lx-u_
}

sprite $osa_server_distribution [128x128/16z] {
xTPdUgiw481XJPS4vxB_tLu4Wqs22n3vqIbyFvAuleCe8VofNLtb_RNZlNQyzma-8Um9umS6A3o4VK6gFa0Uen2Q3E2yXFsX3r2Hrn2Q3E2yXT1a0ESZX8DH
hG6o7_gj1YWyXj1e03_pJiN9_Jfdtl4uZ_tOrt0wgU67ys5Z7ohvSAfwFfxfx_BvM5JRbuC1DFMvli-qkyk__Ck__5RNlx_GfuFLzl4Vl_-XWrNsIGxMs6U0
sZxJxYx_yl7oBx_HzU_lyv7fM82Dxp-m-Vt7vUFVwlFRFklBsnhx353TPr7XnUUtr__AFkcKK2DVFMdZYwhbBfigD_5LBSQkpwhImYVLc5BNzwRQoBTkv3lT
xUDhFxtjs_fhxli-gKeLFwVthNrMrPXCLMdsN_NU7rBIDyMKLZwApl6EwzzxFwSHU9b9J6db8pjVmI-ynFGw4qlP_JbYmZdw7dxlfP-SVvsnfUJ-Y-1XJttV
UZVU3k3-yPxxAJ7Wy-WUWgRwVawmyk5L0JxWfnXklbfurSTzeiO-j_LLc_bUMr-aYOzBVCudMlzS_Nd0zmxxCqTtsNyUya-V_qGLVC3dvpyWYuu9uyVzxVcF
OgR2H2ngnl19Vxl-8AQ4i4Hg_CY7yXEWS02h9uxvNhX7fWIthG0epyJqnNU8UVvP_FBJdo2YO_xw_0SsHgGf7m3AYk0E7ohuOeJ4V1i0IY6muSQ7h_xwYOC-
KboQ-Vi0S1i0zljqqDVOptNEBpwv3_F2lFVvbC_YVXIWsUVlFgXiVLvyVkCFmnu_6o3T1c2UVO-Cxlx4YHHEfFWY_eGVbXj_sB7-aKVV1v0nvlK0gZ_oX-S-
iUzzc7qgV8dz24Jq1JZjbvxuH6AJdnJypjjv8RgH062yzaFXGYX-2CNt9vxxmzQdAVSZ0OwvhsOcX3JclkekNsJZTyFSDvyyNtz3y04cFlTTKcBcPG0sz9Wv
LFGr-kvtdrd4kl9SLXOc7u3U-E6ipphxmGTWvkMKC1OVOEkh5awr-AgZh_h67vxuSlV1_UG-hNrQ--6hFpqXftnDxli24BFuzclnVG0o_8nFCba6lW34p9hd
ArBnVG3U-BBuyYDVRF63-qGeCMTZahil2jvynq8q_WGY60sYzHEhzlX-i4KEFi0K2vFppCKt3iSxiFxPPdyv2Fmwo5E4P53F7t84-hRzdGEtaq1ctdqnEPKz
y8SllkZoxt_nOVBN4LdA9rlxpW_TocVtLmi0I7CtNs8-NR_cjxwbVYvfcDhwn9P-dStrfpvBxqMv-RZsYImEvzloGvy07jx_-W2u7e18ut-rV1yW6TqJJyrF
yYy-iSLVzNXVWFoeBaU5sm9uOjMstXkUzoiQpmDuh9Q6QhmtlAYBfWHJI68M-vgwDxogIpQcQYEUQke75Y6dbFpAuLzHp_PsZnNgTVK_
}

sprite $osa_site_neighbourhood [128x128/16z] {
xPZfVleu34LZPx4bNVxp_cyxM0W7N8icXLypIywdxkT24rqvmx-BavEJavEJavEJavCJ0CVg6JXIJtHS041oFYu0mFdgPpuc041P_SS4079IlmOGN7vPBpcb
LFH7100u5JAHr03uHJrL_G41WAnw8fOvpiA_6m2IbiNqKunnqW2_TXk0bqBHynZZBmUuWEvw8RM764Ts0doys82i-amaIUs569q07oys9DEpp5LV0f0u0JvR
RBBCyqq_1hCRoGB89_nUiK7zHLJTbSK6mVl-2wGMcxJN_fo8c4876mIGZ_HgxiqKi5xuANIPD03m_d1LVoS0MA-yu32M088tzMsnuIaRozHOer4-1B_d5yZB
OWCaNqL3vIhDoHZ2a270XtgrErLnISK_pZV68SIq5DGVaeqjuBrUPLcyiQx-EUTKc4BZhyCJFz6lnJPxlQB-CAlT_BVVogiV80P-qgjNQg-slUBxRtUh-k_Z
OtU0ovTU3V6nLohK-ZChvgzh-RwL40-zcjNUzeeY8kgV77z6NSlt1QZ5Hh8y5Lkg0PYK_C8V2SZAteqCjTZAd-pr2alV7vRxnrS_IzRBOVTE2Yis6RrUOJZ-
Xrb4TNpit4SWY_Mgrok-ln9v7H_O5-0YUkNHYrvXuQ9drp_Amrg-SoU55FqI729h0FNJF0p3kDoOXihCQKdhMZu-1F0YDCMs36wn1M4IzHDJxi4wFefUU6o6
L-4xFq3JyDHijTXoAJOHaC4TGFN-pT6W6a1g0jSkbAVXgTY25Olw4ucw1TG3sVIyZeyOizG0N1o-dOae5-TanJOt_aoACFS2IAhwIVNjy18XBu7Px_vqe-nO
zs9R_U1CdG2SLK-sblU65uWqGKSlH8xVYitynNnRoxdnIvwzjVn-7zuaqWQ0wXr_vaBrizXW_n90qZnhSRcpWuNl0T1xxwj_TFqYQx606__YZuze0KXX0Crx
Nnc3wmzPs8hbVZqzW6J5zM9ueOO5-lhS-fVxnqCOGLOilG3e5DVZXioYFzC60EY9rh_-YKcowRbusm0CaJmq5ruoOXWckK8LmFJysbzPrbhbt0qWbChmZCOG
XYNPy1YlVflT1WDVttrYrv-hNcYCo_gyYLRK7t8XfHHQ_pC2V7ttcPVGAxR8MVzGVUGnTmEeFochFztyCpMeNsZ5BpORxSaUUJJFcrxvxHZPymkQ_xvRRD8U
2a9uwdPs_VOJNJzhtsv0lXmA2e_TpgwVVJzjzLUzKBKt3xms-9UV-fcMULPzQhRoUZ2HlZ_CsOZl-4knEOyyhDk5-_uX68Fdvot--yEs3jRjqlUlTFoCMhml
aQnBHGnTPbcBXL_wkJE0W2r-zr1GkxtwhrJ_y4HYximVyFT-8Q6XiKv6-H3CvgVaGsPg2u2-HK2vsShdd9HSQfdgg-1NTCPlKq0-wb-CUFLRiQW_4zDkf1Qm
RFKduza_NFsxyHSWtnyU_La_okP_Gwy1zljj2wIV-SLPWBVxYGlgdsWd3C0v0BpqBv_nIwlN1CBx_CPkFujt01JUxW-p4RJOTzdX7xzvitym7Bzhz_H_NUaa
yFmLn-_Q7RVY9-2NVkQjTfLuSWNT29pBsZalDyRuH6RU9CTgSUpAdru4fkn1p5labsUBg_SZzA4jyZyTIVNx4I32z6DO19vSCR_B1OemxrQpGBcy57JyRWWH
varYkQkTr-twVVvSBZ14uGPHO5nC_ORVpN61W-jzt-_dsU5phhy36Oxr3uLZxSgnTkL0T-LGkN6CkkKWTSi1NeyFIe_dvEJavEJaRm
}

sprite $osa_contract [128x128/16z] {
xDG5Wkr630NHajHitUn_jyFCuqxoiHxZaP4d_UrlEb-odzJZL7sC9MtpopYPHIrzTm8LpcSLJ-tvx1I6BR7HFsnLWIRzCByO4DAFyiDlxbC_oFV2nW3xlZKs
1jZtQSPDSUY7-DNP663VBy760Fj-59uDiEV7p6FOQyJUEVc15vuDiEM7SYnDU5wLyxgg0BpoR80jVybXJ8FQs_LzYLwngUwbHdUhlJbOwyLktWLlzdo03Tzq
m4rJXzB8F9QwfuuOcUapPoOSMXhNxnQmPpwHEk-x1ZSLDKA3QomNJSvGWH8sP5MLscWANlcKrERokzFbDt2k9xv1NPdocqzvnwTA6zi_u91N5LppnZyUVTUm
9c-gb6Rl-DQbitwavg61P_P3SUzNZHW2rwofkFuqRz-zzftdsPHE-lWuPhrx39WTvi3MKTe2wffr5MAkxjXS1NZbOuSkUp4FtSPX88XwPvPgPzd__xVdXAO6
1AA458rzgAxFRrIkzFW7gVts1VxjaNwJ-mtlUvoVLjJ2xtkW_mUcVO_sropx7kDFn1khsAByxkcRANr1cEaY2F0RtVrbd-PvMPRrnJ8vp8px7k7F5nv0kgVZ
TyoUpy48lsL_-G4lqel9RGlpbm4ylN5t9h_V0_tv1_ZRxYJJklVvSHr-uGSa0KozVevHrCnwm_u8EVypU47PONRRzwZzvTRTy7RhxESdAFOkVpzcrGCXklre
X-uaX92-oMytSV5Kh-dszsCim8xdH9_V15hn0xBQlQRNtxE-O6R0tmtu0Ze88iPlERZw1U5-MFKBGlqeHnminFfbP061VZk4eC2W7xz1wde7_0k0_WNTfH_m
DrtorEFtim7xWmSuUSB4n_Ud7n0PFO6Qp-zFpUprKnfVV7v_Q6K1RN_EH_PdlJA_AS_M3FhFnwyULQT-nO3_7EgBGQaGjB-6fhkWdeUTSKzfciVsrz1UGnq0
Em49FYtRwFuLAC-Op6SuVPhNxN7DNwQbcikzpbyO7FOhz9T-kUO7yp4cOApjsK-pF_J0pVoL_-_PxSUt632GVbph2il-Fw3TZ6dTxjr-lcNuXjH9hdpO7y2P
KfgMVyzEVpwm42mowHr_vnEUbcMzj_kPSLrq6VVp-s6D7S2DdkPL-Qr-zxTU6gzU-Ckl_4dvpVkJkkI835tFDPnxojVHR-tN-lK0BYXE9_2Sl-qVyZiRzLJ-
fFps_Ka0bEiu0EN_7Am5Hydl_VC_zxae_It0h35VVeZANz7gVrFbj_ghknqfCm0wEc3ENzT7dr_NUZt1h_kZeigV7uyXl-ZnAz_tPh_mSifN_MX7-UpqingW
dhyPvITSy_k5qryetwt3BtZ8YjWTxL3vlNvfAtzxVNNq_QgVbyUlyxlzGb9telladvTjueXVzp-Y2rBvb_o2bFj2_f1V3EJ7--lyUB_Jc4f-lv-Z953vyVxq
pbzoVlZ-hlpGVkMxyiFzNXtz-FsTK7vel_xSLNwmlywFth_E3_ShVzcK7-Uly-FzTNwmN_cJyjlz7yg7yiFzob-L7-bdAlcEVZ-7yV9txeaLKNxbN_1p73TG
-U5-fu5ftcQFz8ja-Twd_6W_wDCoUxXVPtzQviGhViUmdyOq_w076_x_QyCe3lFffKT6sFAt__cupzCOCp2jom_Viab_xdy-7uEidlQVl-Gf_odFOUwF-_E4
MmkZ_dqVq8zJY-8PqyVp7m
}

sprite $osa_server [128x128/16z] {
xTQ5Tkim381XsOBWFNx_jxrHJprUm9EhWVuoVYgvWVsYA8hc2xdoMXT-6aGR3fhg0DOyd2jr643v16u3p5i8fyjr04EU0Jm6gBm0U0nG-G4kXdK04tvCu350
vQS4rwF9ofyoj4GwkWMF05u3p5i4hR65Bz3UPE0Zj3SQ-DdPHu3KbA6VM_fLFl6rqDdFoTodytNnyNJVmWy__2byZ_M7U_WN-eL-JXUpzhEhtv3lvu_UlkVl
FzRVyCCFFxO__Fpu__-zVlXuL5-V-2XqzdEozv7msQUzUlZ8iiNLnvrw-2ZtdFnD7gPHHDZ59v5nMjP5HD33Pv5fdDTr4Y4dVvaNLtzQrtKPdDv_595fMVGB
wFFzPxc7FkjV7O3SrbzaOSByxDDEnlxdnVRV8_tmmmy_V4GzkX-_kgAtNw7NFluTF_oKi1wdb6_7IAHNzFULg1oH-aJVnwS7-_JQ9tUVlfrVlFrIsldothz1
o9msZjLdndh5RQ3tVcdcztq-wvT6_XCVG3c0pGTGlrxngLyQ-R9yxDDLl_Jn-OtFXdwvxhFwwRslzVN9t2-xleXoehu8rYiUxCjxdp_rIwiVVcE_n2SV7wh_
fRww_goEliaRyA_PXs8P_3mVN7dDbTTSUSrNrrpvMaVQl_y
}

sprite $osa_arrow_green_left [128x128/16z] {
xTfPTjiw48JXhkg6F1lxt-qLMIV6FHH4C697UF6VmOzVWV1iswb--msSx3id-ywvVhXFzUdkcEd3mp7J1yCvqTU0URu6-3oV02DycXy4uE7J_F1rG62I_pE0
atmDO0Hd-H4QuDFye0RCyTk0UAwFrMy3F0Ap_F0sO8BV1d26hm0omYVvRS0qFmWoIaposu1PlWPuAVYtz1AxVd4DuB-YkUHhNRyui0pmV1iGpJMWxvS0o58Y
7tSNsuhk0AOF01OSszZrDI1AITGRhjiFrVNR06JnK7Hl-Dw0h3S3wGq_vb-k1TS1dg8BR-to5rKq8CxnPDEF-AlU1h1SoYaUIxvjm6SDQFU-RSWhNejBmGcU
tclCAry7N3o37_ioRmRuvL9oUHyTlnMF3H3lzpfwV3s0wp1xnFUx7Ju-itbryFX5V4dWXtv9vAtnX_q-xu_oF7ryyILI-UF73_7-40y_wJV-ESSl7Jxq-KVw
yMDyV1SFUyptE77ynfizw4Vi3g024A5wV3p64_3e3xZx-N-vuOluHu_V7K3Sr3i-J_446Bq1Q77DvM-ENyIxsQd7hxQwQAZc9_9w_AtsvAMZy_L_kNcVopCy
OvFBRdZpkto8F_tubRFf7L-y2l6mHD-b0sPzFv5lrzyY0DVPE_wMZmWxoVEMX_YUttXFu8q0jpp5T_qjxtRQzytbk_IEJp2Pt_ehVzydjtokJxt76VjSULgo
3q3ylbyQd-fJ_AxVU5YEV-JupHVludFFx-87ldY7fViyueTuitmVrspWf_BoUTnVStTB2yrtyGDVV5xyyNd8TwVb-kZvzQRL5r-NydnlVeExVkDRQQy0O_yQ
3BLJnYT0M7pi-p3MkvsvWB4FBBnNbREX_ly221lui5B77SQNDE2O3xpKOntJcy-GRtk-uQqURwWhru0Vt-xx-An_rGZVFW07zlpuhd_R0Rv6Um2h7pMpVRqz
0CFgmmmrjI5VttzkWBg0v7Pq1GtmyDKlDRaTNfa6H50NaDs0hw_o6Ne0NhCR-DN_3D0NFvyrkrs-lGhmMhk1v073WU2QcLsUxRS1ke6t_05rlyy_0zmruCb-
VTC0rwVNU7-gtvw0kuS6FDDNi6iUKK83dkrNsZMMeW4brJyqO74DeG76psVxzHscHn18VGHshHxARSbBqMLyFTklBz0bw14WSlWsO5pO4ln2lVnA_W0yZbh0
W1Qyvtu2CkwJjaQ7bhoUuXzOy2tP0EY5lvxaLJrUmDOqu1hBzmdzWGMlnCtlnxoTupNWU2_SB03eyPht5TYu2x6Te1MNhw6UDA6MjW4mj4YwUqIvlBn_R_JK
1VMx4305C_Hwt-2P4zIB4vgXD4Klp3wsUFu4zLMSn9gThkOqSuJbD4lUbkl-zjj_
}

sprite $osa_firewall [128x128/16z] {
xTS5ikGm34LHo-mcxN-r0qsEClbAevMgUITOUCFWh0000030SPpFzj4_BDilqFk9fjoZIEMd3cf_LwKOcufgqwNOf9L-az9_qaSVVVJHBr4AVhA-W8BavuYy
jD9FAqBAEX-BQlNuwtnfkf2RwcjzzD577_tqLh_-emYKobmMVCnpQKhlfxM_24T-olakdFaWUEhhyQyjld_HHnzzzD7FYxyFz2DtNtcKtcz5LLEikY-__rDi
TjyVwACVq4V_Y_yVHHTzrYKVacgdzYjT-2joNY9_4Ix8Xn_4Yq1Hqlkx9XM_UhPrXPfq6DklR_Pfu_rarqSV_OY-hb2Lzcg_UayQvywpLz15U_ZzLnUaK2S-
-lvdo-zFPXxPPvxbX_TPrC_6VV-TphsU_sW_FThddhVfynRwBFg7lQxL_OfIzwffdqN_T1nYItrslA7-CDpxZktOzvrztrdcpwpxpZ9_PfJlhEgTLRqpgtTs
SMb0rme00030Rm
}

sprite $osa_image_generic [128x128/16z] {
xTjNOjmw38NX0Pi0qbVxN-uLPdpSBH8ABQJeVqpx3gcusxT_kgkhgwkhzVG-y1m3tSw9GapyRi3QuktCY2YszGr_EvdNsWf-ZGuyHJo2bS_b4SEFBZmb-C65
fmYVN7WAy3ruxNIVV7tozSdN9r-VV7tozUdVzidN9r-VV7tozSdN9vDVVxoEpwyjHoixrLlVdxh1xa-UOFUdRh3xioOWipz_mxY_m9g-OT3VcZy1ZVdOO4w-
3wD7V6J4wgVQsoeRV3J5HzNcema-OgEFPlcrvyloRJoZvUcmF-Kbi-kNKkPEiFjbwWQxFtS2isZuxpZYpzcWg9AAlcRpxHlWeeE-VG9aRQQFzXT0xl1Mlp-1
rOO-mS-vxFRU5ZJBhrdhRO3Tv-q-skDXezevljL77TjsVBkF3GYNtk7d-fY0W_VvkiFRV0Hyp6-pVE2oMpNv_zdymYApUBk_G3Von_sMKXgwT-ZMutTyZbh2
nH_WP_WnSMkj6lGER_DJOPRQMr0jFlWHVzFlRrVl2sf7x_1sFsrqkR_awILWGGS7tpj-tyyRlsIDDva5bz31E_ouhnNbbwe-Bc6arZt-e0zUVKqmmSeVy_Nw
IzLm_FPubte2F-8NyA9ZM3QOMJeJsZm_vrpXPqrtR7fzRDWwoe_-_vDwZv_zHUz1xeiUFS0T7VmnNt1ybdoFcV58XF4k89u6-Dv__d6_ulZSNdsz1j41ovPW
mNTwrTyzw5VuB9Bn09w7R2g_6_0rByoC0U17VQcuVctJIYwifoub5taUmFAeVHbh8l31Z_ZV9E_YhPq1WjTQ1l-qVicdcTbzylNft_R9roTVdtnzylN9roTV
dtnzylN9roTVdtxU9ny-m0ykF4NuqOMd13-vy9JXYuylyDVamQTLVMrzelFvyAGy1gIp-QmyMjUrvXZe73x4bEj6Ulxu2NZanYC7_j_jwkhgwkf_
}

sprite $osa_server_monitor [128x128/16z] {
xDQ70OCm44DHNQ7klsyIDh0SqUyly4G7TwsgrlPEvRTEvRVsu1UtbdpUOS366zgoHJvW_HK0DK3C3sZF6mQG_0ZG0uJy1EW6yFni80lLW9MuzVSOiF4EY0Vm
JnvVRWDqJnvVhh_-zaTqDoXyzESd-oRohIkTxpqzoq-kKFi3cTcfVkhzZEQKVldbbry-qmFz85Fx_lB_do0J-p6GdUodcThFQAxyybtebry-q_Dyp-0o_xPR
dzdDwa00XZLz9CXb_xkz6h1EmA76-Ell3vl-q0y_z_lZRlzwyC_7FzNdmzxhos4_sMU0stqM5Mu-7xx_R_P9nuH-ag-FvEVuecgbAwRAh_egs-ayCtDtWl1L
pRthYwgyw5U5wNoifeIawZbtVM-gh_aYbAu5ObHzwohVwMaVLtqHJ81q8OGaXjKjVTzdLNdDvuJxt7D40CQigfvDLMdozzhp8H59xe_hfeoGaWYAJl69zz-s
hvA0QEcirC_AI426o8r_qKVIlijdAtrF26YX4XDE7L-rFT_wJjUobRpvcy5gLttRoBlmoV1g-xurK4Li9m-VaFnklwKikgE_toVM7Ttpctr1qWsz-Vn6NnbG
TdWlR_5BOvJImzSLFPUkgpuZlyiNJC0ZBKzywBNHf_jyNVZAa1A5hwnpFGS-zXu_vugCfpzD5q187dPkzevFjFXTJZZZJsN5XDMlgW27tF1dFy_i4Q9FkVrU
zwkQA85uDWAqlAWy2b-Q7z1jVbKJC01RLWGGhwhR8lVm-JRVPduUJxzW8dK1I6YLLrh6shFSxNTkOmA9fZS00G68Lpuj0-xbsOVu1GWEO37XsBVm2nFHj0WR
9n01O4femH_v0J5Fl-7NtpQ1YCxv22rnhJO3IlnN7gd5Oth6Xsj-fz9ILqo4YTGemUDb4FcZN7tHfGzBVpxXsAVgvyZ7SdNZ0CobyYJcJy_W9PzE-3pU_xdb
3910t8rWmKUZhsTylkP_4kDnexgx1Ez-okVcyu4_34U-OaeKi0N_l0FXwymVEP7WHC8NQHF21_ZY3tFVg-yBVtmBJhBvrCt-yCMVy-uCgBxesRVN_26rVCqN
e4j-2Ywby5CAlqtOz8UPp_BiAxBTuejyyRjXQiyt5Z_hCtEwstVH5_rqrIyBN-sYhngSQlYgrLSzy8U7dvT-vBx1R_ffwOyJvBIl-knlyU5tFTbzViv9J4hV
BIhTPdrlx2k-D5-k-ogsTUmjinQpkfd3et6xYQZ-0X5KWsW-OTQcRwPhoMhg7dwwtfRl6vblPVv-txGs-tUjMVEpV2VxwXVOy9K0mrD65Akc8B8sltol5Hzv
u_2n-jD-GBZA03Vu_O9FGs7qrPHnv4m-Zx-TVytTn_SQMWz-A1buy_fFM6tsNpEBmtYfrFoFOa3g5pApN8Qx_A4hJZ26Z-WHj-IHJbaf_zt3Xp_4nxUlbDUB
U_WUFXgYZ-vA_STm4nyDFxoqx2VghUlRkC7--VthVm
}

sprite $osa_ics_thermometer [128x128/16z] {
xTK7SYGn28LX1oKaCFU_xKwBTc8zMGCR-2kwqbT6rVEU_kAYlEM6fvJtVFZN_94ZBzdxBzlrIotYLsC-fPU3sk1GyJX0tlmACnV_rTbFndxuuOVFxrNb5txF
nX_A1mFVy_xXXnz--E7phENypQyyC_E7yi7CbpRJylxXXnz--E7p39JVZFUdJtyWul3R7q0a8dHx_p5egxZv-9_x8_pmu_jps9-kVElz0GzVtx-BRx4_uOSV
VlZXysme7uptfoc__ilx4txuuOSVFai_xuzaurVb5mlV__xXXo-yzhCrh_rinwSV_MJzxrSK7umFK8NhjFk4rTGN7cWWxQ4yWALV28N_yWIMVgD1dmrp7r3y
FNE_s_lXy-oepriFjS_xqWDixHDfl_3N5kggSjwNLkldVTqwNVlmZKVnVsYLhlr6f7z_A__KSfvbRV6ht-P9-CTMyzpt0TBpyyO_jzhdF6j8UpshvrSjvhbc
0HlqGst_ivhvRoN_Nc4pd_47dmnz7aNf1NcXB_6fu1iFBDbyWD9ejMnLGERLliGhUheZJrtov2LFNNB59GzSvuBh_6JT0jQ_Nm
}

sprite $osa_mobile_pda [128x128/16z] {
xTNPTgiw48JXuqdghYg7zt_RumaPaP6zr2W3_rLg6VZkql_zkiY--hNSboSxysG__x1pNkh57tUxFVhvs5rA_VnqzVSaqSS_xgxnKX__SFEziQylvxUeInty
keOyJqlpbZwF-ttwOldQvNb8pNmxd1oBiaDgvalvWANbOqF_TCBI_D3IDy3prpC0fyP-llorAttynX502l0FfRNzpT_ygjLzppdDVpbObPTw-Ewh-yTAx-Yx
T_Iz5EjREXnd5RsNxxwQRvQEyzxHk_f0Jn-8y_FybxcFKW-_qEpXeyIRdrVryOoh-vZ6CD_VzEVwoZwg6EGxuFw6ZpfszSaeFtt19tlwP4-VxEYp5EtRQvza
H__4zNoGtjd7SLPUrVzwcx_vcx_vJThypJSighcViJHFBVqJbcQT_TJSttoEOJxh7UDJpt1fCbbFXVXtvYxJGUanAKqdOdnA-P5VGSd7BS4fZ1EYH_YqCSbT
yd5IS0dZX6Xh-yRQzqZV_wZlZqP_xE6FSoqVjSzeNmMO-QfzXlYGn7kw0fnCkK5YsJ2F_V_hvfXCrbDkeVS7RZxTRkQpdqDyTtlaFf_rZl7VlRVrnc-zly8j
ZlUNPQEQl-x-vZVldxrpVtqTlxu_cjsVID__fF_n_PsSexLyhEj_V7yLT7-B3udp-rksMpKHuLFFiExzpVNzePjF9yekCyHtU__-rZ_7-2N7BLQpAiAlxorO
xMg6-58bSBfdFqVubAmSM3bK3gxTxo_7dnbr__AZyVwE-t5_n_cdxkzsVxVxoxNkB-vHCdzEI31APGRvzVtbTC_lRuGFFdctwQIRWomJKVVtaPdvPFhhsTG_
Z_wJm6o_dYbBGnD-66J9iR2BVnw69lmWJoalBBbUBgysyS-ojBHC3TTQ-CDPN9hqqiuVpikxy6tyVotKZ-TBlVnIBxuKgFyF
}

sprite $osa_hub [128x128/16z] {
xTJXShCg4CRnHjbz5Z0dzt-tPuCknjPOIV7b2_zf6KPdyXDKlzhLw_LwlLwlr-lrUhrUhzVhXGernAsslDQMrpxZVKdo9l-nxpV9nmNji-MFjyE64paHN-vd
_kyNGBO1nJnkDVm1jW6rbbz-1u9MpFDDQx01vW-r_D4se8YdMnrVOxk00bzgBLyRxHrii_py3ZPOVkaZQCjtmr30rzo0nCkWrUDj0mgMdohWQts44e_1ggDh
337_n9TtUAa2her0q4ujduVlxTlrDo0lltuZO8zWmV8hHhzlGD3itQjgtqviW2sVx7PNqvTV8ti43tanlje5v5y3_E--kyvtjW77oxzc_tz_1xTVtg5wXnkG
UF4OBeq1y_TMN_3fgViHikNpjRozWsyVFbt-vHiWIbLOVjqD2DhrozT6XbThT_jHszh9CR3lYv0hYKhZES2_yV_EFm-p3go3MmPQXeqVtla8VYuuRpDnqQRC
TZvIFeW4Z-gFeogwoSlWvc5KNuTZty--8AGuEFrFGNqiKuQTZvGFFdqHSNNyAGNrRQg-B5F6Sb0YsS7sli8YQEcJUjHo_mbqrkT3dv4YzGafLfymnrWYzGbB
Akjrk1e-XoLni2cJjocjvqdMyyJgK_Q9eJxWyd3QHrpo93OL2ZPbjbbO3uB8nIauVlf06fmEHf_sYKWuxw_jF_cyrPplW8kS3mepEo8TF_GVZn3L9ytRGwU-
JJslZvhavsyzAEdxwfBFvhjv4D5JQO2swol_qFtyxlEUBxi-e8Gui7CiajI5Df_LdtlwCKoFLzvyPdxnux6FLv-IZyNdhK_PJwaVxuz7vhFF6n_P3pZsVLe_
wDKdnqOlleYi_dzg6h_rML8K4KbI7DQfx9tt8aWKY22YW_T4x3td0SpoRFMrp6SVy74f8DZK8rhYrscql1Hqu6DE85Nohud-pPclxVWVCEVxuHkV_GEbHg8n
XnWVF_me_o80p77rlrO_oBVmUNoKxFXJr8BVh-BY8H9KchQ-NS1qUJ6L-Uq5QDVhcSz-xZvDzqkRdjsDi-z_exwinhpMcDVQwLP3tMg7Rxl6xVLwlLwlr-lr
_WS
}

sprite $osa_server_identity [128x128/16z] {
xTQ7SkCs483XxMYywFtVDWlnaCYg10qEhl0VpmhZzgswu7Vjx2nlRoxlpUMz8_X4k2MAsHll9uHjOHg-GFOOODO2sLFO7erT87i6C6k1x0M0MGjaBo9qngCM
oEsXFsc1oXF0h0Monx0hgGkCU-Rr9zdxjc-mEntXm_veie-3VDpLE9_sz6VvqXUFzhKpnAc-ZFU5DtVwft_wfp_hzUyFzBcpqJxzvPz_kBF1Fcjdatr17EqB
R-xqJvzE__GdlVxzUJu9zpNQ9-nhjDyVdZxzgRvyx5XVFpRP5yJXlgYfD5y-lluFzjckAK_oxMSwnrUpa4iEPZB5Tpx6icGpdU6pMKofB4imc-I7udonpJuD
llqjBykIp7IABsOMK_39g_-k0tnIMvCDhtyVVDjUIgdwDMdyz_nWlIdzZ8NRwJwwxvLlfWXziGcz2P_sqbVe3etwU-KJz6SypaVe30_o9QGWdtKyo8yvnPGJ
Vk2FyaCsin1oX1gRZzn-ah3fQmVuL8AgXX0pN_qG4Y-PIsQ8R1epnOHud2_PLDHYJ0QUc8FPfvhxKPE69HxfQp8lk1y002Dg96Cn5d0SGiGGZlGv1o-cc1MU
XBKtFlFTRCUjFkGKelEnq0VzmL-vTTuSkSlNKXoFgHH-rD_vp2DyBPNElaHQ5q1wx3WVIumffv9Jyilw7U8d7UQ7758h5hkx_esdLpxMYNKIuiqtDlivnRpg
R7w2DNpiqLyXaNLMtsVx1ZDlyajAUIrvvSdjJtq-zlannznAEJ_utbiVl_gttzZaov9YMejfKG14-Xhkz7dhyo-djLm2u6FzllJum1RNZ17t-D9y-U1VBW_-
RVWn-kfVETNAgLPVjNsZ-eWF_kN1x-A_wtiFVeS-mh_S-OAa0egiWahCM6SzAxFMirp_D_iGUVIXSW2aweRxxHklVE-h7qbYm4XQfojOPpr7aUjtZ69aaXZ9
jCDNVV3BPMsKBo9meA_xVEZoNSRdKVsYcrxuPfKpgxuP0fXzy2__-rXzLL4MKrLI4MCLay1gfgngQcIXNZxtuQj__OPs-8B8mapiKJtMX8LOhcT7QFqk2G_r
BqQ0RwE7t9S7NvklFVxb4XIWXTi2DAARzG20sISoenlCjz-uwT7tYyKOEaDJGjZHe-zbwqw52KVuS3qjPKlBDJ-a56C8PjfVU7pyTVRV5dbNt_P_hFp-1PR6
Dx-tVre_zdHfGLjWJZ3TRqtclScyDutlRwvUcwct1jZpE_iN
}

sprite $osa_desktop_imac [128x128/16z] {
xTQ7SgCm4CPnWxP9EE7zt_PWxHqoaCNQKUHh_A-aw_Sf_VQxkxgwkhgwudVq-tZhZAU-iURoCCHAAOt3wyOleUl7-H6M8hmDSFoXYp_kSdqQeYM05EL7ElKJ
TGnU-p1rZA9--Sbg_U7Mf_AN-ECt3S76Rwhr8Rrkt9KgQl2F1VYmlvGgYk2m5F2rgWcLTiH7s4h7025L1zRcSyJNTlmI1EmstzhuHn2WctrBVGi2TDZtMsLl
0LXjFkAPJuYmBJYm_ko0l-RwXB0DgBGnwll74z5ZXuOLTj0dt0LsZlbe_1AUous-jLagm-CfDFwSRlVf6QAY6YfKuTeHKusFqwIEPZ6pyKjFlZeY5iavL_ix
W5OUj-fvubMsWZwPOxp9wvugtEYWpq_QCfzO8niKm5jyDPVOqiSSLcEHVAmq-6fQ-YnoOyKFUgdt5T5OppFOrj29BjdHGxuccZsoykPxiQU7V7dgDaCVDrH4
mdhODzu6R2qyH_6uhxmi6RhnzlYk4ptkFyfBidq8B5VtxRYVLzu6A9vzNdoxtPU78FQKg_jqtCzY_chg7Yy7RlHt0ppVKHlzhFwsmFCDx-rdymDNR_BptdU-
khhvDg2icH_Gs_sIxIESHS9uksy3b2zXlTrVKHD3ThjVicaFyl6KS7tj_dPVUyXKNwD_w8t-vJlbG9DJq6ylxaFfs2k_gh6X1j_ZqtlzlGuTxX-vVNgh7t7Y
VfXF0F16Vpm4Iwchx_Fcm-_sKsVVvnF4_UJxCJwf_Yv_F0RFnYw-prl9hj_VTuuwy4q-ZnLyS-Zxs9stwpi32A6bb03IQO3i--_gvlGx-SfD-Nul-P0yArC9
wV7MtyF5YNdnRtqhqoJiH9HBxksNmkI4AALqzdCfX6wSyqTdFsVmmvnpLvv5A9qa8frvIV7lxUtDIy9hE9n6l2JpsW-ebkd6-ut4skVyfGROcdYDql2g4LcR
ZqNftVKH8DK4WCHyTmuAuXOptEeRc6Ls2-3M9_Du2qJcEmNv-OCv3O6GUJujnizt3ZV_v82foM__0DnbAxzArdA0j-RkcUxtEsshcnsh5nolGUrNBwf_LrTN
LrTNlm
}

sprite $osa_site_branch [128x128/16z] {
xTVPcgCW48PXMuM2WYJtVxT3MzRV2wI96Gopy9rHZycBMNNwVnkDHgFHQ3GQZKPyThtzKFFzgJ7_uVx9FUHxTqfU-Kh6h6ydj1WpFTBmXp_yUMdRORznH_qK
1jigMnyxuBXla3pVZFMy3QOLWvt3UfK35Wpcu_xYI79ktfwDC23P4DPEFFCnaBFNDJax7VV9RX7HxfEkrTS3n9yC1l1r_Oplm1tpAGsc5Zxj6lnzuDGdvTJN
HtpnwMd_FUUzKry7wiiw3TJN0zJ70K_vxm_abFfw2Q4-3b0V0_NnYATybk1xbk2p15yFWA_he_xmKqwZJPjM38puXC4iFx1Oa_WMW-MuFtqat9TrDgWzug0_
hd_MjlqrvpzyszEFCN8_FwQ2EyjtiQwpztIMxsECLNttPzEsTvyufYhwYUTFtj_R0VGV_0bbwze0lkoWm0UnuPFxoCh-ILla-OskhMYprO7PRr18coVrKm4R
W0uUlhEhPWdNdyNx3rp_VWocxFv3V6mWvg-z1D_CcgK6zn_mi_S09v_vRs_mczn_mCTx0Bvo_lVlF-Yd-myy0dw-WHZzmtxAPVSVtdluSW2hZmDot-y-tlkw
xrESWh-lMNqz0BuEIZx7Y5U_vZUw_eQFTo3vlfVlDp_K_6M1hwclQ_YQ-XWK_H3nxXTzqU6lfAtYMmpcRJrZRSKt62mbdsFAt_EjuF0hzn_r0-2Zd_qamszG
qHy-vxvxaSyn5Rhu-06AyOM-otz_yZU0MNoo6ftYum_WEy_UfCXzHAPDZh-UVkdldrFmsaRC-GL0lW4fD8sbZ2zkuAHoFji0Eii6dry0lp1EO7u3yBB25nxl
0Rz6vt3l1Z3mItJXio9sSB8EllmQT3XtxNQJ7VJGRtju6zhZyPQwQwCBjj0Klm2uYwChjj0MHvbUta8CWN-7tknulHMgy7WdKe7vCCr2uyGBYL_hgfi8s4O5
3afVRvNWrpTnYNjXYoKaqxXt0Lqfy-lxkCIyYblnUpNyQUhCJttvL3yTzTDHHnjrn54FEgyBdTV5BTSKxTzeD1gDVW4
}

