sprite $osa_user_large_group [128x128/16z] {
rTcDbgke4eRXtfq859ZE_T_jYGMlKeq44y_ghFdcVwOdJr65ejbV_uMadFapjiq7SVBtUjJyRGLO4Zm94l-iWbyu2I6E2_3-_yD79PqjW0hsPPFmhXvL3zuz
mcTfojzGGHyduVt5evEGinKGd-k47xWVvUywUNXR0P7qI6XrDqrNpJGvsuFxOLy_sgC_As3LmQycQmdAtr_W1TwLr0M8c0BW7QmfmMlUv5sLfe180UYNHs0P
0nNylE97mxS5o5O0_8HEfYLL0VDnFdaFRuA_5f0UoJowBO0AzFzCXtqn_FI8BK1zAGt8lKUt1MZM0bvOllBecbu3r8Tl2z1GmElBXwS0V1eWALZ-ikH40N5T
lczuNrBv8PQjLt1Y2z3RmZ4_7pfs-VMjZ0g40hntDK_Q3amKC6w_1b_nDa5zxVuLlaxR05tK0JziVgrJZ7DR1K6xhpxyRW7E7Mn0vCnd_MxllavDB1_UflQr
03Vsa_MBthcjQt9b-DyQuslSiIs8Jm7eV5mTXt-f_QlB3ubHGj3QfkCDOFlXs_jwUrjtlzS_-PXCnBlQduxwmHFq_crzvHsuYJZh-wF-wBwUTm6x0ptA-f0e
aGhKTrhmIpvy_s2XW4aAxkjGWkHhwPWVkR3iiNBPBy1f0Rhu2Bw5fwJuic_u_csTepttpJwar6yBqRC1ndx8lZrMoDwv8hdglOVrhGKUVtZyXJn_PtbY_Kb7
RzuLI20yfno-08DlZvL-0tprk6fZ2uZke1y3os_vzhRg3E-Ms09aBM0wvgVGBf_RUdkknD9yzDxRmb8c-tyy0E-A3w_PyQNpi6vyAPlG7VDZUwoLj7xtORrf
W5OwzkVyI7ijWU_uaf9OVkg-BCIKPEpVjKntpFVx3-jxBmiqu6latvFW3_ildOTrrpwiqu0ZFkCVxJ_NFAoJrgS1O_-6Fxp-VFkmJfe12A-B8t-UhM_Jjb-Z
F6ToruzZVtuag4-U-Dh-nhzsVHdwS-LF-9QtxJ_iCu0ndwn_xV3gYp_QV_muuFNyppu5K04wHi0Vxx_n1e2N_7d59-ZmnXzTVzOVy_WKqAGWmhjYU_-nopV-
a0_BduhoZ7V53ri13hxZ2_vJNdG3PEO9N_o0Rm9_UFqLdyz_e5R7r_ct1S3ZoyXd-V3204gi3b_xcbs-zLEFZm6U0LJX7uaQl2om2xiyVj9qXh_n4cX04tJy
a1LFiE7t_DJjlX0QqEKrvMM10iWkpm5C0MttuUiTu7Pr8lbbGJFW6R_8JW5Rzqda7kHSJsS0QneTlcu_NzitopUyHA40UrypqGCur34wl6c_lGZiycFS_2IS
GgwNnt_L0V2AqqQi7xCVc039qm-o-F3pl1s3NLxV_J8qvhNnSIt0jZyy4X-1J-KaoiyJUxgMvikIij3NUVvV25x8RVj3aDLFAI-BWv0U65tvlAN0UZZBptvz
7yJNRQ7HnPUfIlNLPxNvwbzMMMSgtL1PuUq4kFVeyZNA1wy5XK05rA0qkcxPD2o0xkDp3Uoq7pv_T1IEjlOGz9bFyrow5VewF3vtOkF_uaNA3tAuLIkVNDOb
FVYjW33WvxbfW1c_vKNKRmyN8YdpsmX2HuTV2n0k0UDRNWl8pmzxDtVq946s0iAkhbQCLG4C09_nmvV4a0k8hhISDao9nVFvp80Qm1czI92q5Y3L0DZ-cO-P
9-NxEoalDLnyll3wtoLMN_sQK1pLHGfW0CQ73yRtEXftDOahxwbylmA9AIVQ0XW0_SSFbfVrIZI_mZTPFXU08viT4z4rUqy13C3ilwLBy7K3L5XOykrZMdan
1S2bIiwy5a07yElhd-7R1ETLyDzLfEAh0aJgAcXxvAglHi06C3xBjmbU2QdzvJFgdGAGkm4TyomYgGg8qVYpgC_oRGfo_RTcQfxNyFNYipj1iDS2z4ROR42M
tulV_0Y_fLvVvhaXmClw4wBb6pzfDrZ-VlvzAVxrDV6mRh9-EfjHr-YpRqhK2OZnPubv-R7lNxzo_YNpgcGgo4znH8k4N-TG9c1FW7BZbzWlm35zkjzc4QFr
qQjDcWk8Kfs0MW2FWBriqu_zIQbF-2duUW89dmR4xDCjQN8nou_I3v8FhRzDOFDvXX3swkuSfdNvJ6gKO6iYt8NKrvJsrqMs2Gj_rMiddma70zysOBwNhtpl
ZF-PhxT0RnxMN-Pj0nwmwiRlLt1z-68Urj_q9T-4viM_Dtwt0lVmatbOVuVd-5UVxFWD4SFtzqJxIzxI6S3Ojv77-6a_UODd0CTzShq4_2s7zNO0jpkP3_dJ
HHX_dG5_qETpdyHV8hxD6Ezl0FmuziNwDeTm8h_yMs80AJx99U6VJBi16S1JVuhd_DJrEG3tUU84_sG1-6O0Oz_hxVUaR-TFKjw1pttX-ZzJWFM_J0DaiBI7
dyxvzW3W06G7oE2ZPJwx0T9ldm7yB1COVdOwFO1g-_seJ_WYHmP-2YSRmEsFzji21fy-dsy03s0pFAc-HX6Hfmq8P_oGst_3DnsWWbwq0ISca7cMZqy1lBLt
mjlRcG9u1PmN7f_SKWxdMI12bjBPfs_fy0yStrGmfq7cKa2GjtHMVwU0moN0Ky2B9OW4-FBiWz_cvtQxpS-IefdCC858Wb-2_rf-QC5hGTSxtxa2Q8AyXglE
kOl_LfXEIkdGKtZ2Pl7u5F161U_aXex_NW7iqXFuMPyQ7hcDymFT-1JmcNnfFkbhFkUJZ_daSpxvc4u-nvCFwkHlzVy1
}

sprite $osa_user_green_project_manager [128x128/16z] {
xTg7lk8u38LnGrnqv83V_stNFy89cakpRnosyMsT-bSiPxhxr_NjsxTlcczz7Czt_Nquqy_ey-e1405K-J7Yze-sf5i2Zl2PIwV4ruGZoAxyJOyn_XY04-pD
e-96bwKaDGwm9ozMvmGC760lNgc_6a1tuUTdF0U0I2tNobwFBrSzili1iDC6k7lop0o07GUGoysFaVgB0NGFdyidRx8-U0K6yyhJfnyk_HW0jUi6oWwFdrO-
i4yT01-V_lq0z7a0e_bi7z_qSm4y01ti8zMix_rZ7tm5nlf2dtpjRW4Olm3U_jJiOrd0wDjFlsPzydT-tj5dJtqTxIEP0Ip_KR_X_T_HbzMFpnwVFlRoEK0a
_acV0ppz_c-_yrVwjJVyZZu7iFg7V5cGT8tw7J_-sn_-w6DHqeE4FdaP__qFvCgyuSTVVovWxLudl-FtlrbCLhVyFZ_-u09484y2zZj-Um1ue-_ruy_20m1U
yzn-6UpFF83Q7RxZuzClV0KiXBk4Zp_Qlnp07VgCdtVmtmn07XT-j3_NCWTun-VvL8RpTW1vefElZUSpS1j0xdNkNlDyQIn_SQ7sEmAB6nwYz0VoagvVlvt0
nay5HC0L3EIhhwfv2N8Nyf92QXnW79ygpm78hE7syQgGb3Z0E1u01x0MRX-bbuzQ1k093EGvG6L8sXIuycfMC8wt0oW0jRO28af-t00hptH913NgmCMZhNQ0
pOyFydO0VbDhtmP-4jRFWRcsaLT9IM1R_Tl5areYRqPK3h3fzCdR2VYyjFXwsXtn2WmyVQP82NehBH_aU4lSmCR7n-D--A9WgYCsmCSNnSC4i3uCRmUW__l7
LyNR18m-Dw1TFanyYJfJrdS0v6NDVC3MxFSV012duDyKf9rNTBq243_vyAxKoFC0SeSVV8XlQ-Jx5u0KMsha-nS0sU1Jtx00G1fgqiVxOArw_mK0N4F79foX
nu_E7Pvt6rERQFfezZtvbpE8KKVwmD4ry2xivhi__Edus3-s-7cJVnGzbLBESXrXIdgUrni0RIZt-v7y8PLh5Jt4N4hjlFg2Pf_lN-Vrmoc58AUg-iCXboNo
pZVvsNxxqtdzbcCF5Gs7W-JaVIbbSjSEq8RwVQwV7I-7plyjth4sFtFzlJvDBINn0zMFZgMs0JhN7mrVXLCfSpomSodYsDJgYmXot_KZLpkbuu7DfQZhl00P
o-FtN3zoysM24lWHMihirg1DYTb-__hzYVUl9gMS76lx9jZyIbI_p_VlQBv5SZqBW0ZvqdtzLlFqnonkBQ519r_hkduHK_tt54ifme-RIYbJom6W9ajAljPp
_QIKSZgNclAZtA6K4joj07aP7tukh7tzKfRCw-zSdISvKy9hVD5FvLQ3pwOeAKu7mxiaubt3001KyxnKR7tNZz6_Bq3dLoqhD3LSlnQUHUGsd3LSltP_4irF
w9F5RGthRzEF0PXBR-wbtzZXw0M2EDYNyAQOrZ_TbMAGbF9ONoJ4P_5FF8IrX82HF8B8yTPayhS2Yo8Ufs5yKVW4I7E0J9A7yTMV98NO4QQectNoHMLAugVc
l8WF6CONH1y5FQKmOTwkqmy-njHHZ66Il16t_kH3NtvAkXcdhrn-HnvvCqu_upUTjz5sWFESUvitmwpyEZUcqNn_G_NzXt3_WRvz-_ON
}

sprite $osa_user_white_hat [128x128/16z] {
xDI7Lkj030PX_pFn-p_olHGTYmuBovesa5w-ACVHzjx--kilFHLNFG-lrhlK1TdGTMw7aksgA8jzr5RHLNwIsvbHK_T7NUFJDv2-lixlo74rwcB_VYpnUSOF
ggVD7uNJ_60jenFy7Bz3blZUmw6tq88le6TCofRUGUhdpmzWHM-0OFkxZvlajrpqePFuOdFyDDnu7u8LG3fGcU8_YPFU0zpxX7CNDBfrARmzdXyIdJP_sqBk
Jvc-DNz-DG5j-twG-Nod5Sz0p-WKFy6lmskaEChFF8Z2rFKpha_YKTKJzDxew0W-IrThoUd0wBFrgs1Wz3bwuuEZN_PzjTuuk5-rLa_X0d3vg3-c1mgl_5zi
VU36hiDG64wimkAY_U_soMS4uWelxXpuHxir7qrfZ87_VTqUtF0sGlNf4VzxTUieZjDW1_1D7hGzU2j8AIK-FW3mrsoKbr8J1tyufCssqbJGCg1d_kyVxYet
Ef9CY-O1eGmTEVZuVcN1jMAbcrH725WspGKzzr7ukm4ObIuT0Y_sc_ol7t_S9eWfsIKtUloTLt_0mwFqK__K_FJZLeB_oKvQVaPyt9BvFDGP-ltx-yRDQVay
RIuM_k1xFk9YBN7e1z3XMtuOBEtvzkQhJMItnDq7rKepk34ELeWfny6AxZuEm4gPA0pR9VX-cN-O__hj0fmlUllvsWAIjr-mW7VM3nyBkF3usTbV5n0ld7xn
zXadS7Rx3D-nWXCulVtYxe-QxGGE-TdRrzgv0MBbLMTd7Z7ku26VTCsT5sPA1vSmf1efSkQPc8Knm3xFpA9hdhmGLLzLCYROrZCBCx6k-V8aeYgV0MBulnx1
YmWJsG2kF7pbd6o43iV3IpU0ArzJ3849KAnzQDEv6y2Hjt0PKyiYwEAx0VWzNzDQpfsUQTJczmCyvnbyduwSkvB0PsRn6i2st_C0FYzZm_7ALV0iBOpzS836
S-Vpn-V-zBK6tgAQhZqyVF3z0BfcLp_My4S2ttfy0hRzBcu3vFXFMByOtv-0v-EReXn2YBLGIu9OkhYTWD_ZTqmC5icVsG8y7zzAmMAnTXRWy_WM3pKKfClZ
2i9dFFvcOMWb4US5sFfbfpIqID3s3RYzVfQTABHaCxO3S5u_QdoIxMuVmF7wxHEGzttvcfy3OZay0FVhXnXybE_uSkYBlNpTBu1T_-CBaD_pSwpHaIzVyodM
MFvC7NmIfB9LhCc6hmzzXR_BIuenRVfwqqVd_Bnz_5fxvZCHx_D2y7S6iFj_zmBi-nmZx_fu_pnw0QhAJZ79dg_DV_3zGsMljEqB_8TV0EZ0ptdN5oRMktvR
m6v41pvBvtk_0fdtV17XktoPi02c-twRGkToNQ-Dwm0uWbinDtuifLpbKRi2jmPeSskje6iyMhH6QyoNTVXQMygdQpoQsmOGruxXclq7uz5LtWOGkX5qyDPL
tuv0XVaMZgjttqUJVX96Hp3EI5jpwRhker5lDK9_wgDb6c_YZ_TlpTCqZMUQfXduBHyLX-xow4qUlSgZDtdqgexUrT5xkFMkZjwqhRVeFb_v_Vu3
}

sprite $osa_user_blue_security_specialist [128x128/16z] {
xTS7egiw3e3Xu2Ah6BB_tOu5KGx4KGg1wVzxjvTFsE1mB_yD_R__1sNkNqZVmtyXtezmFPLVcG3hMSJuC_qxdPELxqCOVxPkTZS2Ad-Ux-XpzZISpKDAiMKN
hgtN0Cq_YS-cM_blXBmCS2QVakdF9iX5EvFlTMMNJXq0NFxy0UpoyvsFIzu09_6DDTqo_yG1p8UExmO07G1Ey9TRttXt081i2t3QvSV7dYw0d7tv8OJEFsq1
RiVkbjyEO3wSSGUiFdICd-iM06m13lNnSVc3zTnFfNNuygVFV1q03lVpLtu-sO_6_y_unhzz_fSdy0m_cs-zziiv_klp_rJV1d3uK_riljRpvfzu_okHBDCx
_aJ_Fa1VFjs7c_A6F-tyBSRulFd7V_w8tG3QQ_wS5n3RWALEDxxR_gCtmDhW7P_WQ9zj0xoCF-dzxugs01_moVW3_T7k04yt_dRvVB1_HTi1SFJDwkFrQFzQ
bW5KS_NxpLVDFsu0lky0k1bFrwFziTQt0sJbi_BZqRw8r4hs6fwTYpU-rdemhp7XVO3y_EBdnKUfqZgQHyHvW393snilBtgUUIAPEvHdL9_d0I0_dht9z9b7
6-0uNhU-yOnOD4XzkMWaX2qMxMXUVPiWvmqEHLENkHlW67xnjJ8707O05TEL_sA0yZQ-yneJjWYnz2sxpjhV5kp1_V2XyXUm6DyDuFgGzfPRpGVRXrHM_6OB
Nl73vPU6WbbB6fjkOKiqtu-NuPSk2TNMOZPzCm2zzSCFNIBcUAjm5zaEk7veFapVDevZlFcq-244uZvilVMnqkkuIyOSLBq4oc4fyXoHimE-J_BqsIe0_UDc
4uqGSbxvmv1dlTNlm0j_Q3wBCLjTAqgkOFEdSh_-OQdmqzKYMm3F3q6uvm6oNfGMCX9IxskNuUvxcsKBuFkrzvkkSco5zYrGvsE8IN-Du38NFTzV0D_NOsc8
WDH2Y25WvtD8aABwmrnsU5i0nxyqVtpm6vaQVpSnneGF_YX1QtvPV7HuMu3F_1i8RLdGo7c0GjlClzpyuF2QVmOKqEDlefd-ytGiM6ivmaPd7kko_XV4sK_6
x_8Vqf_6pK_4lBAbZgqGa-x_pIy-hnl0N_a8bx3zYP0sjXOqXODckkEJu-Vcnm_y8HfkJI6a6CsFlkvlWFaZFGQNsFkBNczD8O8U033xYVVufQJcfzV-l82N
G5mtJJ746DIFpOSV_Epxt7ByKTdcvzd7vx18TmFshn_G-LZ0FWxjNHU9PEkda7DiFgVca-VB3h_0Khbb9nDl_1nIQdxY76DarvV55zylMvyBn45VBQqm5nEI
h7q8BVLBZFcrZwuVce_cCt6B81bkTeXQ8dxYHyOOWLyCyDeFWQhPSthuRs6rMx7GsY_cKupe-bhpwONFbQrlV3IVOwHVVFdSbvLFYn-OKsJVhoAts__glNuy
-EMDBtELxpvatw-BB-fV7Ly-z_-g4bfH_GBirdmcqikldZ_ky-lyoyF0ZCNtvysb-V9RlJzqFdtinxZuX2zyMRwM-jIVF_vt-J96BGpylkNojRU-oAV-TFFf
bKnquwSN_be_r2T4OXPRVQr__OhZIj_XeujhPBphfz5myyDJFqRizt_swJ6yHsByCn_puiiwBddx-ME39BqMYtbCYry4dOZ5-AS-pduUPHiM24E_0a34wyRy
qYTRh3fTN_hmw0lXBTh6coeiFiZJvytqKLNFJyqlLHvZXtHyjshNxljXu_CNrRBusR5xlFTZyx7ohYf6hVdZj6cS3FPvyuSGQAzFYv-avxxoft5Nq-A79ECk
tlmGz_Qx7zJtWvmpX2NNZv_xbo_zb79Enlj-_S6FwSVKtyFR_gStvTVf_jTTlFfb-BBGHpBkutK0JB7lc-K0bhfFLv-StFUuldsyjV9ahceYmhYDHEhufEcw
cxUk3oalLBQXSwaxTPyVHPXApcKRP40McOxJhUxYAMkTtz9DE5Bl_L6uv3buA6k5PJnKDzuIWUpuzhWTYVS-GNOFlPGoa4m7uTRMPu2a9r2Fwqy3i1n1-xuW
G0ujcy7i4686A287oBu_YM0faCBwj1-qc60-1KP7t5_t-1SjANlHsXmn5usDFyct4u2n5DHAWVltq9x-etZ_1DIecQtbgsPhOySVF80rLkTpxcZUkdPDOwrr
WRr_oXpPZe-LW_lNyTO_4_y7
}

sprite $osa_users_blue_green [128x128/16z] {
x9bfUkis34KRIo81q8xslzjQX2v31GQ7v8j_lTEvJNCk1aelz7yT_f5gtYsNP7XtwPRzlNPXPY9Y5dbZ3ueyLX0ZmdlqAgyXudS4AFRmv5i0uh_UWZrtdgvo
okXVynJaJwkNLwKh273_Gpt7OhS1C8FtwCFt05m2_6dpinlK0VXF0q0FExW6m0xyIVanGbzJ-pM0yLCi_CBFqBS2s0b407vHVj5l6GIe_8m6eFAN_BRy3LmR
mDyQ40l7_tCvkJzOlcZr203_fG41xctzOYiPfill--i6e7Z8ROGvFsLzXFxujWXG-pL0_dhObsLvdM1--ufVgof-Em0vxOlQovVZR-D1cXf_7FSpnoUsz2tp
5M1g_B7HV_WH8EjH-pK04eJn01Wd_Fx-PR8-eFXUW7b_wFYrUkXD00K19ltjvuzorI-A3Q0x4CRyXq7z6UWz__RKmWxC23J0SFs404WGe3Vj3nSzkFX3cS2a
txv_RVdh2hqR8EG0Ktu4C7gl_0K0-1404-ZxMHrgi_fc-RVRpVElitu0-UlorGzxnWG8EK0Oz0kTbcWXrSEFLrxNZm7Go8_xHAUdgRVjlu4N_Z0p009MVoq_
ggJhdnr0nLKEEyO_vTy6_Ibho02z6Ry__td_VZQ0sTFx_aNrddyTyj_H06RFhaJu1yv_MK3g-dC38FFiMF_A3pp_XWFGypzm11WGMx3-Q47h-J_iHmCq0BSW
qlvl2E3fuLz7_OyxpW0rzCRll__3qFw1-nEi07dspEatIxWQ_SZvWrtz242kNbYVFmXWsMRzq0ipTe3efHq_TvoMlXxFtm7zuTK0OazUVVc41NZIrMFz-lei
nIshyn0KJQV-ZAE77-sFNJth9IzkceLVsHKiW6BjqCC_geyiWW28KCc120PGWDlgqVwXwjMl9hY4wqZwhmWDS81-w9S_bRuAm73MMLYo7Wtes55-No_G8u2a
_FTNEHEftJJ0rslvgQCdrTS1H0_Vjmz2H443rYquTjMZ-tjJdw2_9C3IrUTH51OX1CWQ8rSzbkzpxmwVQrIYzLf__e9K1N0eFt_BlWzqtoHG7o0SJrsCUz8L
y0DiA_JtHldelaKunif_D2dRTI-rQzg1xPMzwFcfIAtkGs-WRtvMEsCW260JLFTFbF9BjLa-YnE0MG07fCGBYj619vT7JhP3ZoFKEFeamdrgFSUy7BX_L1qe
zu-g9z8Tzigdl5Oy1lGvj11rxb_fFCO8OFrbosVrEAB-_RFso0a0F-EXDgbdLlyJv_wT3iGDWFR3FnH0eDTd11yIPl--WAGH07uvcT9h0CeU5bHTEg6jYIJN
0CxumK3tHVNAUM72YVGPKCv-JBeQB4hvpCmPF-YNJwe7kTCYibwHf6T350sG3Zm_cDDpn4bSbY9VbYtfiu7a6i3wIVqrlU7p1RoLbfgep-l0Kc2iWBj-xGWY
Xz_ecOBwDrm0t9xaVnD3b0h62lJye5QBwb-zgd8Y4RfziSW1odSd0FyOADyGDUJjG-KV7n-RlYynMO06N5w-mtwKxx5z513ocv_HWCR-pvSFwCjlzAO1qtwK
B-nomxTTZDzf09v_WtvzdlK7i1Mzqu3f1OIVMi-723zvUc4y0ouBo6F-xgyKRgg_5RrbOW1s_FMR-bMALVshqVS6m2F--WjVwZceFyBk3Q3sQmDuqDzvIzmo
gdTG_wK1J4GpVZ_0SkWNsCSMG2T04tu_mNRuLvdmbmdGlDzc28S_ED-WB83K_hq4u5c_XGv_TC-lzU_x_ba24FCl_N8i0BlVeF93Zm29g_l6d_kFUs2_W5Jx
eKS0eIOov0_BiZNyoVYLy-PPkEaVU5BJiWHf1j3zXnyyxahIXIOBb-T_4XzU5khvsVYHe4bPWDHU09xrWyzs1Bo0cdhP5d7zn_SunxyRFp8yQJUWxO-Rk9p7
B1t-7VvnpWQq_HIaqO0a-bFCOz_tQVyZDu2b2KTnqVElvSC_GnuVTm9GmozFjFm3-ASQm4mmJCEd_hx3FucUWPy6A1-jVEuA_7C1yAgS0tV9wFxF6l1PVpOt
9y_-fDs7_ybF0WZz24ce7lxCP80xFfUQ0BL33p-OtG5y6iD3PjQve_TNFvXhmIImO_6DVpR2upulH-ST_rm8l2s7pFVx0_AU7-nluF_Yvfm0G2W0e93zKpk-
KVy91NX-qp_get_K1_L1Vr0Vj4VrGNtK7jL7xL5xM1wNn-LPgLy
}

sprite $osa_user_blue_tie [128x128/16z] {
xPQ9Zfqw44HPJI_CyFz_-soArv8pM6HC-n99dEovowck1elkbxoylBoyB00y8tyeGbZE2P-TFOHvdgVuArYWpzd3F04mXmLyHWzvJlX003RxE8vcpZi8ZOSF
Vyhd1FxMjWA2VZIz1R04eMK0T7_MFB00xVM512q3e7pJvq7cvW7eq9iSv0522f3yr6JyfCtiMG1mt0MjbczwusS12E3lDtqvGB0DD1dVTf-H5H2QR03d7iO7
GwBWdrhuvmcO_ZH0s0C4Ptz8sxVweI_xiO3WVVK1yuDJFnRWlFw_zTi2cgp_kdyieB5__BWVZelxhwr_jW36P_na_klpDu4RW3nlV_X1SVpS7zpxFmqmPVwM
r_zi0OhF7ytzXia_v0-GJ6UOtloXbNykwytVulp70X95E_Hj7a3CdoZhy_MtM038x3_rMBydP0MKWDo_Vh1P0ILzi_7XPnHmfRVnoTc_qL50ADdpyJTllnmR
YBAotVG2lsy1U0Y2xyGDFThVtFthcWK0HRstNrLNjG3pkTtqkdvvwvEVSGmNAi0BIqHNLVNMgn2H1K07sUocvzslpdgAiAG4uN1PXFb_UzZrpA89JtqK9xsa
04W0TZM0dOIPY3NXgbzslIWlMOBSlaInC5a0LprB8lq34MpqESanlAf85i1H3tzIXCN8_geHoG8uwXD7W66O3gyHfg4ZsFq2m0yz_62Ah_HZQXtkUUoxY42V
1V3KMmAonoAEZ1qOeNOB03tZbiu3z7XzuWJrHnZvCu1OW6g_cDx00YBzjByq7mL83aKquTQ-SInW75C1D6Bxa_mCm7VzRFeC6TBump04vX3_w2AKIlVRW8tF
PwG21lYNeUynFdQJ1u3VStmmTSFKztrwTVVtHp4PLe3h-60SbxW1H8cGwRqAmCLFmWK2zzt8aGLt8ln-1HpZ2nUPky29FXlVgG3KJoBb07Hefwu_rwE0Qh_0
NmumCcC1KydFTMS0_8n7ddA0mA1VO3yleDfFy2F0MGXYC9dURm7mYnXSPZ5zQG4r-ck_8MNg_NBuZOe0TW7SzODF-rbE-4k_-i-VSn50zQPVx_grpWyy_Fgq
Nyr_u_pLiluw0Ex_-WFWhfzl-B40lUiNw6iN07tHNmwWwwhAjlxA0khzigwhC76z7zkhklxXLs7JLnR0KYQp5qx0UtuXfki0Kl0ZHAr_qmZpvI5KVWd-Mls6
07IrWz8BnB1h_AOQkmKe9YY33ntwH9L--qQ07Mpw4euGWFvx0nNw8u0m_Hw6VTsC2draLKIei4DlLEWJNmhGxJMuvc7VkpSg_4YmQWMmU_WHeLvkLFh1zrTa
lIQ-wzlarVFxy-_xZGVru44zU58F7hI3H_NWIJjuL0uUb1iFoet7r3aEukTvUNbvUVaF
}

sprite $osa_user_green_developer [128x128/16z] {
xD47jk9G38FXIB9rAQ_iVxU3Sy997e6fPlfF9-MxPVep-z___fUsyvV8Nael_Mmy1M2g02Xi_qG-MEwcQKBQFujNuRl2_YcwCUrzYXDjFnstYb_yTHoKY8bf
-zaRN-nqmwFu-WTA-scyhkugRwPFpYD8-vbyjVCLmkpN_-dnJFw-Jv2i_mcad-47rcvyXeglSP44x7xUU9o25IwH4cYtymBn84gi5bv2jFi9aFTrKhpwccFt
3gG5pkrnKk8rQGxgzMs2cqfUs_4YxLO_mCTffQk84DAzqwSUy_g8Lv3To0kgUAUz7TqBu8IsSRKMU1zfj_dnqG-nqbBSI_1eyuL2Lei0gwtlZ4rP_dkVpyXS
0IfsZLpakUZqHqv0v1fZLuxS547wsEM_69WOMpzt3MzvGNxlyjyj01jKd_T34gBH7m5UqjVvnGiv-loZ8P5IVDaFLOIFVVxx44DLn6myyYCqrxZzrVl9KCny
rEk-7rf37Xlzb_CGexeQ7uSGbRZofC_5DtK-dmmj_ZwkQOx8m_dSwPz7GlTutgGAygdPFpcWdSyxYP2FvsR_E1oWli87v77gzuUJu9TuWEbnEFRxbvm50An4
RTabfG-Ndk8VQWZEqCnDDu6AUUgVsh4F7RbX60Z3g8bc99_V_sqZCuELXONNMP8BfVterpwQl8xkCzlduVS1bFxxfRxrxFMmFkRR0AgS4Wjyq2z6Qe2vynJo
Qwf_F8ty5mES-28-SG4eObxoyf7lipnwiNtvpFThEJNhukVrCv7N0RfIBW8SwtSi03Uw7Z_TtxK00LVykFwUx3SjGCI4V_JnvHyBuDcRxC6dFxvyMy0JUiMt
3_Xt0uY7yTb-wzMx0SHtVzkp-Mc0SgMBx-Np5HW353phkZrhit9vSy7p3u897pmAvMVovRi-lYPuJgyzfe5EaCbtdzG0Ei8Kz2hQwpH07jzzKWE8EONnSXB7
i1eWZmSm3I0BJo-o0RI1LDuiSHVHcawGnzyFG2OFC7X5MgzqJ0E47n_Y5QakT0AF3Q3rWhpztezp7CsuU8mJK0F4jYz-nEjEhnwV0adRlvzWVcNq0dfygBi9
vbV5Bw37ByHL73s_L0F83pm-YRVYI0lmFtwnx_eEFhe0FNufOC_XXnOWtzxTSlA4lWHyFkJt7Bpb_YxSUhP-vU131z3v-SZ3ZmD4pgySkWuGzjMTdk-3S-_f
ykdq8N_k5fz3hgzc-iP7n0yKzVad-pNgw_kFkxhQ3t_zDOGEKCC_W1XQGDol9RW0dT_hDqGNCCw_OW76e_hzniW0jSR-0XZ_TV9MTFt87__-0QB_YTf30tIy
YDzz_3u6A813B-9x7bq3L8p_D_A-q_yZAVx8msk0HXH7wBhnoiDhW5Q9T_6V-hQF77nlQnh1LdldwaeTj_Pp3buJ-Dg-zZcFRtrj0JpkQuPj-qLw4-uTO0_d
u__xQXslrl5g8Q_MwMebhnRgQYMkbk9gAQwMqNE9yFh-zmC
}

sprite $osa_user_green [128x128/16z] {
xTWBhwCw30JW-snc7Bhy_tzxaUaer4AYnoJbhiJi-xo-YTqMzlpns-NEdJjthBPy7HVSSXsks7VqIPwH14WplGLVu6MZj82gy9q7dQ64G1Kmb6_wu_481THW
D4_77mts-9ygC997aQwWXIemYhUWxnQm8VmK-LY0_djTCeywFbxwGma5D85HV17ViYd0WGNWZtpdchrVm4RuMhxuJRQ-5nWm0DFqvV_h2GMuvBM1US3nY_Ek
AzyQW8xV_5W0OG2z-HgEhyG5Q03MsMVnDF-VV_PzwYdGruTyyKlY0i0n2p0V_wS-rmLqV_It-KU_xFbrhA_i-zRRPmaB47-1l__y7-z3VYiGZo-VmtnTVuH_
qrS19V3WkFbRyyi1FyvNWQ1_nSUAb5Ua1tx4wu_kFbQbx0Jn-EX__I5Up07lFllx1YWxklXnrz-AJQ8kVipzXnO043iHFsxyRG0yq4VTVyuQ0BdFn-tFdVr9
0rWIyP77bp_hAR25o1Ze-Brz7y0EkizF0_o30kBfV6z_Mb9Lu8YlqtFkpcyBO5Tl_9B-V2LR0UpgldkhawSlxovjUo48k7Z2v7VaKLvVNmrYz5uIe5RGaLzy
ivNG4XHjtcF44XNennUOgO2OXhUtcn6bg40_dcGhq2osDvc_QIsW2VJatN9Ev3P6ldWBA-Z5jm96ydqG963Y-nK8l0eOm2NIIVTalnKuVNoklB8vdtoz9fg7
r4U06i09tk_xkOt9RmyyB2dYDnLD1T9-5HyQwBoozFJSxaWFWOxJLuobq5hA-a_LMwCDd3m-znDyE2w_mmPqV1Xt0tBhC_0g83z_V3CU1jppxJM0_F5HOF8F
8_xy07HyFSfJlWQGz_tJFKdUgAT0oYVaMuBtw5KujVxm8fFWjO3q-jDyN41-_Kf2rm9E-igHtj-dlUT7kdnB-dG_vaDSOLTV-OYMp-v-oqZV_YT-jKJgURy2
IFjMU_dYKtx--QS7ODglfoz0NhucVJllL_SjwzTm_Kak89sQNtyR09dtdMVD-vE1O7u1v_u7qBxhb0sq_Pn_ii3PxqJDNW390WJ4ppb-RWL09dJnIpAw2X1h
-549Bi4Q4xyamQl0P4GYh9FpIe9NWQaQVugl-dDkIV1BdfCg67dKGbjoN8TN4hmQfFByDRydutj-FNDu7ryTdiyFwQVmc8IVIug_VUKoNhcCLwxZbSjqvK9U
kKvNBiILAt7bIbovY8xf05-VEtVktBdp7m
}

sprite $osa_user_black_hat [128x128/16z] {
xTRfSkEi4iRn7A3fHGltVxS7FwLqv9f8iYKitkt_VUhNQXZYhzFzrt_zL-cArthYgAEERXTXbfyw-AYtx_sRVTJPL-hfpvcuep_Gesu-W-TE_f29KBxVdooJ
nxVwysXCcLRbuGP_diR1L9Z-IFqD-Dppm9Hpfj_YkI9MTchZ_rhEOpckjU-uJWLry3C1x-9dOWD-lv_9xHjv-9dLncakw6xVF_b-7dNLo_dwwltm_df7VExw
xGCJTTD73f5gNVJPKgYbY_v9VE0OK8H_ApyfGGwe-dmZFt02cuOn81p0FVna-NlhMaf9VW1t-AF0GtakDRtBdmQX63mQ2ve3-hW_Mmu_PUZem_xyD4B4idag
fOsFjlPjoYbmUSf251_9yjfFxHu0OGfBiNmt_6zw-E7du-chbC5z-ceM4Npa9wrV0_wxaViIIg6T_JVndPjeBlZQN7uQmYTz9CMRKtWUmCAd_1WyM_CewlUV
tgNOt0UrH1Eu8GKl9iefUAcvJs4TPUOOjYFuxNB_iFRhzmlmUgcrdzzR0BNs2nRGPVselBK08igD_K94wOtJBwrzmGcykds1tx224tXv-wMvFrWcIY_oKslV
QgyDa2flDZNcaU0E7l9aZvhpAi9qS0aZrTXGOrvOH0K3xFCYelQe9Q_CrJVJZ0cszImgmcAFslAiQgQA0LByKq_WLLMOVO2cF7oJJ3x24uwFrxO3hFcQOGXC
W58Dz8ykBGTOynuk8w5L35tRRW0--7LMovdMPHxC_VK0rta1_vmDafyYXIyYscu0txwk4lXuZ1t7aslWHPSmziK15bvq5GGynklOQk0zhjcZAxmvxtq_Rtxr
KqsnAlZUvHFuPVlm1LfEgx1-TVxv15f-lYicCSPKYpNokx5EbXDe-Fbh9aMFzTTy0Iq_twFeYNex2sZp-Pw4xwAkQt85uGi-VxCObaYryG9y_ReJXILMj7q3
JgzVT2UEIxgP-04qNZzQUDBjJX_0mVeHHPJtVVsOdoCIFJo0vjSF2VYad_7rq5T_V9jV0B_-nnSWz_Dpgl6Hhn_pETL4VyqQ-Ap8TAjKqmtVBle6VvTNIeas
VJlfezVyl7tyLhlc2xFiyyhmjmU0RrSUW7rVKf9T7-_FfGVGJ7TAf7k-BVw5tn-cUn7fPl0l_W3W0p_dNL-5nSxwom9sOpxmHTt_n1CeikUhgfpbouW529_t
lxSmbVVrsc1cWYCubSZ23wMKTtbasC2v0J0tU2leFHxDLkD78c_hyAqsbuBUuz6qR019xHYk-Jzm7htB-m3A9u8EtdlNzoCm5Jc5u-gTzz5eXbJG4OmpigMf
FFM-ZmOxrG3zge_cSJY9Nzw_DutZEBpIE4x0J_ceDEWiZthog2kFUlAeguxwwgWVxlNLKK_RwqUlQoltx_y
}

sprite $osa_user_blue_sysadmin [128x128/16z] {
xTg7ckgw3WLWDnNR6NZ_jxrMvA014qAOXDlEEdNNVqbE-OPlk_-fCDtoVPmUy_N9ntnzT4G4HFng0rniI1R0RpKWpOAF5SxbJOynFczmEW-2cmujIGCagUVo
u-WmnmgSojli5h06I2tdyMZ3Vxi0KuloOw3dn0BtVDIC1VGQm5DuI5sCbk48jC0PFWwyvCx7iqv0xppZLmhWNC3yCyQFZp5V2zW9d3b-267DJsVusFskQuO2
E1V04toPwrqVY8ZFN7zOyiH7Eu13VScsVyO1Y8-xV3ZSXxHn_j_re_9hVZh9txx_9UhpeNuotxBYm-pJqJwajFdyFyq74JgrodS_dUoll__npEiFh40oVU3F
kVymMO4nSBfFNTdWJtl-4dHcYxVBxuGBG3Bom_XmWeyc3RhnvhiZmtq15hD7Fj7H_jKMi19y69-FzRCjO5MtyOK_rh-oBM2Bb_7hqNxfxs30KRV0ilshEs41
lG3YY1kVgELok7-PhC1QRbz_b-lH_ZHDLI-1zGAYApyTpTTQfodJiW5O6LxvtBhMOtL9PbuAZ0tiyoVYEjMMW_d2pBblG1k0uQftFcVjUoYVgVcbC5c313tB
Dx7ppALA3kM9k3IVDpv_vLouHLTmE5yoCx_u_5daScW1utDMlsNbytTczOyiO7nBymN9cMaCpw4YiG97ybA0IOViKzicT3N4vRx0t_cYlAQm7dBb-HbWzpvL
yOboiGAbjlpPP-4jqaQ6JFSfLU-Dej42LN8idscv4sEyuJ52BKLlag70tmy_tuNwakFlp7FhZop9Uoy18AB17_ZCg0ei7m24bZpxoALOygvBW9OyZi_v8KHw
9mHBB18RV_S901746FKvzc9ybZgK9ILunRtteFFcsRUylm0Yy7E2dS8mll1etm7-bbxIV3k1TtqA3PyR8D4u_i97k7qNcs_yvmkWw6MXMi36ByRh6Lc1u7gY
-HyiO2om-FeyCpv5II9wE00m_la2tBu2JH2-ziTvvp65U5U05f-D7nUGw_i5KY-0ip-tboWVXUy5L0pA1-E7x7a80b6uBQ3MAkMNCPJlGL8ngP-C__m09DqF
Fiu-ttmc2CO3PGsgJwQl7S0gEFYQnIyQustxaZ17-DMykW2evVxRqJtta_AsVKqKFfg-xm90akpmKqh6Iq3yLFRwnWKY6dtd1ZycJGHYyr5yV0xNsmLGrdnq
pXEHyU3KzyJtFdHV3hzOM7nQyUiRldVzQMky-E5-VhRvyVuT6vkVr_owvPEySgI01lpoHatar3S-IXBGlIRVNLRz-exlVI-GbB-x_stw2828nFS8nWWl_BhX
HzyZjxSttoVA-lmpdeYaq7quHYol2hny01CuVulp5YbGvbzhV7vcv1Xvoy_hFWLJBS6t01KvW7LUasB-Yu_E3NgKet1I83DH2g_u0h6i-jDKQp_-grifaDn3
V0m-I047L8X0wgppXQ2iPfecyQlugmN0FIG4-QVv3fKFQPqlZEj-dMh9MSR_kQuNm63VYetrMa2-jSsNJ6KrUl_h-EOF1GZcQNs3YEO2VYuGDda9l_2BHCT_
MO0iU2iG5vxBXycTdwxclwe0pbc1W0lF7nRWh7ozN3LkCrOW8aRXbm-LzYRhhwgwVVFVB73ZOo1YISxxyDclklqTlXO8DzwvGFnPIjNfz_XLKcZXavzlmrpo
7jXc5tw7Bxycvrmhno1yzBuNcD-aERybPpttlliT_jHWZ16nLEZJMu4FCbskk_nQ2LA8W5GgoFH12aY3H6KtlcpUiiap4CP8J8tZvFHDt0lKdwdbBNcQVWGV
iiNd_WawpmN0_ohWWQRhlkpd4M_tEkNAHnVOu8lnpUTQ21eSWky1-ZcV9-9InC_r9pyKmByLsEPRa8lupFBE7WjSpkBpp2DqdagThhr0q4WJvCi9_DHvX1kV
s_WIjYzAlFoDVBnVQsL4qPFmHNaPr0fehC2nFEcVclpDJyuzBq1yj5vmrkC3_xj0i0AH-3X-Qdo6MHzuoVC2-IXUXYUGpSVG-MpyUe5ou8K704ttmBakV7Lp
h059WIXuZ37uHDC1lFY4gdjSU5vuowr0YxGD0VceXqxJzPhAUlWZBv42KGea216YJtJC2uyWwl0BJqNv8L8WoFZEGmgHfh_WvcFqFd6ByO-_yghvcGiaI00n
9Bhy4R-sJ9MHa8JFPJdyQu_PIxI0dZzzW8yprQnwvxdpOwn0YEsVHFmnRReiW73cy_BEU_r-9qgX1OW-W8str4AuyBBzhQkAYP28-F81QxpbfnOYyREEl_bo
dp8pry_cDjyozGB2Pnj_CuVCRmLQxDe_rnyBrCooWrel9-hh3NvgptZjknFmiS5baZpHDOVQbXsRFIzVfV_9F_aN
}

sprite $osa_user_blue [128x128/16z] {
xTY9akeu38LXXiIs9EUIzt_RmPpKQJg5pRrkcTxorpBxVB8SbkBqZnqT7HqTfVi-5KUVYIDvYPxJLWmXp7C88SQqbSVpnEVxGapeDJpnkxO9NgHFq_Jw2R3v
FHvA-BEn0mZuYJm7u0Hnv03OFVMt0k80u_dA12C7mFB9lnya31z0DfuuUZz0B0CKNuOSlx3KzmDiRQ-2KPTFdkqNm07SVVBr0I9lOCZnSVVxw6E04GlOtlVk
-7EfuiyZ_30ZyWy7YBS1ehClvVQvVl1r7nUWtayVeeyU-hW0Np_-hSyB67BzxVtJ3uFzwUK-ZDRhRxWVE01xZI_qdx__bl0243S_qh_LFZxzwBv_3b3__1lv
_0SEKFt-CTndn5_dSm36o0zx_ukRKkVfpmDyN42fgeCVymM4VgdALwxVymBGJj_pMBzdmWNK0kw_VhHo0ItU__ZqjRs0k3--EFkhR0k8JPt7NxrzmmBcArRN
oHjyrmLmWDBU9e_jh-x-iWW7O3N-uktdd9VC0S9ZdNnU_dZpnLV-z1OU7nvyoalEsPlF9Y8SW5VFix_nUlEpCo_NLFdJ9qOWVlSZgAXQBddo9ab4pMJtuoje
weKN5T5SSkLJuKraFy5U5rNX0Auy_6ly-PjBA3XqIMQj0Vfv-ee146I4sQmvG3zVCasOG18ZhZTUp6y0-E3XMy80nfrlTv4o-AJsRW0_7WcUiIpRPt7SlWvf
DYp5p6i0y5hETDTjrMQsU_pnRsBz7C0uGBTlvEbZnscw_oqs5R9SX1h2evfBRjj7cs_JNMUzYIdY-1n0F-ehUIOHVZY_DM7b4STtkG4UN_VXRrcwyyFca-S0
yBsEZqHldVzZoKnBy1aNu7by5jvyLV9k2y33BwQrv7IwuQVJcRxvBM0xlcarNa0WxxS0h5_CwWFClFuAZmLq-mQ_Ea3YzLTzxNiFWAyYQgq1DdwkwLX0jo_m
CO3LBo2ITxm0-COU-H4--Ve5zF3FVS6RB_HA_RxHhqum5NysvFe0q6zEC1S_ZlFL7aJTB1PVx67PxVprfFXQyVC7_VpSr-cQrVpSvoFwpUPf2dK_3_VZDCM6
d-b_uFqtMxqqJMBD0VW1qFq0vlO3e4rVwVS-WBdbspJRCz_0zrv0axSGwlwovAoy_ju5jFqOhTgoBAQYtJuMqFPJQldPb7pd0jIQYLWjF3aVyqrKh9LgmySG
lVwQhwcAM5yOhPzVCO28Q1Sl2ZslwzgZSu2E2V0VRNofYryl7414ItyXNnC4_hAY3duRm5J-FOM-hAo3lxPaZD2XWsSTVEbFHjZjy_3CGx_jddNuc6397K7t
y352FyuwVNJvSsrvtlNVkX3lFhz_NzzddyYZJ-JHP_Be4tdqcJhwL1rzAeu-4MUVYBCksZy7-FCxEZewEleV
}

sprite $osa_user_green_service_manager [128x128/16z] {
xDO5bjum30JWOgoHqvVxdxQWP0pFwvGa5pQpZDzO-Y5l_hayUVBaYUQQvNWUiXeVeslqlNW0H00jcv05F6r9DG9MM7EZK-8bmWeIobTzsxQ-G6aGpSFmeiiP
-yW2aRnGBv4Qi40KhzJl2cW8lyzu5e2zprzpH1rVBdrZnW88sW1tJvvf2Y2mmBUvmdZgqm8QuNFvv9kqlXK8681o-lG_Mhe2vkFQm15m_5JuZyog0V3uzCS2
z3a0RpwFnxVq2wW3K6SVXZJ-Xmyl--1TmDSN-kI_PbW0OXQWDluVzN4kmFtMty-VFld1pu4-C_NLsqUwGf_yOdz-_u_tfVZRxFZq4URp-OVuIfy5fiz_SVFN
wgSf7-spGASlykL4qXNg0-_--CEhZqj9BqJeanV_vn_8nTpnzE7lgvICEld0vzyiJGQTVCZr1nSW0fa4Y1n_7G3kzR3hpuC30EvvRlzmzdSE0C201nwV_i6x
G0jXYF3uthuDO41d_1xWbmBtF8ptzlVTV1Quv_F-wV3ckm8oqSb_ZJ-VWLf0HfsxrxnRV7bpeUqJGOyN7gBq7Nb9r_zd0uRXJm4HS0MEV19HrNm6euvyHkrd
BE379r5b0J8bgDzNXQJ40duy01PeBTHlgNthBC09UF9c6KUoZG8NhyCAdFXIG07qWm14bBnVWS8pUaO40AW3vj7k2lpsyK6-BS27slRUm1-X_CQNzkmqlN4R
1i2mY1sadDp_jWKiXW-TfefOfNk_TaR9hnScl8_lqKs-cghvtF1hRTFpWNP-7h7kqIs_TQJM-ZB1kBtTKhNEZntTl0ia7hoRYeOLFqyZL5UT_AggFaQilJiR
IDmL0OcO2UCYzXndzCctQRXwSmEfLmcNrOvttSnCpn7QOCnzzdtYvm5-ZrzR4oH4zkEZXWaHFnEVpc3AVFP7UG3BVZ4NG26CH5KYn1n0H9YbVZd0pDyx050Z
11Kp1A0a2Q4FeAfCskgvV-i0K2Km3be5G18lW14HmXQL0dALhxxw402Xq0032RWGbGm1eCHiBEQkafSBVBRuB5o4aXfmidcJI_o5xYvM8zDh_Fe2X0ECW9WX
sLxeXABThsQjNk2N5o02S70mxFuxCh86VsJUwWLzSG6a26M8-UCKaCvFRRLTq1Tzau-RZH5CPt2ief2E0RpLSttz3g0AS3p6095AmK07Zw9CPIlSLs2rrLEy
vmi-8zFnU2SCVEO1nK9IYk5q7C2WJts_vbibbXm0aQ3CVCIYmk91AsnW_G2cxlkximQI4vGFllGWU68MTVMS0FC0zf_rcugfYZ13vylWWO8_ld9NhrLBiMgj
dRXjrIzDr4rLXNxD0wf7Af7c_gc8do-WhVecIPWHlFBG-KpT-ni_1V5pV_7nXqz3nFgBpQn_y7LAKSuNqDQUVwom2o4IfF_AYx_unrNfV05h_hu3QF3OUO34
3nxjrRVZmdhkjx7-IxuKdFciyppp_G1QQogdVcqBwq-VDcGwbZ_nN_ijCltEJzxRDR-HuaRumkEH3duQ8C_s6xzT_WIGFXAN3PCltUwH3NxuhNfrF_7NFW6b
JvWlVidZx1EHJFwKVUEx1z-MVDWo8EA1P_QPRoreFVK3_-3VB_ay_88aX3HYJju_yQQrdUg3ZxPlQuA8tISMrQ57OgAYDlkkrhxoFRAZsldiUr-HPj-quvba
gjMZz9DNRsudUUh9zxxpdGWny08nGFXkmY-yg2TuZA3Ylf_XX_v8-T80UsKYt23tNZPAfayW8pLJYzoJh-rBESTBF4lsyW4e4Mpu5B60zfivnQ9PJa5QFP6p
7c-fBXm0SG5YaH0K2qs-vdMSX2gokr_0b_nTQIFcqCszAa0WXzTv9iv4aDIi_YRzwFZg08qBXvPwv090YMS7tmCKLMk9B7NX9JYjq7kQ4mm_QGJ00ha8R-y_
x6-xWThB0CO8o6g7ZrZwqmEp-lxJj__zuIngqV0rOiG0dpvip_9tI_zd-VVtfYQJxtQaGJyR7uL9hAR_atocrNJuRYDzZW0VFh8k-ziLlzPc-jbtTrCH9joE
aAJxz_NPp_OSOFZUCrNXvCVBao_vsrK_1t3runNMHsOgi1L4A0M83tz1l-fdZ-RcDVafux9H_t2Ul7bxBE0BVWpWhxRNgh2XY31Hw2pXr_QsW2_uKRNM-l9h
fhZ1yHmaHsfUzmLySO0tqTR_mJTYs43SJLNpJ-Xgvcs1Njy0atfjrOHWsr3xGRYRQHRysmgylWBjtyCYMsjjFshzES6zBLdh0sJLQtkylJsYk3ptihTMe_Qs
m2zFS5vESaE_FS6wljvj_Nv_dJtt1yl_zt-_
}

sprite $osa_user_green_operations [128x128/16z] {
xDVNGYiW48JXKrHs8UNztzQmn3y5x0pMEVNARnXI_xmdl_dDR_Rb8clnCaXUhVTPgcStivIIcNjUjy43daZhaDTCq7H3Nji0_UwGvjR4VsYWvaDFn5hYNss1
-EdEsOaPSGg8ZcySVcc1dhzZ1Weu1HGyumTEpWguii0c7dhmJnJ8aW8ztnTmfu3cyk7x0aO1Ra1mVFZR5WemW3E0wFZmaQ5l333r-AdZAO0l6Y2UUn7uWSy0
ZZ_lmzQ1ll1lRcxYtyxtTW5vzlmH_9iQVDq5CF-hV9_k6_wJ-tC18hz__7ycttL-5Re2y2E_oFp-zPVv1Ky0zZSA4FXhl-Zyz0GlVVpPi41QutipKikL3g_s
AP30uV4bht_PA41wNlVwNyoEpXEyuk7F1HZfT7Z5_5p0MS0DNZK_d_w3iL7WPP__ziS1tCUwwlZuTG1lr82N7Hy_1W0RuV1n_FriVnS308x35z0D_hG26mey
pvVzT7zJ_M8rJ_9n-RlP_gQ65u7xzkn3kLLc1-2uLz8M5PptVzihR3HmOc2N7ExN_zFmaE4dXDFFU55LCxkTzqIzjtAaitesTpllCiS0tgSUF8lDtSkhl4pr
f2sj-9Ay-7bEysxbEVx061Dy9l5dOIy6k8-lrNbn8vHjCLgSgZ70pRod6sUBHoB2hGvlOFUdsMrjKsnWRUVrjG5AGTW90NUYzmxqC5aQVW_K2e-Xqjo3cioT
ytnXW59JWk4ID5awk_dO00_wRThFDidRPnQ93dHcYG74l8x_IA37tyyZDK12zptPf657wmSCFO4w-zOE2ryce8mfBQ-EYjFh03s_7FaSXU-5VpJ1UdBmBH3-
iRpwI1Z-xWYV9xY_W9hTdyxay14pfWT7twdTmM81VJ_mOv_0Sx-Ro8K559fzxYPJnepmQ9Vy_W8gFG2iTq6roNr2I6sOxoyWVBIUFLV0ItMSZmN8gOyF83k-
KkWsLSm4gLpZXUC1NFE5PSxMfWQ4NLy-wZo02W_8jaE77aqCNieN-F2bunVRkuBQhmaKmfIx-lu3EE8h9AYsSm7xdW8Yf2mNz5Y0UIT-CvPeXu_0IoGNzF3r
n4y9MELRQiU-I0U_x8ls-V1HUbttLGTulUZhnfUUVwZhsdJ__SUFFzzutMr2G0IGqVH7laOxFjxlj_0xkcTqpHSTym6clkvPdlrqmTV-Dw1MLbzlzaMxR__L
rsvMVkhhYPyVW9DsaZchBvyl-FhYsJg-dQXhrgxwejsVlnebeAqlXoc__7R9TvvxVZOTknXwgQaC5xVVymUVviklUa7dtg_03HEKoOPw-L3rmhql_DVNcG_a
vNxqyeiEuM-TzSrxkxpC_ax5Gm3yp7tkrI89_cY0vZvU2hAsiTZru8ycu4Q9bl9814t6TBLNqzU17mEaes0tLE7pH5JLbfvX7os0kUIFodwrLbQriUBUEmEq
dTzPPPEkjwElXd6_zOuVBISdf-VQ9bw-WN_DFP_FQQHdq6D-dDH5hfiQDw-M6ZFyNWTy-EvuPLDj_hfngvd8Nx4-_t--YJFPbKsbv5oRJbysZu18kTGcquty
wZzLwemGvIKY1riJZJT8g-KrHMbs2nz-3A1SdN0M0PnnfrRMNwodSIs4LEm6FlneYdzlHQ9gEu_SMa6gT_2LMRwdPyNbE1FVSFSiXIYFfrDSKAZyXXu99-m6
2PPIquu_faSg6Kit0eWZMlofPge_noCHo0Ev7qTgNqzjDME7x-An_ej-5SSpvTAwTZ-JZ2C-0SKHQgkrDHsbU-kF2zUr4jND0k8egVNSyQGbUfTfhnm7xiTH
rOur7WlXc8yGnuZwl8EFzTTtL7Sg64S4MDvHKhk1Z_N3vL9Hr-z8XE0dgVw9VafubwyYeZ_gSLFon-l_zL__zJy
}

sprite $osa_user_green_architect [128x128/16z] {
xTc9jfis4CPnB6aqYtmlx_-sPGHy1rj53XVJ9V7_rDcJtp32j6w6twHFdpuLA_-M_DY_XwD_HRT_V0B8Ai9J8gAOuf_YJVWXZ72nVlyxVTd2F85ToTkgvwdL
NOu14royUmMEA_VgrrgyItbXw4yJN3t0lFiClXrWFOFxPJvuplWM1b3nhbe0bbznj1b05KTm3Q_i7lX_Q03uXglV6K1LrrlWckrlUI8Ci5c0OW6NN3vuciC0
y1KBkE3o7G9VWy_myHvuz-LpRdWC0F-Q1JnUFktuM82-sIzJ_EIdbCXhVCK1l7dz7lpaxVhsTbyRltVz-dPVddpw5_tSlV_g0F-epnxuQtmNk1qWN-xZzeVl
GM_NZpV0swyV0o3my2yxV_ZSuQ_rCK33N-_hRF3SezxoUfKll0RS-Ujz4mo0MlwwvtyHMPmUVy6__t00WXeT_1Nhnm5i0mx-glNZStTbfAdXBrZ_CFe2PcT7
l-RouVi2TA4wEax__cQ_BW3Q3hxv_3E-s__209t0VtLz-sdwOW1y_1mxVbd-dEEfOGDz_dliNZtTVXXX0rt-Vh_tV8q_JfVLxUWBxtMl_yUfhS_1LbzkFLFh
3s0cd7yKBu0imPxJ-MTLjFG6O3jHyKmUmyLZkjBVWBvez_Pt0yesnS_uJ_6B0PXJBKw5kTlB0cC0pp2cEWxU1s1iODTtU8kcE4SlVATc3e7sLty0-F7sM0p3
4dLzhvXY3zjjhBpjtmFmd_OT8dxkHlk-sfnwcA5-NqGNNdS6wFdn5jRM1QHjOV4Lr-VVVhmJCDkw0JtWXxYKrkkFsnOV0-1PLrFni1eSWM60WtuR_CtbcRUy
uuGN5YFsJe3vjkV7Ms__c41Op90mywB3nm2_vgVk_fVhHwRFlhWEldCBm3-u_w7wIBQ-ydQsDSK2th7_uSRQ15yL6MeMqF6dqeCVjjtWTmA_iu2kdpYcplwF
-lq5m8z4L5bAEQPQP_-7U2oWvoUyeR7gS_i7ZGLOrvT4b5LLG9tOFtYaE80TdwVl4Sl6R_P_mBSc7C2ExzyWok9-zDhzLtmAVf_l7m3yOV5pZd6WoO-hdvlD
U_0Fw3Y0Zi_Y6s3U-A71uH_GuKlFd_zAXoSVSNZ6avhfRVBD3kYT6u1pc7tY9KaeFgqzcQP4hEvxE_OndzAYu2P3ppgxBbhSxtJ4bnmJXH1V5SYKOagJN4eu
ufSN_eJdz8hdIKyfKU9IYhxl-iV9Jp4GxQtTkv59rNEUVBFRSCWlVJ-cQO2OAUuqaQkUEQlHRNYtxnFGpW0RNIOr3Twn_PUEhzMVLn2nTsm-ptfstKohVjml
UFxj-Jv084gFcvSYw-B5YiR1E-vRsNt-mtSvf9oslF6ggnK9mt36Lwo_zJ50e8Jz1wC0dQ7_o2_u3x2UxmDW1MdYGvprZA6E-bW0Bh_hrnNGp6V_gkh-R3Zh
rzFl-3ZvS4iJ68s_Y3ARSVAXV88JllDQdD_rCwLrW9XfchL-ckIKgXzE-Ihgs-_wjqHOGM19ZePAXvFxLvdIoe_ZhZyCzUInWZXCDJ3yGpXuRyVdgRpS1Nx5
b3Fl9_eB2JBmKmz-WL_Bj0pWAyZI_fscS4qEfAuxZ_xE7sfvNi5ywCGoZ2Fwkdkbc1x5lQ_nfRzCGDLVLZ1k-hulbL9-xR4tsz3HdeyLE3_V1VOmWU_WUD1H
wpz4621c6H56E8xtVTJ-l-10kVqJlgU-NlRzFQ8ztxP-H07v9nCTtnrEk-TZ1Pc_h_9ryeackxvYh4FKLmZ-2cbUGRc6Tp-w6oc6I65v-R7ZvS_WaEKIVf2S
YJAzBkVx1VnGXFDZefApQlROlvRbe-NzdJoQlpyoJuAQEqpitrnZ4hFwRlf-l-wosfRJxFmsfcprAUupd1sYmQUsc129FIMKTNcQVs664pYo9WRV3eK9V8Hp
ElpoSFMQwvMsAL6s6ixXZ8t6oYES1Mf_Igtu06TjDDgHV0nL7ixIxHIgfGApiX7z7xmr-VcFt77FD8xCrLg-mX_tM_JfqwTFd_u2
}

sprite $osa_user_green_warning [128x128/16z] {
xTc9akic48NXMJmMq8tq_cyROVwQQTT09CgDdUMUvAvo-JiqcBkzFP8_-PC_sUGkpyMbaVH2dJnLJp64i2nB236cvyr0m1UR4AWWJ-5JmEqqcAzVz-3kuJiq
cCtVTBFocjktSmiasHDPkqduIPnPGFO45ZzOm9-_sZ5WKs2E_pryS68An9a5L4IIuVi5qfG2FTuMY3y59cq-F27u5607_Fra-QyQKm0_Ce1fouSdJJ-u3u1x
p_A40lWp1e0VbrlWstx0Zyx-9Y8xVUTVBXSAM9y2PLxkur-iVoan_hmDOFn3VdJt0_xH_2amp--V_zVxSPvVX4O1-9Ol4_p-_Hlk_UJjXqAO0YPBmvTv_dB0
Jpj_eLbWUOuVgx7K6Dtoy_sm471uuq-w_r8m1KY3dtR_ImWuVNxIyMS3mdSQEloSyRC19XQ7dpT-VlT_Oq8xqDD-_xSnW1Wx-hJbuoide017V11_dm60jN1u
bhzv-oi30EmaSFWLtx60cW97l6pklXPV67cNP_DNRrzBlY-1Bi_cg-e4NfFigKfRP_XQuixlSgH0vzp3nqG1JvxRH-n5_8EJEg3Iam9-V3H_mKW3Gj0btTfG
m95VbfrF540neHgF5Wguyma6n-8afHJ3mWHS-KW1cyQFNGjOdWA8pIJYSmRmuKyK07Sg09_WAK3QEZu58lv3l0HuahxJqSjBA90UB61uasHoPyFpWjuEZ6z-
j05eXyVt1LoNJxey3nsE0Ck7Fwxm-q5a08yjFwROYQ7QnSO7a4rOVafnADZZ0zYgAJMgEMi8Itc_SNzy00K7lgL-Ls8g6UJ71u2EJUhFK62G9rn2ftHjHMWm
ofDuPWEwEWqeCCOJDk20H-yM40eCySSR02_mtTG2QL2t6p32z_TWL6S0kkSXdWcK3EYz0p3EKu1qyN5_XJzL81rbtEVaJoWWPpu0EV_cmrBpsnVnNdzh-fUF
6gy1u1yldtprVH5dNnh-jVAVNYS0lxFyhd_HHiO68ER-qzE7V-dvumCuEFxDvMke_fUBFpv-ZTM_gii6X97nMt_nk8Fu_TV8-3Lv-cNvWxvKFpZuB7_Cr-h7
ZYyZ-kwdBl_tVdh8P-tmspRYVnR-FMKo-040htgKokyvxry-tlV7adzovyV3X40I_2tdrtzxhDdcnq_XPEAkmvDJViuN7XC2h_6aBhpTrlFNXfzBlihJTrX2
WooQua5I4X4bwsPpyFd3kPQ77xaPqO6mTfEE3qwMyl3og9zNpBwlakznmayref9FP8K-yhDe7elAkWscxw_ZlkZcuPFUEEFbOz7E-Dtu_WP8UNRr77__1cmC
WC-_jdXrv1d0a9_zU4wWd9-_Ydho_G6aoqVGHY_9ZZe3K0eSH-7zT8xWMLvN5toy07nsmyTlOHN9tZOfxts6p_jhFMcohMKBz73ugtrJ1zUy4GMEz_xDEHjP
izAWD_kD-FCKe45Bl_kjp0oU1loRnnsERZB9PmO5hE7xw7DzikuLYakKtyazpQS3MIq-_m3qythVdoUluyaBTV9AdRmK9q-s_m8
}

sprite $osa_user_audit [128x128/16z] {
xTfPOk8m383XW1TjRhd_RKUEejGKfmHmc1V-bzddawrqx_HYdpvz-WHj_nMt_gTklLdFEQTQpk-SmF4Kcz8wmdjunpiZl87FoeKGDYOu_F2AjtggBJ-ryOxY
ins-rOsT-ndWoEEdxirRKSkWlO5__m3hvSTEwMS2g1tDXwNE0Eaut_dGTBC26-2evHlVTkNdj3m2-G3VUFUx0-Hyp0Ri-0tVvhuFSC05s6lTqF1dhUCVT07j
yLT-dQ3rxG86-rYtt_hdMpysVXhiWsQ8-rxVZw2DzTDUtnRm9Zzi-6cu7pqZ_xSVElnXFfcVV03Bz7VuqFNxhtzh-gi3_VZNgzyZzv-w0yJt-_56T_uuFyr6
N7FzlNwA_LR-iDT_UL6s-TMFH_ZWp1t-a7S0V05MNtU-NV_u1LYjtk5Z7ktZke0r_sN3Zxz-hzW5fCtoeSUVBcXFm5tUZu-3_Oi_0N_hw_4letso2uYATNNd
xVWqtFSDnDbhy1wFby7-TFcITW1lW_yUxfTI102CkCTB6SoBLeJ0Ro3rTET1YeYCveMHq0Qm2JgwyJJxCfWdH2G2BVlhtGPlFW68H2oreJo2yim8jVJh4szM
XXeY8Te0GtceF2DkV08s9LXvZQGsaWVYsVS9xDAjbBFh2CpD00DveiKd12zhi6R3SJl0G5vZfeeGgTFKNZmWZnnWvIrcEoLnoYsUCuZnG7mrmEiyAKaUupm0
2QmlWVOIGC9sAMoXngAzohETVcs-QWNYLMaUL4Dk1f3QwxUFrxxTCOJGV2W2mbmdpSIURs0iJxZSCOMcCyqYPEGrUdc0PlbDa67MulcdO2VEy_4zyaVWjUFJ
xvRN1T3uoK3Zrr1xpUVr-6r8S-UJTZxLeEf4QFxQSW5ZZxyMJsjKusgfAj9kGBHNZi-q5Ko6JzFP_9Gjb14Ni1oVQJELhJJpkIpb4HTWru-ss7xXj6HBmbAO
MKf1UVm986xowpUVQQFiljr-4M9D2cDx0RJBPqeUk4-8DjRc0gnO-Sp5U942mjxU1J1CNdGVtUSAR2yW4p5IOUTz0xjzrbfV4_DvYRZd9_FH7ZxxPwMMIxC0
tl1vZUfdSoVlfBy05b6Hrxe-dck1YCrtlgXvzm5WXYLCq-_E14lqrm2p7rcp3phSbtO1r5y08tYt_ed0--iEOlKprxAgpXUGniS__7c3eND-F6bdG3I_FmEd
wYFFGV5avcMF7oUjwqyryxU3wjC2YVleRmRs-FNy-TO7_VtxFWLj7MOzVk7Pbrs-HZTVLiUuo-SGGk8bTH09YGmMRQT_JhyBftr-2Y6pXoIbYCh5VTddztDV
UBiS0l9L4cD8uhweJmVw60BnTQ2j2n0wrgSG-If11UdAP-UtzzzhzVyifjyyeHsVfPJPbxj-wBJJJ_cALv65Lxym8SbJvxVxftj-1hv9s2f5c9n_Ql_tVKJk
vwy1pJ_i_CJR-LDurm-tDJxoav7xq-FdFpK-qbCwqi9VBY_j7n697iOrClxxeZru_fCr-uIr_JCG-RyGvxN7zj_u8epFHEoyzUpvHMDw3fTo-UdX_RjlCTNk
mcHFdVLrQNlmzR_xtqMUghX-rm-zzFatN__bTocluTQ3vtVV-legzvEYVNqvVkVyQFv6a_k3slRFRQl-FZ-qkJxSd_QVVxBE8_sfusDt_zFIAG_qfxs-klQT
LGbWd3_jzUkrvnY3bkpyu_LjtzQUfde92TmVhxkVhdpVk_gdeFpiytYzxnjlvp-73DdziNZVDztzSmJ8xa_JIBllJqsdcBFgZLyRPriNgNxkVIyHk0uut__K
zBhi_uyGuBreUVwdVZrnjry8sh0VeFaZC_-R2NV4nVpn0to9LlvCH0xXzp_Hu_HFdpvz-WS
}

sprite $osa_user_blue_tester [128x128/16z] {
xTY9VkEghy1nWpOaqkRzt_OAsJZEILmcyp7tl_LtzlKhWPsPTlblwBVVghJuNsBBS_olmtlyhz2PvT7_gyw4FUB_jmbqmplzCi9S_g2VJJ2P3nsypdhF4qpc
gUizYh15qfhA8tRzTO8-m4mUEd-CrgOEK8Fl-l__0EBHpiFQsG2JU6Uxtkl-t072vmD_CW2t0NY2tn_zpfyCm4pz0AQj3_zi_W7qzV7WvvoV_Pa7i7tiFlFF
0tIVPnn0FFnhdOzU3e3t0vXw_BdttaVnhlQZiHy3yEK-V-JJvJxXuFx_o_qW1k__P9-wtplnUNq1oWn_-FdVVUzolmzmoXDFsvyEFhxotP_t_0U1lQw_y1Fz
6E1zDDtdJHdmqpv_fJFdFF6antz_0A81tu-_B3Ck87hHEp_b-eyNq3lYhppArVvNlu3J-BZ-vVwz30RWUUk7_zsVW7Ezyx6-NUm_3e1FzUF3Vr-k7g0_WewS
wljN7xVh_RhV09z5dTVxrVxNxMOnW4UdVB_yhwlvMkljfZyFGDYtlzrkL_EUQMa3qFixe9qlzLQzg_bIIWmW0Jq_UCVlFXNL6btAM_7Kol4xhxI7BUADBvSE
4Bp6_zci53bES8maUDFYMMrTphk_Jq17crYYKghPOO0h-V0ZYPYvVm39Mi1s7E1Iljfwk5gAl1Pw75A_Wg5ltWTyLRDGL9NbETP0HUs30Kn5pGQyxRofMba7
g8B4NfCzGgd1YssD1mWVi9Zzx9UD5_Sz5-EK__6TRwlQ-6B70KQFW1a0YjdWz8FdxrltGs70Hq2rclEYTXn0Xpu2zW7EJp-sHrtzhYWS4pFJTR2UZc_0h6Ga
YW7EJp-spu1Lexubvexdd7NrrGuLR-GRGj6p0VhfEvyW_8X5rI7EZo0MPWs_ZJoyWUuBg_3x0QeNfrybPG3gVX6DSYyb2h-4BmX0PR-1WM-4n4p5x8VrCxZF
tUzXsXFJDKV9vm6sbWuEm3m1udM0izkld14XXt5CKi_dEvIM9Q55umCmHIGMPZLxkxxv-aZCyVe_vz1QNWwj4zcV7m3IEi2h7qzI5K3djQgUNO3xBEAqxuwf
bNLy0E5_cvBxB2ncBySVwmEwNynUV7xuMKXpOcOWvjptxmTmxhTA780qujbVf-_hcxxKULYI5aqlv-yDFWESD2EFusD5d_ms_Bx-EnzIXB0KDPKbG_IHxmEK
vgy3B2rfMQsnVW6aa_MLKYImQ9Fy_bjF--lm3V1VUJk0OYhFwTdwKScHjlrLI-frV_G0z0FGnmq80hGLifJ2B1hhirOpVLFmuFwIdihPHXVGC-zm0xe-Gjsl
sDTllVYOFJH8082GWH01210_z4ss0OhnwaFugdtzdZx5sUFkm-xJq3yEe6QwFG95BJzygRIkVvPahxYVeVqIKo1uxjSwVW0ZKpKhpEi1gEx-O_sYzZRDdbh9
_uojeN_eUyM4umPSult-r_N5QZax0l3iVTKBVt3-CO2xpFq6OFFLSBlz8YS80T3FVXdxY_kiPHr0pKhpkPJAs_hAV8880DiF0upzo4HulG5jzyNXFzPdFjk_
09HpttDVn_uYdeepXKNQ3MGiLRRrcVaK0T1hV60fgamKVqmPjAxh6pES-mXsxjzgtHx_-z1V5XIc8AKOPrZNPs5CYK-NP3htRwjVctyV-RaDu3vuI08aCGiZ
v9JPpXAsqzmtLNF-Dl8NGVyTaK-HeWm0CKppuHmfOgVLcvbfhEyDV5gS9bXQgTav0oBHmDVoWr_DY_N7FYzUnjLtcW1SNtqK--jY_MZeU_dXO_EP0D92nVuY
rOt__XDVbgZxZiVpHvZ_pjTIDFWu_UX3dv35VTy_FX8-n3qzy6C_7VnuzfXMFoSkMpgkx6dT-R7F0iy-eFE2w7vcBHyMkn_vyGE0Rtns7X9mhMRw0Qvrqx-x
FVPfsSiU898GhgzVxTcm-kZsTS27FXzys0w0cxzWkTMFk_NTF_TJWXOYCpMVz7x__hfzOWV-cIy7FsFtmNssU-zxqDTtXy_uyGkOulCF8DOFlzulQEZdWv-H
a376I8c_vlFn0gQKzlUF2BEFWP0oJru_kWivwxll7xy4FeRxmFDv_nU44-IKmcyyOZi1zr6c-_VLHyYhZ-4ZOVEfpEUz8hv_yrE2vaU8EP5EvRkl0gdvAQw_
y-wpJUR3Zmj8iNy6TrSUV7sUh7U_CiNZtt_o6tf2jjby7w0mGTg-_RA5p3gTZm4YHe0KzHy0vNk-Vfn02U8LM7_ydx3xQ82e5flmpeyx-tzCq4TZBC_DnyVD
nyTzG4ziXZo_ttxxxRV_0m
}

sprite $osa_user_green_business_manager [128x128/16z] {
xTddWgew50LW5PBT4dZ_jxqXXZLnm6Ek14zTVvZ-xOB2wEMz_Ck__4imivyZsxVy1FndbQ2LgQeVhc1UPM6c76RHZrMmulGObF09NfasmH3EvvFkKugxf7mW
jkHaNg6Zyvnyn0ZEuw5lAa019_92qFSB41HmBkzp7WeGmGJE77xMaOyL01xwGmLt7mMSqZuJ-3ghZm8ivPJsQzuvjob0KZ20Kzjt9USF0Bvi-Re0FdC0Ssu_
E-3t1Y220MZtxLFTFhBnCO3Uuy-1FwPW0DzzwUypmNS_zkM-WBahRzJQFnRGUVtmCG3t4tpQFV_EzmN-aehVz-KCd-5xyF3vCpuA05-tVxx_ulftcg_PsFFf
Wpucy8I7hwVwLEdWp_MDxmhj1dmExW1w5Y1yL_Rq3S_zhp_AQrxm9rt_BC5Sij7Xdx5-BA0ESEZWSVazOG72su3ltpuIoW146dYsxlwC0OWyqy4hnj_Fdp20
9RjuVVA7IsT_jXI0puBfpztz2Hju7an_wkw74F0az98FSsy_XDS5CFYK_dfGHG6yeuFFVkZUl9HN-8gqfukbgA20ZdpkMpG3l0PsrVpokQA0VZmjl5eEo3fY
U5sOxoFen-UxJz4KWu9WCZcwZ8TGG4y-nm1Xwna7hyf4c40_NWG5L5uj5rxlo-fo3bGy2b0JmHo02qlHwm8wy0eU1MYP1aQULw5Lc570GTuOF0hGl7Mnagp3
5nIWHmjO-6NwKaMNP50n_CnBuKLHW8MKuykNnw2z7Bj_HbJqXnaTz37zJGL298haCxJmy0KRwCSZohMloS_wwgC0E-PhycK_3pxJmtGwR03RP_Ir2J0Xtl17
1u3suJT6zOq1-4sMYIQUMTxYKO0r-kEmPgpZlYLLriwhj0x0No_DkMchtpu0d_viplLbBbTjuU5hM__9zxuQy-CH1_WDEXRGs3_vhz1T9dztrwE7tyHZ0Ks-
T-CQvyknV0cVmc_IuRVC_th4LsIp06th_th0LptgNvDVlxL7pZNkNv4dlhJrdts4Ti__qlycXtswOluOz9BXLextmstuNNnxmoVo20qvRYp7zT9mPlzKF__T
SiRXuJYq-_QJzs-62y1FyHM-lR5_ebJ4r_v77F-dB_2R-lzAsV-mxd_zjDrNmntO-_E_lJL_-6Z_9-nVpTflG7cx_vnxHUl-H-o_BOpsctplNB_-yHzOk--w
xbyOV8k_FV-pEzpTyTRgGmTV--txn_C_ZdZ-Ry9h_j3yBobf_fSbjrlsvGTXH0py0V_ow2-VAB-Eg8MSUMxsw_l_wlblS9xLLCYd9MHVNWHucEQSDf_yvle_
EevJ34bN2p5EmItpjnybV2NEo3lplrm6YKOeYOWj1d-pq91KBF3N1KZn4PVucqQjz1pM64Dy7U382tzx_-E2xhxFhd6QdhiJv8E-Y-gWWoy5p6_a_yt_5WJy
WouYAE14NzJjwZdQtTyy_g9pMvsb94ud-DuxH7NBGrUngIk_dR-oUwghYavJJtxh1tA-rgdUleh0FyGZ-ltw6zZLF8z4A47WTz7Xv_MFEIw8gtJX8HM02IZ3
xw33p_Zg1-Uhivw6eMwV5FvHkkw_ycrP08Dqm-ZgTpnjcYuTizs_HXD74CSKV4QiuGo_xfzYCF5KU5w-vC6RncdkxzVxznBDrFjCgXzT2fUNnArt-_DS-bzI
_354io2qLA0knpEJJ_h2prtvMJVF_wEFIm51cSXZAsA5dxloioM_Jlhqva8CPY55A9V4MTUO-FFzLC2WKmmFx_UhMaXVcvVqzZTP_ksI6EFIVmvBY5EWmKxm
tNKdomjU79QxlViDxHJD3pT_WX_iURAT4b9iIGJVhu1vUfQv2hu0laiEt4jroa_aaPz1_yj_
}
