sprite $osa_cloud [128x128/16z] {
OXYQO1ICWb4m2aR1A1W5em10ZBaeEiw2GBWgYFh-3xm79-7GfJGzz_blvkzqFaIJk5sd_fGE_I4T-Wlw7DAxZ5-l071kjK4yb-fNyRs-gPsIfVez_6Z0a-gz
1R-5bqsdBMOcQaH3F_WT_a3hZS-iWn_hm3frNCo0vyv70Jy6XpQ-HNpN0bWTtusFOkpxEpmAwE1_Etr8vouJ5zFmdey2q2Be-vupvMrOtjJaVVeHBvr83KxV
WUSzB13DDJEy21D_vri1pTvqHTPQIgdISxxW8J37c-Q2liQVslfwu9YQLf3ZXQbFOUZSBr_55u-ZglmCBvtOrFjHmHUwN-_ngchyamCyvFcgBpoJiVKQqnsk
SwlPz8S87iHVBm3TnxVdw0X59jS7-36dMQqnNofWUStkSC27TJQhVG3Dh_2d7Dd3HHvyEjNX7MRr-2wVQi264muPkAajKa1k9rw2rUEn0f_1zmgrrZgcTMur
fJS_UubMaoGDkC8J4Y6QQqa_-UpmZ3V2lNKON3LoVexdSYRgP9jYv4Zir8olnxw-hNHl1Hxw17zKmwkQhlAC-Fs_4-k9nnP-TTx7VrhncSVXIdptcLGpjGB_
-W8ihuvCVyBjkCEsx6dJrv9ePRrnrRDDOG5okgc5CmxHUYmgqJgzOOvhlZa71YwJ8IAngQjEwug7mNVhsGFmB_0THmtzSeylMQQkNMNPrgRMIYEnuXRGSJyF
8bTuANREej7kCt6uv2cyyQE-M_KidbZj3NJ5TwUyMbJLCkaz1aET_6jMkvHnnGU-744xbOZENSqutB9gADwihPO2_frL6DerwRKLaE6dhgPDOi-f-Pkgon4A
Q_7McbYj9I9s3iluxNRpExYTiixAdZ-DRQrFhU2R1GKiLOeNFoNkR3Fo2ylx3XZtraw6zrR3mtKU8Z9-mVGpF8JfrnUiuBFXdpPWxJbL1qhnfAllhJstUdn_
rW3SKEqgSzzLQmciT6KbJySjiFMGJxURQscMsLbUjpey-FA4Ns_bAXCfU_UxlPTRtSKrlzogPOBl8btCIAqU3_bn5-ElHtpTKxPoERvFyACrukKU3_v8-FLM
po_p4xmCjHRUkh1AT-EJBmcVRiNcb6Io2llloce3ZzVQPyRl25NtuynpkAsa8_1pgyD3K_bs3WdF7pg-_JnphMdM_WfUJFCyCGKyRe2ZTqypvxQMQoi7l2Xc
HFvQMFz2sBKk4tAPyx0sy1zPASEF3Nh8drMFKjNpVIgVLxg3cbhBfPLFl9l-UGvCVcF1qO4W7tjUzF-id5jZ0MED-0e2ljdlMyoT89ThmxaM0GyhUwVnOm70
JpGXyhlX7StbkZzboyQtIokvFM2pjqtmuEYHy25yYAF7IzRuozJmDq6OlcPQQ8kP-5YdRvrAhVSLn8T0u3Vb4xH38H-g8jRLD-iJlhF42aRWrrjnUF2TBBJ3
6Wx9tckZ-49q2n1U_JOF5nhKlHNP54pr7CHjaF5nd3D_33r-s97DTxc9jMO5n0s8-HTu8IQAaIhbrvBplJTi0rT0t7yQwkN2lDXRWJT-CAS5H3wL4larYjPY
M0qFhpUNSb702Fp-WEy28Os5rUF13rvNGSwt0aOfDPb-SQfrhWahyBatBq1a1lvgrbNVKIHw3QmLGnaU2WMS3LY1ZmOWClBXAggsreJrsbiI_dnm_9Y4L6J6
I0kLjM0D_EYjgh00OVfeGDKlj7HAlW5L_qkKrvhpRVf90M4b4Uaokvw_IlKAtemF_6F-cXGYeVyY1tvfzmhcVFy17xHKWrjBOY5x2AzfrkZEuFpqDy3rMm8-
wXVnVrZ1l_RWG000081XqFsf3x9g9G000007
}

sprite $osa_database [128x128/16z] {
xTD9kkCW303Xx9gP-z-sCrS6U9WOMHlLFjyloUGqoB8iox8iox8izvKAsav1_awH9a7x7ydCq387hHjXIgP5LvYXQTLR-0LVzne5S1hpwt7ldQEbkXlZzxOD
CALliOa9XlnAd9XWB-ycSMA0lY-04_vF_8GzDG2-14uX-BzzWQjZN-lw2LzWyMVN0yI67_25SFpGy3t-qgiJ7y0FxY-m-F3-sUFBuBo_tFAZEoTmzMy_DFqC
8B4ul4jjtulYy2wt_IHmTO9F7JydKJp2T_oS1lOEF0OFt_Dpai7HBtpNlnIMNHqStQSyy7FoyFiNl-ITGn_ubwAZlNZmh1CXcZv5xsZU1dSKKXxwb89xRVgv
iJVuZCyHQ1EFpEyu_2QV4XSahW5v2TUH3-0pFl4LDuUTCatxb1XYajxlK-9TTRfyaeYyrgTqBbxYhvPIWjtXosU--UQJ-UQRN-kXVgqV_E5-VTCL_0glurTu
3VyIlBvVZ-OlQViLlnODl-BNO_bll-ZuL8xaYPHuKkAfAF4agfSwhYZfL0xKJ_8Je8zzAj8ulkm81Rt1upShHSA6nryw0_R0Pu1rKo2F-KjrgdAke-9Ey0nm
KEYan9CMJqewQUcafPEQJcewQU6aXvCUJdesQT3VgSX40gv2bcLPrdy
}

sprite $osa_site_head_office [128x128/16z] {
x9RHTgiW44N30CoW_l_tNgfpOhfg6LAkQhiyJ_jjgnfs7jNTktVlthrxzsBJTlIJCqT_sU_9dD_Ltx2Tdxzd7Jt91T01xpznAcCMpo02CPtXvtFzk7y-olyn
oTcpaj1AVVwOwflzEUUXhFX11EhqnnZgc_t5f7uGyGBTVdBrXGlue-Xy0X63EltUMF4JUTqsxUqFndgVFx4kFCbxKDYpVpZUqyUOKr2I677GnEFzVBGVhXHa
oq_6klsYnsiAe1YVHCuRw_VhePf2LeeHzAd_JqekWERdtx2AlvZK3ueHrDJ_uAs53h_TV--i-OgVH1SzA8Gd6VVVwxUErx3sNxxlVx1MyVlAr9_BQlqFZh0j
mltlrb__45uc3iGhFVRtumXb1vALuD-Z__r-gkvJ_zqcBSz_qHShpx2IvU_l_-ndaPo7Olr2vlDddVzf_uiVduFR8FYD_XdztTcVJlOpyu_xxny9ELp9iIx2
N--__Bp_mPWt_4R_2RVqNVy3rLSStVtbP_-uZ43T_Jk__twZ__7I_HUXbLpdz-T3RRDVrluh4KkXw_IVBzJ_k__fj_UVw7Vr_-w_B4iF1ZdG6_q7nVYabkyl
-Fh8x7_M_Yd5E1FwdtJEVw7Oqd_gxI-Z_w0_sVyKGF78_hjp-n_UwRzizB_Z_-V4_xd__4t_Gvwsz9CSrFymJDE6VkIc_kTbuXE86DJebn4NW4r5dvlyhjf_
zzf_Nlkl17yUY_2pViYslxt_BABLPyclfFuy5ENhiy-vmT_VV_ZBy0wWFzIl5m1_FiEVfqdrmn8uCVtlzPyt-fzU_FFF44z_QFFtzvzcFzu0dhwMpjXB_-DA
R_P_zUVPFy8_ZkCmrfQq_wpzLo9GO_zM_pZXxUC2R7z__rV_C9M1xQNk_iEFpNwiqJzlk_zTVdkpNmJz1n5eVx_Tt_Vzmqb-V7zZkz_kVxiV1z0qlULt7dyZ
AIpxrvvz93SK0a4OTWxT0zp_j0vKByQ1OIXJLlnNsdtDKvRyhQGFkDSVGzfFlVxE_LS0_WqWxQV-_twQXezq_Evpf__CQVBPVGtOvZ-jyHgmqqUSvnS60CZv
6Lsy6s2Ou6cV51844-y6CEP9PlpxZ4_nFZCYvldwcEYLPEo3FtLT0eH-li273lyp6ovOzV5He8jVk0PORl7ighN1Wd_Gcp9Ds9bmQny5jYgQi1alhQa0LrKJ
zkCgqFq48_4NkjjMc_A93olM8x1CWsOw-2Zvawf6a0HIC2cwjadoCoEAAVRmBVPC5T7Jd9_TKMnGu0R-0RlwDpS7vcyEotzqI5qTKbU7idq7nTNXQDy1QTy1
t55hw0dr3W
}

sprite $osa_site_factory [128x128/16z] {
xPZfOhGg342j2261gU__jXSJcSyHCZgzHU_2-TFb64_KhZFyC-XqEXrY6XiTyfCn3aanLZ7Q39YwKNOT2CqqMMk9TcOcNpDXcSac56U3rS2PF08WJIODE0UR
smQ4BXbJ6b8DabUC1halOyQKdvO1vxr7GZ5sB0nLZFMGJ10pbORUvyTbLxvV3i3PzCRJh1h9Vsfqw4jsdMJ4ydtpz6gcPDYBmPh1REp6s6nK_9Z3orl90wI9
EPjfRmX6pfScW56C1e4ix0mFE1a030CvDc1t1XJ3crd5g22OpS9k0H98GpWqfZ3a32Svlp4ugE2uBEpCUYgG2KzFCvN6ZzQz67WrTcUGz3vD4q_8mf11OWDr
O-p7HeDmj3mX2p-XnKpWfhgndneLGcicjrjOBePKasVSUQD22R-FWASZ0-TDxkli5mPF3SpxFjJFvNO6WshoZ2lCF1om3Zp7i97H0O1Xy1ag30YdZIlDCVI7
7vYWczDzPBZIp1ptaKWp3Vgzt_kzt_kzt_kt_luBr8JJVRgzZqtuj_Hxl_TxdtwNVztrUmPNF2nupBp8V6mLBtpQzm9i-xbHI4QJCkW_x0FmomVFSxe4y4b_
AC_sOmpSzwzd0Vv8J-WIigHmflxiyocsznG99I7IFwLyj9MmaUoG-p4UrrES-qY9FsUXXFIF9TObKKmSra_sFvU4c3TGwqpbwn-ya3-ISwFWpqb2r3V8zTpF
SyetF2nivDQ28WanRr391x7IRmBXIl5r62MVQVNp7pSBHENUDx_-yXdmnL_RvrkWvA_fomBIhnxecVKj7k3T0lZye_T47sDSyrGzS6ISbRS7VHYPTMWwrQSO
rxklzBz-qlywtUSdm7V_Xkjdk1_kwuV8Jxz-eFcyRzQ-FTcdcC0tVME0-yQSw1iZVMFEzl5jFy5zVdlKDmmF_L9_MllcJD__U_jqNvzYhFxukQZFFu1YlAvF
nUsl_VWdEGxS0e1Zy02_HSadghy0YiCQihjyxeTQF_moPJzmNrtWahooG0EqVBa0qxJDUVqFuFPG2gh_0BGdIBxyj_yIA6Z_00QwfXxVlFJGlfxpbz-3VEqw
yymRt5AVLzey1ex7EQ6tCmzPuRVZZpcZnpFViaABkB2hQol44EZlfBaTl-SAUdxx99X0z76QECqNhi7zGxxp4Y4GdGg7dFwU3oZw-XAFk18OsX6OkFAGz35g
Nz_Z4LNqhjw_aTuVXflpmxtvnBrrvjuwSsSxSsSySsLQvzAqpkLTdQRHw-bqEftENm
}

sprite $osa_site_neighbourhood [128x128/16z] {
xPZfVleu34LZPx4bNVxp_cyxM0W7N8icXLypIywdxkT24rqvmx-BavEJavEJavEJavCJ0CVg6JXIJtHS041oFYu0mFdgPpuc041P_SS4079IlmOGN7vPBpcb
LFH7100u5JAHr03uHJrL_G41WAnw8fOvpiA_6m2IbiNqKunnqW2_TXk0bqBHynZZBmUuWEvw8RM764Ts0doys82i-amaIUs569q07oys9DEpp5LV0f0u0JvR
RBBCyqq_1hCRoGB89_nUiK7zHLJTbSK6mVl-2wGMcxJN_fo8c4876mIGZ_HgxiqKi5xuANIPD03m_d1LVoS0MA-yu32M088tzMsnuIaRozHOer4-1B_d5yZB
OWCaNqL3vIhDoHZ2a270XtgrErLnISK_pZV68SIq5DGVaeqjuBrUPLcyiQx-EUTKc4BZhyCJFz6lnJPxlQB-CAlT_BVVogiV80P-qgjNQg-slUBxRtUh-k_Z
OtU0ovTU3V6nLohK-ZChvgzh-RwL40-zcjNUzeeY8kgV77z6NSlt1QZ5Hh8y5Lkg0PYK_C8V2SZAteqCjTZAd-pr2alV7vRxnrS_IzRBOVTE2Yis6RrUOJZ-
Xrb4TNpit4SWY_Mgrok-ln9v7H_O5-0YUkNHYrvXuQ9drp_Amrg-SoU55FqI729h0FNJF0p3kDoOXihCQKdhMZu-1F0YDCMs36wn1M4IzHDJxi4wFefUU6o6
L-4xFq3JyDHijTXoAJOHaC4TGFN-pT6W6a1g0jSkbAVXgTY25Olw4ucw1TG3sVIyZeyOizG0N1o-dOae5-TanJOt_aoACFS2IAhwIVNjy18XBu7Px_vqe-nO
zs9R_U1CdG2SLK-sblU65uWqGKSlH8xVYitynNnRoxdnIvwzjVn-7zuaqWQ0wXr_vaBrizXW_n90qZnhSRcpWuNl0T1xxwj_TFqYQx606__YZuze0KXX0Crx
Nnc3wmzPs8hbVZqzW6J5zM9ueOO5-lhS-fVxnqCOGLOilG3e5DVZXioYFzC60EY9rh_-YKcowRbusm0CaJmq5ruoOXWckK8LmFJysbzPrbhbt0qWbChmZCOG
XYNPy1YlVflT1WDVttrYrv-hNcYCo_gyYLRK7t8XfHHQ_pC2V7ttcPVGAxR8MVzGVUGnTmEeFochFztyCpMeNsZ5BpORxSaUUJJFcrxvxHZPymkQ_xvRRD8U
2a9uwdPs_VOJNJzhtsv0lXmA2e_TpgwVVJzjzLUzKBKt3xms-9UV-fcMULPzQhRoUZ2HlZ_CsOZl-4knEOyyhDk5-_uX68Fdvot--yEs3jRjqlUlTFoCMhml
aQnBHGnTPbcBXL_wkJE0W2r-zr1GkxtwhrJ_y4HYximVyFT-8Q6XiKv6-H3CvgVaGsPg2u2-HK2vsShdd9HSQfdgg-1NTCPlKq0-wb-CUFLRiQW_4zDkf1Qm
RFKduza_NFsxyHSWtnyU_La_okP_Gwy1zljj2wIV-SLPWBVxYGlgdsWd3C0v0BpqBv_nIwlN1CBx_CPkFujt01JUxW-p4RJOTzdX7xzvitym7Bzhz_H_NUaa
yFmLn-_Q7RVY9-2NVkQjTfLuSWNT29pBsZalDyRuH6RU9CTgSUpAdru4fkn1p5labsUBg_SZzA4jyZyTIVNx4I32z6DO19vSCR_B1OemxrQpGBcy57JyRWWH
varYkQkTr-twVVvSBZ14uGPHO5nC_ORVpN61W-jzt-_dsU5phhy36Oxr3uLZxSgnTkL0T-LGkN6CkkKWTSi1NeyFIe_dvEJavEJaRm
}


sprite $osa_site_branch [128x128/16z] {
xTVPcgCW48PXMuM2WYJtVxT3MzRV2wI96Gopy9rHZycBMNNwVnkDHgFHQ3GQZKPyThtzKFFzgJ7_uVx9FUHxTqfU-Kh6h6ydj1WpFTBmXp_yUMdRORznH_qK
1jigMnyxuBXla3pVZFMy3QOLWvt3UfK35Wpcu_xYI79ktfwDC23P4DPEFFCnaBFNDJax7VV9RX7HxfEkrTS3n9yC1l1r_Oplm1tpAGsc5Zxj6lnzuDGdvTJN
HtpnwMd_FUUzKry7wiiw3TJN0zJ70K_vxm_abFfw2Q4-3b0V0_NnYATybk1xbk2p15yFWA_he_xmKqwZJPjM38puXC4iFx1Oa_WMW-MuFtqat9TrDgWzug0_
hd_MjlqrvpzyszEFCN8_FwQ2EyjtiQwpztIMxsECLNttPzEsTvyufYhwYUTFtj_R0VGV_0bbwze0lkoWm0UnuPFxoCh-ILla-OskhMYprO7PRr18coVrKm4R
W0uUlhEhPWdNdyNx3rp_VWocxFv3V6mWvg-z1D_CcgK6zn_mi_S09v_vRs_mczn_mCTx0Bvo_lVlF-Yd-myy0dw-WHZzmtxAPVSVtdluSW2hZmDot-y-tlkw
xrESWh-lMNqz0BuEIZx7Y5U_vZUw_eQFTo3vlfVlDp_K_6M1hwclQ_YQ-XWK_H3nxXTzqU6lfAtYMmpcRJrZRSKt62mbdsFAt_EjuF0hzn_r0-2Zd_qamszG
qHy-vxvxaSyn5Rhu-06AyOM-otz_yZU0MNoo6ftYum_WEy_UfCXzHAPDZh-UVkdldrFmsaRC-GL0lW4fD8sbZ2zkuAHoFji0Eii6dry0lp1EO7u3yBB25nxl
0Rz6vt3l1Z3mItJXio9sSB8EllmQT3XtxNQJ7VJGRtju6zhZyPQwQwCBjj0Klm2uYwChjj0MHvbUta8CWN-7tknulHMgy7WdKe7vCCr2uyGBYL_hgfi8s4O5
3afVRvNWrpTnYNjXYoKaqxXt0Lqfy-lxkCIyYblnUpNyQUhCJttvL3yTzTDHHnjrn54FEgyBdTV5BTSKxTzeD1gDVW4
}

sprite $osa_home [128x128/16z] {
xTU9akCe381Xm3Q8euVtVzk5LYSYmQ9nJCZkZlywzkZZKmMDgaRyPxkwkheAuRDyxeCyza4T-nnlhQS1flFUMXfWFky0Q839ElBp1o3U0lef5rApdnxGdpu0
yl0JycxY0FZqjv2d0QOzFVaE2xafF1GXJmFCUtgCU1fWojEJJxtv4D3Jb_wi0N3pZAdyAGCW3oRrmDj90-3ccUzAlXg03i5etfbRn4yQ09_-7l4J1g2dfuYV
C00zFKKwEq0O__GKt5nF4umUW7ZByY6yTG3aWUDzo5di7OSW_COxoAypVW3YlM7u_15R9Ste0VZDmopnHaafzVW1YBSjNakbqWGR3Z3u4E3JQwtPpLipdmTO
1mz0Jwzp-xnVf4HUoiKt_no--lJw9sRp90sWXXu2vAs-Lpyz5Fpu0V3fY-hDGrNc0J2RHnuoGCWP_H3oj7aOyjYWGu2yrqyzRLxTYKF0Rnvru_CNrIChXFnf
Epy0FNrPkVZmh0iQO3qz03rzKRrv9KyJC8UWTm3KFSFJvjKw3Q1E3C0ylM4tJvJ9haFGSNIwDqyyrNK8-ZSFOpTFr4aCygZ71w3DAs8tJ-o6NzBy06s_jVYh
489qBlmYUmZyx_wMsjiyaIAUx_kBrI4WFxJzBOS30F5EbPzlHzmXQFe-yzZZvjcRYNnFp27ezotnflnqUvExXy2tV4T-oM_YfUf3W7xeyAlDUwczGz3ohTOL
xwHuFLCCqEVd0HusJvofFWIyJyU_uCqfdGu1rbo0-_K_ltbbIpb0XryyVLXEkEmbQlZcWVVgXCfTehPVtRmJSPV8D_o21p4mLrwY40BZ5z-XnT0iRM733_VD
is9mxZv0Q2n0GDvREBRY1dOpjC600n3F3E32Dt_C1ovJV0iEu97d1i0Hu9WlirG7gNB4aFAXwMFY1Ly_X0Cy-I9WWW-__Eoh_GxxWdX-057v2lPR3lk2UBPE
tnXpn9VqxwTyGqtqoUtpJUMh4xuaalTDnK_sZI6-zfS9FbRezht-Mlj4kzHdVBIV_7ME3nRnkRu2i0HFyxV2Hvttj-7-vUl_bYy-wUiJlZ1C_oP_hrc-0APP
_iRnwsbVfZW_ObesKZ56BuGvwgEiKil2y11_0iMs_abV3r8cFtRYCKQRV9dbPLstJRTypCDk3h_wfLJsO-pYqPToINIsmJA-ZPrzBKlsSnqy-agjsGRhV3Zj
hojaFzV1ex_eRFlm5UDfVqk-ZLW7d_rb1Hyo7bdVzViR-R79OmvWNTrNtjqXlYxzsELlMuXncAyF-rfRVulnhU_C7lLzybDcK3hxxe3_XN-XCwCcW9Jlyp4B
07PSW1y_-Hq3ZCt-8Rx7ZzxPWVb8VBFuziGlVL37FibZ7zMngJRV77b-LrTNL_y
}