sprite $osa_server_application [128x128/16z] {
xTXNOgCm483X6KrHm-7-jrraLeaDDaOWq1R-1pfyanuR_jQkhiBwclAffdpg2DuRN9Dn1moGU8HreQy-G1WYW1O3P5vWVIOFK8zNW1O3PDu2j1WWymwXCAer
GCZV-eq6IBm1Q3D0_idR5AS1pll9cyTXQBUli3cfuSFsJ6CVA_cugNg-sTA_vNDPLDkNmX2R-bpVPrfTJV_oB__oBx-aVz2dmchxvZ___uSAg-oJ5DROPyJQ
FjFgBl_oJKN_yY-_f7_FDqnbrVOD5jR-_O_BD_-gpnyxrfUFDVOPiRhFeiBPvu-__olxfFU46ldwEsdZYweDCLXLRk8Fl7En2whImYTLvttiEgkwt-zM5sDa
77qR1pxgQj-yyxlIFDs__KBQL9NTlaV0CO2yNWY36iEgwhnLLHhzfHRzhYDW6IEGUmnBSKYaZl6Att-B_gtZRzz0dcCfYSdapE_slL194gAvHqncZAQPQOj-
x4eAoNyVlcp9TpwMv7qqvItvpfTa3_73YqxqGumJF1qvpuyAipIUuzlaCuL9oAVw72UPStrZ9-6vFimwrPUvBwjzeiaoRvxWZnnzotbPuDljFb4DtxbFllj9
p_D_2eVxE4i2v4pqxtrCIyJ48KuExF9Z9WN2Mpz1pECo-SCo7o2YVNxE5VfOoVU_qsKVd_s70xM-_bjzEi9tQtm-r-ViymU_x-lwTquaSIB95ya7aeyuy_jN
Vd0qoxbZ_7xYw-3xE2_GGNu_yTLQwxxx_lR6XuAtkPaFYGD8Fa3oyu6tVZ_p7_8XetjzaPaV-x5QFZF3oRvyzk5aNpLngibN7NpL9JzLwCSb7vxz-m7PxiUs
ldlfksLViYyLV9hnzEpZT_Vd0j6mH28S3AB70m-zzFl-Q-hR4ES5--Z3bcP-qcT-oispH_ZZLgTb3RviorRokx2nDxwSvtUPt-NVjfQy2dw_DtZqBKj97Ehw
jsYBVDVTgl1vWAzRLrGLVZ91GLzzHJxLdnlihAMUgs2tx-eN
}

sprite $osa_server_media [128x128/16z] {
xDS7WWCX28LX430ZU__pffDUn6LYYly5lcVA5FZKHYEjhnjlTUEjEVYIiAOqpJ1WmoFKXILyWAuZW1u3Z1UeBzc0E3u3z1XW_0AWnm3Z9mHd53L0xQVVQS26
Jm1z1jW_hodU38Zxv_bZNVTlFqDp4k53UwcpZq4-DXNdfvQ-osTV5EsBCyIkFiVxJDLziZ_yuG__Jm_HAtqzgKoBB5muulhdT-sui_idyDgLlSii8ZcB-UIi
sb-pkmFJ4SxMqK_eo-6pkGQRBSnilhzgdzZS8xpVHDJw-RlyItcpQ34LLJQVn9dBtyCc5xKsFhNuZEZmJPuECcmwz-ElF-OJNShmOlz2xk23zIr--Wf_-DhR
J_xht_VvYSbNj9_GLxJlR_YGljNdfythozFYV6pn6R7PL-l2Pyd2vlFJwx_3PzKBl9HouPEz4CtbcpxbuwiO7VsyJu9yFKIhTkj5krKUXm8m86blsP3o_cyx
o5fuaJIqoP2P_xhFZRYNJv9zd6x-l4PgBOZ-DjaiZTqtW7Mk1FIwt_7kBy7FrMN3KqUBQ4qVeFkyLC0k-pdb_1Pg5lvjNOjN3ptzVRTPX_05y5BcPI5mqG_S
iiyMQVqNTw-QIxrz4wrE7PlFUUDdlEnFp_rQYmNUa4meJaCHYtHTnQgBWf09G5sMfG1soQ-LCecsvliceq9LKJSGUq9WvJIDanXD4Jj009B-JpdtQ_MWZvji
8eLjvgNaUcwACYOL6KS1WOo-TF-T-ogcBPtNKYp2KYijQuiN1I9JPfoKdR_cYy8oo25RAMWfTLrgJ_6snLEl053TNyfZfiUS-X0D6L6aX5uzUPRRkgxB77R4
xUuRHm4FJ6PydlFp5sp6M2ltu-wbs-dZw4S1HfbUpec_1k44lSHJ7hnz-rFt29dzgu5jdw9HuB8_n2sVcMUdTDwmsyapzbyH3oH8asq2jCl-iFOuymwq3FsW
CyRVTASNDoEt0eHosUy5n0dNOzZrv8s0WKv41OW235VzoDv-VmymqmXstsaYIbY43eCN4h43SjtF2Wert-t0PA4Y1f28fsaoclK2ZANj0Eowdo77y8rRicdY
xZh1xfl74voQ9-13lhNtLHAWCmEPCdT-3i0G_lGvNpVVsXv7-uZmUBoKTZy0nXr0RVVlTFTtVtpT9sMSXCZ98XCjzWXf4LKD7uojpmCW7UsFyhRVRbHxy6tg
oUeqGXfoDeFXWpuUVN0wHCciW6Jmd_G7ol2a_rH4pLGaAhW_cUD0am_vEanvnN3tSuy57TKeHREKzCVcgyWu1ZUE8STZBBpdsp1EZ09OlEbcf8YrDLCpGrIG
UV0rEDNmu-zSY2fUzvtn5O6XUYFRyKVg6OkLOmOXHBxvut_X5-gGmqRD0R3ngU-vBs0SwD_ziVcvyB9V2ZcCSSZ1J4ZAq8y1ZzzoedFpxSoNjto90lA8MNwf
qVG-HZcq3tYyDjD7Nz_qrq9m7ARx48-yqpe_A54UVFt5NzSptuqOXXzzewU_JnyewBvP-6QRdmkv2u_-Ukg3-b20yN3suUwbKFRkHyBUzxSyzmk-5w3SVmAA
b5Ahi_EWcRkzwKUU-NDnCz26E8GzO2cbqQL6dBhpREtJfl2ZRhFD27yOS-7KNv_uRG06OXo6-m9gJs7oyIbvLHU4Z-U-sJT_NayBg3400od74GZ8xBqucVom
0Or7uSVy601j2uXfE9GWnZsQlG_2vDs1s7JWtX_UzliEv0WiAkXVAw9cgfBuc3h8KkDiRElf0-4ZDX0uzyy7i1I7HH2zXhLfMwBhBKDaCf9UvcLPvdckM-Rj
gU3W3-7RktuKK6CBMbX8cgIvfnq6h_CSVPF45cjNGvbdnrK_9j0ByALw60n1r02snkCWHjDxeXYQJCAb-NR9Nx_AlWTbQMrkQN1UFwNKp7n8RMDZbHZN9187
L3Pkt1OE-TsF0jQoL-3pKajBipFrn7UlFloIN_siuBOnZ0fGusJrdFl1SyO5VxtB4Zr72OmAvlgpNzDVQB-5p_prMRx2T2VWDV-hdITzN-ehUVJNqzooRTzI
ik7bMmv-USrVNkGpN_5D--3dMopjkTsMbkxVNiZwsFx5VDrQ1SKPdRsUuKD-f9LGvZ_CZstQSdkB_sm1COIlj_ZFL_0c_uVLC5pC7wjdFc3_yVat_m4
}

sprite $osa_server_proxy [128x128/16z] {
xDQ70OCm44DHNQ7klsyIDh0SqUyly4G7TwsgrlPEvRTEvRVsu1UtbdpUOS366zgoHJvW_HK0DK3C3sZF6mQG_0ZG0uJy1EW6yFni80lLW9MuzVSOiF4EY0Vm
JnvVRWDqJnvVhh_-zaTqDoXyzESd-oRohIkTxpqzoq-kKFi3cTcfVkhzZEQKVldbbry-qmFz85Fx_lB_do0J-p6GdUodcThFQAxyyjrGVldBD7tRhGyT1tKb
0CDu-WpPvVtVzjeUmeKqKiZfloH7QuW_8tbH_fptt-oRhZOGuwiTukkyLbljJHy8N-li2rNVSwLGLNijV_ltn-npGLt26lIMktQQ_JTQ_C8LxX3-EJwgSlf4
s8Dpk8fkzPaFYv-KlrmSu9EgUIzQxvt_RRJR_trGrHWZEyZdtHO___-I7bxkNPzAIT-qTiplVs9XElkq__vV_E487wN7-Ag_p_z6p-sHBtFycXzxU6JkCNVB
Hs2HTefLX8xqcwppOaGiwb6xz4b1HCRJwHGYV9mV4SQuZSIZjlR13KNir5AHm_ogtro6DI9yyOj7yxNneppjmvuV8NWlyOX8lxYfGNMZ-Yx21_aHZBUZDcX4
TD-CL854n5phYEa_QjTF7kxmBKIoQaU4K_E19IDe_axxleV0FJz35Ezy-a0pVumVZe1t_GpPmvca-IqaX0mlWyjs_0ZELKZCtCsKQSip2nDfvTE_MxdPZf-F
J-fnpYDCqf_v6X59-c-K_eF7rwhM6iqL5lTy7H7NfDS_yGi-0bhLpTpP1CWKeJeMBfJ-t7TyH_ImLh0I4W4B41E2k0lHjtq3Qxogcm12ZKe1wkU6tPY-wxjG
cBP2seq34PPQNWKB9U8l-Y7cJHSDR7pfjyy1aRWpyHTzYywBEVI7Be3jCol07l9LFxpop6BIVK0eK6Qz099hyj_pHOHOHQdHM8Toze4i-Vi-ucRSJZpXUvY8
00MhCAqFN_raTIEIUtvokCZB-88VtI_YOYhCa7pf0IT_sqSynbTc7bZDsmOwNp80SqBYSqJq1T-75egxcqBogOE6C6spe_tiHEH2oEtUr6iIDzhwfOrbFhMh
YLUUlnO-buRd4URLb4LDVBrkGaGvDh-DET4kFkaRhe8Q1-Vokl8zOXpDG6Z7Bw_wEfHr0xZaukd7dCSOvXIozSlMNq-yvnTNpCZMZ-zryE3GPtryppURTI9P
-33lO_LjtwVt_K5S22dZLDFt2DUHmwzyElkquq_JdZ-mCukaNZCLzUwRkQkDilOxnzmuvkOpvyHoB2_zwR4_O11MKJYJcfhNLCr4FTm-ywV7FfZdiPVaMser
gR5MdJxqfxj-nc6W4Q5fTxR6JAJgZXV-qBXXg7urcZzFtFUdn_u0vioUljQHMLYK45d4fR0-vpDV-UEKFVJR0k5ChBtA4v4gLetTe9Z0EI8Q3lTp1-vAecRf
gnCWIkDBy8u_VEZd3iZ3j2R2ObPvSPUwE3fU-2AD4sc-j5j4TlnfwqlpwqARsf8UuJqrzz3-grWLjlwmzVi4l-u3NUzWACZcFS4sqLQXO_rfIjz3ozKvoDP_
c29U-Nps-ML_cdsBKpXU-8ccdB43bAM-xe1Onu9Oge6udbXrnv_I7oH-fcaCkVAtON3ElT4jVvfzZjDKEuLJ6Hxnqfx-C7-QVLokZE5OXfjy6VZyKkPtqhk-
zmlPxnZEqBYLdtzQn1WVTDUFcDQT8enA9nTy08auVSZ7QU6t_dJHRzi24qB9KBn_-VVdewQRnt-At-cwd_bPtJnguyzqLDktp-D-VaxZwPJsL_nX-kCRDlsP
VFPdyjcVeB-tXU5B-jnpNpxMtj_6y8t-wty
}

sprite $osa_server_directory [128x128/16z] {
xTZdOgiW5C1npeG3jhx_sru87PhM28PUx_3_8Jl-tClzhLrTnVPEvKkdygMVu0sX9GmnDzutS6s1nTneFf9pvun0vSMrXnPpGtbrxfmHgBntxfmHg7m0rnbP
p0tYhV0dZK3XqRcpHY3co1sAhVZ3jxpsEEQUzjKTJaRuxdXuiW-3V3ZKE1-Fz6_vt1UDzgKpW5Dz7kypDNVvbt_vbt_M_kyVzAcpqJx-v-S_rDbWdwIpatq6
6EqpDNVvbu-NV_adxV_-FH-P-Xhj8_JLur_tN-OvnfZIbEvwqiSjFxKstg-y4YBbk4HVmrkwvVDkZ_oKfEX8_3YYP6RV-RBROn-ppvW9UHHZzAfmn6U01tw4
xDEkBsY2pEy-Ymg_-zom_z_qBVlSv7iagJxfBQ41VcZrGq3KwkjRyXjzKYDKABwe-fYYL-NdVT_iHuBgPpw4D4LL-Os-P5ym-wGQpD8qUTNdVMtrEH4mLT-d
p2Tjzd7RbqQVAJ4or_clSPecKvL1FZRvNjHZZbKrcC-FLFr7jVcqxsCAtdkJGcgD6_T_stvCtEn79I89nUGt_ca_DVk25ZB9HbWY9gpHVNZVGv-QVM-gGiQu
7NpR85zlVc3ixf6FhJv9L5NoyWC-jFkgP_cSRhuVwqEhprHybZ3KZps-ppxRMJwc6etqhSEFvdFHHllKv0k6eAgY4mtqGuVlevbvcHYN4QqUrn_i-hx3r-87
IOhlLOu-vSLZguz8rEPBghv_r-bvNsy-jlZ4nJU9uLpVRA0l7JvLFyI53-KHoYC2h3uOxZEcc7tr2MiLOgwFnI-Fo5nzQl7vW3_H8nz-pe_5zphnmeUrl_nW
tv_x_73pPP8cd_RzAL6xNyy0LVPzxlEvrTVeSpRHskTtdtVyULxpyvImnvSqvJxtVpTEf70YnHUf7rGVu8i_V-SJ8X7nVNGVSiGwNSVzUSbd7su_ujNayrQI
0Af-t9-_-EGj-8Q2MS9xtnNEkU8xL_ot3xRzUUb70B6Wj9yKFb6pB_B5JtDjvPCPDSHc5fFYqcTczwHleAROaB_vrE2xFZyOjrnCXarVjN2gnLVDlkgEFt_u
AK8mWORybk_M_kq3QVMdXC42kFt8SZ_WYvfvTFlnjY_lllJwSpAod9VlubNYBJ4iGomZJfGVWGYoGRJyOD6M_vA2MdD9m1tigp_VcfA53XzXb3-_zPew2bvL
ZkKt_DpBVg-vAUNYuJRyzbwU7O5flVZxUosz76sUL_vfkV_RTs-TovTEvakdwlsTgzS6sETtzGi
}

sprite $osa_server_database [128x128/16z] {
xTVfOfim3C1n-P8FOBp_smuHfLu32rPGvhNb_o5tyfET6xvgLrUblQuyrPMdti5dQrgowGq346-WBPFL1oXB3g3B0Cm7QC_o08ey0dGPWFa8q6K0vfC1OKvh
WC8l_Lu346y1EWrGttdoF0sWzywJvylIQH_XvOA63wzdE_j6oJSlfUVRL_fUlfVbjFqWp9YkljVtlMjEqx_yox_yovVq3NqdJDktF_ptZnEcxBiWhBFlZT7s
lMlkyY_VAlgNV_cIlfzllPEbxLiZIzkNT_bWlwll3tkl7mxhx7jZr7qVCFYxxni-_rLzXsl1TVAH2ttyW1ZBK2AYx-8ZuZ2EOq4CFNo7c4Og8dRo8_43Dlls
1Jznk_jV5ZyZ1dK_fh_suNj4J3aYehlvpzhuShhc35WYyPPl-lohVfiTDwLQN3zrFFDA_fRUzpc2dNVsbdlCFdRWL_eOvsAmkvdTdlevKGARx-2jeEhlyiru
vkYqr_0zwIAyJk0L_5q-7U4yWDFmfGldIaufdFOB-rASIYcwitucNxBhP7Cv9N_M7yYNuXoz0CxwKqf9ikkV_NBUB-A5LpuDg-yU3kl91d_AKhpoPMBELPaF
s_qfItQT6_BAJrx1dueC7uP2El4AFZNo5XpRXD_qF4vAFaNxkVOSBvblLnQTVKESCSGPGp9V8F2fiUJ4xVf4StcOxdc2F1-IJuTyWNDEu5FZGCQpSXbevSzz
8_4tyIPlwSpqesy--tzU8FThzFzYRHohA_FT2N-JoFV_rlTttn_uywpi4nS2SI6G7m9Vm2_BZJ_tzcTDFqXzIjS7uW381o2VBzZtr_wD7yB67-Q70URJFfpn
vxVuqEhFf_r8oqKa3f5ynCL7FF1dva_xkFM1_D3Wpskd-67nJKS_8wv-kFj1xFywmG_XzgNZBC1oQ1R3EG3ukE2FTlop0mpUsOKtqDJMFpS0yGe-zH9VKbp2
fT1MtFglRy7znr4HjVNb8x0kvgcnyjMl8pJDyEjJawGF2Ue0xKCGFQi4tFpNU7LrlIph-Z1t2MfzUQelJ_NKkPuwrykMZm1lhHUzxTtgRm
}

sprite $osa_server_gateway [128x128/16z] {
xTZfqjig381XC49iwUJ-xxR8Z8WLsmqcsExs_lWMpcaV4QzJzQVsl__5zcxbgLjvwWm-JBgboPym0F5QjQN3y05YpYXrnm3CMzNUL0OOoQDITmp0l5FgZW6O
zreTp8mQ8FAfVzC0n4zAtJC0NtbT0GrmxPKdWvZxsaVLdHtXg_wcctqzoDTTZVEddluk7uvbHllsO5hVwiDu7qnpH_p_Vjhl2Z_zglDzOPNujojyCiASpxaS
OeRBqlb-oWKoQvMduWM-nrSqI22UEzcdtHFhSyHvHB_WlHzz_tkazsZ7DKH7vqFDXy7-YgST1wwSU_7Lw_Ct1zlnrNhxRhbzltVzJwFUVr8kUiuX1hbzsGdl
7-LJv-JsqTL2kJFqVlx2tnz07lr5XQ--iGUJ_dg0G8RCbKZtHHV-mFUF1mt0UvTvLpSl_A7td_q1dDZy4Bzr0BdvatsLDWRmYEZAvNcwhvu4yG1YyocCy3-_
__C0OlDN-Jo0G_HYy_FYwRuSe6m-agqKhRbhV1u0w-RLQ3yurp80RtxVFrRrlLiCGCX6tiVtXH2v0RvBSx6yKpT4hFGdCCTY7u6VfJddd5yNAF7xukVUzm_s
hJQkPdBJNFs_SiPQMkKC8W3O4liTiQzjXWkqxK-id-GRvspn0SpSore476A6iVITFrM_KA6fk7Z-ZF31yVqqKkbp8KHksuUFlVp9EHTJf8RvzcFLBzTV_Qjg
UpRT_z05hjC7hOllNOxDHZzi-s3H0llGSFzdN-tuAEF7mBPlSCwQmxxQy_MwsVTRFcB97lEZGALlz2JJnNVeLxwTFvpe466O3nh2CZ_xX8ILZuZfyNX4H3lC
nyb8VvfYFVpIDuZ-GJd48JuDa3tf6qE-t_OTyGcR_UcZ7uqf4WSGnE6Ndt_CVa2qm_m4WCAtuClXN_k0Y3uuH3J5_rMjlhDM-6WTV_pI9n9Bq73_Q_Bf05Yx
j6XxvFkLJm7pu_oKmQNl4MCARh5GVSg0uP_UczvhysDvDDVcHvL_yItl7tgp1fy6y780xtrAYt7OxwZDZraCedcjX8ZnD9y726_5nJzEkJ3ARn-Wt84eEXbE
zXyx0qJ-A4xsQG3YHAbsja-bLQFz_W6K6k7tzzlwneYlSk5alt2colpr6j-Ok_t_lgQlMXEdjLYumYS8e7mbFt_b1Phb5bzVwslfBnTkzk_RFrph0_lmmNy-
LN_FjJzprX9dBVdMbWK-BLV-ivyVupzx-I4-rSVl-OeufSXNYdnUsFQf7lwuR-tAJy_IA1y0r2N-yuYlBlOHYKCa7p7xYFj-QQIlf3yls7_Bj-pR2tpzQlvx
bJ7vgpP6PyEOvSAYKNvlVubl-tC3_A_gzdc0zAt_wEJ9ftuyVdpJarF7UmvC_O6-kfMdRkMfUtdgNfswK-S6sFVtlvy
}

sprite $osa_server_file [128x128/16z] {
xTY9hkeW481XO1Pc1czy_xUzO8DfzLYd7awuI_yaxlgrW5l3tzhPcVcRohUcygsVu3L5JqciDjxN67n5jTfetY24MHjWDGh-abfjACyXpDe0g-KGPcs0rII6
Wy6e3R2-z2TjGEDJ2BCsm6eGFWgr-SFVUVxGQj_sENmSZV33vwN9VXpanuyQvwTF-hTyF1QCzkbWCKxrSRoFuExqJ__qJt_Mvzy_wCF1HllfF__z0mSRx0CT
RBAFCOxs4ToT_kcdqp_zIPz__vwV48ursa_nOFEFVvn--bTzVDlF-lIsoJx6EDn7OiBke-FpVwWFV8jWai-yH7DyOivMB3FZ5B_o8kLYp3J31sPHBPTBPXxb
Mx6dT9NSu-RdKld2RZ-zyuDHN9TUHPLaPhjSBifCutmChfgFp2oQcHaMVo-dNzZl9-8bT7p-xVYsJdm-SpEnyz_npN9DbhJvaVQ2cq_f5Y2a9NWiFVR2r-Rt
b4DRThk5MgQqK_oob-EV-PvYyryVmEar_t2lVUff8zBhAUm93lGbSw-4w1bJK1Zft_S_QsXBYNPhYrtIZ-o_uit7LV3LmcOUwUlTBp5L03SzyJN1eJxpVVWR
JtiXr3IDz2rdlcKOmHDB6EepKujB14IalQ0b57vY_qK2VkdZGnQVVO3DwVQ6NRzqto1rVNS3ieIjlt1mb_kfp-yVWBc4hkzlWkB61_YkBvbhcYDvoXP-n2y0
HFe-CrdACD8N2qXPsP_ItO_jDCR6nRYvmUDhpip64J4Bk4F3xbS8SJbjVZtjDm20nsVcaW1H6CWN0sdQyUC1toHdiOY8IkZa6N9U-N7hhszm-3cpSlCDqSaJ
ABjySFdP0AfjNfxRjhxnqUsBI6bFO0MFtaBMjFMn-_Z6lrx3DklJdmKTzEABTF_64JMEgFb4_ORcn_ZaNnzy4PK809BHORS8bJ_sQqy-f-ehunkwHsJuiTzw
y0sXPYwxXMomyaFZGcX-2DNlDxpmMsjVnHgFvg7lq-_nYPxySbrwzbdHORU8b5T7FiFtVQn-pXwxHMomxuSZlebHzPM9VL7MjFMP6yVSVERgC-_vhOtFrJTo
-vgtVjZwjnleYA-SHRq-iU50lrI_9GU67vvywZuTzOE9jZ9xanplBOSa0Eff18ZL05ZVi6hVDtQd43vfrpTbRw9Xf7-rgfi9B-MtQQOFor_ursknwcls9lPv
h_nYulRLljFbYRzUYXxQ_Sklpslqe_-hc8axAzS1XR0PW4CJEDYVKLWrbszDvNlEPuxMZpTJxmsmvtVs6m
}

sprite $osa_server_web [128x128/16z] {
xDQ7WOH034DH9sB__IvGmLbp6g9_0qzavAbLrPhlKlxeKlwe1x-OPhAvmu23Lycb2tt0kkSYq00oFqW-Imm0-L447a3a9n7U09oVLS2SDM05RlqU0mxUHCW3
y2SFBuu1l2SFBzQzV_kZD3SmV6dFBlQLv6jJFDzQUfSVMCxs1p3LI_tW--7fc7xvvPTVFj8BVGTZ-_Rn_ny78_i-W5tiXohR3qzNVlb6zCil7-bzleLZiNrJ
BBQFLxxOM_tuixv-ylzlAxvErnlLOG0CQvTjUPhxlzk3ua0TwAHC7dhw_UYYMLxXxB_d2-BblgYfhBwSUFw_r6Uxf_nBlZtIt_7Lp5iqDvDVyHU-bEZDJ7_4
xrd4-7RqsQpK6hsxsUL-MyZUenOphotobtxqFRSBE-tJIR_tQ2e4zt29jEGE-_EtrdklPdgflqYEy9c8C259wT5dNonl0JSp7lwhplgf1mCIqJenPb4L9gcz
zzLFqaPouldlhDzxA2my4ycOy3rHKoPjqJzzafM_pEzHaYGGHCm1gX5d8ao8P3rMFsDX6l4-sdV2xo40f48CaZwR4Zry0YHareZXlmY_x7k_Tm8mqIG92PYH
Y4HoWuKl22H04Uc_rMi_UJ8Y12PSOisbi-I1XNCA57Qzlnw-tFyMydHecR0nAmBaIBfSxYVlurmnl-7MUZTJ8nW-Mj0F-8yvZQ-ppmo4C48anD8kzoCGraXK
dds1jHmWXL_jz_99fF2q0C7MVO0QVAqV7M6BDDqNFc6KQ_tkaquuTzVLX6JoBVX2VxvyrIy-jfemiu4zVAR3FO1v_heRVElt2e-OzZmHytWDL5CQFgCtsXeS
R_BqzQmlC4B3NTidDn5HSny-IUTLv_Vz_V6JqO5FFICXLkNXCuLTv_SO06XgJmr-T_yNPghrGhy0i1jB-lIA1n4aAcvaCVcONn6JGvm6Ptq5T15cfcp_s9_Z
maHIYthdrKz8P7nDNuJM0JEVyGbOxpvJjhlhJI6w4R68UvTNFlwB7mIaJCBp1lHevrFX9IdsvEEpFm_E-0A08B8kC8TxtvrPwkBhAV_K-Gin0B48Rr76J3iU
IGfhQqN3ll7bj1zAQeei8iIxQEzJqLhRyVfbzUKR_tOx-4QwX288o2IhBTcEJr1Qcsx_EwUQd6hwgjjW7ClUto_GdJGJWamaxKSg1vwjDVVEx_ktdL_p_9SO
xh5ivH3LJF7JbxhufTExVlRiDqf2bM14cvwvBUd6iqPhLcFo8Jc0z07INmTV-zcJtrcI45XBUyqobusNXQ_MwXbVzU37xR10TED4U9h9h9kxhJoNbdU_C1g9
2BpfptU0L0ZcPDFDbvW-Bxzv2Nxfmx_vmUfv_NFaa-w57_pT7yS_-MR9cQLljlXch_nizhlnOXZCoQHxAVRWqoyUzkJ3ityVw7b_782xJ2CicvvyCHxyuzxF
b_en3i0PSHtfXdl9zC7h_VATzhwklhxXhmVWWciowSCVV8rcjU7MU8bc9W1aniLWdWTJh_pkR6MSm4YVz5fLxdn4Sm-1T_gxVxlrhfBOzXQm3dpbgoV_EFs6
r_hvQm-LuMTUaztqxCvR56_XPlfM_XS_wqqqx-R9SvtraINVgjSUqTxkw2UVVVIQ2t0cTS97hIoyj-INtlVxNou_5sYgpbcfAK-rrggPLwkzVsH_tYoXexyk
4COi8jxsUlerR_kU_yC5mS7FUXYnbAEU5VVe7xSVyxFUcxBlxQowrylvum8VlLTJywGdlAIUPtyzdzsc_lIedYiyxlsbkDc5UlAl_DoWHqjrv6N1BzPVBv0h
P14j5dh1FtvKpsxxriVunnSsN6gFtlX_BkvNzT7_ZFy7
}

sprite $osa_server_terminal [128x128/16z] {
xDQ56SCm44DX7GJttxSmGIrN_aBt5lWL3gvQLUtj7Sf_EvJ_DeBVt5hoTS20BszeopRvWFrJ0DG0CJ-XFMyOGF8pG0yGyWkW6y3pgu4iL0DsujOVCU3BEo0U
m3zvVFaTe7lo-7B_zBS_exj9uQC_FzWtaMzTwNplwLv-SeNQdyZC3lLJxsSqf_JBBx_yyfbkw0UPslU7__y4cTYFYUnWFytKVaPpvPVlGh_yyfdkvti6bzft
urBxVEN3x-hdpyRwqyyEzj_5sqdQgoeGW66Wg8O2m_vtUm5Z7Z5wr5zp_GRs-XBIpEAjlTttIEWdt-_-_j_i0xKG7lBf7JxZ8n5hL2RoZ_Y55ub9YV097uWa
X9WI4ptaSonyfCE-ktd-ILDAWGYl-xWUpUEMY82pHVH4986924R_NtN-gkxtcWzBs1UInlontxzjlvuq9xBMWg1pVkAl-OHWh8CpEUkakk31ZS4ojspJHwpw
oQmNjvLTRTjt5W0yyHHjXU_Q30YuawtxZBRu53GSJRXE0ECzFhNf3p4TJx3uTAVlms5y68Rm4pyW8kt7l_EdzdtlBT_kKzUExvZkzOU0-AYlH7mW-Ps_LSU7
rokGnuKFq2sxpHsVcZyCofj9AmIjLH_d_iZ1H-wMLtsH6JxtXTuw_CplyTw7s_rO84QMUQ6c6kVzobTcOUiyBuQWYwfFrFcsBgsjdBNTWNsVvwzVoW7hMSAK
ng-MVeEy7vVLBylf002Sy4CGQ-OZq9ME-VQupzMNuXTG4COH04aerah5LoBodMzxVtxWgFzA1TGGXBmp9GYTsllCHtquullHdn96P-rLtv_mKLwlf6D1o5jZ
hQQkYKyRlfzyl-FdlF0TVFpFx3iCiM_JRnnYvH2hZ_WvC4xBqi_hVenHhMawQKpBEbymNF3pmiVg3yLeFd2FzpLVBlfvvaldMoynffE-gPmnrJUc-jE1JJ_t
FhtzYA7Yj_c8NtxC_G3axUVcL_sSxxqtLtqYVkNNqDhZXvmF-EQCxoT_rbBzzFQfzuagHrHzek8JxVZvtxxoFDtnJU-t0tZApmi_sEx_2p_qG_5vnPzrnCV9
n_C-V_ifTgtuQ5ljkGQWB2s0BGR0_C2iLJy4UFi7opcElZdVke_LFv7-m4_7-HTnzHdFn-k-23DBY_SZakhhNrht3yfIgwihVkfvezNVZqaaXDc-nk4lvIap
fGYodmEInlFa3_bA7pwhEDhtqRzX6ddHV9EV587aKCn4F6vekedFEIe1-4_OHSku9XhluTi0agfGZLUIxuBUnLU_bkAfqd2JNil_R-Qh1-ph8p3tzm3zTFy1
}

sprite $osa_server_mail [128x128/16z] {
xTRNmggy4e3XwG5bR-x_Rdz3-KPwWd6n2k-1NP-99G9_QdTtZ_GkuhsBUEyRV4sO4bLV623o26bXNNo0noi6k6I0WLT8Zto0Khm1N3B0m0U0ImOO-0eXCour
mCE_-fSC47a2k6W0_-Nb9t600hp2oUJnwcFVu7HQmeVpqSK-5lBnLELyEjFVvKjUNDhNp10lzQMyBvpSxT_-xT_-LVlVN-XpPgLz-iUFVpYpmZvhPXVxWbZQ
5qxkzc-VRl_sBzh__ZwVXFCgxHFcLThFx_Q1_bPV3lkkhuTTx0jYSL_KL4PV3lV_B5_3Mwi-MvVo5_mGgzvQyMr8o_dEAuA7MbKBNyt2u_a8PbBATvvW6bLL
E_DVV5KzcuUP5lATHm1y3m2hAanyDglg-jaqmQoi7moSzmdY05C_F5_yqv9zIl53v74U3GDCtdzxD4rJcsb1NzTu8Xe7S5yiVWB1pBZtzvhvMQkdFko-0-wJ
Mfyax7-9lYrvyhe1t2TnlemVR8lt0Tn_nSBKn_DeNeBllElp0MhtjyBLZlqmusaPO5sxdvVxIJoj1bJNt_7D40vqPYRW6ilwpX_fCGIj2lhEqpxFOuWMYljc
3B2xU0ynM75V0GvqKLFMVe1Qolfc07jwn1a1GAJ_3bPSqZT3sDIZBGH3ogy8BHJr5TPrPb5b14za-0Hu_iZPgLzCy0KGrnVkzkGDW4hefvvZb_qqtL_YIh3I
i7xtcKluG1wpl-cBK9df2pxmpyA5O2U9_1Ty45_uHlWAK73XOpn5Z1pYx8Pa7uLfZnvYdFiH4kbFenzFXnkOETa7uatQOqhoyOGFJ1kq5x4L7wV--mqPFWXl
qSvd-fpZexBJAx5WkYyvlW-0k_osBwCl1txRRlj0nhWL2Qtv7QSQETNeguutH1znuRVRFhBo9izOo6_NVOo9CirofvJVBdqSK-KZVkv3v02Y3n3zuOPjlvtx
wAdoCX4wuQik_6VRj-rJ742dEJ_tHGG-z_4znpt6B1y-yR5_YR7-1jhrpI9d5dqp130xyDjjNvJdcp2hqeuFKx-xGS_weZZQ7edIB_5fwpzWCa2bSrz7Np_o
oHS_ZvNT5nmY8W1W9W1aHW1YVhy1lGIVnVMz7RXYoE_O5t9-Ou0l-iGmuxUFVqpF5DPzXOudrpSZfiv_d6pR9tJ-S83pVhFWsn1zSlqWefV__D-v1jtzjkry
mlIYtxIVDUgnIW6pAk-lz5KV9hx98jslRZxctMz22DMYUgN7J_ylmCVQNnzCkqptBh6lx-u_
}

sprite $osa_server_distribution [128x128/16z] {
xTPdUgiw481XJPS4vxB_tLu4Wqs22n3vqIbyFvAuleCe8VofNLtb_RNZlNQyzma-8Um9umS6A3o4VK6gFa0Uen2Q3E2yXFsX3r2Hrn2Q3E2yXT1a0ESZX8DH
hG6o7_gj1YWyXj1e03_pJiN9_Jfdtl4uZ_tOrt0wgU67ys5Z7ohvSAfwFfxfx_BvM5JRbuC1DFMvli-qkyk__Ck__5RNlx_GfuFLzl4Vl_-XWrNsIGxMs6U0
sZxJxYx_yl7oBx_HzU_lyv7fM82Dxp-m-Vt7vUFVwlFRFklBsnhx353TPr7XnUUtr__AFkcKK2DVFMdZYwhbBfigD_5LBSQkpwhImYVLc5BNzwRQoBTkv3lT
xUDhFxtjs_fhxli-gKeLFwVthNrMrPXCLMdsN_NU7rBIDyMKLZwApl6EwzzxFwSHU9b9J6db8pjVmI-ynFGw4qlP_JbYmZdw7dxlfP-SVvsnfUJ-Y-1XJttV
UZVU3k3-yPxxAJ7Wy-WUWgRwVawmyk5L0JxWfnXklbfurSTzeiO-j_LLc_bUMr-aYOzBVCudMlzS_Nd0zmxxCqTtsNyUya-V_qGLVC3dvpyWYuu9uyVzxVcF
OgR2H2ngnl19Vxl-8AQ4i4Hg_CY7yXEWS02h9uxvNhX7fWIthG0epyJqnNU8UVvP_FBJdo2YO_xw_0SsHgGf7m3AYk0E7ohuOeJ4V1i0IY6muSQ7h_xwYOC-
KboQ-Vi0S1i0zljqqDVOptNEBpwv3_F2lFVvbC_YVXIWsUVlFgXiVLvyVkCFmnu_6o3T1c2UVO-Cxlx4YHHEfFWY_eGVbXj_sB7-aKVV1v0nvlK0gZ_oX-S-
iUzzc7qgV8dz24Jq1JZjbvxuH6AJdnJypjjv8RgH062yzaFXGYX-2CNt9vxxmzQdAVSZ0OwvhsOcX3JclkekNsJZTyFSDvyyNtz3y04cFlTTKcBcPG0sz9Wv
LFGr-kvtdrd4kl9SLXOc7u3U-E6ipphxmGTWvkMKC1OVOEkh5awr-AgZh_h67vxuSlV1_UG-hNrQ--6hFpqXftnDxli24BFuzclnVG0o_8nFCba6lW34p9hd
ArBnVG3U-BBuyYDVRF63-qGeCMTZahil2jvynq8q_WGY60sYzHEhzlX-i4KEFi0K2vFppCKt3iSxiFxPPdyv2Fmwo5E4P53F7t84-hRzdGEtaq1ctdqnEPKz
y8SllkZoxt_nOVBN4LdA9rlxpW_TocVtLmi0I7CtNs8-NR_cjxwbVYvfcDhwn9P-dStrfpvBxqMv-RZsYImEvzloGvy07jx_-W2u7e18ut-rV1yW6TqJJyrF
yYy-iSLVzNXVWFoeBaU5sm9uOjMstXkUzoiQpmDuh9Q6QhmtlAYBfWHJI68M-vgwDxogIpQcQYEUQke75Y6dbFpAuLzHp_PsZnNgTVK_
}

sprite $osa_server [128x128/16z] {
xTQ5Tkim381XsOBWFNx_jxrHJprUm9EhWVuoVYgvWVsYA8hc2xdoMXT-6aGR3fhg0DOyd2jr643v16u3p5i8fyjr04EU0Jm6gBm0U0nG-G4kXdK04tvCu350
vQS4rwF9ofyoj4GwkWMF05u3p5i4hR65Bz3UPE0Zj3SQ-DdPHu3KbA6VM_fLFl6rqDdFoTodytNnyNJVmWy__2byZ_M7U_WN-eL-JXUpzhEhtv3lvu_UlkVl
FzRVyCCFFxO__Fpu__-zVlXuL5-V-2XqzdEozv7msQUzUlZ8iiNLnvrw-2ZtdFnD7gPHHDZ59v5nMjP5HD33Pv5fdDTr4Y4dVvaNLtzQrtKPdDv_595fMVGB
wFFzPxc7FkjV7O3SrbzaOSByxDDEnlxdnVRV8_tmmmy_V4GzkX-_kgAtNw7NFluTF_oKi1wdb6_7IAHNzFULg1oH-aJVnwS7-_JQ9tUVlfrVlFrIsldothz1
o9msZjLdndh5RQ3tVcdcztq-wvT6_XCVG3c0pGTGlrxngLyQ-R9yxDDLl_Jn-OtFXdwvxhFwwRslzVN9t2-xleXoehu8rYiUxCjxdp_rIwiVVcE_n2SV7wh_
fRww_goEliaRyA_PXs8P_3mVN7dDbTTSUSrNrrpvMaVQl_y
}

sprite $osa_server_monitor [128x128/16z] {
xDQ70OCm44DHNQ7klsyIDh0SqUyly4G7TwsgrlPEvRTEvRVsu1UtbdpUOS366zgoHJvW_HK0DK3C3sZF6mQG_0ZG0uJy1EW6yFni80lLW9MuzVSOiF4EY0Vm
JnvVRWDqJnvVhh_-zaTqDoXyzESd-oRohIkTxpqzoq-kKFi3cTcfVkhzZEQKVldbbry-qmFz85Fx_lB_do0J-p6GdUodcThFQAxyybtebry-q_Dyp-0o_xPR
dzdDwa00XZLz9CXb_xkz6h1EmA76-Ell3vl-q0y_z_lZRlzwyC_7FzNdmzxhos4_sMU0stqM5Mu-7xx_R_P9nuH-ag-FvEVuecgbAwRAh_egs-ayCtDtWl1L
pRthYwgyw5U5wNoifeIawZbtVM-gh_aYbAu5ObHzwohVwMaVLtqHJ81q8OGaXjKjVTzdLNdDvuJxt7D40CQigfvDLMdozzhp8H59xe_hfeoGaWYAJl69zz-s
hvA0QEcirC_AI426o8r_qKVIlijdAtrF26YX4XDE7L-rFT_wJjUobRpvcy5gLttRoBlmoV1g-xurK4Li9m-VaFnklwKikgE_toVM7Ttpctr1qWsz-Vn6NnbG
TdWlR_5BOvJImzSLFPUkgpuZlyiNJC0ZBKzywBNHf_jyNVZAa1A5hwnpFGS-zXu_vugCfpzD5q187dPkzevFjFXTJZZZJsN5XDMlgW27tF1dFy_i4Q9FkVrU
zwkQA85uDWAqlAWy2b-Q7z1jVbKJC01RLWGGhwhR8lVm-JRVPduUJxzW8dK1I6YLLrh6shFSxNTkOmA9fZS00G68Lpuj0-xbsOVu1GWEO37XsBVm2nFHj0WR
9n01O4femH_v0J5Fl-7NtpQ1YCxv22rnhJO3IlnN7gd5Oth6Xsj-fz9ILqo4YTGemUDb4FcZN7tHfGzBVpxXsAVgvyZ7SdNZ0CobyYJcJy_W9PzE-3pU_xdb
3910t8rWmKUZhsTylkP_4kDnexgx1Ez-okVcyu4_34U-OaeKi0N_l0FXwymVEP7WHC8NQHF21_ZY3tFVg-yBVtmBJhBvrCt-yCMVy-uCgBxesRVN_26rVCqN
e4j-2Ywby5CAlqtOz8UPp_BiAxBTuejyyRjXQiyt5Z_hCtEwstVH5_rqrIyBN-sYhngSQlYgrLSzy8U7dvT-vBx1R_ffwOyJvBIl-knlyU5tFTbzViv9J4hV
BIhTPdrlx2k-D5-k-ogsTUmjinQpkfd3et6xYQZ-0X5KWsW-OTQcRwPhoMhg7dwwtfRl6vblPVv-txGs-tUjMVEpV2VxwXVOy9K0mrD65Akc8B8sltol5Hzv
u_2n-jD-GBZA03Vu_O9FGs7qrPHnv4m-Zx-TVytTn_SQMWz-A1buy_fFM6tsNpEBmtYfrFoFOa3g5pApN8Qx_A4hJZ26Z-WHj-IHJbaf_zt3Xp_4nxUlbDUB
U_WUFXgYZ-vA_STm4nyDFxoqx2VghUlRkC7--VthVm
}

sprite $osa_server_identity [128x128/16z] {
xTQ7SkCs483XxMYywFtVDWlnaCYg10qEhl0VpmhZzgswu7Vjx2nlRoxlpUMz8_X4k2MAsHll9uHjOHg-GFOOODO2sLFO7erT87i6C6k1x0M0MGjaBo9qngCM
oEsXFsc1oXF0h0Monx0hgGkCU-Rr9zdxjc-mEntXm_veie-3VDpLE9_sz6VvqXUFzhKpnAc-ZFU5DtVwft_wfp_hzUyFzBcpqJxzvPz_kBF1Fcjdatr17EqB
R-xqJvzE__GdlVxzUJu9zpNQ9-nhjDyVdZxzgRvyx5XVFpRP5yJXlgYfD5y-lluFzjckAK_oxMSwnrUpa4iEPZB5Tpx6icGpdU6pMKofB4imc-I7udonpJuD
llqjBykIp7IABsOMK_39g_-k0tnIMvCDhtyVVDjUIgdwDMdyz_nWlIdzZ8NRwJwwxvLlfWXziGcz2P_sqbVe3etwU-KJz6SypaVe30_o9QGWdtKyo8yvnPGJ
Vk2FyaCsin1oX1gRZzn-ah3fQmVuL8AgXX0pN_qG4Y-PIsQ8R1epnOHud2_PLDHYJ0QUc8FPfvhxKPE69HxfQp8lk1y002Dg96Cn5d0SGiGGZlGv1o-cc1MU
XBKtFlFTRCUjFkGKelEnq0VzmL-vTTuSkSlNKXoFgHH-rD_vp2DyBPNElaHQ5q1wx3WVIumffv9Jyilw7U8d7UQ7758h5hkx_esdLpxMYNKIuiqtDlivnRpg
R7w2DNpiqLyXaNLMtsVx1ZDlyajAUIrvvSdjJtq-zlannznAEJ_utbiVl_gttzZaov9YMejfKG14-Xhkz7dhyo-djLm2u6FzllJum1RNZ17t-D9y-U1VBW_-
RVWn-kfVETNAgLPVjNsZ-eWF_kN1x-A_wtiFVeS-mh_S-OAa0egiWahCM6SzAxFMirp_D_iGUVIXSW2aweRxxHklVE-h7qbYm4XQfojOPpr7aUjtZ69aaXZ9
jCDNVV3BPMsKBo9meA_xVEZoNSRdKVsYcrxuPfKpgxuP0fXzy2__-rXzLL4MKrLI4MCLay1gfgngQcIXNZxtuQj__OPs-8B8mapiKJtMX8LOhcT7QFqk2G_r
BqQ0RwE7t9S7NvklFVxb4XIWXTi2DAARzG20sISoenlCjz-uwT7tYyKOEaDJGjZHe-zbwqw52KVuS3qjPKlBDJ-a56C8PjfVU7pyTVRV5dbNt_P_hFp-1PR6
Dx-tVre_zdHfGLjWJZ3TRqtclScyDutlRwvUcwct1jZpE_iN
}

sprite $osa_firewall [128x128/16z] {
xTS5ikGm34LHo-mcxN-r0qsEClbAevMgUITOUCFWh0000030SPpFzj4_BDilqFk9fjoZIEMd3cf_LwKOcufgqwNOf9L-az9_qaSVVVJHBr4AVhA-W8BavuYy
jD9FAqBAEX-BQlNuwtnfkf2RwcjzzD577_tqLh_-emYKobmMVCnpQKhlfxM_24T-olakdFaWUEhhyQyjld_HHnzzzD7FYxyFz2DtNtcKtcz5LLEikY-__rDi
TjyVwACVq4V_Y_yVHHTzrYKVacgdzYjT-2joNY9_4Ix8Xn_4Yq1Hqlkx9XM_UhPrXPfq6DklR_Pfu_rarqSV_OY-hb2Lzcg_UayQvywpLz15U_ZzLnUaK2S-
-lvdo-zFPXxPPvxbX_TPrC_6VV-TphsU_sW_FThddhVfynRwBFg7lQxL_OfIzwffdqN_T1nYItrslA7-CDpxZktOzvrztrdcpwpxpZ9_PfJlhEgTLRqpgtTs
SMb0rme00030Rm
}

sprite $osa_hub [128x128/16z] {
xTJXShCg4CRnHjbz5Z0dzt-tPuCknjPOIV7b2_zf6KPdyXDKlzhLw_LwlLwlr-lrUhrUhzVhXGernAsslDQMrpxZVKdo9l-nxpV9nmNji-MFjyE64paHN-vd
_kyNGBO1nJnkDVm1jW6rbbz-1u9MpFDDQx01vW-r_D4se8YdMnrVOxk00bzgBLyRxHrii_py3ZPOVkaZQCjtmr30rzo0nCkWrUDj0mgMdohWQts44e_1ggDh
337_n9TtUAa2her0q4ujduVlxTlrDo0lltuZO8zWmV8hHhzlGD3itQjgtqviW2sVx7PNqvTV8ti43tanlje5v5y3_E--kyvtjW77oxzc_tz_1xTVtg5wXnkG
UF4OBeq1y_TMN_3fgViHikNpjRozWsyVFbt-vHiWIbLOVjqD2DhrozT6XbThT_jHszh9CR3lYv0hYKhZES2_yV_EFm-p3go3MmPQXeqVtla8VYuuRpDnqQRC
TZvIFeW4Z-gFeogwoSlWvc5KNuTZty--8AGuEFrFGNqiKuQTZvGFFdqHSNNyAGNrRQg-B5F6Sb0YsS7sli8YQEcJUjHo_mbqrkT3dv4YzGafLfymnrWYzGbB
Akjrk1e-XoLni2cJjocjvqdMyyJgK_Q9eJxWyd3QHrpo93OL2ZPbjbbO3uB8nIauVlf06fmEHf_sYKWuxw_jF_cyrPplW8kS3mepEo8TF_GVZn3L9ytRGwU-
JJslZvhavsyzAEdxwfBFvhjv4D5JQO2swol_qFtyxlEUBxi-e8Gui7CiajI5Df_LdtlwCKoFLzvyPdxnux6FLv-IZyNdhK_PJwaVxuz7vhFF6n_P3pZsVLe_
wDKdnqOlleYi_dzg6h_rML8K4KbI7DQfx9tt8aWKY22YW_T4x3td0SpoRFMrp6SVy74f8DZK8rhYrscql1Hqu6DE85Nohud-pPclxVWVCEVxuHkV_GEbHg8n
XnWVF_me_o80p77rlrO_oBVmUNoKxFXJr8BVh-BY8H9KchQ-NS1qUJ6L-Uq5QDVhcSz-xZvDzqkRdjsDi-z_exwinhpMcDVQwLP3tMg7Rxl6xVLwlLwlr-lr
_WS
}

sprite $osa_vpn [128x128/16z] {
xC410G00100W_rTx0LJH1m00002olRfRRnG4mZZ-19aFm6pk_svtV2jjw6Ce6Wmd_W_Ox_qvKqDZXmRYkP4y6icZOtpOaxue7FP3aHukMiV6dsxLN4DUDHpp
mR__09GNi9kNMm_V2HRGSVpzNu5exUOPme05hBxhvKzv0RjuklNm4Uzx0FZQRNmi8C0VCNxv6Um_VkzN47pmpZNn_HS0NftLmFTVG1uVjV5TBo7mud8zTCIY
yDjkNlTK1zoQH5eM09xTxofsrmNayRk71U0LR1o_VuG5j5mzM7XN-zQs08nF-SlTJrzQ5Y3H-llgkQrruv5p8k5ltv_d-xo0-lZdxF_lps1vyxhkLHS0NeEu
KsCymClfsw-U_fSGncTtSeG5l1fVCVx92r2ZAkEFMK2qCFxPJOmtO7FzqjlQoBF8jgzAVa-qDqRcXnV--xptnjZ1TlZreFKe_FYU3pw5hw80deXecaon9Q-7
_pecy-se-s6_Bn79ugkg_w1FLj8PZVSDLfKF-lJR9_DeeEz9gDNdjtr2YGHXVdiEVvfFcsbSOo8sdx9lXvWluh-FNJwr5TFQilyqHy-BBuB3um3TxbDJl9Rt
pyhC7hz_q7yyOZA_Wctr_VufxbSFdxFl2GU-g-0GQyC7_qWfgbQykY-2-qVOUrQ5kjBPvyL7Yv_Y_2ZurUUM9FVi4tnPVIvzoZvQ_7H_F7xux1TAjT8Fc5_e
sISSe5TVLN_yVsPcll2blKIAEAWAA24ILJj28E8G-FiGPbtwyItmXI_rj2ZbWkweucT5j4lXEGtvARDlRVW7cFP---0BlwBqI2tcc1BGma_wYN079VZb_h60
CZaUrz8DVqvM3Djr75vKeqbpwUS7c4_Fa88l7i0wNmTV-hdxFDzFRLwwPoxV_sC2ZuRoQ2YFXkfeh8x6uMNdk5TNLrTNLrTNLrV_0G
}

sprite $osa_laptop [128x128/16z] {
xTc9UgCw38PXBDcI36rp_tTx-0dfGp01ESSCPyat-_g2PPQPTl-KFdtwzEdJS51_N5xdjrlfPKv-zSTjBzrDVbDr7G5qKobA-qL7QJg2OpuHyIDgLWY1rUFB
oCVaAGfMtqIZ9mg1FNuaYlvm6AwOGw2SxT37yh_LyGJ8pEkBtfCsiTyN-9BRffFF7byf4AV6lbJuuGG_JNw4VtG01ZzUvsVutDYFav_07_fqXWy-YCVlp_2v
rhUsFfQ_2_elyFkUGs3MPhHPZT_FlZIH4Nox--RoOmlVbcMjz8bJAnpyv7ST-Vm4FxR29rzQ-tvyyjFaiyyN-Dn0BttLxlW0rEFxTVWHsw-Bwl9jz8cQwV2v
thTAtU4dyCT-3Y70RwJ3ftfVc-YA7hxu_9xWIvrUmZCEtnhuFXrgqUm7hV6JMmTfkjDy-tNx33_cVhTSdEzhNwhyVEpdREhEgdoyBCBd_5etw1L-cdogyYbl
smNky6ETd-v-TYoxsmzTnrvV9jzMVc7xVVRxE02TRu3BDNyB5r4HiVds5_r-D_c5x5R1pZtvdSktoPTS9qFTh7Zy-FoKwyztsxTAFxjygAwotdsfy-EsNwhj
VTmiYBCvN4UFs--xllpDShhxwlOPFcMJ1btffuJFy-sN_7wS_DqxZxZJpFN-_GROA9fyzlfcQV8flb4gYnK-CfFHRrAtAFfzez0rBWG1x_I5gNNEqqU6r9Me
-5Br-uv_L5LdkH_SV7_Sy4vElqflxmF8tlfbkT_vVV2zl8LtefWIlk6Kxl_Rd4qfp0aEmEbdUTEFSVBZv2Srary_MOKV0xMETVHlDvTlFFhIC2OYxKT_p35-
7VdOqez4GV8mVDsEZk26vK-Zdves-j7Wttkft-1RFC4d5co0kPSy_Fj789l6640F_z4B7hvCfzzy02aFm_Vjjsr-mDLtZiywRu2vWaVprSUjVQP0oms0Ilvt
_B6r7p607lwYaeTVN7tDhi0y33-tPGN_XV5lBRzKvTe0QCLZ-oblBB_QSVh8JBOtGC86sFNd3x_4LKcbd2W-RPP4Ona6qCD_wfc77mELFdEiYDAspuODiEDZ
_1oem8HYbR-rCXZ0QWEWOlmK2gpMPv9OHY74qbylVmeRVghpuxPFWR41zlsjcvymL_gf33wjDW1w7h_HwDiwYbQJRFx-qGzI3k1v_8BnwogXf3K9iPNnVGEK
0rXTVIVMqP5Ff_eXsDOZu7dyfxNQ08MFyGSwjOxN0tX-zlFPVbZvgtSVwiuEBu7R_XUs_t9O2D-qZFkd3R1y__Zk7mtdzltY1SYXD-ddnGlWy6VuhvSlm3_B
ttLMcsUFRd-uRjsbFBgMHvVgw5eUNQkZQtLqhOwkrT6L-Dor-jIb-Dm5Tj4LTjabSbaR-Fe-VVhq5m
}

sprite $osa_desktop [128x128/16z] {
xDXNbkKW34LHeuJaclzysxulPmHKvxFqlvq3ost_-z__QdV-q4mypwDVgQESRoeJCzzAyLIMJEL3dFHbcLkfxfxm6ViqhQLepgUDfscLPP4UN-gJh3svzYFI
VensvKVABqVV3bNhUGIimHlElFkSyktekoBR9b_TVJOLfcx_8dVvSlQfm-VDHmC-Zd-NJqD-tLf32QLz7V5XF_YUzoLg5ttnZKXKUCpFozU-MRUlRNu5_ifd
WLzgnfUo5FXTyiMlX3fzYvgIN_i5VkRr_y9FFOqZd8XLUFSjupFyUkzNo6svnxhxQYhSx-Tbu17hNXokFovbzwF7XznZ7ttKvtlKR0xxcQyPdov-jmwVYLM4
-_o8CHs-u0KyuEVF-gKG8X7ual5BqdVWJtqqxkTv-7hjhzdFZnZGmOUUZp_7EjrttmRyw_rdqqvVtlk--vl-DiF-p_GlCefFFahw2byZNiXDEggzVjbzl-Vl
Yepl8pwuF1y-u1jyI6dzqQU4BoSVzV8exzUJNsEOl_Phmby--T7bPpy_ndJ4t-17scU2lqxn8vFiEk--DVj-y2E6TVWClpJxxlJQZsHAdFGTFi4Vq-5ptg_m
-T6F4Lz7_UZ9Hlo4Fj-NY34TrRClpRvT_0G-rIz42Zy6ysl_gz4lHnzDyNdpuolbsn_lemvVIvdkK-6aNt-Dxz_cUyxtERxaVVaj_9Ziq-P_jVeqpTVVng-j
FiCNcn8VVShvsVXLt-VNmr8uW_y5lidcYu5lyItZyyHaYvlzs7sMsRNw4I6RhvDZ8c_rZKefDDZ3wPUrrVSVxPg9jgiW34K5aZ14w___xUjHMCKgnLxh6j--
yxWFIRFIYQsvWZs2WiBV9puHsi4VaJP-9MPzdmY21-4pyHDfWvxKWtXCwg4TXjCKdpuP5nHVbH3DVAff_PLnoemWsxzZhfdIan0puPYKu8uUlpVEMuPB-dbC
nGg_F-GLRxdWl4Muf7-CgRupjEKF1Iyiowz7VVp9Fs-P57ufCo67-1nDbezCLCOIqQRvYl-X2Z_dQHRVPF75c8BtGivPvn2Zy2S_K4qu4nFBaxQScL47rN5E
InP62AIWaeA_rODn2H240BCSm4n0C0Ygqper8OTOKhn2VES7kWP0KS4Q0q4OOC43XXtwSIwK42M5ond-441Zo17i0P23gD2_4tsfadCvmdT-j01JKEOhrpJt
5bqlzhs-J639G0vfHSxxmQGW8SCnCIaO7mtzYW16WdO07xSRPSpeIhK3zjjdd1R65xljioPmr0fmPTUryRK22Le1Ohgkx-zV4N9yw4_eiVyjKLNd-Is0ezRv
nVmO5tLTHNK0ElJdvsrSmUxnhx5idx_uWt5o0OQG6CWA6qwgzInog__mi-5Be02ymRe8Vq5arKkh_7m9slcTUJKW1G-x4saStnl7rtZwdN2DeQK1kamMx0pz
BUNF3P2tH44rhhk3Y9exK5EAADxl6o2gGH1An3_9St17-NC3U8DnILDvqehESzjFXhX6ph3p7pO0ItAQCmrzi9Pgl9S-WMaB6a0rpd2UW8vVZACQTjJ7ojvF
J3LeW7Rqy3lplPuix_rlcOm9UGTyLNwnT89TIBTlm806T8_Fnl46UsxWP3-193LaRDM0eUMtXa8DkN02iVxz6q-aVkwG6EDLfsnl3__khYDt1kieqzx10wbg
jhVBRs_3cAIQxStot-aVglk0M-M_rKyzFvlXJapFdx0UVe_FnAuVw8tq_NepmqVqLjBEzv___0C
}

sprite $osa_desktop_imac [128x128/16z] {
xTQ7SgCm4CPnWxP9EE7zt_PWxHqoaCNQKUHh_A-aw_Sf_VQxkxgwkhgwudVq-tZhZAU-iURoCCHAAOt3wyOleUl7-H6M8hmDSFoXYp_kSdqQeYM05EL7ElKJ
TGnU-p1rZA9--Sbg_U7Mf_AN-ECt3S76Rwhr8Rrkt9KgQl2F1VYmlvGgYk2m5F2rgWcLTiH7s4h7025L1zRcSyJNTlmI1EmstzhuHn2WctrBVGi2TDZtMsLl
0LXjFkAPJuYmBJYm_ko0l-RwXB0DgBGnwll74z5ZXuOLTj0dt0LsZlbe_1AUous-jLagm-CfDFwSRlVf6QAY6YfKuTeHKusFqwIEPZ6pyKjFlZeY5iavL_ix
W5OUj-fvubMsWZwPOxp9wvugtEYWpq_QCfzO8niKm5jyDPVOqiSSLcEHVAmq-6fQ-YnoOyKFUgdt5T5OppFOrj29BjdHGxuccZsoykPxiQU7V7dgDaCVDrH4
mdhODzu6R2qyH_6uhxmi6RhnzlYk4ptkFyfBidq8B5VtxRYVLzu6A9vzNdoxtPU78FQKg_jqtCzY_chg7Yy7RlHt0ppVKHlzhFwsmFCDx-rdymDNR_BptdU-
khhvDg2icH_Gs_sIxIESHS9uksy3b2zXlTrVKHD3ThjVicaFyl6KS7tj_dPVUyXKNwD_w8t-vJlbG9DJq6ylxaFfs2k_gh6X1j_ZqtlzlGuTxX-vVNgh7t7Y
VfXF0F16Vpm4Iwchx_Fcm-_sKsVVvnF4_UJxCJwf_Yv_F0RFnYw-prl9hj_VTuuwy4q-ZnLyS-Zxs9stwpi32A6bb03IQO3i--_gvlGx-SfD-Nul-P0yArC9
wV7MtyF5YNdnRtqhqoJiH9HBxksNmkI4AALqzdCfX6wSyqTdFsVmmvnpLvv5A9qa8frvIV7lxUtDIy9hE9n6l2JpsW-ebkd6-ut4skVyfGROcdYDql2g4LcR
ZqNftVKH8DK4WCHyTmuAuXOptEeRc6Ls2-3M9_Du2qJcEmNv-OCv3O6GUJujnizt3ZV_v82foM__0DnbAxzArdA0j-RkcUxtEsshcnsh5nolGUrNBwf_LrTN
LrTNlm
}

sprite $osa_ics_plc [128x128/16z] {
xTRHRkiW3CPn33QXD1ll_xOdb9vForGl8b1GrVulejpzufXiDMgVujzDrD4y7ZsF3y8EsLr4v2J4qfDy8JLJ8hd4qXFuG3bhTJzdFVRGVtp7ZoD3TejCZXps
qDLd8bOo1iUW-nxWEx8Ax-3Z9HYxn7k3VRm4OknXZ4z4lru2IRpNmxV7FlNV0tm-y2dtS0yuZ0Fz_Hvyl3VOnqimBiHxRRxROfOjloL7VevC-nxWMyUPNafU
EV_AIx3OGulFYlzdP9Gz3F8j4VOGI-TzsViCNuzA-psSdd-fz8cGAN6J_p-fzl48bB-6GVx3tolsfE_OL_dgBwPHFYd-SjAN7ZwTztsTJvrzVXbVF_ijlZJw
rEh_gCdt8tnIUZrVYizJ_Oylx-sxT_PbjY_orZvlOALl-_dEodlxhiP7FNqqsqVmzPxZ8_Xgp_8HVANPlktdEtOiBCpb3lv1lNps8JWEwtgxE_PHk--pxq88
tgth6czt3F-uBZul8J1VrjLNp8-QVUnV3lP_s3bVQQ3FpZ4kFDndoUUVyoNVZVHn_cyNZ_C_rETDPLxoGsoN2UVF2JCkSyz_rb_t-_luyaB-n__uFDjd4NRx
-CryuNqopb-ovd_rRZvlkHyDzjlF7whtkvu_Esd_y_tvxvy8VklvE-FJrcoVEkt_pNobLzi__9J6-WX-gl9zp_z_oyrFTVxYzvtpQUCfnclAZPiV-1Q56DTg
Nnht3vrZ7hyqqATRRedWw_ocxvzASecvDQ5Z_uhpzwEwyuVHSzUlb6hy5Vu-nLTmMqQ_hj-WAtrn-zZ3lnbrewCZFkc-zuglZ0wprW-IVTudFaVmwR7E0QEV
yx_kFaAwZz5znEXDlXpxwkWuSi_pBNpWJXkzlu-WMxvWzA6-zhNfV4TV-KFJvfllFtrhI1kzavzYl8YQCqOPlPs77tt1-47Mc8ApCdg3Zt-0ST4Vm94nP7qP
_OhHctcKOkuIr9Rbee_UxfjqZGTXzAuyIklr25yJwiUZz8nCHRDuD4r7qtGqWQv_2FEIVVhq3m
}