sprite $antispam [366x341/16z] {
xDi5RYG144FHbAoIxt_YvGqpUDgT_yKHFrKyq9ghacP6sj_vklsL9CqLVHgpTlrYAmciZtJj_EhsFOTECxj-P_iMSReb_TNYh8S_gLSEEKST06Ug_QS0E6Vj
BokouL1Vjv43n_gwQs-i8x7WSZ89wsGIrkVnnXhlMLymOHrDZ4YrDuSDTyuQx_6H4eTTvyrXmoqVCl5M99bOaMJBYaGRteia4vDzR6ucc_6MErgmemtOXnnl
iE5UboMmamdiP0BxGDnWmotN9h2J2Una0_R5kS7cAwfnBhXzXiGRxMHYj9CDs9VYvXMILqgVAR4ZoGRiP8nsikrxfxt5dm1KjYEhweMRAcoLlw9iquwe_li4
5PrsmIjuuvRCqGzZphGbIc7djsHuYKno7qux-3_82wMAjFktfE8cT98FyBh8IOnkz_HVh_ExcuAZYIx3qt-zpjdZHhl_kEKMxUXnezr_t7ADTlAuqUu_Rhb7
EtdSQFSVjukqwuzRJThrn-qcxVRZLfLs-t7xEsdhGATzVkqjrixdyYbnbtRtSQjLk_9viCkqgwTashIhfqHjsjN7RRHpJPdsk7bALAQzRZvkTsdBtq9xT8Yw
V_UarsgB7_MXtJKbRjDkdXATL1jjfcJH3kQSDbCoQ0TJi_RFzivjwNcLXy7MQ3Iv_ol-Dsk_Cb_VcXXZ2EYuQU29i84MHuBzBkfgrbjfY_zMGkW5LmZSrm3Q
JAesmzZE85z9cvuH5VzYpX-uaK-RQHjvjXfj5j1E-aM0KwV9GnisM5gBDeqUsWGr8-rh7jfUFFn6ct3wI8Vszs_YpxJf6BOrjB4IRTwutcdVRwVPQBCtRJsc
BVgV6d_rnRWHTE1UchO0C-W9RS7CIEyGqIN0RWBuDq0NRYnCM_S--cdJVXUze_u3f_iZq5IqrKxRmKEjjFdryIlkfdhQrmFQ3XvgeytlV93IGIv0ss4-jT3c
fqiFRUT8bv-sFD5DAHtKchJrAIC8m8Tyna-NTZGtPwADJhJr8G4BttCqdAr2e7-legqFBEcm7hpDKg1xhw8TQO4_02YXTpPIx4ARSzRknVLAsiFIDyEmrwTD
Ir0SZWxjWTwsTz9M2ktuZVJEk8rCsYTBvfkRFT3e5RJpsqotfNzV_nF-NYv6Ez_SSCSfk1u9rwMTZnjk87IE02vBEn-t6mZS0MTLslcuvGP2HmiceesatsxY
iDjfNzY8zgMauUPkFNUYVIa1TZ9jhKlxOaA3taJRkjAs3bBBjsfZsamORSbp4cv0szkY_Fasr_rdMbABx0V12Kwleysan4tNf_LeCe1TQFi7lNvaujW3b5xt
ZsBcDmdTaz9A9q4ac5i0VpTgopMApDVuAjh2inknbLYSzlfdolJugV9fPa7dhd4PsaB0PWylLUT0mcNE0ZFISJxqGw1dsz16g9zu6aautybh16X7Rl6aXIYe
lRmSRSPiXUTEv7Hbl8fegvaskY_UQCEbHMWZqBkDQECAqauxKmORBgn16-kyoF7GzZUXFat6bj-QD99mxXh5fheiURyVupKSO0M2dpPZj6EB8tu_YmdT6ChH
gmLeLwmbUNk0v9rrK-qTMOdata_0iwZ746qsrfMIisESbRQS_vVsuyQZF8UUDTDWTQ74sJ8-Qoq3FNrG3z1b8YjIIvb2FXk9V0mRjol1xxKkYV2V5kldW77S
yL4XNnrNwGhGhWub_50kzMzzvoRdx_JuX_AgvbgPsXf7FlGAIJIwEOqshKngxHb-eO8Nes99sfYe43l6l3V12bLR6lonGuMdRrIb5KhpuBvQ9FqZ1oz36zSi
k7aDaPLg6aTe26mkyHffqf9LOEsgK5BF6o-pTdm44yYRRsCBsYZeGHbkAvTciGidiJP0afZHt5ff4kZ2eTnCDS_OPBcreOBIgMx15iBjld-Szm-pXuboF4kj
pJvzX7wAHPeenwlGsdGFO7ymOhyyYPNMb6oxTTvH8qwqLYYrThodT5oyFkruOz6Zg_J40BwVTlxX4N_ad-UT_rNMPeSS1ISfpeARLTPMXxxAUxMYVLZVsc5p
qzq0TEm4wPYKCi7Q0MEcVmSwc9iVY94_i_vqQQ6rm-PcmyD2j1_tc_BROejhmRuK6nx8MEBmYndWkBItFB33vcRRmr8Ft7p-VabMBMpG9VetFdDqw0pRtfsA
HM3xAnJwXmR3tM7hUu4nu6V9Rh0lT2rcfI1kjh_p6kcmwO0T3YL0-yD2R3xB9-zpPpNi86r0UZWq-1Yt9Baw2iUbu-88Gnlwe48FI-csmZLKTC9kfmqfkg95
0UqosD3phuDwZ3E-YtRdxKRvMFldD7eJRNJ-lLanHd2qObtQTCn5scb37Tk3PDhLi2F05Ek0ChSz6HZ0gPlQ3FG8lLl4nB29-Wp9a7zYpp_JVsGXRBY3Y5z1
9mgfk2y4kXeJtQpZrlPBB3XpL0CR32S2PWnum-jWnySLkwKq8XDtFMmmmbeaVWUaf1PoOTZgR6kbhBJv3jpgdfdfe1q4pXV01lhmILkRSN7SofXmAcybB2wC
MpbpUsHE7iX5SIjf7QKHV-Rdah2Xj8q0vJMTg-5M07NOt76HM6jH0sM7g6I_h0CR6h2dI3Su64lXhUmBMXDkmV7f8sS1OVzEDXy1FxITl0NyefHjemvj3sy9
lN-VExJDG7b8duZIyTSWaf94EigP-IFA4GkEtvv04XOFy8HQB2UYI0JkrUXKKFW6V3rgVEuxrNZbYIWnOA0Q4kI9A75laYqNduWIfiMMYqz4YTCYAKa4R8oe
VL37TIAAHZdpH1G9jg1u8iXGWGVrK947TLL4ENdnH1GHzYhXH92HEgX7IbF2jd4wgL8sJYTmqyRf16xOMwMzm_O99RJtQc_Q9vJOYuLZxP7QU4PoGedirSA-
WUIOsrukx6hjOsvxlR2djO-vRGDXHsiVSziMmdxMFkQsNNIiFLBS2_Q99RQHSAmzKjm7zeabjfkEjKSAIzC69Fr-y9quiUIBn13hMzjd1mxfAXOPG7qNEJFh
QmgH_PhEWxe1UBpjEAWT4WEDdnSte7NFE7dQVcpj5Xbkl0xg5f483KcS2D8eaGJ-R3dLqdOSMw-x9G1Gluia3kgRc1iGH3PN4Jkq8ouL0xO-jDlHaGTrloof
fiSAwTfJ0pT76R6rmCog0UGoWKJ-kq7FgoWm6G6f1QpDOGKhcFdj-SHP03ko7SGH04ZDItji7HQEgk6i5rlRZm8SLLC7v7JJFmslBaIciyuWJkkWYhrxCe5r
zkCj-zj770IPpxflwcGbxJW7Zc3TZxWa4MMqunZ84QZznFCTZjgwdMH1PJ-mh4v1UJrhKEDBPhF8tHeTGTfVA1C8c0cyIqD9Fyi19AL_KXO9JFQ7VjIPc_iT
e62TkM7RuMRTJic6vuDePRXjFzoqCjos7swM_Tz96nuGGc5-tWztNOAclK4e6SxadhGDHLq6jUEPMzGP3FGYruRdykiQGDiED-jEgcE_CWYik_-6PH3gKWVt
AuF0ki5bxv9g9s7Oh0f8yRHWim8th4rKtAp0ZMeJbHPQsQmVEh7PspPKktBcNeMoKBnDeRsgagauSZfWxs1kbHKD4EorOlLOPl0nhuzRPGqGxDrY-L0cgr0N
23Eu2wX3NMMkGQYFy3VeewEZ_m8
}

sprite $BotnetDdos [367x340/16z] {
xDo5ZGD104FHiInh-g_uEComFlglW_oiF1iSluGastatLvB4jgNn992SP5wIs0zLXvJCsyGUjuESUQ-RhdD8cO-onnMWP3v7h74EbFbSbUAqxXUdzKeyMeYz
Ut92dWsDu5pO_U34NZ6nkqpilnMSs0GlnYQuvpUBsP4gioDFHt3D7oDYHwhC4LaLiTfLPaYgp91qcI6fChT_LMP8kaJjAZFRLUR-hyeSabMcTbKu9Aj2xIvH
kqhKhXArgqJjAb6xIjHk2gzktaGQ7sJJUukM_n3NflTAdX-xF5Z-pxLz-eIWjmkNDhrNN7ZSZU2YThDtnc-mO6qbk_-YGUyiLbivzImSZnN9de_mVvkIL_RE
HKbMLel1fb8ft_-9pttsFWvjUj41kt66kloN7cNn4GA80i-NFEbvSqH0-5cqPMzCmnjZOiAFCcw3pFF680teHre9EzNFOVq9Vsa_b36_NmZHUVlwTe99Li8I
3Xt_7uzcnFlPYIQ9koW_7GWrqcGKng-LVALZunBm5_wG0F6ZffCiDtSUDfwYX262q8yITmSFp0cITwCTpWevEKpyd2TJEO-Sjtx5tSDZPnWfxZFazlnUCLTe
FqhX-2TAvFqhRg7zM49jR4oamLlJtklY5Xv6mbRCIgAzGp-PYriuTJNY-rDotSHEE0lt2ssS1MPOkxVS9ta9EgIDIXKnaFTznQtIZVcjWqIXZd23mU3-3YzH
yxHF1UdALCaYykOiBs5PsWVzeN1hhIll_NhSxJInAc-iFfNdzLuYDD8syZPkig2yDGit3BAciilo3fea5nHtxYLifDqZRmGYkGrker53csUNJiADrJhAtBfX
RUovcp1GYUudRZzu41eZCRPl-yebvRtFisulBzgBDGUt5X1tRDsUjkaiBUuLvSqhhPk53PSq5pSNzXBVbpdQmSWZmwr5n9ttb3Iv5d7ck7UiB6xVsNdQ_deK
fgohoHiJSNlQhxi9mtPvCozHYxjTwPL44dzIEROSDzRs4j_OMsqJvGA3f8pu5tCJJCJDSSCl7A37IbdVI_p0H1YY3N8CRYpzfDitTWb31KB53LFtiUwZ-eHf
Ik9wk3aLTrNM0C2l15mGE-w4kygObFHGVHK38fV3_PPDMm1APVyNYU5gqMs6WO8bBLM1782A60hy7buYH5lS-yTG8eUL0GlWpeJz6f32uVnS1VTri3T4WtTF
2bh2l36tVqIqWu3Ef3kccQxi9SB9XDNJhfjtMwyaew9WMTp2cLFHqAxgxmItlhSeVJnkJO6DlvnCHcKWShN0bql3wt5FW0tg3n0P47KWiWztXHTvQusUqiFM
_-lFULOT21pkuEFMzQoRZyTZ1rE9bnHX7VremtV6BPpSpUGIcxTVbyCdzvKQ9steL3Vx3Dmqkm8L4rV2BPpFwehYbYJL9pf-TDXV9YqqCA4ZQcat3_Z0GbzP
VXiETyHD2zJaKJY3mKhvl1BHAsyjCmx4mKSSRXOdeQoPDqqbehTKYmnCzEmU_cVQZiJZXidrAwoRuTP1shuS9z9slDseZzOmqEacM04tdz_045JNG4cFSSFg
01-AMo5jzU_xAX-GwIih6zAW3pS_7pUTaJodqjjt7oFb5tsVyNrmgq5Z_gQ_W3HsVAX6cxC-4tU-qxp_cnVATuARnHrI-leaVJfkjBGDK_MFl6XwFvPhUZtS
dYHBPT3PJv14uzuUz_v3SClJzf-xj_94fJzfbptvKt2ZCFcdGOTll9oysw598MfzCcxCsA-ue5IwQGPEXYObSREpO1-D-uoYVoxRYabse7A6UwllCCWRu2xA
Ay3jrjrLoNtVReJxS5M26xQqUdWHEyIzxKlXpiMDXnde6r5su4OWxfLn-_9wt4VPO-l07OXxJTmTugOSxlyaDB3zS2OGzvAurJ48F7lm_D9ae2nkt0atEyHz
XXkLe0oIOkuVYdiBSBlWJvk2NbbXgj8sXLfb4jygioWlvyC-oU2kqEOzS9UVncrcaPOln6J47T1U3RVtJXXdi8a6Tu6sAzBAPkB5tVILmUdy1N5pZUyNrA-4
WhWTxXtT4HdQ8hODXAcH1N0xzQemfRFUuyLja1HeSRyRRXIdT7ZbjHuQUsLA-_su6PYt4RUPubdUT4jn0UrrNbfhCQaYRi5bGXED6NAqlu01xUjnumNSA3ft
Bs_8qMvn_-_6MEZ4EGIxfxafFWjljhQmFO_s1ZXOqmfRcWmxJU7uqty0qjSgyHJspkUuzvNEztlDwbGGDmkJ3v4a9JzmyBYv4cwz5fvyH_c50k4dsaOPmd-p
aodAqX_wEIdfY0JVLyUmvyvgFe1O1ZV7l979Peg30o_aujwUKT82soFXPSNHV1E3__mkD7-SICy8EtXv-aDn-rD1ZZThvSU0zjU_cBrarpdeUOzvjrxIzlZ1
e85VK0phTOunruXlAld4NHa8xy-_Dgo9p4gkmHsJK7DzAp14UHo7a2TorXUlbSxYGYmBKcOd-j2uTUAmqD-fAQ1bTYN5W0a87laIKSJjrta50pjCsofxqp-a
S0ODhrUcOPqdVZXk7opEJ1v1ts1WhuaRuy8bDU10O1LOB-ib6yRgWrHok8r4otfvt9k6DqYGwlvaMY8GXBc4b-Jbu1aZaCwyFMZJ4I-E6zF31Xyd0Cyv0vDm
RszAdwiII8N-Th5ZYZG4juZXgFtRH77OIxe9_ggF78VQ3zxpjAsD-ulE0EGq2qNBuixTvBInYxtE0g2XFHKtj_NaxRrLuX-fuuGnfSCGlGMBESDkh8sRpzvq
a_WdIJhWCxHd3KosDoPDnxrLcpPxhr_mN7vCmEtDmDDkVy9YulPf8cuPNeRst9wIxyMj6BSSRfy53EqTTyID2RYBm0HRwNEiUzkMbRUXMUZiP68m5yVYNbRU
rPqKvGiEzpll9Uxyy0y-dL70q_PET1Tnvsu2Wyjtba9r7t2z0pT0u3etoN5xUNCpj6TQj-FGUXlvKV9cUUjAMTgNMJShi6Ux3y9b4VN9MsZADWjtiCjo31p0
Q7atB0loPgsUPtW9QxHpu92C7I4rxxgy1LkskIiv9TevR-Z9nOfmRwhAMp2PnbwIYpkur8YNe-IjhKFUHzW8AdAYk7FUD1TVAM_OeEPRDmkWSjuqd69vio9l
usw1bymGTxxcHdTrBkz2fAh5b7j9BkwSjmULoxiGAuoqh_EIVbBPnfF-QWQbiDSB9TYvb-JYZkNDGW2PdSXb9S47v2ExaZOAHSqQ24RQINkigW1J-nUBUyY3
8qGDHAcyso10KZfzRLj1Vp3TId9vbq3bK_d13n-twyND4ILbNsrnFczychX7dal7JawQLHm8XlVRQMDCA-cjBKmf47GoWF4bqcLMWZ7jcDs1SFXtKO3yBjll
5pT6V6S2G3srbKjAH8DQPbTpZ-Oosjn3tA3qOYW8YoQI041AqV6YlCfA68qAG4MrnNr2AlFMThMLA9baI47LftQI7msjxM8hWSB3nFCXypwLjvCl9zIv9knN
rC1ESEDTlBbTPDm9CMKHCgZpSEyPkfgORoLyNJ3GoCQcVM92Ms99s2wadH1JrlwLTDSv0f3IjCR5EU_fXMuQsNSEOHfjJSY3eHYtWFVKDfwd6HMQwW51I07l
WCGxIyPue2nUnzi3XwRdm93La8PFnhppJA79zPddGCCb9QvzUYA1msFQYRH1PK_UYB4ofE6zMk9WOMi65V4cl3dSfZ072da3tcnC94_Jc12By-QC_fSJfoHS
cJVdZ7LGm1tRk5Qb3MemaSaA95VapK3OkRnpubgEDZJLf3GtVYv56vo5GzSylzD2jA4BLaPO9eUDt7zJXdj3pqBXB_74JQezSReU-9ja01hMeSH_SNlWmid2
nZ_REnCSnu4O1eee4Fx_Y_S-1bTdnkb8ZgLwGRQMPdS23ErH-1LuAD16iM0Ylk7b7XW0BKnFgHIij4sfbAoqYMFO_uACAHKRIV4V2N35oZgtTxqupGGRipsb
OiKZ1Ddhcj0WrmiWUygKNgxNDpLRiMPAvMbT0Wn8aGCqAEnBmRZE1SPrBhZ1uJYbilLmd5AP4bc2ntKkZEjSBkmQnUtm17lgn75JT4dTH29Jtef4fhpZjcYw
99NkkgTDuiPemfrARztJ9d5hr3dS4--uEUeRxebtt1vDk5CPtQamjbCPtQcee-svd4GJr2_S4-zeWoRSgT3BzjH9j48JxbHeOtjyEnAP-ZRnB99j7pOmyNx8
SvBa4_zzbSX7DMZZHsTSlyIu_5x7h_1n8T2ke7Y2_IbWpuVtkDvdN7wh2wRiuyfufLoVIuecs2UKBrolyRW-unpzCysN7agDwmrKwPRmRpvcu4JdpJZZ6NM6
tS4UtMjrHkFw3qefOBFuwjY9j5_lg0zsFKxyQHezuThYTHBIdZQIRF-6a7rwSa5-hGF1EtG9QUDFl7mzGt3nS9Ev9KB6LG4k7ExStHQIuWPk4-xr6qlILdZ0
JPhRAnLibPscdE8kEM-2r7qfuSlSkOk6jaWUyn9SuVkxoaRDH8BhZSfj6zNhFh_M1_aJhb1QuCLJjb0mbqjTXJkrHCwVPBOKsw0gtqvolKOid2ywiq9uQNbx
ema1-2U_JoORBJ9T95nryIRU6Bb0jzhgZg3WtqnBtUUpHkqntItWH9blHJ_VgZob-_akl1L5zFDT-7AGwEVRTM_g8_hv9lOXt55tK7TS2TnkQ9_g_gJNhWBL
3xHx_QM_Yoy7wlNI3bMVLis65IZMxMQh8QuzhTHiW4Z5DrytcyIXr7Qesm1HyTs0PkyIe_YmwhQkLToUwcKxL7plfTbod8k_PT3ATltZJ1FRwyTPPH_0YZj3
zTCiAcNN-xPgrjDiHGCWKVRmMtXkleRBcnw-0m
}

sprite $BYODThreat [366x341/16z] {
xDW7hkr028DXm67O_ufVkRqt9bOkyhU2er_8qHdx9TmToF_gGVu306woBJCowrC9m1haeVENvKyENTmpwuVoEyNbIUcpY-keQnF06fIQ7bof-y75iqv3sN2b
Vf2m1sfD07kWrWHQSD1QgpUA3T26C05gpGIeDHFKcWhwE591Xyq47JOLTDXCq65JGOVD11rsctfdiIYtrtMbLeJA5Pi9ccmcQBAPKh6PKfDDvOhD1CLcWc8p
GR6PeDXCK6mcA3OJ59i9Yiq4nMPonNwRSdlnw8cgU9GxQm1ej9cWs4oksCyeTysHyx-GjOvmsyBZMDM1wJjok6tbHpNuwDYuseyQFDehx1InHautgYEl-3M1
OZDp-yWTMMudyZLjIr0TOQSAmfOCsP5OZIupjwHQtFgfufmtznntsii-X7vjMuEE6zM2I__2QRN3JXTptajm_STDd_DUKar6CERj5ODgN_-uQthj773QvDf3
Zhjsrewjx57DE6xih1srLH3-x7BzPUyERoC8GXWA6o6B_ZjE3qaETEFtIlZ4prdl96ZxWTDUrNxYk2T3sm-SzgRs2ySzAThMVHsZFQNp9aVRkgu3j4-E6-tM
SPEaRTtMKTfJEcsojAtBEanxj1ZQfSCcJTkwg-EqfpAqqPuyRUkg3jIUIj16UnArhPigKdjqKsTgbqvofhPrqg2zLuTgJxskZRPJjQs31kszEbPxj1ZQfVMS
gzrQRtAr_RGssXMiFTgkaxNhPMsqdQnjBJTlQgEDTaLhZtRhREr26ssq_oDdQ_UxscXFjhQ_J1jjjD56kyAr1ssqqKORRRJHHXjjjD566ssqqKORRRJHHll_
2jSsscYZ_G_nmk7FeOqsshm3V5KRRLxBlwgDDj_Tx8LsyxqascZ_ELO5wbLjDXpO9rcCfQDdjT5cCsszOWzm9ROk3tAgTh-kZNQbQcipjkLFSgPsF_e75lu9
WhQESg9s9sYZNOdQEYjGktMMqLwiyhHrcDEqEqKRxKhJrcdEqcwTLbdQEksdlJjBRfY7OG1C145w_nF_-xweeu0H4vDuTyRpbOKTrLOZMcapYgFHFXXqqexo
w6BQ_cW308g7krxxo6ZZz-aJNoAkBjhSi7vPpwEBziRJUhRt_tUHUcXp0zloXhJe8exsoe6xrjySV4djVRIKstH-Up17Uwt0JUprmRg-DgsR1UvXhn_EmlMr
uRqzm3tiDRUkhattLGquItnQ3BUdZKTgaACThhQibskOEznn80MZRTokhux6jRNTp_O_mnZkSktyqVO_X3jDT05j4zjixgtBBA-hZPnNHv5vcTLLjPcq2AfO
HNj4kAfs4lPwkB5xDA-fpIJijJQtVpLqJ9jtwKv3EnVRhX9W_uU5GzfyVFsI1mzeszZhpmAa9tyrU4Jx_kTXTqlR7srQDpUWh1SrTK2R2unb2h0NdmR9VIqM
1xHJ3ZnmqxRyE2W32I_NnjFlYkPyht70j3vq_snu9MqQBRBGPjvtMbsdIRWSx6Ur8VDBhTybsBqbsRyfGM9fFmacxpPPaSHzsrNR_odTqdxVw71zsTh-oJ2U
Ohjj7CQaKuASfLlvsZxtuvd7YOJOo2C56muNl7LffTKQOYSttk-ynKvWOllMN_IVZcCEjzxhgNukh8tHn9STmXYaZGgsSdD_zf3BbBL1gEXpFn0l31u6jcij
4aXzlPHqkVK-FOBSiTRYD9B0cS9TZuq48HhQYz3YVjnUrDcFfx6HuxFGpgfmrhx-wI_vGsagYturGnfVAk-8rE3-v8q_KkSG2sqxn8fxdSVzXYJfs_tnB8jo
GRIi4ZzyWhi-CAZTuVORXH-73HdMpd3x8V51re8rrlvrqey-25ilxgYjSXM2fNYVF1UCBMx1-Cl5HB71BSGVeG4-sjzw2uY_nMYKqLvwIyZwUzXeBmj20k9_
mm7tbe10Kh-4N41lDyg4vvRO9egzE8qoGUnc6aKYy2SSG58L2_VWvQaH_nEGIfpiQHHz2mOgexEdKGHZtXO7JwEuMjJoM_WqoffwFoGbYJlIqoWwnJMD8fsY
daOHuWF3eJuQSAYFXfphuj5mhej70qw3d0o6-cI6-cHqWNL-ArCbYdCPRSPLe-P5CjfnsM2Av6HwQq-Ln8M3pgCzmusOuPwlDadfMoHJ9N7neEjept37vOEU
ept37Gs2ZgCzmnqjWdwZFSCTNJAZVJBiXJrT4es26UsJOP-LrkaIHA-WIOzCbyZN1YJfIn8vNV9TF2EewdV5F-5wSF_CoQ7-BaJUgVDDgRcmhWFtnmGprXkL
OfyxXZeB7FoevG18NsySaVQSQCPwJzmxTmprFZc1nJy0NmJJ8Cz6zKi282b9905hh6T3orqvaJ2eHtjVZZIeHtkVZXphduDJowDSKBV9mSLHEjIYNZbnv0bi
7bs9PW1wUXS5llXlaAG-e4XuQiiRw6K2HyHPWEri3i8N3ROXVbZx0FNIs__yG-8g66sNWZorfmwe9aMY1GLJhO-9CqgAn9SW3rXdYqULjWz1djsN2-GxZ3RA
zYVZ2UiqSL4aRUt2VJj9c_hqZDFKhjstayoYFjJZAkrjtm7KyLrOoQBfLW7rvZ-KaOZt-LS4fLMIDt80IUcloYA1Dti85tN3pNuFFRDkk17jk1bMs5OxGiUr
WtsrWuRsSUw8TjoCCkxemrs_yAg6hx-Xx0BDwCTTztsMqOwRaHUovJktg1imKkrsIc3jVG70Lcyui_g-e9LsgFXAfLvRhXHt9tfjbO3Ycp2rqWxLtXQW4tRz
XKgzj5bxeK8dxFhgLACzuEgh4ytsRbBjWYTROGUA5uNK2Jj2nKlvweGTiB7pkH6N3Qj_bxbuEge7j-9WM61ToLqzNUJY2Ush1UymNIYKhXgkGzGJ_0azcKn-
1
}

sprite $EmptyThreat [366x342/16z] {
xDk7ZHjH60DX4GJn-g_OEMTxptD1yvKm8FvLl3qJITgzTJxPjhwHsmDHqktyrjhUBb2wdR-oVncwaktye_rDSVr5wQl57VLv8C0XDpKGtDH_4LpP-M-86sxg
pqOCtDQVVUvjQu8Nl5XhU_VGMcy8gRKrgRKrgRP6rOSZgWwRL8UDgiCcrM6Zwh19TTYNsNk7OkwSfsjU4LICJQedcrHFDcd69isJZOgnIJKsgSOcrTYa6fjK
OvDgR5ADJQgnIJKsASR-CNFdSFo8wd3ClVC2rADDgh59CJOfFY51ymb9gdU456EJFDgaEMrIZKsATmGqfqsgiKdnZe3cj4anDidQf1gR51-He3bjKfmsQ4wR
5ASDcjCcnMc3vhH9STgWEMrId3PeJfiKfmsQqoR5sg1wI41psgGuRT2SDidQf7X8G7FQf5WR50y9Q7SmRSTjRTRXU4foxfA7X1J_P0sQPniq3mafrWR5imsQ
Pniq3md9sgHuja7rR8DcRT3yI8haGv8KQuFYInBGV4XQszg-9BdEXoGfrhQsjNq1U5cj3Qel046pjhMV6MjRE-VEMHjWRMjRszhMjhQrhMtjUs5jQrlRsjQs
jhMjRMq_txxEsjQsjhzmkCxQrhQslmCaMHlah-L9reRvSflaInBIh4snDiV7PAmDkk5yIKAQPvjXRLnzI8BYGvBaGv8qppR2shnujacURT8y9A3uQXiKppPf
7XA4jNdna92SDcdM1iL3GfhJHbYR5my9QKuR5ATDSjgaMHiK3mbfJliRUOiOjzFEpdklsplJNObP68PY7Ldp_a_yxVl2lJGPc3Rn_wBgr3Xq8JLwhxdRslB2
4J5pjxL9gwkIQfkR1TWXth8dMKJJdd5WbVKN1pViEGOYdmwpOEwszXfkld6m6_PGuEZv5NEzPObYkmTOWpt7xSwHsDMQ9x-BcNj4QNlDslEBxRPswd9zVhIA
MpjzZFdHRci71s4bYHfsCBcNoYnrLtyi3nCliwvgRQLi8V5QxgjeYLJA7D7gqPIqjd8IYUMfuOPzCKgazOkbUZcYw5YIVN5gKCtQX1Otmg6DccxOtnrDTdHR
h4hj-_NruUICK5ET-nhvyiMJayw6AZd2zQb2thLt2TZovM2I4yz75KBRrqTKxWdfyIjj8hYoBp_FpX4vCgJJ9niFXgq8BWtU46r-AcmvE6Rqh7WaRl9PlvnI
qz3ZAgKdgA-Ah8mrpyBjNDO6ANNEmuDmAzVMNatOTU0y1BQSM0NyjkB24s0hXyyoxVK8v-wmvJGgxyjNk3DkJL1VbzvPpT1TSMl2EY2_-KQ4M-9M07NKtF54
uNQmvG3hYBdZ0js8jHMoTRnEnkKRmVQ6wil2jUSel3lxWh64smgiwreU2xYjyOS806_QN_AsDFwcGA8qxIblMrdlmvhsD21i_GjrMg9qAq41_aKm0RsSA2rk
y7ku_c_BbaJfFubqejX8VuAJ09_esoWUZ_f__IbmehCxKQolxUQCpEv4iG9-yuAnEr6iWD-iwT6TA75Z0hRD2kbE5E_2rObYxqBTYMAD6uf6lLMYKMyLT5tS
AhekRfNe1DafDUgTQjJzivQDh3jAFFQfQJEUAXSFagOz7YjraEnKRTeT9UF1KcLhjxarsjnzQvEaka7IKJ8UBbMrTfjxF5wgQUqszoWWLRHsctkKaEfPkyqz
ggYjlLFKWjrPCWf9RUsTeiwJriuIZLfIaHpfB76SjcJRBzlGMVALOepacyqL-NLOa7ZcqAY_4iexTJuKDNvzZb2QJTIsNeYKyBchKMS15xTw723xzS4oX7tY
jlKQyTYvgr6l8qUQ_01y8dM2N9NFFn8GODk0j63h6kAjWM1G07NJNYS70THDUnqTDEkyAidQPPLVDRNnuIWHrCRlT1pS9aY-pO4X-N8N1Txy3X9yWo1XLyiR
-Uq4m9zjRJOs1s77otNmvzBUsuU5Duo_YRWFM3kA0dRrr14k4YIUe22LzJRYZ2D14YS16rXd4n-dQCT1mDw-N89FiBQEzITZ1-iquiP0cFR1lfqGHhtRutm8
RL_Y05ceD-MuZ-Psd8FmzYwiSCZTFe1wyOSoDlgSNn4SZP8yoqc0_LVA1kd3FiBLENDJxwDdpfbRennkHaWKtdBX_TEPkhG7-yEJmjiIsL-gg4jxS9i7howu
_Kt72ZIZ7kvpzxECShWPUOAIUsvrpc3WSfqIEBika2YrmvdJwu9Ij8SFLohNQhboE3jLgrM23Y_2N8hsyDbbWIh1Fb-eN8isPmkLAi4-7vqkr0FkV7IgMEyc
dttWIIdOGuSV2hbMLp8VVfJlIh27mh3pSMiyLfoUoqo-Zgg1ssEZEC3w9ExJxeB95zfFapx1NJf8-fIvDg5k7V9MgzLg_GW
}

sprite $ExploitRedirection [367x341/16z] {
xDW7QWL130JH5ONG_K_ix24uRsYdUYSmnT0h_-sNg2heUxFq7O3Qpg8gkkT33Mn7Q8N-jDxrr5NLFJlrbv9hH-fzoLNqd0IsJ_5P9uexrxDSMrpLSvdCZjjw
QRO4OoyhkB4pi3YJ1CQE0cD7WR6Zm0za5CREmXtvxS5zslOEnZPupK-2JpiBdtOK7YHPU914uP14jKEILLuaKJZRKJZRKUriHxMriyhQKLWx2W_0AAmTXRMZ
i7OKrex2coGAQqTXxQYoTbHPEwdznVLrzfw_00_kA1pkgB9sLFcPJ6e_ar4u9L5bxIY7EwgzkADmIgBAshis659pufGSU13uk7TV60JcnAk48u-YVTnVL8V-
qBBsWM35x_zdvrTTS_psh-LjU-UINBqAn61KAXNxt_6zcVrlJ1hK1zmQvpZmMHOlWq_RwgIpu-IuiGfFRYrv0EvGaL6qWxGWaxqBztonKRJ3iEYpjn-tjE_k
SVi6Mnn6c_kU5c7_awcpS7DVFD6IXBY2TfmtMqZGKVRc5YGopcZm97llCI2S4neynzxSP0mwfuzuZBrZleZ7YT4qEZsvut52PqLmnbJWFW2qhcppZ5xWFW3U
nLPTZRjvxKP-V9hiRSvWVhW_tTwCu8vVts-U8zRCDhLVz5S7BL7OZXjEslpmnf81tF5_aJm-ziinToc3kSyOoCCnDGydxVGqoLy9eIDASC0Ycca5GFlDpNuB
xhWNyKcqk_Apn1ydYTikyd2xU6kdkN78wvd6FG0RQTEocS5VJW7jJmBQK9YeC7vKmDe7u1w8_5cI-fT4aiJJEC5CgIGIWzjuGfh8kcFqOPHmof3iv-3sxj35
p-pc-6df5pXq-CQ-EPAOppT5hPsFcts3E0ulViS1QpykSm3kU4qmj9QUfnHEEvN0Vdu89w9a18Z77RhXFiy24r4ok2fqt9aow6PxQnGsUegR1nxXG_FnE1oP
cm-V6QY7TH7kZcz5INjuJPvvWe-yfsqDNSL7VA1-9kw-JrmT9RrhxIEfct1tZ6ZF5uSHP-VZHjyeBOwIBqaddox8lbCCH8b5Tjp6wd3egEuM_BXjSJAi8Q_7
BLzzub5oFcvVEdAObYyu6TPNeMumT-7kU1Wbw0dITRZrC4fq9Mw_fUYCaiBTCJ5w3wjmwq6KiEVeniE-u8oImjtze_V23Kyn2hS_IWftE4eAjz_SXJjEkt0x
ewHmEyrTkAsq2xSzIbYuZUPcqojmuqDeDnHkMvIq_wN2RJFtbsg-sqcxiN3lVLpnyn-ebeQtcbi__m7gnGTRb7n9z-FMXqJ9br2u3L5IhsJQDhDoOMdgXMEC
_c_sYsjNRHRXS6Pg-c6JLBZ_ec6Kp1VdhqzaxJpZP9GyGHdRLPb_1a5-bFmiFNfWm4DnAprAVXQUyc7X3aR9k42BErLeRY4nIkOBjBWNs-p21qN966Bq8Ahy
ix-I1ZZuLhwj7QQn-ILpb8oTXPbdXeLxCEqQEDXkRGNG_89zPcfSMKor23pf744uQRU7VuOfG0oKyuIsKW191LzHutp4BKr4jWp9zpLtFCzE_b63-tW2RWHW
n-wiSYVksm6ukH89CvzIjHpPS6_kYZ6G9KR9PUxT3kCHNnP16ktUcPUBBKkU8WOyPd2EKNAqBhGqM3W0Dmn5XAdQC3oe1nHHhYOB1dERqcHBfq4fvk7LdtPs
rXo1gdZKKxyJ3pzljanfBswQXzEVZXjxSRih7wY9HrjnqpoWfi7SZZG9rDuO9pIOsv8cs7OhQQNDbYrj6yJJEp_7VW9kR4iJxsG_zuMYtzuCrD_XEAoi1RwK
Qs_kc_A7RNrXwiQ9IEmBSXg0ZJUqh0fGo6GBoN0RRfcMpYOk5GSU_lWtKnThun-AfssP3z0_yaYBgKXzKgHXLVYxrsAeyy49UnkbVma1si-fhNdwCForUehY
gBIoGUQk76N0tWPj-Im_9rmPuCqdnUSHk4CcyQo4y5dv-uShtFlX1AW0xuT-uMcueUuqT--AzPDuL6iPRTnfMGdXunBW9DnS44RJQQhWTCX9zXxcIDpSSNjp
udRX5DpiERIxWay8pcajOzkp5yq48DZOdXCdY7Y2YzubKt2TvfonfI8d3onxLpbu6PpJ-SRtJtdWAjeTWImvRcovYRQMh8C0yxSB_K8DlHt43KZVV3hOhnC6
j4CN0nMwNNfNb31oxw3m1bgyYhO2brip0E3jmHq2fi5lvvDDRp4t0yiSMjUGw1Mq8SjeQrmWt4qxViuFrYu2ykhW3W5Zq8vgz_B6H8vCu5x_He4kZX8eTWSP
mtqhRmvW6yqzVZtl4jhhZuvb3ukuhdl2zR2xbhLhubsyjPOrIM8Giy5GuKMqeHWbRcdLo4ju3umzBspgHF06tXYmdfV6kECnpjDfWwleS8mx7YeycZQquQhe
EqISoXi3rj4uwPl44taBWn09srjzbyZJU6jWx83e672JE8isrFT8fW6W-YaYA4CJp8bae_gragb_oQdZvTbBiPa1pftbpm3nmZq6Bg3zf42e5Ev_0vUmR3Mw
SFyp8oIW_LKiuj7r8PBIbyX_a9uEbHADf_MKr0AgK35y1R12HI9-o5Y0fEoqlmHUpnf_hpir-yiAbHWnp7sgi48bxaugOkqAbNbSdFfnXKeS5qb98cP-NA4Y
6wyA5Sd6ka95Q2UAnTehi5XxHLRZw1MhSVGAh12n2iNQgc9jbGwV-8-hsaireogysQxLwxEamhlTArIMM5MuhL9bYLCeSrjL_HAhL6CSf_3YB2bxjzk5ChTL
AdCxXJAtLIfpEuKojrKgSpk5ChTLAdCxXJAtLIpQLgcYn2cKkQrYJRnQfLfLS0flYPAA4yLn0vBK9P4L9qF5846dFIrGJnQniEGirbk8GuUr1v3wvuXOvHEX
ZFr4vAAoerWl8mxseOhrOua85ru5Un9vhEmerfCI-GDqW3DbHx7-flIbzDa1a9Gaaa0R2b1_aRZNfo93nYxSy-Z8nQmBDpGtDWFLNoYuPal9kB7FbtEkb17M
eZPwZbGtYDwPQNvp_adOkE0WNxx1lEwYq24vr6u4e3xTt3GU9aB3aZl8JyRjFRY56wvlGYw_kUCiADSfFEHhiaJ_O45ZxKaPQ0UonE8xwxiDf3wdpvrpqXRf
FSmBr4UO6scdcj41UnboKIJZk1EF_2GDhDTsMVWfk4MqUP6n--btUOif_NXLKFOJNCaiVyiPsD_xC8r4VCxN37BJP9tf09BIZvX50csFc3DFzTutgPc16-_T
9i0CX_756xpanztuNjoD0Tn-tkrzl9dNIgkzZpVoMcc-S9DSOZFDzZhUIXnfiRsEDnE_EDGk4V8S1bAlsthEP8S1VDLcQAR7vxjs-YiRjzvrHajsQuLt7Qo0
xAwO3Z2tEKuIcm-sovJTDtZPwLfCRgnuWBcTSSB4_z_k4vBJ4oyxNKl9OsWU42KcUolnVhFTAUNIRZ3GFi7UIYm0shLY-jFCu8q-dxVoIY2qkyNyCx_8DDP-
uIFi1MIpzhlBnRhqixbAfT9_
}

sprite $MaliciousDevice [366x342/16z] {
xTtRagDC3WHWPMHarFi_yPvt5HFU7njKAkgWl9x1-Ej4b6aQso81G4gIslyYIIG9gtHZfjI-HYGja8ex_nezANe5aDh3w8vu1IwTBLwbRfr2MY15dG1UrDdW
5QYbXR3q5BL7D4zPvuVcAUlyr0JdCEloPXiTicR8RjvbxI7BUcHOrZafRxO9mYhsoB2AlQXt5RkusIOBgzXhSLUnorjjL8eRRTwefiZGeB17XZMoHuOricSU
teLTt6pB18KzCYpiudwENTo5xM5X5tT7R05c1gh54zyyjyOM0lUfPMoU6sCpC7oIDi-TiGFSIPldvjWUjN3YcyUMs2rmMILryzZnGXG3bsTJDozR9o4Ev6gZ
hSmTQYS2sicRvtuV8GD7HlhckGZs7jeDMs7dJvB06NmHxl1WPUxSvaw_ErFuTu5j6kt6ZUP8_gSRXe-zhR0RCoS9utkunT3s88zRSUoc3QeTvCx7zd0BxFnX
aj26gP9tNJIe13CpS8zRgEADb2XTS0ShsIGfq8Lzi3qzkTbnMrXWZaI9-cs96zwEoTQN6szZUx01Tf0x7zkpW7QuHfm5kt43x2HkPPHWWrDa2hSoBd5fpMh7
goaH_mb9NSvO97HWaMh7kIN0Fl8dEN9sIqjLE_x9HC0FZnL4rcrNMAVQSMxXfvyu0zYhb9ijcPi_xWOJzmehL3l-ri0fAg3jgkt1V3k5xQhjcQy1shJQyVU6
RVzKkEL4GUmzoysM54vN06nNRGyNc6vLxSJTmgxQd76_kEaWeKM33KS9PyFsOBzHCX-s1xkLcrdOitBlfqth5UmrIcPVrNAdKSBf5xNQgDoSVqshVRJpiAST
tTggskQfSgThS_PzH7sq6VXD3ThjSRYSqDgpt-F-Y3WrjTNl5DGI8oRKUkLHqf8ZJaJjqIQ3nFW9ZlXty0jSVvGmuUI8zXaH3wNzdBk-jbhdNFmCHU8Rj2uU
BChbHqd6kkzQHY89m8q1aDBNRThgscpt8u3yleubUpylrtYrGtUpXBPmXSdFhSUjFLV_WlCFRWKEGF1xOSWEr1vTD_zMkC3OlYulxJFW8sd1FeFBTOvc7zpX
QKVzCWl9czAm_nzTDH-JQwFTZ2ubQHS1gH-WYPzsM0Y_c_bFahhS3EnhG5AI_YIMvAl2opXrM1ilQSSBGTq_DXzLJ6xz4KwkhNuVUCd60Tf0j-veWK-ItLyy
uIIqZxPcrOOcrqPx4awfpNOxYrnkPPvsVgyzc5lRGqwXxTPxQdlukhPRBw6j5WeJjFEfFLn2sqE-fEtMwsYt3c62TggrH-jeU_Y6DjWy9sXxo67QNklpj3qS
ektMwscZTSn0RRPEMLPR8xjzl3P7pksHsgMjqxKnKBkqRQGs3zVMK6qShirjjKlR3jV6M6sDqYxjqhPzjKkRHsjhO-tIneBQThYsIhkqUtouAMqbF9GXe1qF
kCtz93BFPDeUxA9jAsWRfjNEF-x6QvkskEiIYsXZLcta3vBnsZRdXvlI7fmT9mct-2idBQATSjeVlmJ44jhSH5jOG9jjNctizibTC__bDKw-1cZ3Sx2sR7Xq
hZPB-yTmJMsUgurrdxwzeBQza6ErPIz4fzwPnjB-DMrHRPogRQ_aqBlbPQz42_ub29FgaH-SgOsLjTjGRINixrAZ16lzBJ3NrkP0RIoiZUMUAi3r1ebdEMsj
LssFLjDkAsiZJesXLwN8zGQ9HmdMATeUQh5gUvHWdQJj0HVLHW9rG3k_uFPg5B1EqCukECsMApTXbg6TNt1xEO5Q9sWd5vpsSfHWdQ_j8LVIHc24BFSaVxE5
oer9xxfatse305ulDonLEv_xrhsoOeguuis0bA_Dw7lWZzOUlbVkwvKOihLvTTfWdsgpstaLGAZSkcw3ihKl7_UDQBKTE-uDwM8MyRasv5CzLTjtacdQxB9i
XBxyvmVQdzjLhlRry-mHnBvcOEI4pMVblh3sScTfy_ejCAFQ7aPMHmoVqjtQeu1szFJL0Hlj8emiHVLeMS8_g3_31EqBJV9EMn1RipEoxjUZPGdXrXvFcZOl
3Q2qEU91v1AVdgsvnQjtfYHjNZ5AxOTOL5kX_MJAZJmvsWDsZ2dBTG_JRkQEQu-_zozz6ndbLe8sNwssXw5jAEtU-RZsUEnuasuTzipWZcjZm7pZxSt4JxDg
NOA0TWusExs6OcUNd3zNHKzjjNY6_3e5T_yt4xY3siglDlgyCTu-D3I4sxLNmhuU9S1z5hG4xe2sMleSGNHRWFHGXOEuVuDG_Xg9eRS5AlHXHArJ6DP66u0T
s1gaw4S_j5vXK9kjHzHtKYbsu5aYTqYRQHCj0gROa4Ftj-aHdcih_oVETZ-A6I7XZNhuK1ivsF6NK6plcFybjlUrsVf4tOyTnNnakToDjxMXzE_qOeIhzu-V
kTpNsam_iA389XNIJkTklA4DfM97Nm76XD6cbkHzhOtqCpGKt6QBXHp1pGlj3El6X5E2kfpJY8ipPOAtQsTPDoKCAVQQiM8wjtkxTfPrKrzhaK3NOvxCulRm
GzifkWPzQwsC2KicBKmy_D1Ei6xeFQAOSpvZDdSZNTijSh3xRT-r-qPCulOG_sMHMlyWuMoWlFbAElTwWLFttogIwhSgDpAilTngEU6It4YWpYwtJnGkX-qd
WqNAxI7HredWjSxIJlRGGjWQSFRbZPyzrRQDMcPejxY5mBgk8hl1BKIVOLZQFteBwFM8jzA-zfRGw_TXfNqv82IWonEmAhJFWAJ-5HBezqoz2iSzbAaYYwOc
IkRpucgYI0GS3Y2fSNF40svF3VkBWDIWPdl8ywWze7hCx9eeGg1lWkK5t8uwq3S1bXpoH6eFIKdY7UcQA1h5LHD56aLT4qMm1SEY7Xgmg8U6hFFYqB3EYqC3
rWGP6HJro1JroAZDc87MDKfaurBQj5sZmmT9QTksGGsIaJbRkqQ9RHnKjKT6vwv8gjoolNFk8AbHOfi7frQxoctR1sTMkyfj1mGdLhlARKS4vrMxocsdfAez
CZmBksQ97HHKjKU6vrnfhLa2EoiuP8xKB55S6v2a9eciMV8jCIDeeMF5TtX5SEZ6nehQG_JRTKvAJRLvGdIh2QhMFuJijEyewbxWu5AN0o2rYICot1DLhU-9
n_OTHNsVdC2TBm3te2R8q-ZzIm8WASaB4AZrVc7gG129elOmV_QIHUtQgTOENjQjOTJbKPvBxHbuSPGHQb6PZIEN6IJw_TK0FNwA0fD_1qbgWK72KO-yWJ85
yiKvFRQG-bgopv2QLti4jOTPsyyNLqAriod8t1VmW3faaEY2WXdM-UAqb46IBq6cM_SNjopjV0XoXBK7v0pLnc1g3qTOTnCNHJ9FE_-vdMG2TMx7EOcs7ZcG
2TIPSrofSplV0TJmfx2IBxLRxr5xGEeAcfZdgmWi4hnCxG58oXMQ91AOx2PSl5TkddVJCzyhD-muRbeeF4xRe-7QndErZGdQQTosV3XSstYkjd6P2w-o3OA4
uPdYJJkF-xtFixJZk6cUmU2mFOBt2aRgk2SbyDrr0S0D1qcSMvQKexHDmK6I__gsKrwUdJYXsXwyl0ZJKTgcTvS5M01xenELpjBckoSgB82zqUZK0WkIVKOd
zgbslDooxF0eRCFB5uKKmDwgt7hlzMcR1W7iB6xOjk7Rnp83TqVjmIqR61vWxM5xkrsatw6zVJ13kx2STBnSWwWhBtMhKgbK_Wu
}

sprite $MaliciousDevice2 [366x340/16z] {
xTs9ZiCs3yHn3WO3lVyJzsxLDjXij9GfsPe_hkze0kDNXdQS81it2G2ftsl_94aaYN3Jc2crRnF9IEIwywVf9uFkW0uzcaR4tO1qLjn3tIP5HY9JbuEREW_k
e7PP5JlSr3tHoDsweEvjwugymLbcRM-swaZlaATvsxf7sheosheq-kHO6ZtObT63VLDl3xQvsJQB7knxSNkmxQrMbRdHzatU8gN1s9NHAxioUcLN9cDN9g_i
ql1OR4aaAI_lox2bttKb8Fu9DFS5sCIbYztS_70fojpJiSrTXKr_ehCUkmTppy9kqVCokHgRbxuBCZU7Znv-Lpa7k-52RNEZrMdx5bNxNmCF6itSgjFscPAj
JDlSRC_GRhWBTj5PqjojJjjdIjLfUtMpbMbxbx0zIxlTPMcdxafvTIV4D5_RgvkjJjkhkqtIzYx9UVdBzFEnwxIzImOEEAljNSAajh-DEGkxyTRQxMRQ6dYy
JvHfh9dQtYNfmrNRETrgj1ldhMqFTteus7eUxhGLPYqI3tTwEDXUyd1dh2PfUxZprwpj9GztRZ0nOxGztDdXUCNsSEUjcDyZ7kxquRAzvk5EModx11xkDf06
i3tSUIna7k_XPkg0eJQGxtFdNenijqht6crb7kzLadubGXxkJsC2-vRZVHjj8VSaNYMZrWblhn8ch6_gZTsr1SJtWRBssuQcEYVkLS9frZtIm_qpRM7Uqrfx
uF8wo-rLWjc3tPFVu0oDe28LlKe61f2JdzohP00xosrjNdn0AYgvIjPhnxtY3RJrdD-AvFwhvFxOFUskpITfO_ShRXPWio94HEo-k5MWhLRGk3QZl8hN6VRK
rZxQjFRyKA4TsbAxxNEIZ0EqyKnjMlljrEa4RKLnDGS2QrjRsroIdA3TeZQUhOr7QeUrmzhOv9uKZj3cCxLbxOXePslhG6rhnwsrhMrjL6bpJ-rsdhQrTMDj
QsCJRMjRczQsjhK_QnDjQriRTzQsjlRGjhQruw7QrhOs6JC3hFtDqP6O0zsb_Md2-_HpSu13qDRkvWG-LVxYzm6jFMeYaIJnPt-w_XL9_JdB0pT6_7sIL9je
MzlQF5iRpzMsDixMZigiNTpHsegwhCqeJW_LjhQrSR8seYvhHta7QolAqxdQVBQsjNckDg8ydAiT2pfMMx4WdQhDfsjR6wTgnv8ErLOiIMTgCvQ4CxKHTLax
5gKJjNc2jhLnedOiwq1jnh9axS9mddOiJATfynHjQ-CqxLYQpj9cB0rdQSVYZj9cB4xMBWmdQSVoT8usuwFmUt5DE4Vx8mwrFnCl4TSfsXomlcpFunJj-3PE
Ewz-lOjqXZO7i5FUaDxi8bgxEwIveMyUV8GsQ_u8EBzzCAtT5NBS_E31UhusKnSB7CVkAVuRdg-Ddq3rE8RzdbkFrCxlaHuc_Hd9d14HMmL-CGX9RKKadeDJ
XbknOKgCzjpBzHvd37TiMNjf_26pdsF2S3EsZ1D7kyVKSoZ_5WUrY6-AVuTXx1bRSyYA2nO997xrdrxx_4W6XuB3ivK_pQfIknyW-d_wvoWmLPkJRe8gT-Cw
VHKuOxtgY_yqJ_i3xFnmO_JHNABT-d-wHfkpi1iosoZ_ZdB6nnZyuZzbj4Unqwi46F-NXGLxMtZzJug9sddiNkvdnX6vNHBPW2__qsjuqvVQJ5r8lFS2rGPI
v7O9Oiju4NRZo-TXAMqa7hzF_FYYxSTUq8ot9tZMVHB4InamPQnRG_B5fRr7crEsI4-vJnQHVNdnRjYfwTJBGxDOQ4DnBsz0tMRwzyFqufFU16WFARwA6Qus
LplO7X4dBf7-b4ffFvQRqwnx2BRfsg6dOaF9vsovo4ToSxvrqvHp6l6uCwMcKVSuQyUAp-BMN6kHmDJNFFaWRimTQurks75mFWGR4uJOjMV69t1ZbdMlQyzD
l3itfb7tTDr-9U_CZKuzCNJj-H5tvKQtdfakVYF2Mt8ZJLq_t7sZy7ROKBSk7Uvy9Dfz4b9ZdJzFvjEDi5LmzkN0ltiknRlpN326k8N4TPrJ370ByKzCW5lx
Msy1yPyI6yNQRxqbpFeypDfl5uG4n9VHuBbFWq1IVqI-WHxUA8vrVnxEASRAR1I76CqRHIBGuG2IgjiZFV3nr8Wl0gcYoUwHvr7tGCtOsTueGcBUXFWuRnGX
CMy2ukB84wbx92M98zBUAAhYyaQHggYzKOIuOJHrQQ2fIoDzNYoDFY-M1dg3L0PJLsRgojHshD3QgqHHbxKPJqs7Bn9hnsE35qbbPsjxbSI3mycZxU56bENX
LZoxSnU9LqayF9mwsXxkU7muSxGzt750E76qFTnnH3Xlj3tSSKeUxSfu5hPtIHmKFDgLyPmxhTubYBF28Nl4kqHvRK2IcYJIk-IxSaRGpLuhK5iSEV78ILD_
5p7lqBafDTNsYPWs9l1OVn0vwTXXwbdWuArk1q1g6oSoFIVoM8-9vuuTfXud9p3o1y1xy0RvQLf_Im0a9VK1I8pry-Ab2q4a4jJM7fSZ4zJM7gSZRVrxgBez
odEfUuKtHvcX5dNbn96j81PWznY0Vlmh2hpuCqXIDrWahFh96-WoWH9nReyjHFHOyU4wgNsrAwXxlE3vYyHLFjfv2hBgDtL07R98z8Q2KwtBn1bB5abUWYom
dYqUgxJp46I5TG_a3gEDOkeUAwodYOiYkPEsCEP0fgchPvoRQEj73kGiwg8zhgLxE-y0glnNMCb5qwrgwl4_A2CH-_mfWiY4nTGzWAJqRsMHm6PVmiMwuUPv
Nthckk567CVDICNZj7igrmwUgnrCQ9Tpn-rZkNRmNEtWRMwyAXuG4ikpr9jn7lUwzxECuxWPlM9mn77SZBcHEkwN4hZskW3W0OkanzNN1KTfXnQVgNJ28kaj
tfquORHxM7mHfgEqGsil2t0IzleJbSxIvjeJ5Kx2NhywTS05oJwh4qUCTazhRtZoAEp0ufj2EW6xfyMtydKITY2DFPyRyTYu-hNCnBUZdi6jA8m7MFVOLayN
sR-X_VYmmtHXkNJzS1LHE-mExNu5
}

sprite $MaliciousInsider [338x342/16z] {
xTthSjj83uHXT7LruVwl-3iVl5EnGJeGY5Zz_jQkg2UO6L6EbLWQ09BwL_c_zCz84a2uYvAKb9UII7ufQylyLZfT7L2CvGrM1ohR4ldcckhJj2gWV5aYF9pj
aM_4cKEHvZHgFsT_j6Txf3dR8-pPdMZFzlWpE9cBeiUpFThJfeVdKbDxsfIvFDgpFNh1jqTxTaSl-FRuPWDgqrvFao9RiwaoJRftG6tA_CEZZ_Zsu07jZZwI
kgEFfFRe5TyT3TeTVSPt9tWBxOvUyTrn0QX9zu6QLAyw5S0R3wRoDUbd7FAyC_ryyGqRVi8XVyp_jNMPywJxGKyat7cmVW0fSe4e1ax8ALBckuWcvq7tY-ud
PRwJQ780zBr4avEW-qNt7q_8znDDJ87k5zrFYdnFqSG8w7xH_QHwNr4DWAuNtK_AV6VHv03eQj7zfCnt5qqsWreq4OsbHNj9PT7U0vzfqTQjb6dHLbAaHNkt
qhHexrPAY_QICYtQkfKYBTgxbSgYPsfUynPDDeDQDD7ynicYsJsY5bK3g4KxrdrQj7T8QT7UynvfqTvrBulshdkcHNlNVLgqg7j4BQhcOycYYUOHjQYQGIsQ
Q3wMBAhc4RLeidb4BPhT8sfHDe-eHRDxH2tAvX6rQ7QFg4NPFA8MJJIFg4NLFA8MpGAKEqHLjqOKUqSq6T-9kNdPqwBDGogBta_D5sVHX4NdXdJbbUqNJMm-
DU-NpyUrryQL8rgdlTT6_fbVTeurelMj7UlxrBr3cXRjlRcdHPkNVLgqTzd3eir3Ieis3sdsPb5Oj7dPqwBDGvgzMHGMRLxspEaayVDAKNwL5dpCesN_ybaX
MWO-lUp7EVj5pyWdx-qvwpaXEc-APqGPCI3w_7T13Gxeg6X0ponxpFqfpedEZod6drNnW6ZeYHrDGw2ZelEacjv6umoVLuhYy-8ifnhUHbaS6OrteJoUQtmZ
vJWeEk_hwwVZZnGzvhDFTFxTOVsSmoEAM_w_tYEnyirCJehU0yqeGjuZdLtsd1tHx1Uj5xv-aEWvBfmHFTziZMwa6btqEIYQUEOcPdJHyo95ZwY6HVC1qUmH
vLrH36wasFZMLqr_iHbFY79o6sNF9zFQAigzefaaFabTsqr_6Z_gbRFf2T6qQ6FT6un5qIzgKMuMjQX5QT7crFyQBPeMRSsYtGKisXksYrhKejmjQb6BShce
HIqghHArg4KjQb6BMZG7igX5jsRHEejQrA8MjQX5BIe2Y8W0IFscg4M5E2ANYsgng6vycQz5RtdMflwaf8wjlonYKI7Y3gb5QuWwMVIoA2DwI2rQWzQa_kbo
3GfG4acKf1QjGQ7yq8cgVQ9O9tfuVlqzER3epH5LzGZwRplMe2MfS3p0ekKZAx4FfDWc6hj46RT9vTziA1vubnJRHBL9b76LL8MuVqFi7D4R9pxyMumNHfI9
YZJ-rp9HB1KjILdzJotw4J6p9gsNlR-nuEE8rgHOAXfxH7Kyx20jj7Q8xlek7Hul_oJzL4jhHBLK57c9T41q_pTewSPtmHMan-CNYMApw4cwNHJxHK_IvQBn
hpQA5gJBHRLRz2JTBAgjeiY2TAieZ-lVzUwf9WsBthXdAaYNliEF_xHIj2RbeRL8LEi-AK4MfDi-UpgthNsVvgacPRsDMbGVnguYtVM9ytc52t_Ef8eKotug
Kb_-l6ZzCsF4h-8MKHNND29QNrDDcbj46VyB6qHFCbqavGhHy-BMY2fka-OQqVYGjeWcYkbJ776DAED3M2Egk4cQEqLZwz_8PVK0xH6DlwGreYSf3o8KuZEY
zUBXl6YzbPwe4kAyx3sYZB-4MT6Qz0metjiFYzPNhKMYYRWKSfDeR1EzJyhS9CeumYhHP0Feh2ZYJ9j4Qr8eTud6Qj7Qb9d3elUl5hj41Nm5gWMYvSwlHQ92
586xHECNOLAqvjn_rjTRr0BHmdFlE_puPTeWohWL1qNlNpMU5nNYRbmi6bhmy_hxSO5eSMsZelM00k2_moVYUbgKyKaO5gql2z8XH9QZC2yQdwO7HNdvHfCi
IAT56P-6vqHvwxwTE4cNYeQU4aNXMGugdnDLV14U4aNbMKy67XDbV9KU4MKvRZV-it7H-3ACYvuo-FQNll8PKSRNFI3A6mDQ_hVpeb6aAT4QvJwf7X1b565S
j02zyuhmW6YKSLYKntCta4wACke6HFj0p_-5faNZGXmLBPxuDkcmAEDAawAy1rhVSN5MD2x5GT5Z2smWrQGeureZekSLTTrQOr8qBiO1qHE2RSEYEL76rJGa
oWEqPTrZJZGkXo7HdZ_3Szmr9SgudWP4Zn5j7D8XKSQDC29w74jjGpeaYhYJ1aIF4UrxWHeHPTnhL5JPEgGO4OsRyVMYXq3Za4w8CkwcEL5cIveKLTmEBnT5
yulLvAf7t8zJ-oYxNoLVByhuJdgDw2c0xfN8VBreV2jCt8M2pQE3YVjwnlUI_ztb9j3YAYmQtmuMxHtH25gq2VHp0OigVYjOz0pnUz6YnPg_dInQW7QIxXTb
jsWq18l-FqH7R1JbdotAY2MaQ1Zu1K_Cw4eRlpnsVd4esaBVjIWdOwjeD8OsKJmagjarNyVTtt1S6mo0pfBYaI7jF5mPtN7nbqRN2De3sdLHc2TburCgOXkf
OfeKnpFk0mqqlC0nKtM29c8XgU9Zv4ivzLU2hQ0HwDpR0Rucd02S0fqd7QeVrAITeDnyVJHeEwb1sqaDMbpbRbEe7NJZMtror7F-b9ydJN7QSnvq_aDz4l6g
02cp5NG_wVw464u_73JcOoxl3Mxl3Df3Qb2J8fuByY7V7RtY9qaDQb94PpPLj6PInfxWCxuzUa1VIEeZoQQAdT43sXuze2OLOddq4TyUFQ3TqPxjqGk-FTgp
FNh1jqTxjaTxxZBTxsbJ8dv2z7YsHzcpEz2UxP7cR8_sR8yqvmZgVawZIeZt2jGBEO5uoqZj7awhYl_IT6XWLTzADwlu9QPTALsKr7LB1u0a9NtqrRyYYIsI
pZdtTm
}

sprite $MaliciousInsider2 [339x343/16z] {
xTs9RiD638HX3WO4t_-9UxUBL72pIYVIA9uVPs_XAwcr3KSfqm20x3-RV-hV8qa0bNOfsJrxDSdNjEc4vL7su1hD3SmDs5g5KzNRpolOew_VbXMBKn-PyRGU
rdYk-2QdqLnPC_TFPzLuhiY0wcCyzP41lGOreDb_ZbiCg3u6L1y36bGzQ53Himgg7sXCETA2YdbMpCxBOtPU7pEYyXePKNdCYCfhP4JbCICgZtajgezPUddC
qijhPEdbySSjVKnxVbxCRLGVSXkLnzn6vT50DAQkeeqgdlXxGGDJwwEU9_xb_EPbwPyaMfYDrgKOcDg-UE899bxmkWFFV_5KPgG30r4HAKr81mQYVgJ-ffYt
8XqOY7gH-fjYtevqO23gG-flYh4aVRBfl2bfrtVLxqewRI3gGEflodbZqg61g06fkId7b_IPffot9nsKCan8nQOJKl6npv0kKwLeI8TgqP0EIX4cf6BJdbL8
Mxts8HqAH4CgNlq9gTYK8JtK0j6Gwcwdc92ALxz3AbvzJaYrguy9gNZrEwJYrUU4LBpw4rBnwZEaujNdX5GyfXFIpv8FQKYf7jAG3jH36j9MYuPqe5xxaBPw
I4CwL0zfI4S-f26bUaX3El8X3IdLGnhIaGzfIAaUqf2EV4X3IlMGXdISXtHT7FXfi265yP3ECv_yr-eX3UaWfEfQBHhIWIyf1AHcOpfF9ENSd-_5TNsXCGY-
5yTd3kcqySMH-BDrg_pGuK_tM0HVqkF_zerdH_gEwOHKV40nfEhDxv2gDtz2AXvJZhYGTaZLcpyX5OyfGwf-vpSX5My-GghUV5wFHlnNdv7YFo9fiFdj-OiK
ZwIxWNTlle6dWFJcpRljlyug0QaZAkxvRpTAGEg9shViFQi4fAwcjOABg9wqUC_cqqPKJrgyvPXe7r4zQV6Ec-azeY3xLVoCbFqYahpjGxORdlIyGd_d6rBo
7bDSknayW0f8zr3XHgeNvHKVc_26CUrrrTUIKl1LdZxrNyHF9Es3g83KxZNDu9Qzvrn5EX2CgI_fmXWDgU7hnFLVx4ltdahI_J7jIqcltVlHaCvMVJNft42A
sGiIqhddPWhBry2jUMebRY2z-dIYuZCMjEY6eu_Na_Piro-RxVgM8xyDI0KvaKv8bSdlso55wKb3Ic_Ia8QK8LNNLJtYGZeXrHPIUOMGYeC_QKX3IdVIa8QK
zgGX3Mct7sb8GnhIa8Oqf6DEshr-HXTapw6GdkEiGwGvwVYIBi__eHhI5MkrZHhIynEwOaZFVo5SWHhIDQ8Aqv0kXUqwf3iAh3fd6bAbQC6HjBr8-wY6xfcP
RXAdJJka-EGhv3nvHkLZ4xu2VOtQ8JqXsZj_5qAwlVReFVaEwUwGpkkuEwOXtHu-6fEIFgHzuYJ73dv8UH3TuwSPANn8grQQPx65TCNvBDYImeWKPqXPgmtI
aCwJISlnnAU8D3_-m2NwQDBs8HsYgi1HakP7oRfdTUM9dnzuh1NTIF58Kgf9GufQvH47yY6r8wqdafOlwKEVmCEgLHvgf1Rb5caUlRN1jAZyI658kYzACr8O
a0f4dKZhZ-n8zqLhF4dRZNHVb6waRK0g47KYPVqH7aFA5w8X5ObY_4ZhhzgHTFixUo4LYlgHyh11pgIeZHjfI0MYNgJhAlr9UH2r9Ar_QdVIewWbQTS_qPpq
AEf9oledU9CUHKr9KIjlqeEeAsdLgfr9UH0r9MNL2iwa6wA6f6LCoeEeAsbzg7r93wAkf5qVeYrf7oxJbPJr8TYIibOOPrBKnzgL5BMYDMdzAxgIrWhZJChw
LtW0AQr9wr1xadQjnfcqwn0yIVaKKZwH5DQaLSVQdPJEf5rr324LxVqgfAAzNtL8nKDQC2Vjvv5MUxyk7MFIUX6it-FJc9JrAZ_IPSen9gsNjIFf45NeCIPb
lGpvLGLgqkgGYaNrOnhIwf1g3gSLGYeQqbL8HKEwOaX5GxeAgMX8LmofQ4XN8HKDwOfcf8sg8ar9MJjvVX95JzBQYZwaIxGAZgIilOn8MIiOajPcj20z3a7R
aR9sQqzIs97MTd0XXJSfQxys8QsFcP6oIZkc8QrJCOil6jAL8oczIEjai21jOrBMsTg1T70GTI5bbNPCyuQqlX0jI8TBr8cKzPNQWdJ8ylksITTAilhv21hr
jHXIqTglEgIQjLyXfAArNp6aehLVTKZ5eeMG7ghIceQKzNzZI4MYgtuoATMaNO8mgv2YN4mX-9SvFAELfOdF9HKV2InLBRoMlkTqeaZKnxJhbZ6b-90L1k7L
z1sYDO9GLgQuOqmXtNkMDZe-9ddVW3wYA-gsXX6LN5RNnQQi5Qr4LwsxkVFRKHjIqQuoDEsgAr0NwCfETDNItG6_9q3-xg--BOp0z8BKeYXRKzGDGIeQKxre
TfywKN_JY1vD_L7H6b5_Ktg37aNzJOTq1rsYxgQh9b7V5C0UGOswi9wVNzUrTKJbSNvshEjZH6yqZMXCKNU5-P6rM3I3sgKjfYnjCKNT7pgtKNdCqijZbluA
r2nzJ5bkeJEYyfWHbOVEYCfZHZIe-X6DgHWqgAo7nEoyF0PK7xFp-XXGVGoeFWPK7mEgZpdbzP76e44Dw8hnr4S6L1_xyPvHRIX1SrjjejubiEEfZypzKn_O
6Kzz88MQZJyv4zbwpahuAcmtNsicW6IViDp732r8idzl6VQVaVZHb2cbb7u5
}

sprite $Malware [366x341/16z] {
xDI7YGH05CFGCU8p_LTyEP4sho_fbI2Cro-H1ERP_Z1F0B9kH0ap-wW1rXNqqlaiSydGbSpi2yqvnVMbz5sBAvbz8x0AJ5qBRkhZmPNPTqFM9uNPTpMi3yww
WFN1rWN4rhi8RDq4jcu2MpSHMpTXw_kmD_i7m64tuR2hSDXDEEmg7FRloksmxJsxnTpPDUPc_sWnTXDUTXDUTXF6RXelkoh6Regncp1s4yPkmjXD6Bi9OpTX
x2QCtHHZDyNOJO_itUjshAmIXM7dUCSStFyLx-ENNfY8aHHbXDNrPnzSJUInBD36zdqZwZZUjwZwEoVbF7vJDywQtFxv702Fj_vPWMFDecq5Fjs1jWntY4kP
8oo14KKBOfFvBQP3kxVU2EdK6GsXGSKhZf29oHridDKkQvIfJVHQG6jXb_vMehcvpZLbMKtR4wJsEjg5LR3pwxOJBWSU4uD0A4_IzbAtMJErouYKO0ti_EHM
e-q5Qid0eOmdOHUlazfnxlnsjTHtOv31pR0d2BtODv56acYq5yT6ahtCaWU65re6Odknx-1BUHOtOrF1wwLscpkElLHobvB97STUAhb9MZVZ1EpvapjjtOoV
WbsyP6h7kSdPDKsOsd5k6_GHW0FOCoOtvIvkwp33m4dOTMYzr6vVcjYdtOLaxEBLKhlDRLtQ4J9tJ2kbTfkRg_rKRe5RTs4y3rn3haLJEywj9PVGKnx9hP8H
MbUx4C5UKxiaXfwsLrutjOkVjrzQDhLvO1huNRNl_D7Ozuoa5LwjbEHXFpGNl69gyzZzqthQR8F24sWlDAtrEgM4v_-0WYP8xeKk8RICzXI_C-G9IiawbsjQ
v0A76NARLGht1AyanCjSu3pz7TNoGdUcAAa1uNVn9uLMqgx1GzHBQQVm4WUNlr1R8_VMQsZx-8m1NPR6ZLaESsipNbljXlqTkOHzDgFqr3DkyYRQjDgs0KcL
iGHsaz9AkChH76yCiiumnnzBrovk_Wln-0VwGbU9-Di-Y3ZrBZGiyJs3DkUOxMN2_M6hSJOsreBhsTh41nUuS7ggMzmxnuQe5IcC4sZx_3x6-SGENt96sjgn
euveQohjEhW-yaW0k9g3sAudAkVX7VK-UBJsm6agz7VWH-UqgdeUqlOKKv9cuEqERPqqk9fsqVW__pk5qLFyLZzFrQRqnHpNxV14RRbqXcQvIu8IjAFKgsdN
GO9smFhvsYwXW2Teou5ycK2x2ZH2EsWzYNRk5-lvsd9irwVycWoYsX7hzRNZ5KNrFIf0KUhrjUkmEgIEg0mthyBqnAzzqu2aX5ltV6BjZhKByOd2MxiZhSFU
NbmxNWGPE15cQUsuaEvhxQtjaSszjRigTdoEyzOUN6L97oOrgxQxiEFS_gjpcsviIvjByIOSRVIjVUw2DiclwqU6jFhMfb5tvDs7vRvczLThgmURBtMNLhRg
hNrTHMtidtE_jJkcnSUmQd1x5UqjNPjJx7sqfdNyjTfMAwuNRJLKrIBKCVTniCntDzQ0x_HfeRhwG0I5HRI7B0wYwR6raxihDEDwalZEjKmfJTGXEUXPjFDJ
-rpR2SdzrgwV68EzTZovdwbDgdQpXwf6t0hyP8zokgKdhvPNiC-rjZwUQlzOkCEfjb9EsUt9sXvHflZ_9cqRtizJED5soXcxtHoPQq9Ft5IiiWl-wRlZCApo
b1FnJhk5okaEQSABc_ZtJQOHbtkjOrMVKnsqVnYEvqw-TZmkD5rF--J3F6joEJ3aF4QRFEtlxhFGwZY-ILjtQollsuH3wpf4QmiNZgPc_AcZ-xHf76sfSSvb
Q_j-RMThdsExsd3EFRu6Ch4sxTohDqk0zlz6zJOgpUMqoLehfOEU2U_-DzL7vK_F9pXRM_ThAqjx-sh5_vd_U5TR-MX47yT2vzfE62Gd6YRF6kRbezS6Qcs_
3XcllED2yx7qM6YO_4pbijUkRfNWKcc_Ff6hpLBQtdVCrSATPh2hvJuV5kBQ2nLk7o4MrtyHN4g1eqLKsZQTs33fYnEojDbrhFhl-lmHZlwXpxKzO7UdBYNj
awO6rKvtVxofj-srDN7PhaFvmsIDw7gBTZl0xaFQaIRCjjVITaNbuxLIsidj5Tcs1SfsJYanQXz6RJvUxqSjfpqYcnArcLZREXr_zMKofwhFUZMXlGTdcOZd
rDQWj6uVHc_wCXrWNxUfTgGgzgSsJFbcuAoV9L75wwybdey-kwxVrMU-ju50QazNIemkDImErwVnSLHqy9GJNBA1oRGLJ-l-Xj6VbBNbm6dFNAyOzx2qRZlu
9C4KJKGwmPbBs-ficOt3BiCXjpSw4n5cqLRQ3wJL0oK7nqkbi1qEaUwd8Q6GP8JJdhxX-2P8RSpdtBGsdM37kTcsMPBRVJ_xlcS3s_uuNgwsl3PAsyRPdrEO
U_lb65Bpv59QtEUloc6_nQTtZug9zOFVrdOujULMAXwzY4-LQBr5dpVeE7zfY7aAROMqQpm5shu2erCp4Wf9GZYWBJUsXxbrwWdjhV7Kbf1-FRdRrEtEU2ns
UouQIEr6h-1Navl32d9kj16yCT3cDEDJMywky-glfNAZreIu--iozAHCnxGzxArcBN8VXDpd969LvCA38ahyqTB0QwGXUlbkTqjjX2-XT66Fmgcjm1LqgnWH
7ihEkKFULk3Q9PhQEG_KqP_SyQjx0jP3qg73AS3DXG_x1kuDVcYzSLDgnxdfMk2Ut2queuvXnrCxpisr-kfKxZe4ZVS0fs8JlMUho2q-nv8xc0VIgnEACEId
TWqMQCEnv8wUTW65rDHkXqAxIbvo5mBQ6TXbm6r-nzfGirlny21jocsf7KvkUaJAsD08RT-77S-WBX0DvYQihIZsu7AbaSEi4xWZsZpj3J6E7RBpFneFHRHz
rnYYCUT8hmR3kVcnjdpN2A8nBH5uz2x1kqkRX3r8N50ZgVzWgMHmzslhlhceecq9-uUd1YKXwDIMxvk94cfCE7ImN3A27ctVE0ybSEXaXq-paXDSrIRnxyPF
8c8dOAEEfNgtjKKP78CVp730kh7OBYjeQGUwSFFhpXmpKcClSWBQsigVViRFOSVsbFw37WUejGFKiHNGFzRMs1rIIGtpILj1w_wPDX6kqNj4IGxpskS6TTfC
EvoS7dxyAGi42JTWWZJULkMcOHriCpvFE0WlYIr71mALSC1ot0IfEz_N4txgT6fiZxK6qD0aDDikj12sWaZEEELX3Mv_eeuJAQV0mlpSJhXPdZQSCJctbN3l
XJmICp6t6nKa6CeKWKcvdNHBqSapOvYGsm7gS7B7gvMcmvPJRzywzswTfyAMiqjKIGscmIQDkfvpqt4sG5asAkj4xOskYIWk_sxlF9Dc1M8OQ5MNxd_ab-Vb
n0ThCzZzVrENC76qnnbyv30UdNgIOF3_BqFGDRMSOtl1_wkUYNB19NFXdqKRnS-SdoXZUo7004WNrd8ESPIPA6cLzCaJPQ8z4yL8Ycz8W2l-jeMdcvRYJmZI
__v9j5IzW0jczamKMoT-lkELq5Fr0XyfJ9k9SjgM00DIv02jLDV3g4v5x7m8ai9C55knBSm4IGL6TPNmKJqJnIWUXIRMcOpgJ7nBsP77J6v77ZEuYJncS2kU
YcTi9w8P99dqjZsZ91wCEaTxmXsFXebs9drjpoY9XwEkqPvmn-DHpsXFkAC1wXZj2NUqGFsYFU6EBaoqCr4lsJDBeX6QQ6T27zapIw8Rymn99jfwa4Z-t1je
qCoIVm1n0dcltO3M5zvGE8VUh9wbkXguxgipggyMBc_rqBrks8i45-L44-l_mkY2x-vH_T_0wI_FRLHxYzeeTEhuQM9zb1-QHNGi9XhL-rxjal1d03IgVuJN
7hqPJhWUsyVDcL7z1LA6hndL7qcxNiTFXqmjIP2zu4IiRV72rW31DeFamAV9RszHuCKBsM67Q9DMMC7Bwp30zuusYLLmP0W0tzTsRWyBEJqlmXj4Eq45MPqw
mhUpxVHs8SZhBnBSINPKz7QAgrmd6eyBK55l9yczN727QAkidmndD_l1gHJPgCxs-SYHNpS7BaouQbltXFFBXQ6iWgs-pnhIAxEXADtELdtykC58zwdvJHWb
ATNX4k2FVDufsI3TxO5-rOMRVWieg0ktOcSe21WDRI-SlpdJrtQGFpnfl9o8TDiXjxKT56pEz2stLaN0QBiAL2K1WvwsGqK_MRZZCb3L1KpWRYkSAJuk4AqM
xrCzErlP3XVFJlUgIYYUdUhL0gBYWp3tQW6Xzh10dQ9TlwDohu8RrUwerAoxoRKxAZUATlteLBFk9jTUyAHN1voAP2_eLRZd8jaBTv8TEY0xIRSLZqNLspAj
QZkf2lO2TmZsWl9D6NvwwE_9Y4pN0pWtNODYCGp3Um
}

sprite $PersonInTheMiddle [371x341/16z] {
xTsBagEy3WHWTNLr-VsV-5oojQkQa4mC4RB1wl-wKu61RuHi64Zi0W4ejOyHIVis5SVkZKZOeLG0gHsCThDNuDmfx5NUBIYaTQVAErUzwZj7lUBUyI4iAUNj
eQMcmFFH2zoxUeKjCw8LU7fOuFbXWQU7h44pFIpm_B1woftGgyJBF1cyqD5cYb0bdXvMYQU7DL6vBdfDLCeSRTu8rLH65NhDL4G0VfySgHFDguqBi1SXoxmZ
EDvS4zMrT1kdcGT_aZ0meCIVRxmLUUxqXokBl-__BFDmyUQB_UBIoZn2tCdniUUgp0Edunz-LeAlkSn3nDilSq49lkeoZn9lvW59wX4I-B3kCcSxbgC_pZ9d
ooKlSxPSyZ9dooKlSxPSyhhUmfPBNkPeoUHrBRSbavUvaibh26NB9Izpjbpo6aBHaichdRTayZ9dCdcrSxPaychdBPcyMekIoQkriEMILsj1IoQlrg9aycej
RCdarLfQCdcr5jwMl75MyMpovLjBkpEvRC8mdNpvCc_fvAkNERF9sLOlyvPDRbYyp9bFRbYwpD7IoVFx-OsBl4twb3hlAzviKlCYVuIBbld8QkAIPSwXUyOL
9os3YmdhpSqv_FZLQcMUtJBh3WjEG6vSgimr0xbneJB797CnhZDFv2oxnMKwopoLX4Kw2-SXDwnHvfggNsg5Cc-daQFHTeVt9-UPv7EQutvznSddDDVj-egJ
7zm_tfkSPvBFUl8F6ndDI6wuSvctgSWzkYqvHv2FDo_ob-5DctcRbznuoyw2FFA6cSnjM9X8FfKvrY1ljBt1_SXR8lbKvbg2_9YvwLxap2MVwIeNrY0_RYv9
zo1N8dd48GsI5-yiBP4yhi38wv8ZczpDnwlRa70GUUC46uy5oAFDZHSaLohvSNFyIImwRKJQEFB6FkoVXG4pHg5hEVAcheyOrJDvQo8FcHTvKyz7kifSLVpt
_n7eDY0OG-x1x-3-6e00tFSdEgz3pj7aZP_0MzFRJUQNEu8boHi_RvVuzlEZkVzuBN9NsxfwI02WtY-DYv1h0lB6x-e0nysv9FbsptKK3fSWRrEGDst4Synr
NtBzINiReKTSduO35db_uR7dmgoVXtf4WhIzvaNEhb56p-iJDelDJevPo7yRsVKlVAfZVRr7wvBxv9gIIFgIMnPVpA_gxfnX5ZctRG5c-aHEyvCc_bClyeEJ
FFMHlz13aNUBRya_12_9JSkIwq-wpzW9CsuuFopdgwSPVQTM9Dz_xlZuBqX9X9cnQuh71xhqM49xohp8sHhtdZBWUMVGjLT5_l96Q6ZtcOp-VQ78Utv5mVO8
0JDW0oxWiRtKkv7tpo8TdQN8UvHedcVq9j97wOxEKkJwl27ilIxqiRCKkNloapZuoCUDnkQOAVBzHZ2Z-tUHexrFaR--Mn7DuvlPSOwasSbjABaJyKjo-XTt
xPTM9EThSjFRnlA1t1lLOkJEt4MkxHVrmuMKdzU_N8kkGgxHv7XwaOTlp-kteR-UUvevLoJVlCZpMeRlnxx-yRF8yKRGG_Xf_SN9EGbvVqB9OVd1O7ATzK5f
av8NkQMdo4Va6kJYt-lbZ2INZOWIo3q7oM7cKHmv5oFldx6WUvDznZ8nEQSYb_UFdp2W98dyoUaBw0WvR4Gm0xbj2TXnlNopmDuJVbkEtD5U2A3ZuYsU5d1o
JankKv3hBnQalu-BwnTormL84jxZTv3BnaHZoUaRyNYnQ-3ZzNAdRTvmTkmLXv4FZRmfF3Vm5xzk1fnvky3SSqGFfhXNQzD0-APbE-TsWO3HSmboR-RusIVu
kXonkUtVEz7SewTd2dByrIAzVtZqydevpOoKtwexToltQ9gxjR3t76qxIUJ4hTo3SUJRQQABxrN3xbavLYRthI2yNtU5FqxuPJEtSe_6agk_5-ZJoyRtbVd9
lSpPHwwExyFfoJ6ItCjSNUI8Al9c8pEKtBjv5xdnepWlyEbP6aM-BNC1PW1Vb-DxKSbVsBf26ncC-TtdjipPULFMDcRQL-GDQvFBji5EScfVcxInqM3oHfSc
IHvu5X-sgyXfOuFHv0rF6q8SV1QVhIzOdbpFnviwoFd5xCj6HwF96v-tv1YvMbzeeuF1v5jp7YBdz4Nk6Kc-DPVm_6gH81dqddsqyT5uSlooIKv4zOdFJuxH
vFfD7Byr3s7_FjWCqPda-wzuQ5kJ0F1YKtcWQcWp14F9zUiuQDvFoETx4ds9_jWS6KbEysm9kRrVnS6FYDFc29F8-mduxbdd5yknHPE3KfD8Eor88-yNu8DQ
pzSLD-Cj5FT-bDirwZHr3IA7_HQooTnSUFo_WEC7AFTRCA7CyyXXdmB_n3B_mkuIz_I9Hw43qjl-f07aWXtASV36WySxlzmySegx4vK7tb_aZ9leyDCQr9B3
VF363gQW0e4-7jIuaZYaSpwZxFX1sSF9h3B7dyI8ktTcaUytxze0PDvKmIFKW6jd5ldMF6f8O1uvzdjdz396DKFsJekpo3MTUCoPcwTx5SmXb-qEMrQHXxGM
zgz22UHJYyUKENUi0Wda72JUGdgNEhTtN9bloJdgaXjZlWqwnVFB78zmGpvCN1rGGMNEVQlWkHy-YU3p-lumgdbP-Bn7fv4dJCSJn1l2vpquZrn87ZZxQvEv
7QfZYH1osJXnVle-8UG09HquKdGI-RpY2lXWSqZ7jmS9vBdY2XsWj-I0ljmWpa6k5XM43j0wuvTJJ21F56VieQGDU4GHQ3WvMeBuCJ1jbeyWnsXojBY4bVYM
d85bm41oZRrV3r4blYLdw977C7AE5MSK-9QSmNCeXP1F9nvOeGoVjYg2V5Pn1gopXPCZWXnZRqZL6LSdGog333TFk0Uh8nqLdb3aIKFe53S08_v7AWIsFp7I
V0PnXe9BaX0zuf1XvXCyFiFO0kTPGmuHWp2RE1JSfjG2mmY6kSGH0QHuSe_uzQed4eVE68tPeaD-Ppxu-J06UdiwHlgOjiu4SWIBdxPQJpidF6m-z7aykdTi
Kfw088-PZnR7AI8ukxEuEaybPxWubF0C7zkPeGB8iyJTEpuurbf8jjEJBTwV_DCXvkndokGmFzfVBdvTXfo2NEtAvCPExmprhEbuFda_keJCHfeuESmdxwbS
0VOcv3XojQk5zZ8W9R-kJkSEK2_ogB38ksAH8OiygyWzv2ha4aayGf9IkhY7DoFldqg0PAguXxmpkV1fxzMtw7Zr-SdxqSZ44lSmdtoyjuVAgt0FcKy-tdlR
OYJ2qaBUWbomAuLN9nTWLmjvNN89TisGboGNxCfX5dbvUyXCyl9szVd91TYTmid99TZjmed91RjbaiZBswCfoREzYrnsvs16SjgjK-JfqOJaTkzWFdBQpLFa
wT5qv7RtO3PoskrJvEdHPEHs_o18eOgyFmfXO6YHLvcZYZms-buY_WqaQfv8Pe0tcbMPVrG7zuCNEVf9w4yh0Q2SkyHtHIqvHOv5nQlCRQMWYZmzh29FZwh8
iuFbnAlCRS5KaQS79PuUNhkj09GaagXstXFnEszjBy7D7wYD3HcvwIpmyzIfzZ8ixrFKmVOsBEzuTUXwatr0RSQ8Y2WMLO7l2ldzjhEyzuR4TmSdvl6csbKY
ad0wG6hTGHNu5v4aJN4b0G3_1BYhjsSu-UOO4ucE1Oeyk1-BKGLUvFryOda_WimhhUIw3SMJ8kuHlobmgPqMPirIcIJk8Oys5C6_JNI4j9C3febxz8s9yNG6
a5VeAqnyipQUkNfddxt8Kz_zaJeNtDaNAF9U46PL7SXPEtcIjuU90kHyufRdxM4g03dPd7pCkn4o-Pu9KjCKEKQz6o4PS0pbiOiacKmUZq45_1epjzgPJHvV
V5J-EtgIWyq7UNl8_7UivL1p3VFkFzxbtEFHntUME0tmMLuIwUkV0ns3EmlFyG3i_82ZEWlNVIy83Y8tBajkq1XoOm3vEeNEuSFtSkQqiUQscFduQxYozSmn
TlZcWWzCMcIeDSaD5_gGPjXovhJuWDHoZyfpWWa3oAKUtEOK4uQbo4qpZ5wQlw_aj_F16q5Rpfo3ZpLQVQf3SB2Kk666mMijSkC4vo6SJNo1Jgh4jZP_Qz7W
RQ3PQcLkAU5IueOPBYXf1N6FPlXeNAqaRXZOnprQGDp3AOvgPXzYuys7xp4N0FTm9BY7z1iGRnzCKs8OpfrVOO9LgiBEJgLIgLJ-2m
}

sprite $Phising [367x341/16z] {
x9e7ZkWm44A349hxd_ZtihqOQvGTymwGyiAGvkkB082aVb9_aIII1AwmpJCbrNj8f6azfgNw72BZRG5GjSf2pgFQusCf3r1jGaR8uxeXv77jiv3nkBRm8nxP
Vgd4zO28HxOXFB8D6DczCB9xOMJF4HxP4Svg8y9HDu3faLwO7cb5JBHROQBT2nBjLfW7abQK8kc5AP9vlbCaVg6aI19mLSLtR1k-KzlTlcERwhjXvYOfixU4
sFu4_cq2iVqPLwectx7DXJqQlcDxoovnX6svjhSz1-64R9EcxMsw2mSqYQmYqDQdVCplRLd5Uncw1_ZcaZ7wUexy88j5PRI_TjI1lh6SK9gshnE_Lnc1ecb6
v_cMCx_mvbvrcczwJnUmMbQdhVYXUtfmfB3sCV8s-LmSZ0ZoiF_pEyuEwmNBitwdqTFzlc-9n3-CuPhWcsNmZZK9CBfiuEqIsyuDprGRHp2rldT6IVKN0SO5
dridt1eb_NVz6S13weIR9rUhIn784-fa-ti5Z4i_lavuhy7bx3hXxKwCa-laZdFBiNN2M-Q8K-kaTZ0-1lDZn87n_ixUcQZCpiCm5264t_-9_xLSjj6b1N_S
dZ1XfpZZdghEKZlZUHtk-yubD7c_Uuxht-TqcpPQ-kLB2gMnlll1xIlknu8ecuocZPO6B9TTDtHneoLYiUooeMl0P92ubl373LtZ9eEKbPidQbhXoDi0sXlE
wnnn2-1yZX6t4CwV8cupdFSPuZR5UPAu-RH71uZR7Ada0DmatuMF9IBv7hgupVAT96u-xH5Rt3Ib18tREDS5ZYNckPvNY1id5H5nWvF1mfC8QPpaozleJCUG
SVEM3A954tWQRrX-2ru4AbOqCRseFAWW67gLir31crzL7b0qyU1vcuMR0vmVJJ9ytk7Wdk7p5YQQw8X2VWnkBwp5gD44CAhxe6WYm6iO7HDDZF3JfqIJCDv2
du8RjI3Z1-yNu8OAd35MPlPuAubBjM-iTi7bGkchc0I1U_6q2fVdq2_eOgJ79jx1RG3keWqtoRZUN9wRr8Sjn1YqzatOzHxAyxbdKeSQ4N5hjgA96oBLkqip
yJIgdHG2jzS-mQSXwhZd1cvNavNtz8lxwki6xesf2HPt0w5YSSz4pSH4t5cRcAY2I1DaD-b3vHVtrTpUSdL2TGhVJVgCsMVZRkUCbEbF9vIAJksAbqAZaTFk
gzdMPmwsFbvHCRdHLxbuBkvtDWDm8t4lI3mmt2Y9yt439FuUt3e0Tsy-4BTdlwqDTivfk5VPxIyCvRDmPvNTVanJpehT_gDDkW4RW9kPdjbPyt6ZOFDnirdp
SQj5KidrIZSfJbzzzIRdm4MyFohg4wGytasz-hfXKamFmTrTTRs3jDV1RQcYkMNIMP-FkwhUpvD6AevYKc0VjG4xFS_aULhFypoJmlhLkBCmLlvedecsyqo-
kE_dcQZZzl6u_LDv9gucsxW5mftFL5D_musGwnFgVH4BXptxQLI-dMVISoXgNxkXUo0Pi5rVFPq-xTUxIUzBLJV7uMxfEyuaAjyDhmiB9ZCfZu62cryA1JcF
wX3QWjn65WB92vfPkFb5mw2wIdv9_41mwuW37qp9J1Ag6fv_PZegaF0B-yCC97pStADWGRa4uXzhPr0EhnO22LJSUQ-pGQHn0yRzq0_S7HHkBmGIfBZdhPjf
kjfPuXwKl_dLn1ItNx2RXYkA6XfkaVzcs3YHQAKS2UTy07lptNMSy-RY7lFaBO37jGadRy3etbk07-71qMJC-riHSZGPqywIPijxHFBUUDmXoLkWd2_-mY4l
o4B2Xc_HKfCqQDwXdJGqQDwYvTs5pJimt1eqRz4oxyBcJKkzqw1vUtsWL38pO-jlwiuqvuqOXg4W7eZS_yQzG1V79Drs_eyZKS_QlYKRlFzllSls4JkqntkV
6p6AyJuXUq_Gf_TiKmP4vdD8NYwuPDkWW8zXDZbdpjoRVmiUz-P-MEBDas8EL-PpNSL8YZSxl9-LSlZU_AJ9KVAltkZZ_RwG6trbFb4DKs8k6xnv_My1uTpy
i8EFkceclVTMx5z3hXBSUO_BsQTh2FT-OAG3T-uTfszxA7TETlwGnrRH1ACwtaEnzxOrHcREtyxzOohs7kuSxozCqCubD4ZPxzN-E3j4NIz_Xoe4AvpyAMtf
0iFhwOG_XDo7aci5TnvXPJUawYSdMTWWlSubRctydSLCJKU_aiwsRGBVYxyuvSf9-ZfQBiFjcn0zJoNk18wlNrVLALtTJXwd4Za-IyBsHRGevXBkSE5jAb7e
fUmWMcun95_YyZQLaCHESiYaIbvnovx-QRK_oaPVjUxoRJxqE9UKTmKEtYtcJhU-z9TtS7Flfrmpn-avJlYRgvtXwOm9buReu7NluAO-kpepqfsbXHCtD9Ex
l-5rPgCxaITnmwi9NlrrEXaHxjoqZ4rjKZU9sBysTN3VV1Kqnp5dhhOSBWHOMENlpr311iPgot5woWqZBPUnKlrSma1igmG497exziJj2TvThMtRQju_T5qk
oOrGDvUu33Q3ribSwerB-dYZjl9pbSiT_nvllKTUDDnoDO0k-uq2lJD_wAijjyxSQSBVq9lQn-dNMkTuQ-8xx_LkvH8TQ1qmkAADntfJySGQ_PQXvpSUFTNR
ZJCEj0vlpL81ciVl7wTQx_7UDzK_sZiF78bn60YoKMZS_rzyMOZUu4HwJDO3TgG2j-KaAWsMx5k8tRw1FrxClPMXNRxNCdAmN0TYmQu3MSIuE_TeGFwTwmMx
ZG_-fK1RsuSh3sSUV6qAj1IRJAYSVsC1U7cssL0zeLBGwdP29M4VOsgeJ75FgAoCNG3sFSKzeM8KcmXyQMrFg5W_A1Da7xK7FLql84ls0lTqlO3ZiYTKV40N
s6jLZTypeMB5Xu37TIfYNES2utf2vSo5oFFXBHSY4oeJ8jlWSPtBk4x5ipZ6w5Qy4ptIDl5MfhWdJUArQB9aTByNJvPaeYdkL7hhdZI9LwFEnJtb7I-7AUvK
-kgUD8dNewx5FUKT3L3BufwB4qSFfhXJeP_jMIsZ3PhYJeLUw-J4YQ8JcYX9XJws9qwY7n--JahODg29xvymLvxL3O-NxVg60bUEdP7z8t3XzaN6zS_0PMDd
N5-RAl97tQaAFxWnpFd1Umhxry3vmMjSxm5qQl1-Y6j_KiSff5XetzWrXNqC_qlrWqQ9XRJ3THEuDHCCkiFrw9PtBkdg97kXbFo5AUn_INiPG6VN2oVONd3c
gi_YFWaA-9pePiUloOVxMt2p0_0dP0bflKIuxw-dAAV0zYaR6GQ47rpSkG_Yo6d28sXHt3-x8AlZaQ11Sl-eGYJ8la4vDLbotWIao5x0Swwv4m9x2n9aNtl9
Klero7aHPCY-JhanKAVxl0V8SxqGBWtm6jSBI7Iz47M-ormlXFExvLBr3DPFw48fy8xbjrIu4y8xe-W4s1jdDCKzy7dbxPjSI74_LEXMusq25CoPlhg3WZdJ
KVV2-NEciUuW_ssyt7Zx8WLpfl4MBohcJ5lTGSdsR-YwNPIYEOCxwWxgbYlzthcYd-_2y_eQRYgdRW14Fzzn5-gbMyMhbPerLg1MTxXPrn3NhbPgrZL4nLU-
RjOIXzfzbUhM4gVusi3D-ZrHQZlKnVQYE3tfPJietX1FioQKBhAzS2lReUf_PtfrHQJwQ6WAVheGgbSgt4JsybrTNx3nGM0FtqPHWTH0TLLv3NNLDGp3y1S
}

sprite $Phising2 [366x340/16z] {
xDY5ZM0130FH7rbM-g_uRfaPPcbU2QF87uuVOcQIdjehFP4aStmGpQJTPpN9yGwQjFigVSkXQwRTD-fhYkiLfTzRtAFU3_Ak8VUe-U1UzVk3QxgV1jbmKr_B
GR0rtzlMfrpmBAcnDIgsHiNMfCHd8ocsHiKH-T6zFMnpTodsdlrEEXusAHusARwAeEAh22ck2AdZYf3YkmWfJZOfJZQfJZPgZ4sAiKanDYd69iNNR5ACJOgn
IN6pIJ4sASOcnTYa69iqndw8kMSv_e1TZhcxlq8SRLACJHgVaA3wX2JL7I75sAHnHq3rJPiKTuGqllo1wewu9LcEMxA_LJrjKenD6dS4L4-RD9usg9usQJnj
K3rjqlY3XEHf_s_lN9TaHs4OZ5QbEk__n7k_x-QCqo8O1_jtfmk-4RA1j6Tbi1niYS3OA026Hr-Bje2nPr25n5t_HbLrnCtgjqweL9PKFvXdfPgRjRlSGALg
RgEGAgULUhKs2xUfGS6hNvRTbQdYffrbtn78bqTHtYXuDcMSEbIKYOgUHmabkxXXT-iRZCaxNoJYtk8EUSPkkA7ByM1dsWmQD7PoRtxFshInbIXeT3l9MzyP
oTxYlf74kODMhcaYAY1jRoJxo9jN2EDpmjP64i6TdnxZcnvjN974PfkV7kEJqiPRczWZp1TsN49rQ0ycrOBnBBthTZ9-Q9OlRuLjOTFj96Aqu_QvVgZyI4Fx
daWP3heuFSPfem1jtqtcfyT2j9tB3ZzP-kdHs1yNe9qYRoX0h01jHcdxcfi_I5eYGW7Q2SbIWVHOWxPSsjUrmeAwpwAjNUz_ZOM-83sMeGs3jfKi_VJegsZN
stO_ZyrFZpvj5A1j9qjVs1WrQSkWRHsS-CBsQNFJbwGyEdE5W6aJKr7QyvCbhWarRLFUyxzentTTOT0sagMH7YlJfa7RLAN_5JvjLAVjiuA2R9gsVt128wLj
JbicxVdoLlnHdpOhq_QJ9OoNylUd_SsWRShRVyYVcGhGDd7xwR5f-mSd329fshwyOQJ78hHXq7QoCEF2ngCwgaZRb_SiOJTjuzNsfZsjdcTaGykcFMdpnCZl
UTMq9_qkMlW1T7xRtRJdjyv4qvu8syRTjFalEs2yAuGk7Bvf1s77ZzBvlycLJViMx1XluUAJRDgNmNXX7VqactOKzf-XWB03k9ls5L86TlAX3wff1s37hmmC
t0RjokVRk63uXRmL-XpwDY4E-neZWoiFJViIa10xXnN2HiVAj3MNDgDpOP2WBd7t-oIy8HnU23k8ksdpramO_5W0KHNQd4YRToT2IHZ3mEtIHjdtjsMeni1z
06qFjezRP_ys0GfePYPkx4lRBxZTFSryKQ3YhvmKe-tlQURZzccp8cqQWZ46odgqQT0sOVkuNTgeryE10G89bQ2heTre-x1ztCLe3uEs3zl7NQptZYpQokxY
AeCsYz7szpG-xbAq4Q9jx6cI2c_77hDf6tkQ1DpRqVOF513ppwp2sp2ITECszZG9k3UcZOzeSwyx47v06zlIDc0duJPiEzrA3DW9k4EqMOMsTlmlPQn16m7Q
1koaVOvX9EarOE1IB5yaClwxq5PMOcmWa_OvXf6aMmb2UvfycI0y9nIWpHZi_7qE3TjEjn8PbLzAQKB3IFB5RS1EmUqOIJvj6B0JS7j6acyb1km4t6P5aYzk
xGRx6hS2qiwC9MqLKi_LTjAA3DW5SRFGU9KCrrTB-d0DsELmiyvYvDWoQ4XxVHYmg-5ccS5oR1kSIXkKlabaffLeMznGbFRDBnCpymnH3BNVu9wfHI09R0CQ
rEJoJtCS590aqX1t-U27gvoVBpVI47VjCDeg6pcRPugRdvSsSlA8SAAudOs7h1p8kBXRslu_06HGt2tjEEwuyxEbFM4VokX9zUcmnuoZ_V3JR6dRvysCFws6
ROgRDvx6eIaoFdc5QBUuEUTW3W7OBMvDEY2NzIKwf0hahDk8gKMD6dQObr_KuCWKoJcMnDi3uO7Iffq004hwO6deEDZoNXM3Z9iw75QFm7an3v0v5hwDDhnD
pJKlQ486uK4-mizN2ZJdJw-tmtQ0AVPed3OEAVxuUHRWn3y-tstQbZhb0U9uCMuQhAzfStA1f1V3jiN9wUMetWoRtdVEB_xntcqDB2MvDak-57TOrxwqErCY
Akju27EuY6_3pQci9KcOY8Ly4sxEbJKVg1-8j-3c1MhVb_JOCFaAs9W1I07QheMhF6neSjAThq2oD6vUeFRYoTAOA6ic3B0sllRHKRCcRCnVbKylTx8URbwW
zWFFxxB9MhXvnTeFBQdKg4AmyU1WSTjBI7xhMB33CHDVXsvj-uG_Fsq1Rzg3GTGEyAOTuYt1FiBkK4Il0iP5jC3D8tDI-bFHuWLf0tZJzg9vJ-wtbYFmbdO3
bqZYro19QGRiTfHunG2ISs6tm8MlPgzxZpPmanSP5NOxoXHfKg67M-1nr35FaHXuk84Rg9E2zL4lOjq2rp9PDt1X50qswXPu07K3xxmO2tPURDw6WsmUZNfb
Q4lM2r4tROsN1YfTOTMFqsctbOpN1bhQA-DiscqbuyM1blRAE9bsMybuTU1SQRUunyi3fqgxnOtHuYugxHPtqyPRORUucpREWztY7eS4MjehWsT9kxs41z76
IR1RtEEiQ6cl33JibS7QFW9GaaYYhVkB43tKkkXSksiWEq-ICuVEPlq8S2gK2ngr3noCfTv6xGE7IXNn2B3E214pTAAMTJH8V-nirBU8mrkIs09reRxG8Wdy
dRJY3wDbRVm3fkmZ0G3yBO0dKNVNl_yiAf48FD2qvtclE47MJJjEJcpK4xCa0yMJxo3rOzrPjEZ8MdfoVOCgOoIyiHs3FkwYm6SxD80gGFiE1Jau1Xyd079p
8-72tY1Sq7e4vCRINjh8YNg2jK6yWBGT5bobDP3rN7j-To4kd3ov5UoHqZbywTp9VMhjdAvxNFm20waTf8sihdkaktAM4XT9Ce-spu6ohnXNQvo9j7t9KUlx
LP9vkDCR79Bhkx0o2xVIKCSNk0pIqtcdMiay4E2_eKiYvuBsUIFFIlWCYW1XFy04A-6vNHAOa2TvBEq1BQSzwD4-JDxCJD37uUP8mptg1yiSl6gSXnjf2PhZ
3O6KvKoTINiWQShaaKt9a2Oma3hkv-JChGj07lKBPsRN1KVH7ahEL3ggBmMIlHDdjKf0SX6cesWFvPO5E0hsG7AYEelsOEx-WYV1phTEdTKe2xbdS3YiTvDo
2ruU1NiW-L18PtKbK_8_ODL9i0UoxqrqLByzPgzb6ckgAExC6RCiQnztnen9uwM_Qe4Tr8Lof7rn2QDZiRWwEZf-0W
}

sprite $Rogue [366x342/16z] {
xTthikBA3WDWgrGgl_yJd_lPxDi4ijoquxRrUu2i3yKqIIPOaG0W9Kd-MoI9966JPSoK_6r4qWAPW9BVYdvIz0aW-G-ZE-AJ6z9HyIcrBmffWGnr0lXGHy4d
a7yjXBqo0ULVZMWtChKE9-0zre61CjPxGevr0U-nZdcFTVtvFTQpFjbdFTxq1uGpH7Q6K-oYtbFiuQO_B9nYr-AUOe-ttC_ZdYaotFH71uEzCvoH_Mpk6Td3
3QyHpSZU6WpsSCUnXtkmtTaPMzZzgcpSx8HL4DjYquPx6xRRJ-EHi2UsaWuLe1Lsl6JmLjnCNlrw9sxuYkGTTLG_R8RshJxSdguD3uRTJXxalk7iTN24oUyu
Es4xipywqEbKZSNIusJEKqvSgGCtVL7uW7sCNR3z4HCDNSwlMpGw_ZoyBmiVeUtgSHeI3zdFq07RBHu_c_jXvxxb9yyIFamR9vURlZ1FMY2TFaUSjYBoOsS9
ZzLsd5rjVzPtBPrTRJsi0JmPs_cq_u5oyXnnFEsmZGwkjZ_l81dEhJPjLNHYkNcyjkFKQliJZxThglq-Vbwv_RdQEgxSzBLvwAax75bjFNJZT5or9GAsCY2f
WygzolcQEOwk4yhDZT1nykhbLbJQzeOiN6xMeOw35zOMB2zaoL4Ie4uEwuqILZuPmchbhds41ogrvGWKksIzomqIsfEYGgEa_jKPg3DAsE_yTJLjbZv_ZMgB
RLQ-3QSoUr7Q6weq25dvry80rJeGMFT7m25LEn083qTaGgVbaHG_HIOIET2LHebyPSJleGEKYbzUxCl32hsGPOHVrQPB90dWPeq1KfBhMpTSFqNxmaU_XN-8
NhaOiFLl6orV7QrzAv4mIcgERQrLONLjU3ZVtlKJ1dUziRrUk_xWvZV7jlroHGY--xLmV5sRfwssBtPP-IkytB8DA-vMscYYZKTeswVQz9KvuKCIPRHnilPe
gxCsRNEyixOErXvjjDRsWxL7czvvlUsehwtFjFqdsYgjhItQU3V3S5c4xtseixRst-letLwbqLvuQeiNbk__mVS-r6LRutkqdPVOr_-05myRxR-z9e5ySr6g
VlaFUBKhZhP_xTU1lBGs_DkZ12kVZBuw9sZBrWd1Hlj26W3CNi5_Gzv_chzvAdAqFng4r99rC4VxfNGLBNoQqTQQb-CdJpFQN7CG39zy0nxjDQ-dJvvcj6bl
i_5fVBIrwsb6UxIZ6UtH7ktH7ksj6Urj6MtP-umsksiBPjkqpSY2sjfW7T2-2jjUJyB0wmMUhASsBKNRL4nxqVJBqOvpe-3rsqZJHh-hvRbsNzATmgcTDbRE
Bc7dzjlc9AnPoR3rAogmtCvUHP5QT1T7UI0yNViLaAJ-4m88ZC8wsYp-iryejUdeh6rzj5-ltaVR6clBjaTzjMdRmz7U6FJLjfqPxOIegpPFrnvjTDMsdHdj
bAYdDi_N7ctqrBQajDIM9KKTjMb9GKTjIqj3RLbQr4-RbXRqqxR4jDEM9KRTj6c9GJTjIqqpRLfgDDeRWrxQbXnrqgOb1vsqBJsDj6dfuMZ_8P3a4cbVIHjj
VMJjlqMqzL4NRTwtME-DBjeti8FUe7uvYzH3cpUm8zvuFStVWQE7zetrGeIRxnwi1jgHkvygyYaeX7jIK3koDjDDxEltMGTfnwjzpHsV_3X9ErxjQ-xuvEVX
sl5xLlCUzhLLTUsmrOe_z-D7ixas5tplv-UFLcdjE7Ryx-MDH-DaxIL7vXJG3fIxd3RN79X3O8C2vIwcBNiJhdWUtdiqJzNc6cpNqaMDJjIEOx-2bOiQdAbz
0pjGRjxU41RIvg9gqwFQ02Nz04n-8qhMZcF72mRU86Fe2rggTdWZunzLaD-AGcyr4hKPsyRu6Gd8RoVqPYjHUyKSeT-D8jRk25rTmZHjBjX0-UqeOksEsDw5
96t6XpRy1r7iwZ86zo-aQ2EmxuNQgH2sqwBS2TeCOKV05C9sXGSQTsj3qIs30kMaHxJZ8ut4DcryBgKBwu2s1w8BY-9PR-r-KUt0xaOl7rnOHweTZ7WYDzTR
EzUua07k8jXWq5fOnyABmu7rmhMrXc6rYdWCDzTGl_8L5F88RYwQ8A_ehKaSNFMneRKh7Fhgi3OtBwZ3vOQlZrYNcnVVEWF1XNOyP4rkNjGw4dsxVqGzRWQe
u-MERpoBOGFoRqGxllQHh8GD-RToV-aW-i6HjXpcqfrl-lH9xE2qRlqMEEM1ZBRn4-jNmD4BQ5zx2wj-yt-qhxqbOC6PvudU_12iHC2k0leaTWeV_urTvFv4
cIJSnskgVIzJS4dYVo9fzVMy0twzOW18BSQUYIBXkcrQD4Qcu19-_kTVF7R0Grnan7ecocqjyiukCGMF5nF_YMqBrOewFwnDlSbw9ee4Anbg9iZEW4ETEL66
UYQA23iduDHwOp3KEwFsrADj-pAZX7PgHdjdr7kGp2ZHQCyWMH9r7YHJRetseODaHeaT7KorTsQqTuOpI7Pcghqpccfl37fMUyfj3OAErPvoMuzCjNU6tR1d
bi2w1BsgFUMsJfbgxmpQOC-wHDOjAhyU0O2P9Uz3Xg5VPI4nvVuYE5JiSm3oz10BDvr3_GLmrbhd0F8dXLXL4qwjFmcvPjivr3V0mnkFcI2VHcIq9vfQtnH7
PDinr7SZyN_e02I_4Su4sHYkffFqQa2argDzNux4SkhH1cykdy2VMeysRxuCv1spRL51FfTQbRJX7uNy-GGHZD-yRG388eC4WH-CkNFJB7wP06I1QclR7Ilu
jMVV8iw4yxKnZ1q0v7ErTr2_matdrabrghQ4Bx-WODSXLNvgnoMumNgzE2rdaCGXkC5w_IyjnuEjrAzmX_LASMHgn-_yIswWNhSybBl8vsZhjWCPU3iJnDs5
HEtuTf2tgUDXsaJ9edu5L637sUsjv1NW2WUGkl6ZFvdUcQD4Ao40ajJ_Gn9ut5sLaLTkzBkYdnO9sceR5D1E-eHkLczQ6ZUi7JSjZTlA1m7jtTvMFoXpc5iD
__jRtlgJre_R5WLigctA-PD1Thmj1V8A1b8Ax5LdS-UjH6d7XDcpKvsqZO_NjfEYtDc9uweT7ztCUxVjh31tMO1ErSx_eD9PrOxFahoNfnqNvNvGgL6ryqSd
cjrBKha7FDdh7d2unixYffqPXR3ZKITiG_Q-hFWLE_MvaVOTYtPoc7r2aEnqrqwcxyga0XUQLWktMayeJshNP3AP_1C
}

sprite $SniffingExfiltration [366x341/16z] {
xPs9igmW4uD9vQPu_oV-bxjDpMrRn6Paq4xjvuZYPuoCIbiM4G1IabJ_If984YKr33EbsfH89go8FCw-TCReAK2g9wKUuYc7z73YAL1ra091dgQU0JnT7GUU
Wkh7r9FXYJekiVXArkFLmpjPnvK9pdgbo6HzfSHaVHz_9-la3TM9Oh9UdNU6IF96lKo9M_Lhn0oH1N6diPCtwlU9cI8BySunTk9c_LufOIzWxnoB96vKg_Ln
9-mCRzOr92JiAuM4_PNXdR0Jj-fYOi9Et67OYJjXjt4dxCJDkgouEEp4dR1z8M7NAea0y3uVcre0zrgmHUmHm63cUkmjLic0Tf5FnRq-R05pvW5o4TgQVSkP
UWvk3aCzkHDu3cmXsWy-03U_P_OkUVihvNSbPf0txszjVb67S7FO_Au-uSuZRU5mwJGThfZ6cqQtegnFravJWpaNYkxvroH0jIcHd-WQRWbR653-I1pUETrn
yCTHxzWhjYOhti_Q64c87Df1t6my8iHGMt4WRjtBscomdhrIt1msLEFYi6xUw1B95fFvg-Pjh8sUnoyx1rOYIJK7ABn1beo0tMO2Trk4qt8CRjt2sl9D8pS_
MwjHWpSNDpS_yJjD3kpIM4qRDzOsDyV3jbH_kAc51aqXZXihm_Rt081b0knS8-YrV0dX7cjrsluFIFoR2BjNPB-b__8FuxrT7tPv-nyEqURRNusvHtLQIzFc
tghqicYJzcPBGplUQzm5jWLvd3QTbYtQHKkQcmDWuyNCHibBFcsuBOihhMZk0MC_LFnpuBXBspAWIvk_LOomeBaPlqBYFNnj_FgqRKkQXLnKNC_SyHn1TMch
dxPsQIE2MqjQsyBM2TfsGVi7krmekh6YjSqUUyp6qwwAH3UNjxRgfRGh0_tNQhJjxbvCkpAG9LWkI3QFreMqAyvdYPQsDjrnNES8K0T7WDQXNETvS12s_UtO
JnjTu-qDXouJ9GZIPeCsVDgjbXvjsmci4YKCmhOmFCVwjBLvNuGkRMjHBMBku2Lovs9N6hJTbchHjXR56hGHjBOV23HSBUrsIvzsvLbpQw4WsMnjFKcpX4Ex
sTAFgkNC7REsDlU2gg9TlwLjMrRRqgSjlolhq_QjxP-Yz6YtM_gqm-RM2a7I3aiwg_Te-oqXkRJZvbw5TkC61PsrDsbNUWLYBEsukR56aD3IzXVGc5kXfA4T
DRVM2n9mPyOCeE3BcnQu-5EUINaxsivv4HPFTbKhHOa2K3YMTLjiOTENquvOMzSNssB0tFEZ104kc58CYRik_MxQd1yaZ7PPvqwt6RIdNoDPUWKDET_mzR6j
uTP6m2EnAE5Nqex_SXaVdWn4oRpWndadOXfiY_lK7ccbsEPdOGC0YY_6JJ21zimWyK1B1qhnC1mbk9gspjF-q0KIwYXKiXZjK6nVM0o33QjWXU36nDXcYtLx
yNlJri3ObXCDFRWPwvdMkKXIPmfYL4dKPcX2_MU3OZvOWNP_GGnx_uaySvhjDCAPdS8Cse7UqNMCmzeJjrRJngtG6u7uwW7W8KhmQBFliBlhi6HPbg1TexGj
9tYhLXEsJzl7hOs_VUjzgS2J16oS7pz-m5yrJCizs9BpdGeQSxFSaZRVMx8qIpJOnj366RmJy6JZzDUlpI8m15o2TcL7YORgvsnHryX7stFhlvysJjE6UGlO
fstVMdLe-WEVzlbFcEKNfmrdnjuXshwrs-C4jXVHOsYh_X9-gLdiXGvA_yAb9gHpFsykfSqWxNfaEgHTqbZRmePKIX6DBRomCJ6tF6rhDfZLEBJzcNVqultd
udJC_M3QS6XRYXjXuLPcBAMypLX8sepGzjlYHLl7eaHLINkJDlmkoD2k-2bd4DYadRIReurNadZIATf9UtiJRD2k1sWdRUDBU8DCSfSs3EqS0VRJLhD_RTf9
MyxTQBOmaWxjsuy0OMYNuRJbzBBr3CVGVjmlTzkM3ktzXvVefCtlf8qpjEtDlBuI3MpxraZDPOGxqswN7_6YXEqUoC9iqKQv6MqJZMpIjkPsnYGju6W_BR_R
_MrjFfSiNIKQwDEsgw4njq_xTiybtpcvJcezS_TxODzm8DsxLxxg_MWxi7tQwlJX-wDcxAmBjtp3eUx0RjEkQjF6BxrelpQwWwbY3TgwzZt0OeMj3NJIDkES
UzA6QfzeZzVM1jIYROuuLtZ7LO59Jkfgx4vRaliqmSzj6jgrB42RK-Oc-54YUt_RzDJGFZ_PxH7pRc3CRVx5txJrGkhc__d9Re-O2ioskNyDwu3IjZRNcGmS
SAL6JN2IGz8ZIDkSfquwBbJ2GSEcfJOHe7Lg-B4zdtO0cOCWPcxw3Dh_frirPNtQ63FrkkULOMWtR5Sg1uCvzKdGEEWaVbqb8UqtPQ3yqbEAUAaukBjdERsm
hL36gyw84WiDScctPuae4Dlh1BT6bYQHGti_QGqsBaCx7YMHNMMJjh0TX6MPOfUeaymD1xSlEZTwU79toWpQaymjXrrdGKokLQGuH6bu2I_wh1sH9pl46RGL
YG2IcsZmwv_-2UplBbki0s-IpAzHZA0dTz7GsyazTv6gBqdupFtwiWJjYbtQwdWYxtC4VmeTfDVuA8XYvcwa8NQhbs3UeoWkGDioQZc6kzLBEEsAZoK_KwRj
kXWIpG8_VbWkd6JjMYQfXimDjrA3tXTmjiavEy9Pj1KRAcjpUesjN-A14IPOUnvjr679_SzkDsWFtlD5lWnSO-Q6UINUJaZmQFVZnbeZ4Yi5pIqJ9E_qcxHr
dBLsG749sgXrp9YRhjTVYdWRghKEmLqcAdf_6c-EvrdQFDZFE6xEfAtemnSwqoUxQADMea4xZdi-ROHlc6gFDdi-vav3723UMiLnbwbI_Dt90RJDkabAve8G
nyt5Q5k3V80sJDGCmbtc2ZMS9HXFcyvlr2XkbidIW3U3NzJ2j9r2_NKCRfRbp6sZ6nM1yNO7xIZkCbsgyUZ6YveD09-sXIc7jZfmXwqDaFWgSslp7iOvslOE
W3O7xc8GTzz75ScfloVRFf5piNDfrstQcyakis0dRdQm_bZESnnkEF7hquRJpcQDIWdYxa0HvWsWPUuuRbcBMjf-bD2bJPOInCqEs27Ua4mMXSrTqRXNHvUs
NSdRFJvdAuTngyFQRGv29-l6iQhZS1UIiAlrQSkseraWWBl3eqE6wMmsPW2tBpgqUtl3CRWxE0Lmyq3ZEXgtNokckGuu2mHnCpHOO3zi_-na37UaLaoxJY3y
LViKSCBQSTmyHgaEnWtLuxGhuRUZiqij2Z5hMo7oGr7-Sl61eEIF2RoraAJKDdRXCOpgjFQ8TpLrjBM6ucOT8tYhRcDGjxN3vcR7NTCexl6ywKDiurQljUFc
xZXOYc4PprlEZwU37FgihG7lnhBh2Kn46CZRvuFZjcDlZiJDtOM8mRD-86-XSstQFou3OBVDpK1jba6u2pcADTJXEzcknU_mAvRyPgD1td7W4ivPHpviTSBs
5LiBnkHisqCW3v66km9r60_j01XVreJTfuPgdBSlqb-_Y6Ymoi772sQZ0UW_MAXHiPcHfDv5eDL6FSUQ3Y4FTemsGEdagS4Q5ijWGHqufC10ej-TqiXAEFDv
GqCx4tGN0ZrhZLFdyuQ6zYJiBSPwzgdxIPpFEZvcirAiP_WKxahEPrqv-CKEnNe6__IAYp7KSN7q1XHBMpPEiA34KwXT577OCKifTlAhcMTnuEX3pIZgzaYR
WUE72ueEnKIYszHnONnACLhYoS4zNDf73b1rg1XcRHL4ezvOYpCdyC8E09HKXujXrd5hMv4ExhN5yQoh76k7WUD-iEE_IuTbB74ht1pBcYGnz9mNxuDRWssj
LiB64uKtWGt64Q55EmwSTu2DCNmSsd5nSToogEFIvv282-EMao11uPDNCt9Ht6hOEhhU-Y4H2-9M0tNOtFpei1NBmGRqoPD6zNCYLyBDfgtZj3_CW-l07eZQ
7tEpuzYJzRRIDNS3sFNkA5NxbLBfm4s4VfMdT9YVCE2zwgJjy6wW3YHAqlP_gqf4yGNMLAWU2qZA_wn6856ITa0J4YLXPw9ygf9q9ee8m0Jl-C-sPA98E3iD
oxJCH0c_ZaWEoEnC50c1tVSRPwA4QP4zZJDHmhH0KjulbamK7_KoOg8-f4mK0ML1aRSPWcIYP89OWObwLg8awamK4ULMGjhwIYNgAwMrx_F7bScj2m5aSFD2
01dSk2rjFJksCqfOxgjdqyueAJSMdcpjD7UvjPZMlb1uBksCad9puQdMJdENsmlFj7QQkpn0UAArqzpb4SBph9tcBazHMljAyLcmCqlAWuIqzfLYmhvIUagE
P9Qm9EwLQ8EI-Pw3eymICO9QCeLKlrhW9DXnH53WwCKKw_1wmFskCr6F1WujSEsraRSYSB3k2sdhGn8nekz8r2CiZcETLwBk8uuTr6kO6r1THo89dFlO7DBM
wzuI0AXV8idFeKxQe4KdigD1qeu7WZZMraaRZQqmKO-xIghhi4AgpzHmsBuOiRN03rOD0BbCa7Hi3JfVHO4VHa2kO6rULh227o-7GUgxhSqBIy7n2W2alfVs
jNLOU4sT5r1FihQFWXzd_I7YcF2mDaw2lAv-4SWb1YJni0xmZhCUJtm4R4ogsyaBM0yzm9n9Eyw1khgo7wc8YoHY6ksuvS30DWB40-94sd4CeAulBanEAy4s
ly0XUNt9R4vojxwYT3Zta8lZICTvpucIyPO3I4gIQjLFqN2UZnlppCtdJQ3WF7EZF0utvzqfUU3y89PfkClpSBDCmrsUXvlJlZsc1quGmaBNv_Lnpxj0ipmE
j-PzHWNbSRWvRovOkOamxtG6gS1PTNFSypw7nUULGU2y2ZfuNXa4pDl-ywfEQ5wMyNbb43ZlQ9TxYNC7ONXO5P39muARMJkU9VCspt8xQUw5IWl1NZywyR12
MPfxClDPXR8m-JQ5NDWFCxVcRH_bfiBiSrc1zz0MnJrpZxbuYiIlL9pL0R7SN9n-AfFcbTuRYvT-TJz5pKATIgLI_mK
}

sprite $SocialEngineering [369x343/16z] {
xDg5ZU0050FHMDRNxx_YksLccALv9OmSpl5J96ddr5wPKssJuyCewSm-QwPzPtSbC_iwqnvleTFMRuLjtTZNNhfqvJhsPqTNhcjppTts3srkxMjtaYkTlGRE
t74JCpStfJ5tPZcUMReWasU_HEl91DQQ6rPpq-grybSaTzuMHtERFFkjJ9mthCuRDjwSqEhD2QpEcnPxm-hT2QoUlc7rT4ABlM6nDwpsXjNR4rZj3QkzORKt
hFQ6rTwmsXjMUyFgymwizeRLth3O6nPxiyQ_Js3Z3I6idb1WjJSizhxDq_Z-CdNWiDeRzR-zCr5o7LM2Q6LaPF3_N_pMcU4kRbgwLGKIr8br5iluE9qWjuLQ
Gwt0vw9QWK-6LIYJmT658WBuIm50KYqRdLee4h1aFo6UM2W2R01vNAailvuoCUSwA-2YNOCy9-9yI8Fob8XFrOs_cLSiF2JWmZSRN8l4bB7WY83psgRBPBvo
7H1mOR3O7ZhdxX5FZpTqx__dtX5dic_e_bkadIEUx9j_j6BNdX7FRqp8yJxj6V5KttGyTDE8Cx5F84yPQS-8P_fsrhzsZ3ZpVDCzuUuOyKJV_YXYluYpHHDn
P2KD3ni7d35Pr6PV6ZBBDpAEu-VTmaL--OeIFocYtjifxa84BsXokT6dho3rqccJ8Nr8nVlkRdgfI3sWBuruM1sI6XIAxntLXn-rl3JY25tJaf41xsb4bztX
AuNJ8znpMBySlh9JacoG2l6T8boh0vuqSBYiIq3Ms3SKtW5lUfS8v8uTjepeWXsBf_IrPf6uP1fkuR9LC6YPJDeTy3Ds0qZo3_xrmlyBEUckj072OOi8FX4K
cImxIBZUBxn38jWrUlM_N3XZXNT48jHriF26pOJxjGFihhSHtbA5T-q4hei6rLLd2PUj01E4ToII181Fbi61vrs4Crdu60q4fmjlE4buvp3XxM3XilcWXC-5
9mjlDfSI3fkEIlXSsj72jRlm4iwpXJURImd7vi9Bk0uNJfjCErouzXPUmb72frB2cys59Nmk9Hmbl8H_t5E9UfHmmGnyld0vJXRq8E7wuvV3zmWtFKLu7yEU
mlkZ7o9SzZUF5-vSIUaHmcMR2yUFnjSBbsiDe0N2NSQN2vVZl7c1SB_nnSBXyBr2kDyurmft-5uZt6_y8SBHjXRUy33XQ9iBRtYKSBJjXJSyI3ZQ0S8RngzP
-FOU9ew7oELxlN2_SLnz9LrVSpn4Bj_hXVkDOzmuOptt7wAWCkEhXBV1QSUL9tKyH0xV2uNBRNnvmj6E4jwmkCFHpXBUZUFQdS2Wrd4yv6_Xt43u6Nz4Bk7r
L_iI7W-E5subl8INy41E5wxDXTSb9ohXSPJmkcomXEDmuLR2QtE3dOMpzaifuRL1JIoeFQycKi8NSB9msW9qXl0Ihd_khW6I1ss5YWN21TYlKFE5snAc2oVi
CvmidBO4JHKkn7oNnlSAP_DnIpYZHiFttf80yuGBzZsQ9jmM4IFSmZx2l2DS2nfbSOdZgd1ySNUmWV4zXID6k6xv1jGVGDuU4VmVJrl65E4O_o1Ml6VSFtRQ
CXH-u_cnRtnl01U5uvN2aRyGvuTqZ_-lz6zmR26nmiScsHp_N-2gaBOG9QyBUVcfPF-WZOKZUTOSM1mOTppd1MmfkS8vy3qmpin52cqfIYlniU-nSMNDcUk5
OufmtdI1n0gtnIXYrfJBTmVVZWfUuJHxSSHnJVZjZumXhS9jENcTSY7WTzyZUcD2Mmu3X9lkovE61qogS9ZjrIbZEH81c7K0aXfSJpwODD823gdVCJuU1GZ7
juqYOZHya3z7t34hE8KpkuAGqodgSWJO5SXnXlrhb2lfRZz3lYFYVNw3tG2ZGIc_KH0qqOAI938juj7h0MIiKQuzgryvDFw4AADJ42sy-s9QmDKYZEkx1oE-
K_p24wPCpn8Pz-FTuOo8srS00FyF1WM_8k1j03nh44w8-2VJbDflY2Iiy-saeCI0-uqFSfaRyLzaKss8VfK-F-1iG-GwSLTwnBi_G1ULS31mEeNhdYl_MTFu
-HaGSNxyrmFRe-tTj2RWtbAvFW1Nn3yVWtTjzvn3qG6dmrNGXmHHfQ9Rnt3wulmPimFNCHGsRw8V8mja1vmHym1RsoFY-G5dnDVfkFT-SKt-xYKhQSP4o5A7
Dz-l225wPw6qgpYE4heOvusXBpXwt1VKyDMInPSACdpd1Xngbv5FECBEyEMHCaRPllqV5e3Ib9iGTPXc7Bc50kTTZ23F1uGHNlIcGg7dQ93kMuel5TDxVCln
CY57B4DB1G_oBSTqEJmUWzv-FieuBRF0-US7X3plVtoD8zot0Wl5vSmdIOvQopTEoobmbpEd8kl4tb0Ep_ODEOof-ON76pSjzwrutKqPUn7HQIbwAqSw3-7N
tM7A_dthZIl0DoDrTs7DXMYVK93nbGTXhEuUS2zadd7ZetmZO5vX2u1yad4XnJSykjMQ10H-uS_Gtp1xbDCoV4D1UbeOOkYrFntEUhCw2hBTGHSU21bbd7_c
JGZnf46LU0_PWY4oZ1llwpP4L1eKtBbguJ3mGlmETK-tqV_CYBJJXnKFcN5VRV22RRyhXLP9fpj9WOmptW5rRSzbDgTlg4MJ_di-8kLUvcItBX48FK5XjEqE
yZUe5zrZvzmBHzch91mbHhn3UerZucuBle34Rmegiis7itGtQSeBmQspYYNA4Q1xFRfLUi9WUPOEUUEAqkSBDrxItU7Zd8DgZ-VgXr5uoAUNn4VPaDeRi0kf
bV1rgDe2H1Bus_HIr_u_IfFyKRK06qEsmh_S0e3uTLXXGQ2SPsx1LzKYYVyWAT5tLSldQGqa5UsxgaM2ZG0LvxkgHN24Jh0qUA3jiNFTqrtLSjyNgIuRDW7o
LDiT03OJ7cNRJrMB9YQqgaM2lHHMbSm6BDkp8SlsR5ZJv6oWcYRdWggIkQ1iJqRjaTXKIhXiAjKfj7rfJmIsBweAhqwXxKm9hqwnhK45V38LyCce0ZuNd2sy
8cxRWvC3NX6t0y2v0Q-8sn7Wr81NnEqGK06V3CltPEelFPF1UG6lUTFEeW8-6HpbkrOgilFG-miS052bSWNHd43g1sFzNFnxN9Oenpku0aXjFMHaL5ZX3dS-
7hnGjiETZqVFiXqwXu9gOr2wBqD6ZBvitu64TvPNsRw9o87jTqGSK7iN4ady3qhj3gXmpmNHMPLw2eYo_IlCZYgPiSLq9HoSUUl94iusHZpRTcVUlCV1Acer
ejvKuMZNe2FSWZ7N0gct26-N8UJOpY59kJ1n6hS0D6zd64x87CXd1vnJzofXvl7pfOSNIhuDAbjtbtvMm8NqPyJaxURqt0ONHp8uDMwathb4yOUxm_Ydo9TE
MoVShuASf3jipIXRAznlWjDt8FJFfEH2uVxSWOudMIBTFu3L-uo2YirsUg5fzIh5Ru8NfAk_ewkLSxNmaDo1r0pN7QuvtuG_su4094dz3v9mgCvJZeKHF_Ao
WPNJffredEO2Hr_QWVd23JxXvuMSwtxBGplHEDRDrxGJZI-Shsad6byuOSCEDCw5fxks2rpriIPrvWM_N9WoaD9nLxHhUShagF2TZNFX08xS06FX06XRmTKr
gjCstT7YbJ1EsmG6gzS9n-qgnSN2UTmkHreyRJa2lccfB7n-seveyRIbmtmRLhVeSTkcQQrlmo6-EwjBb8VvDgx-ueYdzFVOkDRD8uBj3PVlByOZT7UuFcAa
-Wy9zuUShBi0rNh4Zg0eYgBuDm
}

sprite $SocialEngineeringCarrot [369x344/16z] {
xDX7gcDH40HH5KaH-rzn-_xUcvIB76jq2Ee-T3YNpKoolyVDzlUIp1pS5qfdbrUtctpQNUjTthTDTFlGRgtVlrhhOj_kxQMhpUs-6LtiM-sUkMsNpTN--Zqa
Lplx6bXwcHlt7woKCfSR_lwEJoyZzooy3VpW0_hv1QY1IpxG0vTybZRuBRdSLN28tDy8BdcW1oxvB4LmnHTwu98Fd10uE-PT1OUOTnUSzUEa2mxnuwGBJiox
2mwZzwV0ZNmfWYi-In5SyK0Ht4CUck2AXoQuPoKqmHLVck2ABqrmnPSckE9B4rpnfGck-D84LtnfWYk-DC4L3qrmnKCJNF7G1FUVhD04Lpny2_ZItPwBzr05
Ltohu3wSeGckU6Y2-t26AhXdd2guHoLLSCL34zmpFbJ1FUDR1VUeX2QuHsMeWdjKjWhkKGdVjda2tAD25ToZaYguYOSgk8bJ1VVTJ1VSeq8LtAEIBhY9KmKt
yNJ1JPmgk8cd2sxYLC5DF5rm4wSARkBfWfiuLN0JJnVSnBagy9n0u5S5phM1UrEeWljifWjkubmT-4_spaH9TLY9eL6fLFd_BtxxSmstkQ5DEZ8PMhNC6d2E
PRb3Z5bhSJHmh-W5tfcoUu5_lSNvZS3tcmFNVsY21k3tpvGgt8FdBO3hnWPdMEvy0-3xVO7p-O0H0Ce0_6wPKjrmFFG2FnQuxWbSqIXwF1ary0UnA4uuJW52
S7m0_hsPmXhU6Zy6gO7_L0bl79q30l1lpXHKL5PyVWxWWyK3S97V1vm51kVJ4f63CGBmyVDIuhWfS8MJ68-B29nV_Xwhyud2P-CK3p_f2N26e-tIFIDSmJOX
jn61S_jEu2noU9n97_07u87t4jqDE8B5GrQCJ7a0FdZZwofn5Gp9mr3103k01zxV1BnWI1xDc-E71-21zohfRi0PY8TG6PaoW0VUtmIS-oN44P8RupioTFOw
tGnu91v3PLWy9EPNhblcNaqyMdnyoy3x-u2h2lWW7Yq-CeNBUQzVA5xQOZwVDqUcCF3-lbcprY5y7Yh_Tpi3xwy3Zk8HoQUXWW1SUmC_rLm-8Su_RtKg_DVt
rOKyszeGpmn_7T_XvBCsS0xU3zLX31Ky3YkItxeQY1MDvMESCywRsg90DV0JBuS7uj7YKVmwu2e0hb2oACoRIFQuNxmVS8J6uq__e6IGDN0CPd4MpPUv_2RW
HMKu-DZyWuW4I3AiFMpWAI7Ob4-kDuSWxKF4HrpewwPBmmTb4Nhg7mIgP9vu0uz4UVHNwFXeDV2aYByYLqYSA2Q9D_3NiQ7mwmBY3JpaIZmJfWv60t-ljWed
ekJ1RE3po8TJ5UAaX7W3ZyGHbcIbZrK3VmCvmqL_-b0qy3VUiVbMI20GxqlxZ4W5tbC-OxzQ-8u2lUeOR-3vHAwFyGQUYIk60O0tGwM1Cq4EyJ_qPfCQU9Rt
jYL2fU_QLnYS8NHCeR8UEAuw0-QgcFMXijqU-9O5ZefAfO4pLw8yVshuBNxxFJbvR70f58KnLD0ByeiYN87cwYjyke7B-L7gVE5VlTki1dvOWILE7lssmTF0
XG4pSUxwhS3X0iuNVImisM5x-st08s-zY1E4RkdD3TAJPhGlNl6MjHYd7xWCcx8h3AY3_dYd66_Wd8hlnxyxBOxjzY4UQssauvlswytjxi07hMTnSMoo-DOW
-O7VVzRCLuE8dU2ByFk7E5xnFloxCgLX0uzxSUQhGLfVfurnTlzB7yHgC8gnFwppvhP45urJ1VicLhXvBSurm7MrR_GYVcYz5R4UEAyz3-ZuNu_ZNOO8TmkN
dWXp2w-Y31RV5kdAr-2OMNYroE9S1LoNMHmw-dEkeF-5m65UiCpSoDBL5j-MwReNzfdk3R_5kGwuhZiRJaw7ZWlyzS1nuUaej_0gaVM6HB7foY9NgQBGRt6k
12u3yPG0q63nvS1nwHrnpHqXZyMtfTgl98uvpy5YSQu5haj7BIR_ss3nrS2nhoOk7EsqRqWKixIEU5mgOR0uLmF7lfGu0--BBRujrxwAU5mgOR0urmEddtYC
RxXUfiLwuDYznFChuSRH5eF7VIr96APD3_78ssDnpWvv6Ynk81uNCfiidd5tt4QqMd8JZmkPJHPdsdrdNGvAaaYJnMDZTHGdBekdU1SWXuv7YDp4aNjg5hUF
RmzsdeaCUYmUYIVZEtOBN0PdHJq9lUulMOXpAauKsdUzmIigU6IU6hk7UE2Tf0ENmGk8vzur9nFn42T9DreCpeft6Z9tD4plYcJk6OMwDs_cUR7YgYdx_FGG
dutlyK65BeEV3HNleCqtLlcNR0CDmunPFqWY0XY98ybRFtvqp9YdBSwP_fBjZKp8_HyUKD4VA54wyo3HuZRYJ6_7LsRn3E_J5iTSV_53YElvvw7gIeEZfDJX
P7_j7qASsA3InRGikyzuub6SnNXyHimVfEi2HIMtw3ZT47g8J_CB5gyrE5Hp-SIf_l9ld463nLEypmyMWD9iV_dtXg79ueMyeqS1dHaWz1AtM9obgqGORk-V
MwOXAt4OBCxQ-xaAsNyEE7OhyKrNMrmrqsLyF9OCD_ykThpOukMBpa9NJKc9LXYBbNgBiyhUG-SWAH5hlgcptkAiNrDPVms6tKmS4zQeuestcPsqPBOozK-T
OcZfh2zLZtlNoT3DZJR_rCdG3vmt0-fm3_4adKI--QREOxhJCmmhS4TW9qt6nFM0QUgC_N1gscG2jy7WKUH74DyKa-RCjCaBSEyi6ltaIkBPfN1J3MEaVGQt
zbq22c_Jq5-gn3Tg7g-inGHm5fkR5zmN4tF4_KlXvaDSWNRPz5vxvbn5F8X_euXPte0gIzZoSyT74ET-0hWApEtyB64k82wyZW1Dtnk73FkdLOZq4e-VddG2
k4AKrEXY9kGwuZhyXnnlQA_MvGKpiOeuiv_e5iL0kqouVjYBeUqBxqfaCfJ5KUB_O5lIG3mrNpC1_5g3OBeo56cWLXqh-GYNB8t3LEdruSWrY9DPW_lRfgbA
5xoBoHb_-nbcs9Z3FKH-Dl4XKl-92eGJNQ47X4dQGxm1yI3iQu4dN3lC4GNU3ha-OtuP8laJjO0jw1xHGXJmjeqy0DYokWzoQ5-hRL9tYnRIWDkm1T-TeaK4
ob_vayGXIHRUKTo_GS-dDP2KbxS_MloIyEByvUBjZnQ_X9pf9W_kQ3aD34oFZ8wM8dkI6h21pI3ossX7OHfrHukCo3fQP7HeHuk4xQPYHubRODDsYspQRh6d
IRUWdYQzGaU9LsZQPkapWNiXD71v8NIcSFkz-aZWs3fJEiABX4uKinfuPyhsguKsk5bjSBFK1lSA3TmiTQ9uXJQuMMg3UuKsk5bgWtk5DhXPQeDxXJQuMMpU
PlMT7hFG1ZTBFMEQrGOt2ytRBFRY7xDq_m0707IeP2IURhw6OqJsSl7NEaM9AkX1BstjwqLMMeLjxeJ8kiOBJJiZigprRDgbSoZuglbet6cH5QrlsZCYSNQM
LzEUbCW4xS-sEA3zNf98uZ-YvXgFDhTNgFQgzCC5QDf_YbTRbSnNKNcrmq7dHqysS2Qk79hsl-MRzvYkeloIBTpeVEMQ9ymjRBoM0gcx0D_Juhkqhxpj9XYd
yGhUykqCGuFdG7wsmMdTguJNFBuBUdMW66XGL-CkWEupk0C6ZJLnBNHzReABHp1ejHkfJojH_9jCiUefdD2v-O3Neo1DkCjgHcrUuFKaQDY1i7ec9Qk1Mtq7
EioTW6vimEfzHa4Pl5qPQ79NAVKac82kqAFBa7Cry1BVWPI5zH3NN6zYeRUZ09Aa_YEIIA3s8_zdU-TX0Z4G134MCNp_7NyP0kkc0CTD3gCxCSIJjW6pRIQD
6dX_pYzfHiBpAYpfHiBxbuUa_-kyVatISIVsQv8UHs6lNmC8u4GPP0tjM6aDQnf-4QFiOCivsgT7sM8CcDc3mc9CahFxrjKO6TXbT3NepkH9-6eGcBFdX1nL
2lc2awCSJMvREMpQoMthSXYloMrhDMpQsLKqXqsRdDINmzJPHPGQ5X3xnH4rx2LsJf_0sbA5pXT3sBKf_1232OlnQq88iRYE_OGG2-dfwUdfwUaF
}

sprite $SocialEngineeringPhising [369x342/16z] {
xDg5hSDG50HHhrPNh_-AFpD3Cg4v9OpMxErK96ddrdeojzecsyuewSpwrapxp-vAdbF_qBJRN-YvzUzXMpVsivykNNcElU_eodDjhhdRFj7crdxs9hdIMS_0
cJjkOkRcfZJcpYoEPvOkaCcp3gBrP09hpGshkMdrMdaMoPstnT7S9iywAXFd3QlpXeqt9xHwSmAhywR5th1wTmAhfszOFPtGOczOx0shlM7rzWHMUyDgRrZj
3QkzORKthFQ6rTwm-hm3gxrXjJSizeR5tgpnxnFOU4C8goSKMEqDYxrVypH-tTvvA6dFwZ3O6eqczt_5fvUTtz-xX8sDis1DtvB04o58SwxDn3Pu6V7ctJ6E
QqFfZ1MuHE3_zGexL583HS2ueag72fBVSm8xLE83HNZXfCnz0mMtzzAXiiX9K8TAbFLmVqzjSQQaDu0_xwij7jubI1yh9gFdJSPso0SrMKmSUnbSDuuUIubh
AuFh5aknaZXsClZTqwTAujh8uFJXFUur3xPu7E-PRki0Y-SOV2ucK1OgsCNWSmHrlCKP5IZJ_Jx0ufa6Py1_v4ex65m_s0uEi7Y-mMSEqW4fdhv4yTkH03E0
bnEEMwZa6rpm1xNUujpc99Fkvz_k1aN0hpqInPFZO3ywDbEYPY77Uq2yQfsYNH9bt2kz8rDGRF0Ku3JpGZtmUeiZoYyQzEdZt_0iu8m2xWm-EhewyyvFs2fh
r2NFziYRcym1RXzK0jnh1-3uJS1Hc2X70bUXmK_8SA_V31mJm5cpIl52OQ8Si0xtqcx0Bup74yy0xWbKNKkX--d-cS90io3XQk5smAy76e7ZW3TBWQlgmbLM
Y7lY74JHdi0TWvnCySYXmQtdrSBl1swwd0YO0TBWrlCXm8FRZWVFLXoHAOXkE-SNawQ3W3FyoaJ2CKhJRmREwJ63Uk1uOoc3B7wiu5qFF2CGESNRT5IPe1Ix
S8OthvE0CwVrZ7a1Ary5m4k8uoqbRl6hWL-yjsMvFpi7kAxbn8KwtlKFYgTsW1hWThptdpKpBUEP2t21TXPmB1Ya6joDQE0nn3rMlh44_mvLVOKxmA6hWUTC
dT_yj5ue09wCd9bbQHguH-w1GzUfm9M_0F30TRr8RE1nQk0D_Ferm0M0N0IyWGjPixmQ-6YH6Qa6FeR2TE0DF7EYR-1UQKMm6_YOTpxm1fxIw0O-DZYG2Bo1
-q3H2k0D_CjoC1Du0_SNUNE0iu7_6SUL2Bol5lhnpXN06pY-y4u4ti1ze2G2R-2U1LS0R-1VU3lWVTS-4BWFb7s0utt0FMzb0hS6xWDb0V06JjV4BO3Rwu3x
G4a5hWRk0YKLE6snz4xWSBmpWJTmkX7eWFThWu70vPgt3t2y4JWSxpJWri1Te3ZWNTmW1hZdpNJWjENIwu0xtgd06pXTsYK2XoqNNWQSpWgPmAs1kq3P3RYz
2pWTxqpWj0BfJS3fV909l87B1KekS5Y1y2BWSBnpWLk9tW7S1qe-S5g9L0tSzvzR0-TRWBiMPGE7bGZLm7sWB09kHQe5xdbp4N1QaVGAu8xtli3n1k1ohKa7
RcKg1ExjfbN0QMNIYu13VzM6mF4Yu5vA0cw5UW5mhGPEAvGQ-5gX7lY5nS2jL0N0dTO2fvLABm2kau3ZPPTdyu5RiLG1t8ia_gjKuBHYeHgu5pE1MxdE0auh
5uy23YiNJWBEUqYaVyyhM31jDd1cHn2oWEDzmE-uswsV2YnU3DmSy3I38sYY1IL9v1ABlnRu1Ez7oA7lHuYIWMjgGUGJ9CeO_F5WvvF8OBB5lICrjn_B0lva
YOmvUplaIHRt5ftF10q6IAB18rRmkBDhv02N-y4C5xeVv1iyWFW75wLQd9-0Ou9BE70-uEsOJMz42HOVXu9fWeix0af-CvDnPqtZ_JC7kBFuXC7TJmeCFXqg
zniG2TnxahTTogH4eOsKFaZWGYLlrfJRpR1F3XNJPyp75kVCyTA2J1aJn-T4qUf0yT9u8pKMbuSqEUhWKQKQd0ykfpk41VCcFBUvqpavLCmqE4AMEfmyNhaM
nynds1bhS8RTPtombTp5kD-cHbRW7riIqhYu2zHu5alJ_p7VCFsPkBozdLNSAZ79u53CwHFdZvVYCmKV-islpPFmeHdk62JmVZvO04e_ELv8jBZlEKXA8k0E
UwZ10tbxZm9wCa0ORt6xxJNFM_a6vvEjETZpSu3YBOufuj2VlCa4tey_W0Wze98GAZFF7Gp-bg4N2HyXqxCsqH93POwu1y28G0b_wCorT19A8d5y6BYyvpUc
1SeZPizQfCp7LFHnc-Jd_djKIE7D1qD6eICELp9npnpGDwWoUEF7p1vQqbA9ytj3IIGbPNrzMl6uBpqCtSZH5iWD8Ot1OznUJBWHaZDn6cPSb3TXGW-1FGCY
9Z_VYNbuJEFjSUSRt8jSHXnSzorx9k2-63JwoKN4ZHpWHXflFC6jwvA0n2evI2Y3EK8kmR9uGq5zYECY9X8VCvSGDyZaQ8UDqojIP0vn-V5DwWjh0f6ML5YK
-4rUmI8YYO-ldo3qpDlpXXAUK0qMiucF1ONmHYITpFAQf2UUZpo8aroKnCWnoM2EX2PduFQyeN0awH_F81pnJEGne1X5smiBlep9yBQBWtUk7_C6aYkEwieK
gVZ3Y1ZQNY462InOAV9wXqGI-3Te05G89oMRRtBr9ZnQrhGqTH8ik6jsFrK3DuvnkwiPqshTFHKMWiwT6_ZOjVAqErh2hi6H_8fQW3brjCIVjW50V96nbWK9
pJop15z7YoJ-Jv8IUNUq230la5GqxuuM2OF-AuvtHulmm7I2fOc7qlRCnoEZeoN8dgJ-3nksGEHfjBqmZRgZHGkHTRIaXa57Iy94LoHsb7IqFANTqTAqlTZJ
v6f1FKsk5JfA6hYZlPNqJk2sL0rSjbITARHzzKhWi7sbZl3E5DhEQk2TARQrq0PVhAqDtfdI1ZUS3RmjRjiB9nkyBMu72ESQl2rkHmYd6hmjReS8RV35OlDU
hBxJirWup-0zRzfPQeCl5exYtIiLsNdIxmzm0427ogFoXrxZ6eaY-t7niHvHejmHV3jjNVKY8wt2DdSeyt7ZXQOTodpSUZRjq3aK73KVZVkso8ZMD-qvvdWw
owjfJqhaWFRxBOu4tBcII08_gPIDDlTQ8TghqXSNu7JQNiosAZbUHSsh7Gwk_FHa0-TmRc_Q_zQwUOzk5VKUQLcuSUMLQpumjs3CfK3gjm2VsDrFQMVUTXCM
JkCM8Ash3CC5dWFvReDpQQqIPcu_7tf2e6JJeB9nE-Y765n8toCMbvlJUnDS_0u6bzgDrDkNAFb5ffYmYtJej3pW-IZ8HRZ3reooNE3v99XLWJ1n9YKJWUVx
3ipToJpq_0PKrna5bU3jp41JzYebdmHlG9SxecN8MGqyn7SWbSdQYpNdcoZqjXT0ajI_H18EzHkGez3YHxusK3bjsed4QMMXeYDVHgAL4TUHRoEnxbaUsed4
KJTVqquaNZXVqquaNZXXmmuapiBJNTj5h1hMfCvyuPU5BWCf7VT6kyfTfea8Fuau2njmP06CmWRGjXAhOrId5TrHyKeOfnM1GVKwuRYgKYm6pkEg7AbusXeQ
_BXGATm_RKUfUDhIORmDrIbwNDaq5GzgRCxRgpf4UHXlO_M58vwGtsFYgfj71DjRBAylngrnUx7UOgJSWuGRYwijrW9rLLkirMgr_Wu
}

sprite $SocialEngineeringPhising2 [369x341/16z] {
xPs9ikEi4eDHgLIy_nlV-hVScN3QSQTnCpQjscToRFYi2CoMTXS18FMN-alwIoI1Lff8cbB_A8aCSo_MKlT9PFj6fO6rGs6l5so_pZgz10Vi8FGI3DhhcPUt
rpClshRUa9T00_TwcvUvupOlt5aY2ZVKyrJ9mfweGew-H6I5IRB8mfqi5kviiThAHo0lUnVnLDo57FsFab3sJXRBtibITKwonUgS98jbxsoXU2UBrJkv2_6A
xoBEVW-XU2SBnJjPBDx9OdLFaiNYNSHpUKklBJmWMSGlvIsWlOiiujVm5bmDSH7N9DpvoBaXRopjRd8ttlJsy8iuW_OkuZvnTde3oNEat8UtlMbJHDwB5JRX
pGyZwMGHlumtzFapglKJc5H9c2p58Zw9mDdBCANbvEC31QUdGLN49_2c1o8o-kFOf4D87uoT5nvE-GBZnq5Qa6ymAbGc1Ohztad-I5ox4cUVqKFXqMi-ZQ_4
bZ6EALRYy6ycSYHON8yVaZLvZyIrzp0M-un4uUUQShJuZWkoqESQd2SUhJBMO-ZHSshywJKVbCYVxeMCxKDyufgs0uDp_2SCxjjlbUSS4_6uomVJujfjfnil
0ewVlOPKu1sFuJrmioB6-dUbx07L0mB5u3WutgYw3E2Rj9kS11pl5VpyoHpW7Syok8nePXy48yItsY7EMTNXcszfVzG0leV5-rN0vG2-aSMv0_2E1nZSpd0R
E5S1rtCCRZUQC8730Bw3nVi4jTCOZV190Aud6Dp29YjJQ017tyRYK-kYWQFZbNGFY_CQu1Y83tmDu4-t-5ppO70JtsfiHBZw9XRdvAeSBMKJx3csdY8ymE2Z
KqStaPA0zf8HCPUB3p2ucTaySzViGokU0ro3nMtY73-opHasywi2nqAWT8DtFUVu6Nsnr8t9mDTR_99uF6ob88Ft5XP7Tyg_F9m7-zhQTi3PPmh6PKaCl_qu
67oFJBdAFFJrYRNByTUyp3pqy6PFrOE0TyUbiUmOU3mWKToxBuMX51ja2gyTgw3ZOwbw07039IrxB-6zFbEk7uy33Tm3xoqo9MK4b5H_IOBn9Ti1EBF6d6b-
bzMN2Cy2tdaIEDIt0jwl4yy0PrybFUzdf_WHEDGt09veC1u2X_fAuL70xS506BZt09xtpQMnMcYlJ441pnLt1juB-FD3N0KyLtrhu7ewy0BElO7t0fui5F0Z
IG2eEmFNdO1ZlalOajLl11mN-4G5_0plXhi2nts0Czxs5F006TspNyZR0CS5LYdWjdXLqL70ZmC5eL0fuFupoVb2VqVWMWxSV-W-fhg51Vm82aE_O530tO7o
EoFS3tXV3DmVA3qMAWNSlGbeSgYeW1y7IYHK2hW_K4AXKi3zWH8AbGBk3fJveQ82VW0s62e5tBijF1Wg1TmTAFD3fO3RKCEXKi1zWH8EbGBk3fJveS82RkrL
YOTAZHRwNZ7ZeLB0_O4I3vK2xW-KUAWKS7-W-4EbWBi29HugDMll3nGRc2B0QwdRwOwhWbLf1Tnv-g__OEO2Rly9-Al-3_aNHO7N-d2Rm_7uHwHi1Hnku8pq
2ckF3tE15_3k1bxR1cF0vGIkcm37Ok2sv0Akw0Q80juxpm87kqTrk84j_IqOmA5_D7dweSvBCO7VRUri0SVEXun9_5TA0zus1IxXpMiWRU3zpi3RUk22uGLU
3PnjWRGMkD0E14u5Ni25zacy43ZQ0c4XSBOpucN0snAj0uxcqNpWR4kaPS3Rdi3vfm07-BU09E1eIuG_0JYa_ej49W1lYvGEd0Fj_eF8Yu6pBPBM0eTi9Cy4
ZYJWC7-AmnRHNfezbjAMQI5mE7o8yIiJ4TioAHSudJqa6f5qN-18EiBOuBq8U5kef2ECzJQDAEUVlmDNpE0BfKJWyDvLWoqGzCbwuCZvwIIuVdFQ3f0s0tXR
ggHMyv2t0FpzALA7AvSvmoPiIwMSLbFTv4sqNqKDP0pBtnCuaaASnWtL1e7MtfCfBccBfHJWLeD9SnnJpJHu2nhyoHRNWFBaCEaG-RCIfIrNlrHmyXuricB8
uCl5JE1oy-RSH45hEsKAhRhZBncbIpBuE2b2uhxDvkXDZWFZ6ddqb2RJTWLlRN4EDHcUE62POOf1phZRc7zQRd4185qMjwfEIhrBWjt6SeP1w71VpEMW_X8P
jFZeNVAqnUceXC4xc2aEtY7aqF4tHA6qm0Vat_A6ZBPNrnbSVGPnVVfZ12j0ztaptgO5KngTI1SPJdiV8rUm2yBf1eSE2doPmMVqu77creXsGJ3NuD1XSPLd
S3znWzHaYzjbvP71oHEuEvCsUzCrBkIyY2PRlCcHAB_UbJIMlirkSnGUvA2Vjtr_HYtUFXJoA6L8uYzHEgpcgynP1lU7ola2X2rEjy7f71gWPzkXtvwNVqam
xUt7fi3XFts38lgDTmJub55JXAwXoKq_d5qK-cp9q1G4P_3kybyaRd7x8iTvupUuy5uNVGty3E-mnU5xNem29wrQqlUoDE9kzAoUzHiSKxewT3wl8F0Nyv6O
uVhJk1jZwyCvRPxHUvNvdN4CPY7rbz0-3XEI5krXPYu6VDu0DMAnvFYBmEiNZsx9jyfAmCWZ1fpUqIPRYW57-0tVExh0WqrivEbvpQcyunK6A7tpl7359BYY
9nzXlDz4Ko1MOq0AhTDnYKxUdGk0CzeVjAy6AUfGNJedovOFd7FdSpNKBGOStprjwkV9EreTSvxWp1aPhWzsy4eJneXjHDupqqdyHiow6qzr7JGMoM-BwOlE
XaVbaWAbC4P5H180fK-_xY32W0szFXy4pg2zHmNi7JrRb8xgMtjEI1Yj_XJWZDZR1gwfApNWhGpTlD-b__JZNsZm1yEyeG0nzJ1mFt7Xwv7DVbA80jTyt5rN
h4-dR-GKeOaAM-C3eWyu0hWjCRehrq5SvjYIvxjD_nQuCMG2WG85WVMGnFQJP5G0m3SP11TlsyxmX19Dt2a6jqKwY4VdyXXQrjKSm7a1xiv9EqR88F56Jefx
WwuHCXxUYE3MQ-2u1-HV_SPc2vGnbU3sTxpDv6Hpyu9DQAA3k27mzOOf4KFoP05NbBRT3FMP8kEBqstnkohA7-4AHubzoJvPnCV05V6g2htBflt0uLvWeOdc
zdT9_Q91F6HuV5yCEWT6PT0EwifzhQI34Xts3YnRb7TPCQ0-KmQJkSpHPo27eajUWDFBFnGqjwtBzxKIfv-dYFa3S_gcxUKashO1qA-Jw2WxYRal6vrVyGPq
4OsKhTkakaCY2HZBwzs2j_5r62HG71UEVYl1nrjAEpFj_9p1lP3JvfqlkSRqXM4s_GuYZUPtAV36SxXVugsOmnWRIzVPnbkOCcjTQYTSAw4PGZ6FlXYG_1Mr
W6R97oqbDaC0C7_GjDJygcZ9FuAleaKINv9q8U-A5W5j54XgDk-A5WaVwgzvl2jQX83fX7QPk2bjcxbyk2jQ_Bn8cTj6ArfYj6t1ZRgYHOd8AbgKwD2A5Wdj
fc95IRR0efqjicXdYzLCPWkgPZ9Ng2Z95OfsijJ_IBLK5N2rL5Mci3rNDrZn-Iof8hmoXUt9Ak2LAUtHGXayMMNmPAaCdYli3RmitXulx6pmidZRGDZNu6Nn
jeMmgy7BucqJeGoUB1RlPDLCJxAmdy6htMnxgGoUB6p5ktegQlj9zmzm_AKAbJCIMr3Gop4YQxduPuKeKS4dc4zRVRt8cLPXcTl5F5vueMYxcCTBpw8zjGq5
rO-5mkqoUhpqHTiZ4j5MNaNRAP4sxPjO752_boIItnrZZZ9thZ3Rgz8lBa3HVXUljYePw4MPAeU3cJyzMS3fV7E0-gRAQ_TezgBMIsdXnioHQmRCBJHUIu7K
NO0xRlSjxIkdtOJ4PhnDaF9EXc62vq3-sGPdwbablERwMT1d1qe23Ufgt0FqJGmkN7v791ytfpytmKKqMqor6wbxTb7yvhR5MRV8XCws3dWS1Pc4UrgVKMqj
y3W9ffz066z9oON0uxu3WpU9GqylmEfpHa4bU7jce6brBoLEWYUWotgY-SYv6lWKtu5K3kjuJwb5X0NUjWMG9FMtIC90lHOv5bfyosq3AvlDjYDnjf2mzTOE
v0DlY07Vp-HSjvQ7RKVYMDTUi-r8V65xpROZyOKDDjg6nBdmTRSzHLprjIQrvuPVBdGPI6cx7UrQxZ8v8dmdubnOW2qFm5XO0BP7YQjZLBiTkgF5FM7iTWWC
LlSJjZjLYek1SxjJZhIusN8OV9DGMNX_jYTAYvijRSQxONMARdTicjRoRjYCTskhGvIRyMvSFN14ur5lHbphsX6XjQs8vzUPU-1-YUijHkgra703CTjY9L1z
i5YfLFeV
}

sprite $UnwittingThreatActor [370x342/16z] {
xPthigEy3aJLrTMbzt_ZKz-DkUtiOuBSDa7hzqom5urio1Q9km00fFuX3_GN90aWcYBJb78CaNpRVFD2zPZuizfRjfHN4HbZjEsiu_kqDw2o7drjlO5o7cHS
eCFDY0Y-6_Ncz3BvhpdaQGxfhVjqme-KpvVUjJiEyZtOkbt63yXUArt63zZnTXa_8DjtpSevZjY-YtQ7ux1rbzu1jNFcZh1zss7xjiFsROUzODfX-tP3n4UW
l0_i0hw5youeGWIPSn0wu2zYI5VCUyLyiK2qSytMWQxc1mCwYf-FjtEcqtWhXz9fl3Sjp9d0SvWZvdsJgLyZtieXamUc0VHT_L-GliTZRE5ksCzbtMXduVcP
i2kA6xPmDumMtigLdurwa-96s4guV_9Wki5ZXNFLme5d2u_GKvLZrRIHTlZ8NM4Sv2ELCnzbFBcJS7zLUQ1ohhmNOJvA-VgKCHU1rSBz46llSj6FmztW0uGB
REN_Z-hLaFqayNkqzLee0V4t8AbFKCvAuTKVAan_wHblBlo0zRuFo1ihvxHLI5DLW6Rb-miFbeYmI4VOm3pXmOkTLne93E-cNFE41o_kR6YyIXKcE55uy5hd
5Qspu0S83rxhlA9t8hGBhn-lhdqZ0VDS4FEf55vlt9wVc0xd2eyiCEwSaCp2wzDniVCgVW6OFoTwT-Br8psHgi4RM95JbUEUHVpWufD6V1qG4TESorbJweU9
YvrNUZrWOjBKUAUTU7tP-dR8d3CvtBYcH5H_il8No1b_aNt7VSf1-KTh_6npirBkURHS_zaSFpptgYlfY7Xu7aUokhBSD-AXl8g6XixQQUgsmaCpFXydXi5T
wagQZ7FE0JW-4EuHSdggU0GgEgymEW7MpPNtYJZE6kSXPf9oEEkAF-9a_49DvnNYYdCihokS6F7VHweBFH86vQQGvyI8dpO-E2p65UTO6t9E_1F9Fyu12eoV
tOcmPixSCkBySsA8NwYfAg-LSvvoGyGl3-gB-gUopYkUc0ygxiMuOSJrnUJF5d8E1q4nxfmLfHpxHPp_tpWgEwyuFYaMJ5oRHVnLpSR40tBypprPC7CO8dwb
ZFFBOShKFmA-KBuuv3ctg0oKbOA33WQTEuISCoV_OWCZd_88wlM_r8gGp-o3PAQXh1mcHvAEvTiLvjmoRYWhGpytY_-iBx_Ndze5gNIKbV6x4_p5vUbZfuZp
rUd4ro6NfANDQVwl9gRc3AylHOb7sZZUUKL402HL9CF-lJwd6kVWfOZ1ktmXuW3KTUV-BuFclhA1e-iDnpglHXyJ3kF_afbpZMiu65yhmu1AyefpfJdaocA-
-NWE3oGEnkP9UzEdzdb7q7SrwxBnK-R8iQBg3JaDnWqPVpKLOjhyPLqtnmSo_ghfeSuhdDOdObBWuYteCuup8pa-vLomgFmASiORrR6bSGog2Wxkn_dcX4GC
-3QKbJGO7n053NTUyVqCYGJYBm18Ixh7QJAEbwf1dPsxI08ba_A7VFumlXaPeBo0oDNAupGq67yX758MGAnK3gVnyVqu9__i2jSfbw-eZ1iN1tpNE-UUPOM6
KM38TxrpR5bMw1x5uTlWd3kM5SDvDtXOgjmGSLiZfn01NZamjoihT5zfEA_ladBjLbRSW-0xycHGxZ8ESssZuTTfPD-m8CQXTn2q_0AJnW_gDoxh89Y5niUL
QwUoOXq4RRzv9NDTYM7eD4xZRrxHMrUmWV6ik9vOrN6fRSgAZATTtj-ymaXTyHit3eBfHTQGno3q3OBfXiwG8yQWRn3f1yQGCyQGRH1CFpA6N366xRGZLq1Z
o6C8sCuwSmdmdNIiB-Eq2Hyyw_fquzQ8hm-vOWHj7t4XWZI4t6JS777dNRu_vAiNJfL4_7ewQJEE-ZBkBoeiS6KgA-kDbnIlE32K5STTf_mHznjN_CJgfTDq
mhNKUC9LLjOQZoYj23HioGt6OTgf57nCrLYmTkcahwXuz-F-ihBUE6fgrz5vTGlZN6dSS9I2icBVhCXKnfVp0ECqR8WAoehTU3x5E4s5t63SKCODXTnc72xZ
ZodaM6PSXglOi5cr6lUNSV_IwJTEXt7aWVjRD_z5nsN64GSicGCBZVCpZ8kSiN2oAfYVPbo8YA3AvuUgukHyOleQbH-8rLMpR076Pnd_FT6ASLD-ux7SUFqT
7GUcPwugtDTuGSDDuVGKKRzPqUsDu_UFPKHnDfaVONpMdPO6Z3iwh_p6qsJymfC47uynpWsDqsoyZKDo6M_Z1s0RjpUuierF1OR1sOpZhiP3PkDjFDhum7T0
fOE4rxXCnlrt-UE3lFkJh7hZPMF5F0T-uvfdd6MNFuR6ryRZO99ntDzuSjHu6o_hc1Hve5sCwoTGRDp_NJu6FjJRUJK-tliRHrQYkMBsD-vlVMTrnFt61-GO
ke8jdLT-up0Ozxrie8sVB-HjFDfun4txW7Ilie9bnjN6uwxzd76hib8_MBznn4yymBYXBzzJLlp6wJMEtB-i2EL_NAAFC8v98UTaCJI_3CxuLc1_vvM_Ip-S
ndFohHKc3JNDnfLbO4h8PwZXkirX1AST3W19QX_Z8ec_Y7KBPmHCFohchoh-FuFp6zUC0wWkZF4L_bU-Jp_WDhj3plzhbHX1iqCkO-VLUUFhtx5V7t8zv-_7
wV-j5Dsar-qWxsuyMJch-JgKXeNJVvgrhN4QhgAOBeIx6iVqWId6uEmmOSyoJalTCdLnYuI_a8_h02b3tNh9FY-xk_aFdiKeChorT7tdrVpTamp6BJDaIIuv
Vs5XZ093MV5tNlcB2cEOj9SLV-ULuPOiuZFAIXniNbGKiMzPyHl7LaKbO2WhRkF-eeBOggp8t7dbBoePwusZP9egYRYxgAmlAx5qFqv3KM6S8WrbnTbvvLyt
CsBRikA7dgAoMrbH-l4NbN7oaqCUlg8oZhmXxuW7327VEU9-us4OYDA5Vmnn7iqV2JhY1XrO7dAwriqTrquiwBoYFUBt3paFMnzcFD8GSaVdbLzundl847Aw
UoHYkuYxluowucpRY2FUH8O4m63S7N75ky1HvMIeAkQ8CsBha1ixh-ZvC_Pu7pZg77sxmzWzuX6MGYTNvzN-4O-W8-H83zmruWuPCan-rJ7Z6h84GVucbDmf
ufOh7cxbt3ZY5XUod5Y_S4Ri6d9QbTFLKHhNaQUkqBDgxX_n21WjtFzGKO5CUU2ypgjmrHH61KYlylgxVEmVSSC81rGKTLx99vnHXAk-1YTqNYbimZEgu5RA
poL1ndS2CCgGRP0iDaxdkrsY3lXoWLBZTBveX568ZEDaMUULS5lX0UUBPLZKUKNlxmr7BNGg3nRinmMlS4OnyYhdnSuh8Rp2Cwg1EH-yuaV-romoof5zlDIR
kX6V83nYnOZ9KzhrmlPHXAOHCy2gaF32HpY_y33K5TSVwz5mpfp2nrasRbsRjN8oCGkiKew2_-mOTprSDVOBEPDJU3rQDFg1pYjxm0zY9iWrYHcuouTvJtY0
c0fpXNCET5vnZUzaJCOp2yOl3FL8_AQRIWUCwQG7ujLPVbdTum1GceZv85s8_7w9_Eei0P3I1iC0Soqmd7kdSBzoG-ULGRXnzVJ3NOGhN21zZ7TU-K5ObJSC
8yo6OOKjFComXRjHFXc5brOUNdh3WbW2MlXJb0iHv0E5H-2HT_c8XJ0NiFwrjmzJpkLNsDEKny4ZXKVmKSOP6y076KTi0HRDciyKxbUkPH57R0CUiHz7R0Ha
LSu8o7-ZknVgnxDks5z0k64Blwdo5jxA4Kvw_HHYPzWLnGrRk1juhdEmAugxGvYcsvvMJd-hu_v0bXu9JqNfc1lVFzBAZSOH4UtSLrKKjuIJRT1KmTiv9mjd
t1Z8q7dL0H-EUT_LjtF5Hm3sSratRDzss0NS3jkt7RPlEspVTbYcYBO5ivt_fwXrZqAP-e3Qzm7fUZxUlW-urhY8U1paCkD2F1HUCzwwFK-vUELywGtVBVrV
PxYYkwNhTCffMYjx8VNNxevwQRWRaANP7hBTi23iEckxmRlU9Rujkm58weJgCjTj7YIflyW3_GC9Y-ccQPgc-Hy
}

sprite $WebExploitKit [366x341/16z] {
xDY7QG0m40H1FSVn_LVid4ZENgUT4fRd13g_nCmalROFUYLNvkZJCgVT5pN9-G3TT7wJlkVGDTFkE_KjnVMaz5SNzwZtam13RceWkAdV45pJ_JB8XflwGNCU
s1hmqDlM21SyM6jxPsc96q9AR4rAR4sAhL7nSKJ5moR5mqR5moR5mqR5m_vTkJriUtSfvfxzkUgAeCROf3ZPf3ZPf1gRL2SRDSOcnTYa69iKOvDYR5ACJOgn
IJ4sASOcnTYaCVRtv_OZoY-gvPYx-mV4qIR5sAGnDcby8K7rXIJ57I6DiKcEDgcUDYd_DtQRp9NBziv3oNLSYQ6DGg7u_r_ymaRFtlLmPBJOOa255tP7bewW
GrgMwN-k4hYbkk_b3CJxWDpC9RoDD10_oJt4kH5i0N4XeFPmoIsedx3cYNQejjwo1Z1qPx0yRE6xL-BOWYz0sr08Nlzx4zMQUEEOoMLW-xeczMOHRYxgaXBM
_O0h3fGiOjqF5optmmm9PlFM6jNEB_Plf9dD6yjL6-46aFW7OQRYrcBLLiwA70geDRArNDvOgjhCNhvRQcGURgrKRQGlD1CHGEApYLYcsafdtPZT2grIRMQm
xc-I2vIx77RdHX8RSt1hYMephB13HYqBDw8yQUCZh6w_fmq9ETrGL8TPiFbnTIw1mTJbPXRipu-5v0KxOURxt5cmlURm1rpWurRKXZcmPNyUnMu9HHytPgus
Ns4h44u0wjjRYPHT4TLNsuUTvKMr9WBnBeAxszFIpeVD7WxOxKOK9WCsMrgrk-MJpAzGQDPg_xeD-UUUlHrsSMDEsYyApQAjbotq7lp1VBHzZt3OcmS8mTTN
daqbj65Z56oeCVYbdfgitBIbxTUcRmxyTIxv5TXaj3CySckvIRP6_RrjlfvMJAKI9CDkxRv6wCl_fEEIwKJovcpnlgycH-3b9IsNOAelMR-l5cyjXCY8plb-
i4goFSAuX_OBKtLE-7DfqwGzH8WaWVS-m3GgONArCVG7fFHvkJ6JjiV0XiG0fEzFEcPHIQv7c8owDGP_SDOr1sscLfitN7LlGFhbBgFjLpiVDY_vLrE8Mu-j
zZKZO8e77LAjdJm7kRdSceisZKlJHksNMvFSajAzrlvCQth-CCd4QhEWsDQq17Mq_JAnwchJXr94tPJ4xn8BD6ADauh1yKIIJzlvJ1ThqdxpfwoU_Z-TDeng
bzFsLH9ZmqpQAZZxdafGHjk_R5N-4Uc2jFNsByK14sr39TMqPOaajTvKCwAFoiFdqyPt5oq6x8aXxbhQwOgKDpgwAdds533zcfKtVDZYNeqsUxIf0jXDAzFM
-_s_hiEMHXjFferyGKReUzfuUMK2MRJRHmTKIzi_AWKQErDgWbykbSIrmvQapU-EMheopSkbhRLegqzRJTt1CB_RN94sExGPWIiB5Ea5aHMjIrlV_Wjg3Jz_
jyXW7cskIBjz4xqfjvgTFZbCHjiV-YDQqvWV6JwqzTi_LjORnaCR7TdmLzneTmTJqlORfD0ljpCvXdRiGBj_hxlTcqDR0saVskqjRUbMseUslaxPjI7jk9Ks
uoNu-d_p4RIr46t5lvRRr_YXtI_tw_-9BMahxJr47pVP1C2OVHjxDiFp97w3oCxed9Suj3ktklUYpH5s93h3HI9jBl3KfVk151c1lwK2II9RQlHysaYYtOz-
FJgKquwdqrRYWfvgYU7pQSU7j96oY7xBfwt5lkLaIu0mJ98xV4UiC0Nqhth_GUT3ktTdYZ9fqw0zmQJ4mQtsDK8qWUCk5poVjb8ie7_I5lvw05PDl_q_McPA
uazAVDhuvg8c8a8ik0EuehYR6C6kGjSO97tQofWWWmI2xm-SgIAffqrJ9Ux4cqqHY7S15nea8s3GzeDGxwXvbqXQ5AGPAl6Z_cZ5cngWYFN4xL_IN4RR4HgW
4lEuGO1C44azROnHYN_SPExvZvX9t1XCEuAP8b74dYg1iQkEIFPKoVLTzQlTK4Mxjjo2QxtuX7OKHVPYbxv777Dp8f54g7ISfB6lXaWOCOzAqieDenb6jLkK
fTMLMt4jO76r_QYkt8oheUXKkvusoiejVpMxpnvHZjYmt3BssAjsOLHGRlEmIRwKb3FHnkUrPFCIHe20yKiBKvMR6Iv1U36gNLdk6fUmPk-ZE6s8Iqwr3H_0
TeagODVJXZ74eLWbniXS5HMvX8-jDW3WKULclRhfLBk_phs80UMUHTsuusg2xlOy35Q5wcutL9jf-mWWjTpqSMEeH_hWcDC9I6zSPCYNX8bRd_Q6kkDIOieb
27N-sAYdI0qiDo3TvgqKvR7xnsn5qQK-gpcXuIOwWgDXxjomJncKDEALRdkeIvrN6XUyGGns8ATBYyt7pPzTmgfq2NuBISeWx7l47s9-Q4oqnHCkRLcpKXhb
dY16jUtfUl-liNcrRzz6V8bEjSsDy8g93cpJt9U6MRPbWvnxBiWSPhLhjP7opbVNl8zDXqYaN2Eu-jVSijh8CH8lNnewi3zK2N3zP64_Zy3T5Y1zU6bmjshJ
cjo0thfuEh1_kZL8xjryj0NYJzhwcuCof8PztjT07vyyA6blk8j7w3yYvjCERG4R-bXCKEB-O5bf-vLI_XCTM7wcJGTNzkddsXw1d4qgctPmOTXmS25uWzgq
Acp8t6RpGYw9c_cicvAMdbnkf5GwwjQOvLXnBTpAPIqIIBtcoOLm8xVMwXdM1yv5O4E9eu1k6rou0cpayEdIzXNEsM53QLJkyoivCswyGUq5TuvcnAouqM5j
bbljdd1At31Gk-NsZSBfO4C6QwVSVaYqUI9OjVR7IJ-Q2BO6ZBwySEvP2c_cNZ0kuHQCUTs9uW9k8VuA3U27TfUtWFWImoY7zhUy9MH_7dPeHv0_8dsCalPf
44Zgjv1uGzemog7jXkqaVIsLOvJ1Aw4UeqZ4Ys01agfOjn5S7ZNU7pkLsEnZ5A5VDsKu-nX5CFgc2yK-HX6ClWc8JevHl6AIb2HU8NsCeb6uZb6aKQYFKOIO
C3oeXmOyg8U6FEDYcL7Ek7YC8iHImK4zCWVro6Y1-_nMZaeKut9eCrQDDXV9eHtB1aSa8xCtxQEIM3ZOkTgdt8XXEULMh9rzHN9K4ei7krRxb3kM3_QizYbt
R13iMErJxjWYsA_QfzonIqwrHuPxmJukYOs2ZQfzNA8Ob-CIn5x19XuvBf5F6v2a9eayBkd5OmHDTgr0hJXaufwJ1tKlXBFhK_GRL7jEYBIQuDGwJodzVST1
dGKSdEfs0AJsu8YqUw9Jwsl4lNt7GNqTEO6lFm1kqZu6wKVrjmH0Kf980aQjrmnl5O989A8-jFlao4JKXtOV7NbOvusIl7PQeRPd1juSfODQr9sD8wSHYNx-
Qe0-NaM1Dty6IMe2aN3KaZVGRGI64EVZOGlzr_ABRH0VJ7liEYoyOVk3YAkWsYuASjIQEg0s4Oa4vnLzrld46IKYyKcG0rXd4uygsZu8SkowN22VK6sKhK_6
4QpJY8iYQTCkNBUJD50RnEiQZjfrEyair8Cyhb9l-nn03L-5bIngjmfGN_n16ObupayHbAeaht80IUcLiaZWOG_XegxStE-XPzQL6p5pM50mRaixGiDf1_Ub
7JHe3ySTquV3QGVtfHsSviQhDlpw6ye6QCP-k2Cfv9wq0qM7J6xvdLlK5OpKTYibi7PU072hRpYpUbwm5UrGyKYblPPSANOdzbeg0SMJC6r5ErGxBS1EiEi7
Akr5cxK35NQ2NQzEJJ0XMKUTMAVQVhbLfpB6Ya7nJI4Pi9Sgj-fUdx5eOCFEnurODgo-bcay7RK6RfNjW11hXwswNMJd2UsLWYUq2zEHziir2FN9IxTEJax-
2m
}

sprite $WirelessThreat [381x340/16z] {
xPtf4hIWjaD9hKhv_azyxvc_wGnYKA3O-Trjo-eO4DdODf2mhouPr4AL9FjwA0T_G2a07_u1PVbhaA05AijlmByy7_4loTThIlA_oEUY1Ihqw-0lz7dwbxY-
b0FyXNxJz2dqEVv2dmkgcvqe2lrCKObp3lwoVT6VXhxmwrf9Ljb-eYZRJnGro9afQf0pKLJaJ9HLaJDHr2XdegYudoWgxYVA5VSpfM8_KHJxYQBOxqw_s1Tz
Nzk9Ohyl_M9VzBas5SM-w8ViYtwnxnV5Vg9KxBUYNtF8DSDyNKM_RguYKO4_KHJxYL9rjlFawcmdoXKw4qMndoXLwCoJQuG_KLJeJ9Hgb3bFhj2fu7anTFmF
LV0yqmFU8Adz8Kc0NS7pWl5jTCzE0bp1CuYzBRLU2Lp1auMEdJH2KC7pqFYMMYuew_-fxsejXSlwluY0V7W1bFM3eKB8lwnFO9cCVrbVqyxvG_px6PyMQ2tx
K-mdsh_WTzZ_3EklO1Ouq_eiCZxZn07FEXSgnutrMIabESpwQtLHuYJhizh9Sf3rlPvJECNwMj8fd37QP4sdY1Do9pjPIVo-OiGsW9OqltTwUkZaVRSsQ37y
sccHclFt38FMeU-zrYmmugMhXZNmUxF5EcZCvgP62z3NRajZ3G9VkM3sPhO-kX05ffhVfnT3mCIpL2t8PrhHXglyhS_-38TV9LXCETM2tukV5qA_YcxvdBwh
-F27-FfqAtKUuFShkLCbptn9NnNvJ_0p8VGtW6__q0Jwky5d4FF_L8eB3l2_UjRQ7huj3Iu2jRwXFn--C_3lbC0HqDyfTxurZXXcVlQ7htU69Va5m0SZpbqZ
dnP8h45VUyAdXO81F-BDuNlU1Sjq-hIvcdhMfB-ZlNlSoJqLuQX7vy6dZHDPBhFnS4SBP2NHZx4lV9OO9P3GTpJSAVYjaT0l-FFeQrVuNcTyp0JwR0ZVRItw
x0b_qkNQ3z6lnBvtXE_5ok2r9VpbhbS7z4-1Vx7OhZ_i1r_NGFgIm3y4I9_HztQtk1gqjblOmuhWz8Y-Je7_0wiaxD5re7v2duFWzmjo-khzKi7lvyy3MYhu
WuP9F1YVKF07sPy7Vrx13_2dz5NmxyWyfw_kFhVWzxkVxjXNmH_MzRgRFWL_67vtVw_WZrk9xzxOf-0FCx-wWyS5_xxyw0mPrAGJIn7pvxCQOdqV03-Yxqvi
EX2-RVubUs3q-3thU_jzZcn9OGcY-cD_XFNP07umM1IECT3fMfy1tnhs8XJ61OysWSz7nGKGWNZB-jfuivtFQe3KQVq3uDFw18-FvtUitxQ5JrW0cj-taZQh
pLK6FyEVJvY5pVA--ruexUFpMoUoPh4l_5U6M9t1a-KE-swtyygl-alhQz-D7VKo_VUjtyw4t-JkBA3hqpl0RzEAv-d-Kxi0EcZ0jZrkJjzTNz3pIvgTuJE0
VXmbVjumjjvAMI_zjaPOtnCYVz7PdIv27c5zRG2_NQFeI-BlaaBwtFXqR7tsVsCAI9Bzj1JBFS6Z7kkp0NnThyde8NttVFXXmxG1_52eWtw7zVFSQIl8anU3
AxM-7pMC0-3VQAWwlg8WTrQ4h-chqkWWsfCxExoA-rgIljxD7P_rUZxwJi7lvWwjdPCx_SLKwiYT_ePfC_Yvw0aUvxdJ4Va7l1QKddDGd3iEKcTlwyTBRHpd
3a7gx0q_VrGIvuxor7bVNe6-Et8d3NrQEy3wqGIyu_aTTnZ_ZDeiXzPt39_MpiYT9A6LXZuxmDSIzOT-dZiEwhaEi_wboFhtUIem_bxMp-bxUEXt6F-0BhSl
KFm6VDfgOecoSzyoAVT3tq_X2_koOPVSoOD7_P_gduleNCThjkboRG3yC7WUmxzkMuf-5knWVQlZxPEwqsndzxWyChvVwISasuPthC-DfdTplTq_-MRg4AwY
omiIOBZr7LI_TUOEDmxNO_nyEzNUWpBM-lI7cP_cpjt3gGDXLyLINeTZPTRFI_7LCzxfjwOU3NKwt19rfmJM3_PDw8jftyT3HvCxZ1_JlyLC6Vj--hUwEnwz
Jqk-0kFtqyyx4MBs-PDK_iVXkR4mLtewaK_GrBJvxrJ6kST8-gyjbj-jf7cX5EhsmOYRb3_7_YyBpSKLA31-43pSFvWJu_TRN_UTOjlN1FQXzUaucD8cvRbp
lQOXComEu8-tFicyqPVm6JEtg83zSEj7dOw-czjsFwZS-lGTZAXDUUumo_ZaRij7Jtu3_lsMBCG-pnrwyUbJ-7nb_67iBu-4VqNjTtWIB14wZ6wnXEq7rv6_
X7-n07iFtV13zlCpqt3ullNpyfoHZdmDWo-bVIQV33L_o20He8-yglolJEmJHQ2MM9UIrw7cyEKnnl3Gt64bzZamZqCVtsSk_sgMqRRmK8CH7KkB6ryTjk-6
dxUHx6Xh6vyEzFtmSt_vrLUFi1hxyLub6WPdzBKVUuOUyvtLyZbzNJFbZiH9HkQ9u2twkgOgTtrk_FSxNPPahr6c_o7hbM0rm-dxcYg6ehTjgyEZQVoGBH6V
AyQQdlTBET5pW2XewN2Ha0_saCn4O5y3O5_JHOe-tyijZtzVMugGVB2jJoxOcZun-Q3EVMJyiozx-OlxvLSRmPRiS_B1vbS3uuVzsCipTkmOBzYBFkyDT3rZ
yX1ln5w-NfFIu06kqk0RhQ0FBSLRKtPDoWsrVy5lt2IVyI_u_VZVc0uj-7VSRAdZ2wMWz98Vqugs-G4-vLzYtXvhfHPekltB-CNV1lGt0TZZsLVyT0m-1BpA
lknl_Q_Mk_UhnJyd_qCGsBxY9pOkJbnVzi_W_GWWc-VaYx_LzXJxav-3lknlg-qkgBYPAOfysJyWN_ohYmr4TR4pHSNDH1NvYVArekQHB_XkPqWRFDyx9FGB
VkLEEqKwq_YLEmNVbJhpf3EDNxbJy5sfCqyguq-Ko_YphL_6B-khbVLFC7vPl-3hJFPb_OAluzcNzTkPKXb_eYZZJvJB-FEaWzcNzTlHAkDFb8hzHB5tw4ZO
Dg2A_JwPZBp_sBvrAydNNC78KwVGVy4V1_r8aG_uYw0NB_89VtddcmV9rueo6c4Rb-aV2l9pfyW_5oYxOBKYUNpj8WFIp-0xpbrb-Y6oRIysRo69lqlwa7pj
dld75MXGnnSA_l3SDe7f2twS7gR8lzVXqZTCbdqTgMbpxoOnlVrc60ZlcZfqt2JAZ_VzuDqzHOHtWzy7nGcTnkj017kb3X_kTSC7M-a8zZ7-fvkQuKzsCH8S
OFn-D7pbHC7sYJz-Qoq-P04hiszJNWJmAGfOTem_P_TAFbuP0bxG-9grUoMarzMdVu01M0P-ZWN7ZsE_lW9O1tvkIFpzhh2m3Ftf-uR2zpiXimXzlqu-JmC7
u8VZNobtnd4HuD-W6yPop_5hcTpX7J9IUrzYVkvmxhuUJ8VVE1P-asV3Rnm4Fsyx-tRz-zEdhKA_xIzsdLbsEu--LkdwER1ijRqZV2RyfYrVTgvs77tQcnBu
k2qEM6g88JYgp9x5XXX7mMzUgvVp0QdJ7VlBd0xj0FgpckoZu3SlDSBGKUoRrkhapeBVMEg-XetPxv-pFciFEIqrZQZ3zZ7pKYDhZcBVjDP4bWFs6yfhlKxQ
9x5lMkonaGFs-ud5hdI22t1t-lDRpBxeS_hpMmp1mipTf0NDfkt0vrwpMcbHhvLAfLAfzFy
}
